### ISSUE TITLE
Obtaining bundled SAN certificate, no errors logged

### ISSUE THREAD

**Issue by mxrlkn** [go-acme/lego#1001]
I ran into an issue where lego would stop getting certificates and instead log `Obtaining bundled SAN certificate` about 5 times, without any other errors.

I was migrating about 50 domains where maybe 40 were subdomains of the same domain.
All the domains had already received certificates on another server. But I thought making them request new certificates on my new setup would be fine instead of manually moving them.

I then suddenly near the end get Obtaining bundled SAN certificate.

I then tried with another domain that wasn’t part of the migration, same message.
then I tried that other domain on a test system that’s setup the same way, and there it went through.

To me it sounds like an ip rate limit, but without proper logging I can't be sure what the issue is.

I'm using caddy and had a discussion about it over on the caddy forums: https://caddy.community/t/acme-auto-ssl-suddenly-stopped-working/6147/16

**Comment by mxrlkn** [comment]
Caddy wasn't set to print all logs. closing.

**Comment by alexellis** [comment]
How did you set it to print "more logs"?

**Comment by mxrlkn** [comment]
`caddy -log stdout` makes it print the lego logs.
