### ISSUE TITLE
backoff package not found

### ISSUE THREAD

**Issue by proyb6** [go-acme/lego#1022]
I checked `backoff` is now v4 on master branch and v3 is exist on `github.com/cenkalti/backoff/tree/v3`

```
../../go/src/github.com/go-acme/lego/acme/api/api.go:13:2: cannot find package "github.com/cenkalti/backoff/v3" in any of:
	/usr/local/go/src/github.com/cenkalti/backoff/v3 (from $GOROOT)
	/Users/s/go/src/github.com/cenkalti/backoff/v3 (from $GOPATH)
```

**Comment by ldez** [comment]
Lego uses [go modules](https://blog.golang.org/v2-go-modules), so we don't rely on `GOPATH`.

You have to use go1.13 https://github.com/go-acme/lego/blob/master/go.mod#L3
