### ISSUE TITLE
Documentation says DREAMHOST_TOKEN but code checks DREAMHOST_API_KEY

### ISSUE THREAD

**Issue by clee** [go-acme/lego#1023]
https://github.com/go-acme/lego/blob/2dbb71b3f6fa1e5eae9bebbcb34cbba00ad8fd24/providers/dns/dreamhost/dreamhost.go#L43

**Comment by dmke** [comment]
Indeed.

Note: Only the godoc is wrong, `providers/dns/dreamhost/dreamhost.toml` (https://go-acme.github.io/lego/dns/dreamhost/) is correct.

**Comment by clee** [comment]
Thanks for the quick fix, guys :)
