### ISSUE TITLE
[Feature Request] Add CLI ability to manage DNS independently

### ISSUE THREAD

**Issue by dmarlow** [go-acme/lego#1024]
I would love to be able to make use of all of the DNS providers available outside of having to interoperate with the ACME protocol. In other words, something available via CLI to be able to set/cleanup values via the various DNS providers. This would allow a lot of lego to be used by other systems and not have to reinvent the wheel.

E.g.
```
AWS_REGION=us-east-1 \
AWS_ACCESS_KEY_ID=my_id \
AWS_SECRET_ACCESS_KEY=my_key \
lego --domains="example.com" --dns="route53" --record="key-auth" present
```
or 
`lego --domains="example.com" --dns="route53" cleanup`

**Comment by ldez** [comment]
Hello,

Some of the providers need to store information (in memory, just simple global var) in the `present` to be able to do the `cleanup`.
So it's really possible to do what you want.

> This would allow a lot of lego to be used by other systems and not have to reinvent the wheel.

Could you elaborate this point? What's the "other systems"?

I'm not sure to understand why you want to manage manually the creation of the certificates.

**Comment by dmarlow** [comment]
Some ACME clients offer DNS capabilities, but they don't have many of them. Lego has the ability to interoperate with many DNS providers. By providing the capability to utilize the DNS providers within lego, other systems can interoperate with all of the DNS providers that lego works with already.

If lego supports interoperating directly with the DNS providers available, this allows it to be quite flexible and to be used by other ACME clients. Let's say someone creates a new ACME client that has certain features lego doesn't offer. It can quickly be able to work with all of the various DNS providers by simply utilizing what lego offers. Hope that clarifies the feature request :)

**Comment by ldez** [comment]
It's not really clear.
I think that you want to use lego as DNS challenge solver with certbot or another acme client.
I don't understand this need :thinking: 

lego can be use as a standalone CLI or as a lib, the other acme clients have to create their own implementation of the DNS challenge solver or use lego as a lib.

If someone want to create a new acme client, he must use lego as a lib instead of a CLI.

For the reasons that I already mentioned in my previous post an in this post, I will decline this proposal.

Thanks anyway.

**Comment by dmke** [comment]
To add to this and give a few pointers:

> If someone want to create a new acme client, he must use lego as a lib instead of a CLI.

The `lego` binary is completely self-contained (and lives in `cmd/lego/main.go` with the business logic implemented in `cmd/*.go`). None of the library code (i.e. everything else in the repository) references code in `cmd/*`. Apart from a library used to parse the command line options, the code in `cmd/` only imports `github.com/go-acme/lego/v3/`. There's nothing special about this directory and the code herein.

If you want to access the DNS providers' `Present()`/`Cleanup()` methods, you can simply do so by, e.g. copying the code in `cmd/` into a separate repository and modify it from there.

But as @ldez said, beware that some providers keep state between the `Present()` and `Cleanup()` calls. One example is a result ID (where `Present()` creates a record, the API response returns an ID, which is required to delete that record in `Cleanup()` (without performing additional lookups)). This is not only the more performant way, but it also means we're "nice" to the API server by reducing the (small but measurable) cost associated with an API call. Of course, this means that many calls to `Cleanup()` are invalid without a prior call to `Present()`, which in turn means you cannot have a simple CLI doing *only* the former call...
