### ISSUE TITLE
uses route53 private nameservers to verify when public and private zones have same domain

### ISSUE THREAD

**Issue by Xachman** [go-acme/lego#1026]
So my problem is I have a public hosted zone for a domain and a private hosted zone for a domain in route53. When I set the AWS_HOSTED_ZONE_ID it creates the record on the public zone and I can see it propagate.  After 2 minutes of waiting for propagation it returns an error.

time limit exceeded: last error: NS \<private zone ns\> returned REFUSED for \<the domain\>.

Expected that the private zone nameserver used would be the public zone nameserver in the AWS_HOSTED_ZONE_ID.

**Comment by Xachman** [comment]
https://github.com/go-acme/lego/blob/8afde164a15aea9b5d7eddc1f1d267b56fb5132e/challenge/dns01/nameserver.go#L13

Is it possible we have the option of not using the resolv.conf nameservers?

**Comment by dmke** [comment]
You can use the `--dns.resolvers host:port` (can be given multiple times) command line flag to override the default DNS servers.

Does that help you?

**Comment by Xachman** [comment]
works! Thanks!

**Comment by dmke** [comment]
Happy to help!

**Comment by colobas** [comment]
I was about to lose my mind with this. Thank you both @Xachman and @dmke
