### ISSUE TITLE
dnspod is invalid

### ISSUE THREAD

**Issue by vx610sky** [go-acme/lego#1031]
dnspod err message:
![image](https://user-images.githubusercontent.com/17560081/71983569-0f1d8c80-3262-11ea-8321-17c191d1a744.png)

dnspod api changed:
![image](https://user-images.githubusercontent.com/17560081/71983623-2b212e00-3262-11ea-83d7-99f91678de30.png)
![image](https://user-images.githubusercontent.com/17560081/71983768-789d9b00-3262-11ea-9904-1c0688456d19.png)

https://github.com/decker502/dnspod-go/blob/master/domains.go
![image](https://user-images.githubusercontent.com/17560081/71983643-32e0d280-3262-11ea-8088-9a9aedc31c69.png)

**Comment by ldez** [comment]
Hello,

It's more a issue for https://github.com/decker502/dnspod-go than lego.

I can see something that seems similar is their issues: https://github.com/decker502/dnspod-go/issues/9
