### ISSUE TITLE
Suffix _FILE not working for route53

### ISSUE THREAD

**Issue by Xachman** [go-acme/lego#1032]
I keep getting 

acme: error cleaning up: route53: NoCredentialProviders: no valid providers in chain.

When I use AWS_ACCESS_KEY_ID_FILE and AWS_SECRET_ACCESS_KEY_FILE

**Comment by ldez** [comment]
Hello,

The following env vars are handle the the [aws client](https://github.com/aws/aws-sdk-go) it-self, so they don't support the suffix `_FILE`

https://go-acme.github.io/lego/dns/route53/

So we cannot handle that in lego.

Thanks anyway.

**Comment by Xachman** [comment]
@ldez 

Well looks like your documentation says you do.
https://go-acme.github.io/lego/dns/route53/

Thank anyway.
