### ISSUE TITLE
Documentation for route53 says suffix _FILE works when it wont.

### ISSUE THREAD

**Issue by Xachman** [go-acme/lego#1033]
https://github.com/go-acme/lego/issues/1032
So @ldez  mentioned that the _FILE suffix does will not work tho I have been trying to make it work based on the documentation at. 

 https://go-acme.github.io/lego/dns/route53/

Can this be corrected so others dont end up spending needless time trying to make it work?
Is there a good option if we dont want our keys printed in the cli besides this?

The instructions on https://go-acme.github.io/lego/dns/route53/ say:

The environment variable names can be suffixed by _FILE to reference a file instead of a value. More information here.

**Comment by ldez** [comment]
`_FILE` work for: https://go-acme.github.io/lego/dns/route53/#additional-configuration

but not https://go-acme.github.io/lego/dns/route53/#credentials


As a already explained here: https://github.com/go-acme/lego/issues/1032#issuecomment-572121232

**Comment by Xachman** [comment]
Using the documentation at https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-credentials.html for setting up the ~/.aws/credentials works fine.

After setting that up you can remove the AWS_ACCESS_KEY_ID and the AWS_SECRET_ACCESS_KEY from the command.  

Probably noting this somehow in the documentation would be good.

**Comment by ldez** [comment]
https://go-acme.github.io/lego/dns/route53/#description

**Comment by Xachman** [comment]
@ldez 

Yea I know right!? The best part about how vague the information is that you get ~/.aws/credentials with a copy button so you can paste it right into google.

**Comment by Xachman** [comment]
@ldez 
Could we at least fix the documentation so it's more clear and does not point users in the wrong direction before we close this.  I realize you have an opinion about this.  But normal users like me who arnt maintainers it will help out.

**Comment by ldez** [comment]
The issue has been closed by the PR #1036: I updated the doc.

I don't have opinion about this.

**Comment by Xachman** [comment]
@ldez sorry too early in the morning for me!
