### ISSUE TITLE
github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

### ISSUE THREAD

**Issue by deragon** [go-acme/lego#1038]
Get the following:

```
go get: github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.0 updating to
 	github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.5 requires
 	github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
When doing:

```
export GO111MODULE=on
go get -u github.com/go-acme/lego/v3/cmd/lego
```

As of 2020-01-11 08:20:24 EST.  New user here; if I am doing something wrong, please correct me.

**Comment by ldez** [comment]
Hello,

The error comes because you are trying to update the lego dependencies.

The command:
```bash
go get -u github.com/go-acme/lego/v3/cmd/lego
```
must be executed ouside the lego repo.

**Comment by deragon** [comment]
But I am in an empty directory, not in a repo...  See the `find` command at the end confirming it.

> $ export GO111MODULE=on
> $ go get -u github.com/go-acme/lego/v3/cmd/lego
> go: finding golang.org/x/oauth2 latest
> go: finding golang.org/x/time latest
> go: finding github.com/kolo/xmlrpc latest
> go: finding github.com/jmespath/go-jmespath latest
> go: finding google.golang.org/genproto latest
> go: finding golang.org/x/net latest
> go: finding github.com/timewasted/linode latest
> go: finding golang.org/x/sys latest
> go: finding golang.org/x/sync latest
> go: finding golang.org/x/crypto latest
> go: finding github.com/OpenDNS/vegadns2client latest
> go: finding github.com/iij/doapi latest
> go: finding github.com/namedotcom/go latest
> go: finding github.com/rainycape/memcache latest
> go: finding github.com/modern-go/concurrent latest
> go: finding github.com/ovh/go-ovh latest
> go get: github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.0 updating to
> 	github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.5 requires
> 	github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
> $ find .
> .
> $ go version
go version go1.13.5 linux/amd64
> $

**Comment by ldez** [comment]
so just do
```
go get github.com/go-acme/lego/v3/cmd/lego
```

**Comment by deragon** [comment]
> $ go get github.com/go-acme/lego/v3/cmd/lego
> package github.com/go-acme/lego/v3/cmd/lego: cannot find package "github.com/go-acme/lego/v3/cmd/lego" in any of:
> 	/snap/go/4901/src/github.com/go-acme/lego/v3/cmd/lego (from $GOROOT)
> 	/home/hans/go/src/github.com/go-acme/lego/v3/cmd/lego (from $GOPATH)
> $

:(  I am attempting to build lego on Ubuntu 19.04.  The _go_ compiler is a snap.  Could that be the problem?  Sorry, but I am not familiar at all with go and its dependency management system, thus even if it is a trivial problem, I have no clue where to start.

**Comment by ldez** [comment]
If you are not familiar with go, I recommend to use our binaries instead of trying to build lego from sources:
- https://go-acme.github.io/lego/installation/#binaries
- https://github.com/go-acme/lego/releases

**Comment by hawksight** [comment]
I have the same issue on ubuntu 18.04:

```
❯ go get -u github.com/go-acme/lego/v3/cmd/lego         

package github.com/go-acme/lego/v3/cmd/lego: cannot find package "github.com/go-acme/lego/v3/cmd/lego" in any of:
	/usr/lib/go-1.14/src/github.com/go-acme/lego/v3/cmd/lego (from $GOROOT)
	/home/peter/go/src/github.com/go-acme/lego/v3/cmd/lego (from $GOPATH)
```

It would appear there is not `v3` directory, hence the error.

```
❯ ls -ltr /home/peter/go/src/github.com/go-acme/lego/v3/

ls: cannot access '/home/peter/go/src/github.com/go-acme/lego/v3/': No such file or directory
                                                                                                         
❯ ls -ltr /home/peter/go/src/github.com/go-acme/lego

total 172
-rw-r--r-- 1 peter peter   415 Mar 18 11:20 Dockerfile
-rw-r--r-- 1 peter peter  2599 Mar 18 11:20 CONTRIBUTING.md
-rw-r--r-- 1 peter peter 22401 Mar 18 11:20 CHANGELOG.md
-rw-r--r-- 1 peter peter  8199 Mar 18 11:20 README.md
-rw-r--r-- 1 peter peter  1869 Mar 18 11:20 Makefile
-rw-r--r-- 1 peter peter  1088 Mar 18 11:20 LICENSE
drwxr-xr-x 2 peter peter  4096 Mar 18 11:20 certificate
drwxr-xr-x 2 peter peter  4096 Mar 18 11:20 certcrypto
drwxr-xr-x 3 peter peter  4096 Mar 18 11:20 acme
drwxr-xr-x 3 peter peter  4096 Mar 18 11:20 cmd
drwxr-xr-x 6 peter peter  4096 Mar 18 11:20 challenge
drwxr-xr-x 5 peter peter  4096 Mar 18 11:20 platform
drwxr-xr-x 2 peter peter  4096 Mar 18 11:20 log
drwxr-xr-x 2 peter peter  4096 Mar 18 11:20 lego
drwxr-xr-x 3 peter peter  4096 Mar 18 11:20 internal
-rw-r--r-- 1 peter peter 59290 Mar 18 11:20 go.sum
-rw-r--r-- 1 peter peter  2175 Mar 18 11:20 go.mod
drwxr-xr-x 5 peter peter  4096 Mar 18 11:20 e2e
drwxr-xr-x 6 peter peter  4096 Mar 18 11:20 docs
-rw-r--r-- 1 peter peter   648 Mar 18 11:20 tmpl.Dockerfile
drwxr-xr-x 2 peter peter  4096 Mar 18 11:20 registration
drwxr-xr-x 4 peter peter  4096 Mar 18 11:20 providers
```

Downloading the package with `go get -d github.com/go-acme/lego/v3/cmd/lego` worked as expected, just cannot install. Tried to run `go install` but did not work either.

This path does exist though:
```
❯ ls -ltr /home/peter/go/src/github.com/go-acme/lego/cmd/lego

total 4
-rw-r--r-- 1 peter peter 904 Mar 18 11:20 main.go
```

I am also no expert with `go` but have be able to `go get` other packages. Perhaps its only an issue on ubuntu or linux systems?

Versions
```
❯ cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

❯ go version

go version go1.14 linux/amd64
```

**Comment by ldez** [comment]
It's not a issue with OS.

You have to enable Go module support.

If you are not familiar with go, I recommend to use our binaries instead of trying to build lego from sources:
- https://go-acme.github.io/lego/installation/#binaries
- https://github.com/go-acme/lego/releases

**Comment by hawksight** [comment]
Your right, needed to run the two commands together and worked fine:

````
GO111MODULE=on go get -u github.com/go-acme/lego/v3/cmd/lego
```
