### ISSUE TITLE
The RawQuery changed the token

### ISSUE THREAD

**Issue by ifurther** [go-acme/lego#1048]
Hi I have the error in this function. It can change token including "=" or "&".
https://github.com/go-acme/lego/blob/ee33cff0020e336f58604fd7ad69d309b9d0de1e/providers/dns/duckdns/client.go#L30

**Comment by ldez** [comment]
Hello,

Could you elaborate a bit more? (logs, cli, etc.)

**Comment by ifurther** [comment]
It show "acme: error presenting token: request to change TXT record for DuckDNS returned the following result (KO) this does not match expectation (OK) used url ..." , and the token changed.
I use its url and it show "ok" after change the token part .

**Comment by ldez** [comment]
could you provide more concrete information?

**Comment by ifurther** [comment]
I use the traefik to launch it .
log show :
request to change TXT record for DuckDNS returned the following result (KO) this does not match expectation (OK) used url [https://www.duckdns.org/update?clear=false&domains=terst.duckdns.org&token=%26ip%3D&txt=5ri8suBopt752Z8lggcK9uD7gudqIphgjF-_6gkfOwY]\n" providerName=ll.acme routerName=portainer rule="Host(`portainer.terst.duckdns.org`)"
DUCKDNS_TOKEN=&ip=

**Comment by ldez** [comment]
Why do you add `&ip` in your token?

**Comment by ldez** [comment]
From the [spec](https://www.duckdns.org/spec.jsp):
> TXT Record API
> ...
> HTTP Parameters
> domains - REQUIRED - comma separated list of the subnames you want to update
> token - REQUIRED - your account token
> txt - REQUIRED - the txt you require
> verbose - OPTIONAL - if set to true, you get information back about how the request went
> clear - OPTIONAL - if set to true, the update will ignore the txt parameter and clear the txt record

`ip` is not a valid parameter for TXT records.

**Comment by ifurther** [comment]
My token have "=" and "&", and it will change input the url.

**Comment by ldez** [comment]
As far I know the tokens are alphanumeric so it cannot have `=` or `&`.
 
Even if these characters were allowed they would be mandatory to encode them.

**Comment by ifurther** [comment]
But my token have it. And I replace the "%26" to "&" ,"%3D" to "=" , it show OK. No problem
