### ISSUE TITLE
Support gdnsd

### ISSUE THREAD

**Issue by mhf-ir** [go-acme/lego#1052]
Is any plan to support gdnsd?

https://github.com/gdnsd/gdnsd/wiki/Gdnsdctl

**Comment by ldez** [comment]
Hello,

I don't know how this tool works exactly, but I understand that it can only be controlled by a CLI.

So in this case you can use the [exec](https://go-acme.github.io/lego/dns/exec/) to executed the commands to Injects and clean the response payloads.

As gdnsd don't have any HTTP API, we will not create a dedicated implementation.

But you share your scripts (run by the [exec provider](https://go-acme.github.io/lego/dns/exec/)) here to help the others gdnsd users.
