### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by ggl** [go-acme/lego#1077]
Cannot build. The documentation is outdated:

`go get -u github.com/go-acme/lego/v3/cmd/lego`

does not work.

`go get -u github.com/go-acme/lego/cmd/lego`

probably would if the libsacloud dependency would not fail.

**Comment by ldez** [comment]
The documentation is not outdated.

The go module must be activated.

```
export GO111MODULE=on
go get -u github.com/go-acme/lego/v3/cmd/lego
```

**Comment by ldez** [comment]
The recommended ways to install and use lego are describe in the documentation https://go-acme.github.io/lego/installation/:
- binaries
- docker image
- package managers

The build from sources is for devs or people who know Go.
