### ISSUE TITLE
directory missing new registration URL

### ISSUE THREAD

**Issue by samnazarko** [go-acme/lego#1089]
Registration is nil -> &errors.errorString{s:"directory missing new registration URL"}

I've updated Lego a few days to a new version (latest) which I believe has ACMEv2 support.
I'm trying to re-new some domains with the following command, but experiencing issues:

```
function renew_certificate()
{
    bash /root/lego/notify_slack.sh "${1}osmc.tv"
    GCE_PROJECT=${1} GCE_DOMAIN=${1}osmc.tv NAMECHEAP_API_USER=someuser NAMECHEAP_API_KEY="somekey" ./lego \
    --email="email@samnazarko.co.uk" \
    --domains=${1}osmc.tv \
    --dns="namecheap" \
    --server=https://acme-v01.api.letsencrypt.org/directory \
    renew
    bash /root/lego/notify_slack.sh "${1}osmc.tv" "1"
    cp .lego/certificates/${1}osmc.tv.crt /etc/ssl/certs/nginx/letsencrypt/
    cp .lego/certificates/${1}osmc.tv.key /etc/ssl/certs/nginx/letsencrypt/
    sleep 60
    service nginx restart
}


renew_certificate "my."
```

Can you confirm if ACMEv2 is now supported?

**Comment by ldez** [comment]
Hello,

ACME v2 is supported since 2 years.

https://github.com/go-acme/lego#features

**Comment by ldez** [comment]
The URL of the production server is https://acme-v02.api.letsencrypt.org/directory

**Comment by samnazarko** [comment]
Thank you for such a prompt reply.

I have just tested this with the updated URL and can confirm that it works as expected. I did think this would be a PEBKAC issue.

Thanks for maintaining this project.
