### ISSUE TITLE
Using option --http.port :81 still makes request on port 80.

### ISSUE THREAD

**Issue by Xachman** [go-acme/lego#1092]
Using 
```
sudo lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --path /usr/etc/lego/ --email <email> --http --http.port :81 -d<domain> -a  run
```
I keep getting a failure and a response that is coming from the site on port 80.

**Comment by ldez** [comment]
Hello, 

The port 80 is mandatory for the HTTP challenge, it's a Let's Encrypt requirement.

**Comment by Xachman** [comment]
@ldez what is the http.port option for?

**Comment by ldez** [comment]
The option is useful if you are behind something (proxy) that manage the routing from 80 to the port define by this option..

**Comment by Xachman** [comment]
@ldez yea I forgot to add my location proxy pass for my reverse proxy.  The documentation is broken for use of this option so I made an issue. https://go-acme.github.io/lego/usage/cli/usage/cli#port-usage ill make an issue to fix this.  Also do we have any examples of how to implement this because I can provide that if we dont?

**Comment by Xachman** [comment]
Just for future reference I use this location for nginx.
```
    location /.well-known/acme-challenge {
        proxy_pass http://127.0.0.1:81;
        proxy_set_header Host $host;
    }
```

in my server declaration.

**Comment by ldez** [comment]
>  The documentation is broken for use of this option so I made an issue. 

The documentation is right: it's an option to change the port exposed by lego to resolve the HTTP challenge, the Let's Encrypt requirements are something else.

We don't document the integration with other tools.

I recommend to use integrated lego implementation such as:
- https://github.com/containous/traefik
- https://github.com/caddyserver/caddy

**Comment by Xachman** [comment]
We have been using this with NGINX for about a year now.  Works great just forgot how we set it up when I started with another company.
