### ISSUE TITLE
Documentation link broken for Port Usage.

### ISSUE THREAD

**Issue by Xachman** [go-acme/lego#1093]
https://go-acme.github.io/lego/usage/cli/

On this page the Port Usage link goes to a 404.  its a relative link and it threw me off when I was looking at the documentation.  The information its targeting is right under it.

**Comment by ldez** [comment]
the link is good https://go-acme.github.io/lego/usage/cli/#port-usage

**Comment by ldez** [comment]
You are speaking about the link in the section `Sudo`

**Comment by Xachman** [comment]
Yes the link in the sudo section
