### ISSUE TITLE
Issue with Azure DNS challenges

### ISSUE THREAD

**Issue by hbuckle** [go-acme/lego#1097]
We've recently started having failures getting certificates using Terraform and Azure DNS which seems to be coming from this library. The challenge times out every time with

```
[cbuk-core-cibuild152380-sfha-uksouth.test-cbinnovation.uk] time limit exceeded: last error: read udp 10.1.0.4:53670->192.100.102.7:53: i/o timeout
```

I've replicated the issue by updating the test in this library

```go
func TestCheckDNSPropagation(t *testing.T) {
	testCases := []struct {
		desc        string
		fqdn        string
		value       string
		expectError bool
	}{
		{
			desc:  "success",
			fqdn:  "hbtest.test-cbinnovation.uk.",
			value: "hello",
		},
		{
			desc:        "no TXT record",
			fqdn:        "acme-staging.api.letsencrypt.org.",
			value:       "fe01=",
			expectError: true,
		},
	}
```

```
--- FAIL: TestCheckDNSPropagation (0.00s)
    --- FAIL: TestCheckDNSPropagation/success (10.38s)
        precheck_test.go:43:
                Error Trace:    precheck_test.go:43
                Error:          Received unexpected error:
                                read udp 10.0.1.4:54825->192.100.103.7:53: i/o timeout
                Test:           TestCheckDNSPropagation/success
                Messages:       PreCheckDNS failed for hbtest.test-cbinnovation.uk.
        precheck_test.go:44:
                Error Trace:    precheck_test.go:44
                Error:          Should be true
                Test:           TestCheckDNSPropagation/success
                Messages:       PreCheckDNS failed for hbtest.test-cbinnovation.uk.
FAIL
FAIL    github.com/go-acme/lego/v3/challenge/dns01      10.657s
FAIL
```

The strange thing is it only seems to happen on VMs in Azure, I can run the code from my own machine with no errors, so not quite sure what is causing the issue

**Comment by sgtang** [comment]
@hbuckle Did you guys ever come across a solution to this? We've started seeing the same error as well on our Azure VMs.

**Comment by hbuckle** [comment]
@sgtang - that's what we have done for now - for some reason the Azure internal DNS is returning an additional IP address for the Azure DNS zone nameservers that doesn't respond to the go-acme requests. I have a support ticket with the Azure DNS team to try and figure out why

**Comment by hbuckle** [comment]
Azure support seem to have resolved this, according to them 

> It appears an update was deployed to 6 clusters in North Europe which caused DNS resolution to intermittently fail so our Engineering team removed the update on all 6 clusters to mitigate the issue.
