### ISSUE TITLE
Idea: Make lego an external dns editor too?

### ISSUE THREAD

**Issue by smtalk** [go-acme/lego#1100]
Lego seems to support a lot of different DNS providers, it already has APIs to interact with them. Making lego a tool to manage external DNS (simply show all entries/edit them (not just _acme_challenge ones)) may attract some new customers and make lego more popular choice :)

Just a thought.

We were thinking about coding our own solution to support external DNS providers in a web control panel, however.. if there is a change that lego is going to support it, we'd just use it for that purpose! :)

**Comment by ldez** [comment]
Hello,

lego is a tool and a library to get certificates by using the ACME protocol, the DNS challenge is only one of the challenges.

The goal of lego is not to become an DNS provider abstraction library in Go.

As lego is an Open Source Software, you don't pay, so there are no "customers" but there are contributors and users.

We want to keep lego focus on this main goal:  get certificates by using the ACME protocol.

Thanks anyway.
