### ISSUE TITLE
Folder name on QNAP server

### ISSUE THREAD

**Issue by Hamylton-FC** [go-acme/lego#1103]
I have tried to install "LEgo" via QNAPClub Store or downloading the .qpkg file and uploading direct to the server, on both case, the folder name created on "/opt" is "QPKFNAME". This is the variable used to store the folder name ("LEgo", isn't it?) Is there something wrong with the installer?

**Comment by ldez** [comment]
Hello,

we (the lego team) don't manage the qpkg and the QNAPClub Store, so you have to contact the person who create this package.

https://www.qnapclub.eu/fr/qpkg/456
