### ISSUE TITLE
Are there any plans to have a vaultproject.io provider?

### ISSUE THREAD

**Issue by marcofranssen** [go-acme/lego#1107]
I found another project which already implements it in a fashion like the https://godoc.org/golang.org/x/crypto/acme library does.

https://github.com/johanbrandhorst/certify/tree/master/issuers/vault

**Comment by marcofranssen** [comment]
@ldez @chen-anders @cpu @dapfa any thoughts? Just wondering if there is a reason why it might not be implemented. 

I think it would be useful for company internal services so they can use vault as a CA for their internal purposes.

If I could find some time, with a little assistance and maybe some other people interested I could work on an implementation.

**Comment by ldez** [comment]
vaultproject.io is not a Let's encrypt provider

**Comment by marcofranssen** [comment]
@ldez thanks for your reply. I have requested if such a feature is desired on the Vault project.

**Comment by mholt** [comment]
I agree with @ldez, this is the wrong abstraction. Lego is storage-agnostic, it is simply an ACME client implementation.
