### ISSUE TITLE
Example CLI update to DoDe DNS

### ISSUE THREAD

**Issue by Andr3asB** [go-acme/lego#1123]
Hi, 
not a big issue but as you asked to contribute to the documentation with an CLI example I thought it's worth sharing mine here so one of you with permissions could update the page https://go-acme.github.io/lego/dns/dode/:

`export DODE=1234567890abcdefghij
lego -d myserver.mydomain.com -a --dns dode --email its.me@yahoo.com run
`

In case the local DNS server (e.g. 10.1.1.1) is not reachable from the internet one might want to add the do.de DNS server as resolver DNS:
`export DODE=1234567890abcdefghij
lego -d myserver.mydomain.com -a --dns dode --email its.me@yahoo.com --dns.resolvers ns1.domainoffensive.de run
`

Thanks for developing lego. It's really a great help in administration of LE certs for my tiny container farm@home.

Regards, Andreas

**Comment by ldez** [comment]
Hello,

You can add the example by yourself, you just need to edit [this file](https://github.com/go-acme/lego/blob/master/providers/dns/dode/dode.toml#L7) and open a pull request.

**Comment by Andr3asB** [comment]
Hello, ah very cool, te website is managed from the repository as well. OK, I've added the changes and created this [pull request](https://github.com/go-acme/lego/pull/1126). Hope it follows your guidelines.
Thanks, Andreas

**Comment by ldez** [comment]
Closed by #1309
