### ISSUE TITLE
Support for Mythic Beasts DNSv2 API

### ISSUE THREAD

**Issue by danielsilverstone-ct** [go-acme/lego#1124]
My employer needs support for [Mythic Beasts' DNSv2 API][dnsv2] in order to better support our infrastructure using Lego.  As such, we need Lego to support the API.

I am prepared to do the work to implement this, though I appreciate this is a beta API as far as Mythic Beasts are concerned, we need it for the delegated permissions support it has over their v1 API.

Would this be something the Lego project would consider merging once I'm done?

[dnsv2]: https://www.mythic-beasts.com/support/api/dnsv2

**Comment by ldez** [comment]
Hello,

Yes, you can create a PR, from my point of view it's just another DNS provider, if you are able to maintain it then I don't see any problems.

**Comment by danielsilverstone-ct** [comment]
While it may not be me directly, I'm certain that at least one of my colleagues will be able to provide ongoing support, and I will obviously do my best as a F/LOSS contributor to make that happen.  Thank you for being prepared to entertain this work.  For reference, I'm working over in https://github.com/danielsilverstone-ct/lego/tree/mythic-beasts-v2/providers/dns/mythicbeasts
