### ISSUE TITLE
Mythic Beasts DNS-01 support uses beta API

### ISSUE THREAD

**Issue by danielsilverstone-ct** [go-acme/lego#1129]
The Mythic Beasts API which was necessary to use for DNS-01 support is currently beta.

This issue is here to track that so that when they stabilise the API we can adjust the default API endpoint appropriately.

I shall point Mythic Beasts support to this issue so that hopefully they'll provide feedback when it happens, otherwise I, or a colleague of mine, shall check in periodically to ensure we catch it ASAP.

**Comment by pdw-mb** [comment]
We've just moved the DNS API out of beta.  The new base URL is:
```
https://api.mythic-beasts.com/dns/v2
```
e.g.
```
https://api.mythic-beasts.com/dns/v2/zones/example.com/records
```
