### ISSUE TITLE
System configuration check for Lego v3.5.0

### ISSUE THREAD

**Issue by suvsap** [go-acme/lego#1131]
Hi Team,

We are planning to upgrade from v0.3.1 to v3.5.0. I just wanted to check if there any system configurations that needs to be verified before we upgrade our ACME v2 client.

Kindly help

**Comment by suvsap** [comment]
Also is Lego v3.5.0 is backwards compatible  as this needs to run on Ubuntu 14.04 and Ubuntu 18.04.

Thanks,
Suvankar

**Comment by ldez** [comment]
Hello,

It's a big jump, but lego don't really depend on the system, so it don't need any specific system configurations.

As a user, I think you will not see many changes apart from a few changes to the CLI flags.

**Comment by suvsap** [comment]
Thanks Idez for your quick update.

So as per my understanding there is no dependency on Ubuntu version. Lego v3.5.0 can run on any Ubuntu version.

Also can you kindly point to some documentation for the same so that I can update it in my ticket before proceeding with the upgrade.

Best Regards,
Suvankar
