### ISSUE TITLE
Cloudflare DNS provider cannot add TXT record

### ISSUE THREAD

**Issue by ajnikitins** [go-acme/lego#1133]
Hello!

I can't seem to be able to create a Let's Encrypt certificate for my website because lego/cloudflaire fails at creating a TXT record. I initially had the configuration in Traefik, but I think that it's a lego issue.

When I run:
```
docker run -i -e CLOUDFLARE_EMAIL=my@email.com -e CLOUDFLARE_API_KEY=mykey goacme/lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --dns cloudflare --domains mysite.com --email my@email.com run
```

I get:

```
2020/05/02 21:38:40 No key found for account my@email.com. Generating a P384 key.
2020/05/02 21:38:40 Saved key to /.lego/accounts/acme-staging-v02.api.letsencrypt.org/my@email.com/keys/my@email.com.key
2020/05/02 21:38:41 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you accept the TOS? Y/n

2020/05/02 21:38:43 [INFO] acme: Registering account for my@email.com
!!!! HEADS UP !!!!

                Your account credentials have been saved in your Let's Encrypt
                configuration directory at "/.lego/accounts".
                You should make a secure backup of this folder now. This
                configuration directory will also contain certificates and
                private keys obtained from Let's Encrypt so making regular
                backups of this folder is ideal.2020/05/02 21:38:43 [INFO] [mysite.com] acme: Obtaining bundled SAN certificate
2020/05/02 21:38:44 [INFO] [mysite.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53391423
2020/05/02 21:38:44 [INFO] [mysite.com] acme: Could not find solver for: tls-alpn-01
2020/05/02 21:38:44 [INFO] [mysite.com] acme: Could not find solver for: http-01
2020/05/02 21:38:44 [INFO] [mysite.com] acme: use dns-01 solver
2020/05/02 21:38:44 [INFO] [mysite.com] acme: Preparing to solve DNS-01
2020/05/02 21:38:45 [INFO] [mysite.com] acme: Cleaning DNS-01 challenge
2020/05/02 21:38:45 [WARN] [mysite.com] acme: cleaning up failed: cloudflare: unknown record ID for '_acme-challenge.mysite.com.'
2020/05/02 21:38:45 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/53391423
2020/05/02 21:38:45 Could not obtain certificates:
        error: one or more domains had a problem:
[mysite.com] [mysite.com] acme: error presenting token: cloudflare: failed to create TXT record: error from makeRequest: HTTP status 401: invalid credentials
```

I have tried to reset the API key, make joint and split API tokens, and also the non-staging server with no success.
Inputting actually invalid credentials gives a 403, which hopefully is expected behaviour. 

At least one other case of this is mentioned in [this SO question](https://stackoverflow.com/questions/61564020/traefik-not-generating-tls-certificate-error-401).

**Comment by ldez** [comment]
https://go-acme.github.io/lego/dns/cloudflare/

> If using API keys (CF_API_EMAIL and CF_API_KEY), the Global API Key needs to be used, not the Origin CA Key.

**Comment by elatov** [comment]
I am actually seeing the same thing and I am using the **GLOBAL API** key. Using `curl` with the same environment variables works:

```
> curl -X GET "https://api.cloudflare.com/client/v4/zones/${MYZONEID}/dns_records" -H "Content-Type:application/json" -H "X-Auth-Key:${CF_API_KEY}" -H "X-Auth-Email:${CF_API_EMAIL}" -s | head 
{
  "result": [
    {
      "id": "95ca2d2bc907c7645359a46fb9d8611e",
      "zone_id": "MYZONEID",
      "zone_name": "me.dom",
      "name": "w.me.dom",
      "type": "A",
      "content": "IP",
      "proxiable": true,
```

Are there some more verbose logging we can enable on the `lego` cli?

**Comment by elatov** [comment]
It looks like I was running into this issue: [Unable to update DDNS using API for some TLDs](https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228). Switching over to another domain fixed the issue for me.

**Comment by ajnikitins** [comment]
Yup, it seems that this problem is caused by Cloudflare's choice to remove API support for specific TLDs (I have a .ml domain and, thus, I am also affected). I will close the issue.
Thank you for your time!

**Comment by GuyKh** [comment]
Sorry for commenting on this one so late after closing the issue.

I'm experiencing the same problem my self. Got a .TK domain with  cloudflare ddns.
I saw that Cloudflare doesn't support .tk domain on their API, but this is a problem with LE certificate creation?
Any idea how can I renew an LE certificate while staying on the same domain? (and continue manually updating the cloudflare ddns)?

**Comment by Jarvik7** [comment]
Same issue with .tk domains for me here too.
It USED to work, but on my last refresh (several months ago) it broke

**Comment by GuyKh** [comment]
Personally, I can live with manually updating the IP over the Cloudflare api - as it's not changing that frequently.
But the fact is that Traefik with LetsEncrypt fails to refresh the certificate.
What to do?
