### ISSUE TITLE
Allow using custom nameservers 

### ISSUE THREAD

**Issue by aslafy-z** [go-acme/lego#1137]
My system configured nameserver does not allow querying my remote zone because of some network restrictions, in fact it will answer some other zone info that does not contains the TXT fields. I'd like to set custom resolvers or use the default ones instead of relying on my local `resolv.conf` file.

https://github.com/go-acme/lego/blob/master/challenge/dns01/nameserver.go#L30
https://github.com/go-acme/lego/blob/master/challenge/dns01/nameserver.go#L234

I there a way I missed to achieve that?

**Comment by ldez** [comment]
Hello,

it's already possible to use custom nameservers:

>    --dns.resolvers value        Set the resolvers to use for performing recursive DNS queries. Supported: host:port. The default is to use the system resolvers, or Google's DNS resolvers if the system's cannot be determined.

https://go-acme.github.io/lego/usage/cli/
