### ISSUE TITLE
AutoDNS Adapter does not clean up TXT records, causing DNS super wildcards not to work

### ISSUE THREAD

**Issue by amenk** [go-acme/lego#1138]
We are using the AutoDNS adapter from #501 via traefik

Our real .dev domain is replaced by "ourdomain" in the following example

docker-compose.yml

	version: '2'

	services:
	  traefik:
	    image: traefik:2.0.7
	    container_name: traefik
	    restart: unless-stopped
	    ports:
	      - 80:80
	      - 443:443
	    networks:
	      - web
	    environment:
	      AUTODNS_API_USER: ${AUTODNS_API_USER}
	      AUTODNS_API_PASSWORD: ${AUTODNS_API_PASSWORD}
	    labels:
	      - "traefik.enable=true"
	      - "traefik.http.routers.api.rule=Host(`traefik.ourdomain.dev`)"
	      - "traefik.http.routers.api.entrypoints=https"
	      - "traefik.http.routers.api.service=api@internal"
	      - "traefik.http.routers.api.middlewares=auth@file"
	      - "traefik.http.routers.api.tls.certresolver=basic"
	    volumes:
	      - /var/run/docker.sock:/var/run/docker.sock
	      - ./traefik.yml:/traefik.yml
	      - ./rules:/rules
	      - ./acme.json:/acme.json

	networks:
	  web:
	    external: true

rules/certs.yml

	http:
	  routers:
	    certs:
	      entryPoints:
		- http
		- https
	      service: noop
	      rule: Host("about:blank")
	      tls:
		certResolver: basic
		domains:
		  - main: "ourdomain.dev"
		    sans:
		      - "*.dnstest.ourdomain.dev"

Our zone looks like this:
![zone-before-start](https://user-images.githubusercontent.com/1087128/81079465-dfb91c80-8eef-11ea-9a5f-0362cf9fea8d.png)

Now we call

    echo -n > acme.json 
    docker-compose up -d

After this the zone looks like this:

![zone-after-start](https://user-images.githubusercontent.com/1087128/81079538-f6f80a00-8eef-11ea-9f69-4d2564d9b37f.png)

So the ACME challenge was not cleaned up.

This causes 

foobar.dnstest.ourdomain.dev not to be resolvable (it resolved before the creation of the TXT entries), because of the nature how DNS works.
Wildcards work only until infinite levels if there is no additional entry with such a domain.

A simple workaround is to also create a Wildcard *.dnstest.ourdomain.dev with our server's IP.

**Comment by amenk** [comment]
ping @kolaente  (low prio, as there is a workaround)

**Comment by spookyvision** [comment]
this happened to me with Traefik 3.6

**Comment by ldez** [comment]
This problem was solved 5 years ago.
If you have a problem, you can open a dedicated issue.
