### ISSUE TITLE
DigitalOcean DNS provider fails with 404 if domain is redirected in /etc/hosts and lego is running inside docker

### ISSUE THREAD

**Issue by benkuhn** [go-acme/lego#1147]
Steps to reproduce:

1. Have a domain (e.g. benkuhn.net) with DigitalOcean nameservers.
1. On host machine, add a redirect in `/etc/hosts`, `127.0.0.1 benkuhn.net`, with the goal of testing your cert locally.
1. Inside a docker container, try to solve a DNS01 challenge for `benkuhn.net` (I used Traefik, but I don't think this matters)

Expected behavior:

- DNS01 challenge solved.

Actual behavior:

- Error message: `acme: error presenting token: digitalocean: HTTP 404: not_found: The resource you were accessing could not be found.`

I believe the cause is:

- DigitalOcean provider calls [`addTxtRecord`](https://github.com/go-acme/lego/blob/master/providers/dns/digitalocean/client.go#L60) to add the TXT record to solve the challenge
- That method needs to find the DNS zone name in DigitalOcean to add to the API, for which it uses [`findZoneByFqdn`](https://github.com/go-acme/lego/blob/6043c9347ca44682aa5d01b0f8711d1f2192cba9/challenge/dns01/nameserver.go#L140)
- That ultimately ends up looking for SOA records for first `_acme-challenge.benkuhn.net`, then `benkuhn.net`, then `net`, stopping when it finds the first SOA record
- Normally I don't think an `/etc/hosts` rule would interfere with this (it doesn't on my host machine)
- However, Docker runs its own DNS server that it points containers at, so that `/etc/hosts` rules on the host apply to containers (!)
- Thus, inside my docker container, `dig SOA benkuhn.net` shows no record, even though on my host machine it shows `ns1.digitalocean.com` as expected

At minimum, it would be nice to log the zone lego ends up inferring in this case, since I could have seen that it was hitting `net` instead of `benkuhn.net` and that would have saved me quite a bit of debugging.

More generally, could it be safer not to use system DNS to get the SOA records in this case (and instead to jump straight to e.g. google public dns) given that system dns is semi-routinely full of lies like this? But maybe there are other reasons why it's important use the system dns.

**Comment by ldez** [comment]
Hello,

It's more an issue with Docket DNS server instead of lego.

lego need to get the zone name but also need to check the records propagation, with this kind of "redirection" to localhost, it's impossible.

To define your own resolvers you have to use:
- in lego:
  https://go-acme.github.io/lego/usage/cli/
  ```
   --dns.resolvers value        Set the resolvers to use for performing recursive DNS queries. Supported: host:port. The default is to use the system resolvers, or Google's DNS resolvers if the system's cannot be determined.
  ```

- in Traefik:
https://docs.traefik.io/v2.2/https/acme/#resolvers

**Comment by xentec** [comment]
I've also spent many hours debugging on the same path (just using Cloudflare) and questioning the sanity of my systems.

To prevent this from repeating for others, I'd like to suggest adding a warning to `fetchSoaByFqdn`:
https://github.com/go-acme/lego/blob/5c1e21308c61c29f474319afec9c52e62dd24519/challenge/dns01/nameserver.go#L179-L182
Once `domain` is reduced to a TLD, lego should warn that something is wrong with `SOA` resolving and hint at using `--dns.resolvers` argument.
