### ISSUE TITLE
How to renew a certificate?

### ISSUE THREAD

**Issue by ItalyPaleAle** [go-acme/lego#1149]
I've been able to get a certificate issued following along the sample: https://go-acme.github.io/lego/usage/library/

I can't find any documentation (or samples) for renewing the certificate, however. What are the methods to invoke? What objects should be re-used?

(In general, I think it would be great if lego could get some more detailed documentation on how to use it...)

**Comment by ldez** [comment]
Hello,

there is no difference between renewing and creating a certificate from the API client point of view.

https://github.com/go-acme/lego/blob/f13a88feb51433e16a9271404bf8e95c7195fab2/cmd/cmd_renew.go#L131

**Comment by ItalyPaleAle** [comment]
Thanks for sharing the link to the code.

What about re-using private keys? And what about the registration object? Is there any documentation I can refer to (besides having to read the source of the CLI)?
