### ISSUE TITLE
Adding new alternate domain name does not cause renewal

### ISSUE THREAD

**Issue by ryantm** [go-acme/lego#1155]
Hi.

I'm using lego version 3.3.0, and I issued a certificate for domain "example.com" (with `--days 60`) but then I added "www.example.com" as an alternative name on the certificate (by passing it as -d "www.example.com") and I see:

```
[example.com] The certificate expires in 89 days, the number of days defined to perform the renewal is 60: no renewal.
```

Instead of skipping renewal, I expected lego to redo the certificate because the alternate name got added.

Is this the expected behavior or something that should be fixed?

Has this been fixed in a version after 3.3.0? I checked the changelog and didn't see anything that sounded relevant.

Ryan

**Comment by ldez** [comment]
Hello,

It's expected as a renew command: the renew is based on the number of days.

if you add another domain it will be managed like a simple renew of the main domain: base on the number of days of the main domain.

Adding another domain is not a renewal but the creation of a new certificate.
In this case is better to call the `run` command.
