### ISSUE TITLE
DNS acme errors

### ISSUE THREAD

**Issue by vat9** [go-acme/lego#1160]
Recent changes, within the last four months, have made using the manual dns verification practically impossible.  I've made sure my nameservers respond to CAA requests to get past the recent ACME checks, but still get "acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: query timed out looking up TXT for _acme-challenge" errors no matter how long I let the propagation take place.

There are other build errors with lego and the recent dependency chains, but this DNS error makes the tool useless.

**Comment by ldez** [comment]
Hello,

By "manual dns verification" do you mean the [manual provider](https://go-acme.github.io/lego/dns/manual/) but I'm not sure, so could you provide more information: version, full logs, command line, etc.

**Comment by vat9** [comment]
Attempted with lego built using go1.13 to go1.14.3.  There are other build issues based on dependencies on k8s.io and github.com/googleapis/gnostic/OpenAPIv2 now that gnostic switched the directory name to openapiv2.  (pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2).

For running lego:

lego -m email@example.com --dns manual -d '*.example.com' -d 'example.com' --pem --dns.resolvers 8.8.8.8 [--dns.disable-cp] renew

ends with:

2020/05/15 20:51:53 error: one or more domains had a problem:
[*.example.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: query timed out looking up TXT for _acme-challenge.example.com, url: 
[example.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: query timed out looking up TXT for _acme-challenge.example.com, url: 

even though I set the TXT records on both the primary and secondary authorized name server, wait more the 120 seconds, and let it run.  This was of course after adding CAA records so that lego|acme can get past the first verification stage.

It is difficult to tell from the logs if the failure is in lego or in the verification step picking up an invalid cached _acme-challenge TXT.  I'll stage an environment from an earlier Feb 6, 2020 build that worked, though that version was not requiring CAA record lookup and may no longer function.

**Comment by ldez** [comment]
lego don't have any dependencies to `k8s.io`, so I'm wondering if you would use GOPATH instead of the go modules to build.

We haven't changed the behavior of the manual challenge for a very long time, the problem seems related to DNS resolvers, so I think you have to check your network.

**Comment by vat9** [comment]
GO111MODULE=on
go get -u github.com/go-acme/lego/v3/cmd/lego

would fail on that k8s.io attempt yesterday.   Today I'm just getting a delegate loop "delegation loop github-production-release-asset-2e65be.s3.amazonaws.com ns	r1.amazonaws.com -> amazonaws.com ns	r1.amazonaws.com" but building from source with 'make build' does work.

**Comment by ldez** [comment]
Off-topic:
- Why do you build from sources instead of using our binaries or our Docker images? 
- Why do you use the [manual](https://go-acme.github.io/lego/dns/manual/) DNS challenge instead of the ["exec"](https://go-acme.github.io/lego/dns/exec/) DNS challenge?
- What's your DNS provider?

---

To be sure that the go modules are enabled (use go1.14):
```
GO111MODULE=on go get -u github.com/go-acme/lego/v3/cmd/lego
## or
export GO111MODULE=on
go get -u github.com/go-acme/lego/v3/cmd/lego
```

---

I think that your issue is related to your DNS provider as I explained in my previous answer: https://github.com/go-acme/lego/issues/1160#issuecomment-629669217

**Comment by vat9** [comment]
I don't utilized Docker on any platform.  I also build and run go programs on non-Docker capable systems.

I'll need to dig into more of the Let's Encrypt documentation and acme api before being able to utilize a --dns exec script.

'-dns manual' worked for two rounds of certificate generation and the change may be on something with the acme protocol this time, just like CAA records are now required where before everything would silently continue if your nameserver didn't respond to a CAA query.

**Comment by ldez** [comment]
Why do you build from sources instead of using our [binaries](https://github.com/go-acme/lego/releases)?

>  the change may be on something with the acme protocol this time,

I don't think so, the protocol ACME follow a [RFC](https://tools.ietf.org/html/rfc8555).
I still think that is a DNS problem (maybe a propagation issue)

**Comment by vat9** [comment]
I build everything from source, even my Go builds (and original C compilers were cross compiled from Ken's original sources) see (https://dl.acm.org/doi/10.1145/358198.358210).

Definitely getting time out errors now:

time limit exceeded: last error: read udp [::1]:39510->[2001:4860:4860::8844]:53: i/o timeout

**Comment by ldez** [comment]
Your last log confirm my point of view: it's a DNS issue, not related to lego.

I recommend to explain your problem to the [Let's Encrypt forum](https://community.letsencrypt.org).

For now, I will close this issue but if you are able to prove that it is a lego problem, I will reopen.

**Comment by vat9** [comment]
TTL lowered to 120, my nameserver logs see requests for the _acme-challenge and are responding with the appropriate TXT _acme-challenge, but it falls over on some of the IPv6 servers cached on dns.google (even though IPv4 dns.google queries respond correctly).
