### ISSUE TITLE
[Question] Where are the logs?

### ISSUE THREAD

**Issue by lonix1** [go-acme/lego#1167]
Certbot keeps logs in `/var/log/letsencrypt/`. I'm using docker, so I can mount them in my host using:
````bash
-v /var/log/letsencrypt/:/var/log/letsencrypt/
````
Then:
- I can control log rotation (e.g. `logrotate.d`)
- I can feed them into a logging stack, so I can tell when something went wrong

Where (if at all) does lego save its logs?

Thanks!

---
(I realise lego logs to `stdout`. So a workaround is to use non-ephemeral containers (i.e. not `docker run --rm`), and then we can use `docker logs`. But that defeats the purpose of ephemeral containers.)

**Comment by ldez** [comment]
Hello,

lego display logs only on the standard output, there is no file output.

You can capture the output to file and mount this file in your container.

**Comment by lonix1** [comment]
Thanks for confirming.

That means the workaround is necessary. We must not remove (`--rm`) the container, so we can rely on `docker logs` and the standard json logs in `/var/lib/docker/containers/CONTAINER_ID/CONTAINER_ID-json.log`). But we must be careful not to break anything when we upgrade to a newer version of the docker image.

It is good that lego is simple, but in the future maybe this needs to be reconsidered.
