### ISSUE TITLE
[Feature Request] Add support for ArvanCloud

### ISSUE THREAD

**Issue by sijad** [go-acme/lego#1170]
ArvanCloud is a DNS and CDN provider.
you can find DNS API here: https://arvancloud.com/docs/api/cdn/4.0#tag/DNS

I'd add it if that's ok

**Comment by ldez** [comment]
Hello,

Feel free to open a PR.

**Comment by FaRzad-845** [comment]
https://github.com/go-acme/lego/pull/1172
@sijad help me compelete that ... :)

**Comment by sijad** [comment]
but I already made one #1173, if you were creating this you should've let me know sooner. I've spend hours to create it.
