### ISSUE TITLE
[question] How to delay after dns-01 preCheck?

### ISSUE THREAD

**Issue by solderjs** [go-acme/lego#1177]
I've got an interesting scenario.

I'm using the GoDaddy DNS-01 challenge, but the client is located in the US, the server which actually calls `provider.Present()` is in the EU, and the certificate may be issued in the US or the EU.

Due to this, the `preCheck` may pass and the Let's Encrypt server may fail - because it may be checking against a nameserver in a different region than what the Let's Encrypt server will hit.

I'm wanting to know if there's a way for me to insert a delay AFTER the `preCheck` succeeds by a few seconds, other than by modifying the source code directly.

- `lego/v3/challenge/dns01/dns_challenge.go`

```
        err = wait.For("propagation", timeout, interval, func() (bool, error) {
                stop, errP := c.preCheck.call(domain, fqdn, value)
                if !stop || errP != nil {
                        log.Infof("[%s] acme: Waiting for DNS record propagation.", domain)
                }
                return stop, errP
        })
```

It would also be useful to me to be able to have enough control to override the `preCheck`, but I understand that it may be too niche of a use case to incorporate into the library.

**Comment by tjhiggins** [comment]
You can wrap the precheck function. The example is the pr adds a delay before calling precheck, but you could probably tweak to have it called after.
https://github.com/go-acme/lego/pull/783

**Comment by solderjs** [comment]
Thank you so much! This was exactly what I needed.

I won't post my full example here because I'm actually building around `telebit` and `certmagic`, so there are a few additional, irrelevant layers, but this is the gist of what I did:

```go
import "github.com/go-acme/lego/v3/challenge/dns01"

// ...

DNSChallengeOption := dns01.WrapPreCheck(func(domain, fqdn, value string, orig legoDns01.PreCheckFunc) (bool, error) {
    ok, err := orig(fqdn, value)
    if (ok) {
        time.Sleep(5 * time.Second)
    }
    return ok, err
})

// ... DNSProvider...
```
