### ISSUE TITLE
Route53/ Don't detect DNS delegation with LEGO for sub domain.

### ISSUE THREAD

**Issue by MBlagui** [go-acme/lego#1187]
Hi,

I have a domain xxxxx.xx and delegated a sub domaine to route 53, point NS for this zone, the setup works fine. 

While, when I run lego I get this error:
```
2020/06/13 01:13:36 [INFO] [nexus.lab.xxxxx.xx] acme: Obtaining bundled SAN certificate
2020/06/13 01:13:37 [INFO] [nexus.lab.xxxxx.xx] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5199627810
2020/06/13 01:13:37 [INFO] [nexus.lab.xxxxx.xx] acme: Could not find solver for: tls-alpn-01
2020/06/13 01:13:37 [INFO] [nexus.lab.xxxxx.xx] acme: Could not find solver for: http-01
2020/06/13 01:13:37 [INFO] [nexus.lab.xxxxx.xx] acme: use dns-01 solver
2020/06/13 01:13:37 [INFO] [nexus.lab.xxxxx.xx] acme: Preparing to solve DNS-01
2020/06/13 01:14:03 [INFO] [nexus.lab.xxxxx.xx] acme: Cleaning DNS-01 challenge
2020/06/13 01:14:16 [WARN] [nexus.lab.xxxxx.xx] acme: cleaning up failed: failed to determine Route 53 hosted zone ID: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2020/06/13 01:14:16 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5199627810
2020/06/13 01:14:16 Could not obtain certificates:
        error: one or more domains had a problem:
[nexus.lab.xxxxx.xx] [nexus.lab.xxxxx.xx] acme: error presenting token: route53: failed to determine hosted zone ID: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

lab.xxxxx.xx is hosted on route 53 and I'm trying to setup a DNS verification for this sub domain.

And I see that this is supported by let's encrypt:
https://community.letsencrypt.org/t/dns-challenges-and-ns-delegation/74481/4

As subdomains delegation is not an issue.

For me this is a bug. Looks like lego is looking for the main zone in Route 53 and this the error instead of looking for lab.xxxxx.xx.

Manually I can get the certificate using route 53 DNS challenge.

Tried is with 2 different domains with same setup a sub domaine delegation, don't seem to work even if all the records setup manually works file.

Command:
```
lego --dns route53 -m "m@xxx.xx" -d "nexus.lab.xxxx.xx" --accept-tos run
```

Got the certificate without issue using --dns manual and adding the validation record to route 53 to show that domain delegate was working fine.

Thanks for your help.

**Comment by ldez** [comment]
Hello,

It's a credential error `NoCredentialProviders: no valid providers in chain.`
