### ISSUE TITLE
dns challenge fails on godaddy provider

### ISSUE THREAD

**Issue by mynamewastaken** [go-acme/lego#1191]
I have the same issue doing this via Traefik, so I wanted to dig down a bit. I ran the following on the latest goacme/lego container:
`docker run -e GODADDY_API_KEY=mykey -e GODADDY_API_SECRET=mysecret -m myemail --dns godaddy -d example.org -d '*.example.org' -s https://acme-staging-v02.api.letsencrypt.org/directory -a run`

Resulting in:
```
2020/06/17 02:35:48 No key found for account email. Generating a P384 key.
2020/06/17 02:35:48 Saved key to /.lego/accounts/acme-staging-v02.api.letsencrypt.org/email/keys/email.key
2020/06/17 02:35:48 [INFO] acme: Registering account for email
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/.lego/accounts".

You should make a secure backup of this folder now. This 
configuration directory will also contain certificates and 
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/06/17 02:35:48 [INFO] [example.org] acme: Obtaining bundled SAN certificate
2020/06/17 02:35:48 [INFO] [example.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/66151424
2020/06/17 02:35:48 [INFO] [example.org] acme: Could not find solver for: tls-alpn-01
2020/06/17 02:35:48 [INFO] [example.org] acme: Could not find solver for: http-01
2020/06/17 02:35:48 [INFO] [example.org] acme: use dns-01 solver
2020/06/17 02:35:48 [INFO] [example.org] acme: Preparing to solve DNS-01
2020/06/17 02:35:49 [INFO] [example.org] acme: Cleaning DNS-01 challenge
2020/06/17 02:35:49 [WARN] [example.org] acme: cleaning up failed: godaddy: failed to get TXT records: could not get records: Domain: org; Record: _acme-challenge.example, Status: 422; Body: {"code":"INVALID_BODY","fields":[{"code":"MISMATCH_FORMAT","message":"does not conform to the 'domain' format, based on pattern: /^[^.]{1,63}(\\.[^.]{1,63})+$/","path":"path.domain"}],"message":"Request body doesn't fulfill schema, see details in `fields`"}
 
2020/06/17 02:35:49 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/number
2020/06/17 02:35:49 Could not obtain certificates:
        error: one or more domains had a problem:
[example.org] [example.org] acme: error presenting token: godaddy: failed to get TXT records: could not get records: Domain: org; Record: _acme-challenge.example, Status: 422; Body: {"code":"INVALID_BODY","fields":[{"code":"MISMATCH_FORMAT","message":"does not conform to the 'domain' format, based on pattern: /^[^.]{1,63}(\\.[^.]{1,63})+$/","path":"path.domain"}],"message":"Request body doesn't fulfill schema, see details in `fields`"}
```

I tried with `example.org` and `'*.example.org'` with the same result. I am able to get/set dns records if I manually assemble the curl and talk to godaddy directly.

**Comment by ldez** [comment]
Hello,

> failed to get TXT records: could not get records: Domain: org; Record: _acme-challenge.example, Status: 422; Body: {"code":"INVALID_BODY","fields":[{"code":"MISMATCH_FORMAT","message":"does not conform to the 'domain' format, based on pattern: /^[^.]{1,63}(\\.[^.]{1,63})+$/","path":"path.domain"}],"message":"Request body doesn't fulfill schema, see details in `fields`"}

From your logs, I can see `Domain: org; `, this means that lego is unable to detect your domain probably because the A record is missing.

**Comment by mynamewastaken** [comment]
I'm an idiot. Your comment made me think about records even though everything looked fine - I'd setup a catchall in my router internally. That seemed to work fine and then a few months later the LE setup broke - I didn't connect the two.

I added the option to tell lego to use an external resolver and that worked. Sorry about the non-issue.
