### ISSUE TITLE
time limit exceeded: last error: did not return the expected TXT record

### ISSUE THREAD

**Issue by ubaidilyas** [go-acme/lego#1194]
I am using the below command to generate a ssl s=certificate but the following error occurs. 
COMMAND:
```console
$ lego -d "*.abc.def.xyz" --email abc@def.com --key-type rsa4096 --accept-tos --dns manual --dns-timeout 90 --dns.resolvers 8.8.8.8 run

ERROR:

2020/06/18 17:11:36 [INFO] [*.abc.def.xyz] acme: Obtaining bundled SAN certificate
2020/06/18 17:11:37 [INFO] [*.abc.def.xyz] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5319834125
2020/06/18 17:11:37 [INFO] [*.abc.def.xyz] acme: use dns-01 solver
2020/06/18 17:11:37 [INFO] [*.abc.def.xyz] acme: Preparing to solve DNS-01
lego: Please create the following TXT record in your def.xyz. zone:
_acme-challenge.abc.def.xyz. 120 IN TXT "asdasdasd"
lego: Press 'Enter' when you are done

2020/06/18 17:11:38 [INFO] [*.abc.def.xyz] acme: Trying to solve DNS-01
2020/06/18 17:11:38 [INFO] [*.abc.def.xyz] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/06/18 17:11:38 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/18 17:11:38 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:40 [INFO] [*.*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:42 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:44 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:46 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:48 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:50 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:52 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:54 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:56 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:58 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:00 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:02 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:04 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:06 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:08 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:10 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:12 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:14 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:16 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:18 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:21 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:23 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:25 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:27 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:29 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:31 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:33 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:35 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:37 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:39 [INFO] [*.abc.def.xyz] acme: Cleaning DNS-01 challenge
lego: You can now remove this TXT record from your def.xyz. zone:
_acme-challenge.abc.def.xyz. 120 IN TXT "..."
2020/06/18 17:12:39 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5319834125
2020/06/18 17:12:39 Could not obtain certificates:
	error: one or more domains had a problem:
[*.abc.def.xyz] time limit exceeded: last error: NS kay.ns.cloudflare.com. did not return the expected TXT record [fqdn: _acme-challenge.abc.def.xyz., value: asdasdasd]: 
```

Why is this not working whereas everything is defined properly? I tried finding any such questions but no reference was found. Thanks in advance.

**Comment by ldez** [comment]
Hello,

It's not possible to create double wildcards (`*.*.`) certificate.

**Comment by ubaidilyas** [comment]
My bad. It is just a typo... I was removing my domain.name. let me paste the output again...


2020/06/18 17:11:36 [INFO] [*.abc.def.xyz] acme: Obtaining bundled SAN certificate
2020/06/18 17:11:37 [INFO] [*.abc.def.xyz] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5319834125
2020/06/18 17:11:37 [INFO] [*.abc.def.xyz] acme: use dns-01 solver
2020/06/18 17:11:37 [INFO] [*.abc.def.xyz] acme: Preparing to solve DNS-01
lego: Please create the following TXT record in your def.xyz. zone:
_acme-challenge.*.abc.def.xyz. 120 IN TXT "asdasdasd"
lego: Press 'Enter' when you are done

2020/06/18 17:11:38 [INFO] [*.abc.def.xyz] acme: Trying to solve DNS-01
2020/06/18 17:11:38 [INFO] [*.abc.def.xyz] acme: Checking DNS record propagation using [8.8.8.8:53]
2020/06/18 17:11:38 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/18 17:11:38 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:40 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:42 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:44 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:46 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:48 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:50 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:52 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:54 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:56 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:11:58 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:00 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:02 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:04 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:06 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:08 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:10 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:12 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:14 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:16 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:18 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:21 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:23 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:25 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:27 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:29 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:31 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:33 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:35 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:37 [INFO] [*.abc.def.xyz] acme: Waiting for DNS record propagation.
2020/06/18 17:12:39 [INFO] [*.abc.def.xyz] acme: Cleaning DNS-01 challenge
lego: You can now remove this TXT record from your def.xyz. zone:
_acme-challenge.*.abc.def.xyz. 120 IN TXT "..."
2020/06/18 17:12:39 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5319834125
2020/06/18 17:12:39 Could not obtain certificates:
	error: one or more domains had a problem:
[*.abc.def.xyz] time limit exceeded: last error: NS kay.ns.cloudflare.com. did not return the expected TXT record [fqdn: _acme-challenge.*.abc.def.xyz., value: JZuAc9wru-VsVn6HdZCJboshEXLN5o-Pw_s7Pb7lYQE]:

**Comment by ubaidilyas** [comment]
It was a typo while copy pasting the edited log(made mistake during hiding sensitive data). Editted the question

**Comment by ubaidilyas** [comment]
I use Cloudfare. And i use manual as i am directing it manually to the dns server... Is that wrong...??

**Comment by ldez** [comment]
You don't need to use manual, you just have to use our Cloudflare implementation https://go-acme.github.io/lego/dns/cloudflare/

Manual provider is for DNS that does not provide API.

**Comment by ubaidilyas** [comment]
Ok, I will look into that... but what is the purpose of manual than? Nothing is mentioned in the manual.

**Comment by ldez** [comment]
Manual is for DNS that does not provide API.
