### ISSUE TITLE
dns.resolvers not used for -s

### ISSUE THREAD

**Issue by smtalk** [go-acme/lego#1198]
If --dns.resolvers 8.8.8.8 is specified, it still tries to use /etc/resolv.conf to resolv the acme server:
`2020/06/24 16:19:39 Could not create client: get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-v02.api.letsencrypt.org on 127.0.0.1:53: server misbehaving`

**Comment by ldez** [comment]
The DNS resolvers (`--dns.resolvers`) are only used to manage DNS queries, they are not use for Let's Encrypt API calls.
