### ISSUE TITLE
Unclear error message from cloudflare provider

### ISSUE THREAD

**Issue by Lilja** [go-acme/lego#1213]
I'm currently debugging what the issue for my traefik instance is having.

I'm currently seeing this into the logs, but i'm guessing the issue stems from this sub module.

```
time="2020-07-09T10:46:19Z" level=error msg="Unable to obtain ACME certificate for domains \"dersand.net,*.dersand.net\" : unable to generate a certificate for the domains [dersand.net *.dersand.net]: error: one or more domains had a problem:\n[*.dersand.net] [*.dersand.net] acme: error presenting token: cloudflare: failed to find zone net.: ListZonesContext command failed: error from makeRequest: HTTP status 403: insufficient permissions\n[dersand.net] [dersand.net] acme: error presenting token: cloudflare: failed to find zone net.: ListZonesContext command failed: error from makeRequest: HTTP status 403: insufficient permissions\n" providerName=dnscloudflare.acme
```

I'm having some trouble filtering which is the actual error message. Is it a 403 insufficient permission error, or it it a parsing error because `net.` is not really a domain?

**Comment by ldez** [comment]
Hello,

the error comes from the Cloudflare client https://github.com/cloudflare/cloudflare-go

So I recommend to ask the question to Cloudflare.

**Comment by Lilja** [comment]
I created an issue in https://github.com/cloudflare/cloudflare-go/issues/502. I can't exactly extract the information that they want to continue troubleshoot. Could you help me out?

**Comment by ldez** [comment]
> Can you confirm the issue persists and, if so, what a `dig SOA dersand.net` returns on the machine where the LetsEncrypt daemon runs?

you have to run the command `dig SOA dersand.net` on the machine that run lego.

**Comment by Lilja** [comment]
Looks like I had stupid rules in my dnsmasq in my pihole instance. Resolved.
