### ISSUE TITLE
Can't renew or create certificate with namesilo provider

### ISSUE THREAD

**Issue by redmosaic** [go-acme/lego#1222]
I usually use lego inside traefik container and it handles certificate reneval witout problems but few days ago certificate was expired and saw multible errors in logs:
````
time="2020-07-23T19:20:34Z" level=error msg="Error renewing certificate from LE: {domain.com [*.domain.com]}, error: one or more domains had a problem:\n[*.domain.com] [*.domain.com] acme: error presenting token: namesilo: failed to add record code: 114, details: Invalid Domain Syntax\n[domain.com] [domain.com] acme: error presenting token: namesilo: failed to add record code: 114, details: Invalid Domain Syntax\n" providerName=myresolver.acme
````
Then I installed lego in my arch system and tried to run it manually and got same error:
````
NAMESILO_API_KEY=apikeyapikeyapikeyapikey NAMESILO_POLLING_INTERVAL=600 NAMESILO_PROPAGATION_TIMEOUT=7200 NAMESILO_TTL=3600 lego --accept-tos --email "mail@domain.com" --domains "domain.com" --dns namesilo --dns.disable-cp run
2020/07/23 11:49:40 [INFO] [domain.com] acme: Obtaining bundled SAN certificate
2020/07/23 11:49:41 [INFO] [domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/6060486200
2020/07/23 11:49:41 [INFO] [domain.com] acme: Could not find solver for: tls-alpn-01
2020/07/23 11:49:41 [INFO] [domain.com] acme: Could not find solver for: http-01
2020/07/23 11:49:41 [INFO] [domain.com] acme: use dns-01 solver
2020/07/23 11:49:41 [INFO] [domain.com] acme: Preparing to solve DNS-01
2020/07/23 11:49:42 [INFO] [domain.com] acme: Cleaning DNS-01 challenge
2020/07/23 11:49:43 [WARN] [domain.com] acme: cleaning up failed: namesilo: code: 114, details: Invalid Domain Syntax
2020/07/23 11:49:44 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/6060486200
2020/07/23 11:49:44 Could not obtain certificates:
        error: one or more domains had a problem:
[domain.com] [domain.com] acme: error presenting token: namesilo: failed to add record code: 114, details: Invalid Domain Syntax
````
But when i tried to use namesilo api manually then it worked perfectly:
````
wget -O- "https://www.namesilo.com/api/dnsAddRecord?version=1&type=xml&key=apikeyapikeyapikeyapikey&domain=domain.com&rrtype=TXT&rrhost=_acme-challenge&rrvalue=testtesttesttesttesttesttesttesttesttest333&rrttl=3600"
--2020-07-23 11:45:50--  https://www.namesilo.com/api/dnsAddRecord?version=1&type=xml&key=1f79be432aaf7ce0f0d76a17&domain=domain.com&rrtype=TXT&rrhost=_acme-challenge&rrvalue=testtesttesttesttesttesttesttesttesttest333&rrttl=3600
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving www.namesilo.com (www.namesilo.com)... 198.15.98.43, 64.57.93.73
Connecting to www.namesilo.com (www.namesilo.com)|198.15.98.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
Saving to: ‘STDOUT’

<?xml version="1.0"?>
<namesilo><request><operation>dnsAddRecord</operation><ip>some.ip.addr.nubmers</ip></request><reply><code>300</code><detail>success</detail><record_id>recordidrecordidrecordidrecordid</record_id></reply></namesilo>
````

**Comment by ldez** [comment]
Hello,

I think it's related to the zone name, so it's can be related to your DNS resolvers.

Could you try with several computers in different network?

**Comment by redmosaic** [comment]
Ok. I will try in near future.

**Comment by jrruethe** [comment]
I'm having this exact same issue. Can you expand on what you mean by "related to the zone name"? I'd like to know what I need to do to solve this. Thanks!

**Comment by ldez** [comment]
> Can you expand on what you mean by "related to the zone name"?

When lego is trying to get a certificate, he send some DNS calls to get the "zone", it's more or less your domain.

So as I already say, it can be related to DNS resolvers.

You can try:
```bash
drill your.domain.com. SOA
# or
dig your.domain.com. SOA
```

Maybe you have to play with:
- in lego (`--dns.resolvers`): https://go-acme.github.io/lego/usage/cli/
- in Traefik: https://docs.traefik.io/v2.2/https/acme/#resolvers

> I'm using Lego from Traefik 2.2, and I'm not sure how to get additional logs. I have enabled the Traefik logs, however, is there an easy way to test using Lego directly, with additional logging?

In Traefik, you can get all logs from lego when you set the DEBUG level. There is no additional logs a standalone lego.

**Comment by jrruethe** [comment]
Thank you very much for this tip! I added the following to my Traefik command line, and things are looking better.

```
--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53
```

In case anyone else stumbles upon this, I think I caused my own problem after I set up Pihole on my network. I set the Pihole to be the DNS resolver for everything, and maybe I have something misconfigured that doesn't play nicely with Lego. Using 1.1.1.1 as the resolver for Lego fixed my issue.

**Comment by redmosaic** [comment]
I changed section in traefik.toml from
````
[certificatesResolvers.myresolver.acme]
  email = "mail@domain.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "namesilo"
    delayBeforeCheck = 0
````
to
````
[certificatesResolvers.myresolver.acme]
  email = "mail@domain.com"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "namesilo"
    delayBeforeCheck = 0
    resolvers = ["9.9.9.9"]
````
and now problem comletely resolved.

**Comment by redmosaic** [comment]
In my case problem caused by custom dnsmasq resolver config that changed IP of "A" record to local IP.
