### ISSUE TITLE
Add a warning for DNS providers with strong limitations on API

### ISSUE THREAD

**Issue by dragetd** [go-acme/lego#1229]
I know this is an odd request and checking out the definition files, there is not really a good space to put this information.

But I recently moved over some domains to a different DNS provider. One of my reasons to pick a provider was it's support with LEGO. I picked namecheap.com

I did not do my research properly. I just read 'API access supported' - so I moved my stuff over. My treafik dns-01 lets encrypt setup was not ready, but once I got to it, I found the API option and was surprised to see: You need at least 50$ balance and at least 20 registered domains before you can use the API.

That kind of sucks.

What is your opinion on adding such note like:

"Currently, API access is limited to users with at least 50$ balance and 20 resisted domains (2020)." somewhere on the documentation page?

**Comment by ldez** [comment]
Hello,

I understand your problem, but it's not the goal of lego's documentation to provide this kind of information.

I recommend to read this kind the topic on the LE forum:

> NameCheap is intentionally not included because they do not open API access unless some opaque requirements are met (spend at least $x), failing the first criteria.

https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438

**Comment by TokenRat** [comment]
I came from the traefik documentation and went to the lego notes.

But I understand your view, it is not the responsibility of this project. Oh well, guess it is time to move domains again. :-S

If you see no point in discussing this further, it can be closed. Thanks anyways!

**Comment by dragetd** [comment]
Agreed. Thanks for your view, anyways! :-)

**Comment by ldez** [comment]
Maybe you can contact their support team, from their documentation:

> Enabling API Access
>
> There is no restriction on trying out our APIs in the sandbox environment. However, to enable API access on the production environment, you must meet our requirements. If you don’t meet any of our requirements but still wish to use our APIs in production, contact our support team and we will get back to you.

https://www.namecheap.com/support/api/intro/

**Comment by ldez** [comment]
I find the criteria for accessing the API relatively opaque (no public information) and this limitations is, from my point of view, very poorly documented.

So I think it is our responsibility to overcome this lack of clarity.

Could you open a PR and add the following text in the [namecheap.toml](https://github.com/go-acme/lego/blob/master/providers/dns/namecheap/namecheap.toml) file?

```toml
Additional = '''
To enable API access on the Namecheap production environment, some opaque requirements must be met.

More information in the section [Enabling API Access](https://www.namecheap.com/support/api/intro/) of the Namecheap documentation.
'''
```
