### ISSUE TITLE
Building from cmd directory doesn't create executable in $GOPATH

### ISSUE THREAD

**Issue by r3mb00** [go-acme/lego#1231]
This is an issue for me because I can't run tool from outside the cmd directory.

**Comment by ldez** [comment]
Could you give more details?

**Comment by r3mb00** [comment]
I did go get, then went to cmd dir and execute go build main.go. I expect
to have it builded and have executable in my go/bin/ directory but instead
I have builded executable in current dir which is cmd.

**Comment by ldez** [comment]
I think that you don't know Go, so I recommend to use our [binaries](https://go-acme.github.io/lego/installation/#binaries) or our [Docker image](https://go-acme.github.io/lego/installation/#from-docker).

https://go-acme.github.io/lego/installation/

If you still want to build from sources:
- you have to follow our documentation: https://go-acme.github.io/lego/installation/#from-sources
- or use our Makefile (`make build`)
- or learn more about the [Go](https://golang.org/doc/) toolchain (and use `go install ./cmd/lego/`, `go build` is a command to create a binary, not to install it)
