### ISSUE TITLE
respect deSEC.io's API rate limit (sleep for 0.2 seconds after each request)

### ISSUE THREAD

**Issue by appliedprivacy** [go-acme/lego#1236]
When requesting a certificate with more than 6 SANs using the [deSEC.io](https://go-acme.github.io/lego/dns/desec/) DNS provider, lego will run into [deSEC.io's API rate limit](https://talk.desec.io/t/request-was-throttled/120/3):

```
 error: 429: detail: Request was throttled.
```

To avoid this there are two options:
* use deSEC's [bulk API request](https://desec.readthedocs.io/en/latest/dns/rrsets.html#bulk-operations) (update N records with a single request): 
* sleep for 0.2 seconds after each request

**Comment by ldez** [comment]
Hello,

I learned to the desec client to follow the rate limits: read 5/s and write 3/s.

A PR on lego will follow.
