### ISSUE TITLE
cannot get ACME client googlecloud: unable to acquire config: invalid character 'a' in literal true (expecting 'u')

### ISSUE THREAD

**Issue by Roydon** [go-acme/lego#1248]
I supplied following service_account json file to Traefik pod as config map for `dnsChallenge`

```
    {
    	"type": "service_account",
    	"project_id": "***",
    	"private_key_id": "***",
    	"private_key": "***",
    	"client_email": "traefik@***.iam.gserviceaccount.com",
    	"client_id": "***",
    	"auth_uri": "https://accounts.google.com/o/oauth2/auth",
    	"token_uri": "https://oauth2.googleapis.com/token",
    	"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    	"client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/traefik%40***.iam.gserviceaccount.com"
    }

```

along with `GCE_PROJECT` & `GCE_SERVICE_ACCOUNT` as env. but got following error 

`time="2020-09-06T02:17:52Z" level=error msg="Unable to obtain ACME certificate for domains \"traefik.domain.app\" : cannot get ACME client googlecloud: unable to acquire config: invalid character 'a' in literal true (expecting 'u')" providerName=letsencrypt.acme`

Whats is wrong with the service_account file ?

**Comment by ldez** [comment]
Hello,

What's the content of `GCE_SERVICE_ACCOUNT`?
if this a file path, you have to use `GCE_SERVICE_ACCOUNT_FILE` instead of `GCE_SERVICE_ACCOUNT`
