### ISSUE TITLE
Use a latest specification compliant TOML implementation package

### ISSUE THREAD

**Issue by qlcom** [go-acme/lego#1250]

**Comment by ldez** [comment]
As we do have any configuration files, we don't need to do that.

**Comment by qlcom** [comment]
> As we do have any configuration files, we don't need to do that.

i can't properly understand what you are saying.

`go.mod` file contains `github.com/BurntSushi/toml v0.3.1`

**Comment by ldez** [comment]
As we don't have any configuration files, we don't need to do that.

**Comment by qlcom** [comment]
then, why does `go.mod` file contain `github.com/BurntSushi/toml v0.3.1`?

**Comment by ldez** [comment]
Because we use TOML files as an internal descriptor, to generate some documentation.

**Comment by qlcom** [comment]
then, why you shouldn't use a package that implements the latest TOML specification?

**Comment by ldez** [comment]
Because we don't need

**Comment by qlcom** [comment]
oh, i can't help you.

**Comment by qlcom** [comment]
that package is mostly abandoned by the author.

**Comment by ldez** [comment]
We already know that.
