### ISSUE TITLE
May you support dynv6.com as DNS provider?

### ISSUE THREAD

**Issue by SamLowryMOI** [go-acme/lego#1256]
Hello,

dynv6.com uses a RFC2136 compliant way for TXT updates (see https://dynv6.com/docs/apis). They named lego as software on this site, but I can't find a way to use lego for getting a wildcard cert from LetsEncrypt, or more precisely, use traefik under Docker for this.

Please help. Thank you.

**Comment by ldez** [comment]
Hello,

dynv6 API can be used with:

- an HTTP REST API https://dynv6.com/docs/apis#http.
- the [RFC2136](https://tools.ietf.org/html/rfc2136) https://dynv6.com/docs/apis#dns-update

lego support the [RFC2136](https://tools.ietf.org/html/rfc2136) API but not the HTTP API.

So you have to use the following documentation to configure the provider: https://go-acme.github.io/lego/dns/rfc2136/

**Comment by SamLowryMOI** [comment]
Hello Idez,

thanks for the very quick reply. I didn't expect a RFC2136 item in the provider list, sorry.

I tried my best for a few hours but I can't get it working. 
<pre><code>docker run -it 
	-e RFC2136_NAMESERVER=ns1.dynv6.com 
	-e RFC2136_TSIG_ALGORITHM=hmac-sha512 
	-e RFC2136_TSIG_KEY=tsig-123.dynv6.com 
	-e RFC2136_TSIG_SECRET=YourSHAREDsecret==
	-e RFC2136_TTL=60 
goacme/lego 
	--accept-tos 
	--dns rfc2136 
	--dns.resolvers 8.8.8.8:53 
	--domains bla.dynv6.net  
	--email me@bla.org run  

2020/09/24 10:25:52 No key found for account me@bla.org. Generating a P256 key.
2020/09/24 10:25:52 Saved key to /.lego/accounts/acme-v02.api.letsencrypt.org/me@bla.org/keys/me@bla.org.key
2020/09/24 10:25:53 [INFO] acme: Registering account for me@bla.org
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/09/24 10:25:53 [INFO] [bla.dynv6.net] acme: Obtaining bundled SAN certificate
2020/09/24 10:25:54 [INFO] [bla.dynv6.net] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/7433272683
2020/09/24 10:25:54 [INFO] [bla.dynv6.net] acme: Could not find solver for: tls-alpn-01
2020/09/24 10:25:54 [INFO] [bla.dynv6.net] acme: Could not find solver for: http-01
2020/09/24 10:25:54 [INFO] [bla.dynv6.net] acme: use dns-01 solver
2020/09/24 10:25:54 [INFO] [bla.dynv6.net] acme: Preparing to solve DNS-01
2020/09/24 10:25:54 [INFO] [bla.dynv6.net] acme: Cleaning DNS-01 challenge
2020/09/24 10:25:54 [WARN] [bla.dynv6.net] acme: cleaning up failed: rfc2136: failed to remove: DNS update 
failed: dns: domain must be fully qualified
2020/09/24 10:25:54 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/7433272683
2020/09/24 10:25:54 Could not obtain certificates:
        error: one or more domains had a problem:
[bla.dynv6.net] [bla.dynv6.net] acme: error presenting token: rfc2136: failed to insert: DNS update failed: dns: domain must be fully qualified</code></pre>

Tried it with "bla.dynv6.net." instead of "bla.dynv6.net". Got error "Domain name ends in a dot".

Deleting and adding a TXT record with nsupdate works like expected.

<pre><code>nsupdate &lt;&lt;EOF
  server ns1.dynv6.com
  zone bla.dynv6.net
  update delete bla.dynv6.net TXT
  update add bla.dynv6.net 60 TXT "Got It"
  key hmac-sha256:tsig-123.dynv6.com YourSHAREDsecret==
  send
EOF</code></pre>

What do I wrong?

**Comment by SamLowryMOI** [comment]
I have a guess. On [https://dynv6.com/docs/apis#dns-update](url) it said
<pre><code>We require the zone command (l. 3) for authorization. Your updates will be rejected, if the zone does not match the provided key (l. 8). </code></pre>

But there is no parameter for the zone in lego, is it? Maybe the lack of the zone command causes the error?

**Comment by pbox2k** [comment]
Hello SamLowryMOI,
I had the same issue. After doing some digging, the error seems to be caused by the dns library.
At https://github.com/miekg/dns/blob/master/zmsg.go#L1002 it checks if the TSIG Algorithm is fully qualified.

So by making the `RFC2136_TSIG_ALGORITHM` value fully qualified:

`-e RFC2136_TSIG_ALGORITHM=hmac-sha512.`

I was able to successfully request a certificate.

**Comment by SamLowryMOI** [comment]
Hello pbox2k,
after a couple of hours I got a deeper look in debugging go, lego source code and RFC2136 than I ever wanted to. Think I was on the right way - but YOU SAVED MY WEEKEND!

Why lego dotted the domains and not the algorithm, who knows. Deleting the TXT record still don't work, but I think it is a fault of dynv6. Lego seems to be conformed to the RFC (and I'm very sad that I can assess this now).

But I got my cert, all ran well. So again, thank you very much!

**Comment by dmke** [comment]
> Why lego dotted the domains and not the algorithm, who knows.

Just an oversight. I've added a PR to ensure the algorithm is fully qualified.

> Deleting the TXT record still don't work, but I think it is a fault of dynv6.

I'll talk to @corny about his tomorrow.

**Comment by SamLowryMOI** [comment]
> I've added a PR to ensure the algorithm is fully qualified.

Good idea, especially because the error message is a bit misleading.

> I'll talk to @corny about his tomorrow.

As I said, Lego is RFC compliant. 
- Before adding the TXT record it deletes all TXT records for _acme-challenge.bla.dynv6.net according to [RFC2136 2.5.2]. This works.
- After the cert is received, it deletes only the added TXT record according to [RFC2136 2.5.4]. I tried it with nsupdate.exe, too. Dynv6 didn't react to either.

For me it makes sense to just delete the added record. But why should there be another TXT record with the same name? Maybe that's why it's not working? I have no idea.

**Comment by dmke** [comment]
> But why should there be another TXT record with the same name?

I can think of two scenarios off the top of my head:

1. A previous run of lego was aborted before it had the chance to clean up (either by interrupt/Ctrl-C, or because of a runtimer error/panic).
2. You've switched from another ACME client which didn't took care of cleaning up.

> I tried it with nsupdate.exe, too. Dynv6 didn't react to either.

Can you elaborate?

**Comment by SamLowryMOI** [comment]
> I can think of two scenarios off the top of my head:
>[...]
 
That is exactly my opinion. It is necessary to delete **all** TXT entries with this name. Even if you've only just created one. So why not delete all TXT entries the second time, instead of just a specific one? And since there is no point in having multiple TXT entries with the same name, attempts to delete just a specific TXT entry may be ignored.

> Can you elaborate?

In linux:
```
nsupdate -d <<EOF
  server ns1.dynv6.com
  zone bla.dynv6.net
  update delete _acme-challenge.bla.dynv6.net TXT
  key hmac-sha256:tsig-123.dynv6.com YourSHAREDsecret==
  send
EOF
```
You'll find in output:
Name | TTL | Class | Type
```           
;; UPDATE SECTION:
_acme-challenge.bla.dynv6.net. 0 ANY  TXT
```
[RFC2136 2.5.2] means delete all TXT records with name '_acme-challenge.bla.dynv6.net.'. No error. Works. 

```
nsupdate -d <<EOF
  server ns1.dynv6.com
  zone bla.dynv6.net
  update del _acme-challenge.bla.dynv6.net 0 TXT "ABCDEF1234567890"
  key hmac-sha256:tsig-123.dynv6.com YourSHAREDsecret==
  send
EOF
```
You'll find in output:
Name | TTL | Class | Type | Rdata           
```
;; UPDATE SECTION:
_acme-challenge.bla.dynv6.net. 0 NONE TXT     "ABCDEF1234567890"
```
[RFC2136 2.5.4] means delete TXT record with name '_acme-challenge.bla.dynv6.net.' and value 'ABCDEF1234567890'. No error. But doesn't work. TXT record is still there. 

It may be better to delete all TXT records the second time ('Cleaning DNS-01 challenge') as well.

**Comment by theofaron** [comment]
dynv6.com now supports deleting specific records and works fine with lego!

**Comment by SamLowryMOI** [comment]
dynv6.com now supports deleting specific records and works fine with lego!

**Comment by tanishqmanuja** [comment]
I am still not able to get this working, can someone point me to a guide or share a traefik config suitable for this ?

**Comment by SamLowryMOI** [comment]
@tanishqmanuja 
I'm sorry, it was all a long time ago. I haven't worked with lego or traefik since then. But everything worked perfectly. Unfortunately, I don't have the time to get back into the subject. However, the documentation is all helpful and some of it is mentioned here. You should also be more specific with your questions, “doesn't work” rarely leads to success.

**Comment by tanishqmanuja** [comment]
@SamLowryMOI thanks, and sorry for the generic question. My traefik config had both static and dynamic files as they call it in v3. Finally figured it out thanks to your suggestion above ... After not getting anything from the docs I literally copy pasted and this entire GitHub discussion to GPT 😁 and voila!

**Comment by SamLowryMOI** [comment]
Glad I could help (`<Irony off />`).
