### ISSUE TITLE
gcloud DNS provider and private zones

### ISSUE THREAD

**Issue by sebastien-baillet** [go-acme/lego#1257]
Hi,

I have an issue with this provider as I get this error when requesting a certificate:
```
2020/09/25 15:19:47 [INFO] [myapp.myproject.gcp.myenterprise.com] acme: Obtaining bundled SAN certificate
2020/09/25 15:19:47 [INFO] [myapp.myproject.gcp.myenterprise.com] AuthURL: https://ca.myenterprise.com/acme/acme/authz/*****************************
2020/09/25 15:19:47 [INFO] [myapp.myproject.gcp.myenterprise.com] acme: Could not find solver for: tls-alpn-01
2020/09/25 15:19:47 [INFO] [myapp.myproject.gcp.myenterprise.com] acme: Could not find solver for: http-01
2020/09/25 15:19:47 [INFO] [myapp.myproject.gcp.myenterprise.com] acme: use dns-01 solver
2020/09/25 15:19:47 [INFO] [myapp.myproject.gcp.myenterprise.com] acme: Preparing to solve DNS-01
2020/09/25 15:19:48 [INFO] [myapp.myproject.gcp.myenterprise.com] acme: Cleaning DNS-01 challenge
2020/09/25 15:19:48 [WARN] [myapp.myproject.gcp.myenterprise.com] acme: cleaning up failed: googlecloud: no public zone found for domain myproject.gcp.myenterprise.com. 
2020/09/25 15:19:48 [INFO] Deactivating auth: https://ca.myenterprise.com/acme/acme/authz/*****************************
2020/09/25 15:19:48 [INFO] Unable to deactivate the authorization: https://ca.myenterprise.com/acme/acme/authz/*****************************
2020/09/25 15:19:48 Could not obtain certificates:
	error: one or more domains had a problem:
[myapp.myproject.gcp.myenterprise.com] [myapp.myproject.gcp.myenterprise.com] acme: error presenting token: googlecloud: no public zone found for domain myproject.gcp.myenterprise.com.

```
I've found the code containing the error message |here](https://github.com/go-acme/lego/blob/master/providers/dns/gcloud/googlecloud.go#L329). I don't fully understand why this test is done, why can't the zone type be 'private', especially that in our case, we are using a private acme server that issue certificates for private domains only.

**Comment by ldez** [comment]
Hello,

I'm not a specialist in Google Cloud, but as the DNS challenge required to be able to add a public TXT record, if a domain doesn't have a public zone, the challenge will never work.

**Comment by sebastien-baillet** [comment]
I don't see any reference to public TXT record for DNS challenge in the RFC, just TXT record. In case of Let's Encrypt, of course, it need to be public, but in case of internal/private CA, I don't see any reason for the TXT record to be public. No?

**Comment by sebastien-baillet** [comment]
I just rebuild lego after modifying the condition at [providers/dns/googlecloud.go:l39](https://github.com/go-acme/lego/blob/master/providers/dns/gcloud/googlecloud.go#L329) by adding `|| z.Visibility == "private"`. After test I was able to issue a certificate.
I can make a PR, but as I don't understand the original condition (which is `if z.Visibility == "public" || z.Visibility == ""`), I'm not sure how to modify it in the correct way.

**Comment by ldez** [comment]
I think that has to be an option (`GCE_ALLOW_PRIVATE_ZONE`), false by default.

**Comment by ldez** [comment]
Just out of curiosity, what do you use as an ACME implementation to manage this in your private network?

**Comment by sebastien-baillet** [comment]
We use [step-ca](https://github.com/smallstep/certificates).

I will try to submit to PR.

**Comment by sebastien-baillet** [comment]
I'm new to Go, should I commit go.mod and go.sum?

**Comment by ldez** [comment]
you should not have any changes to these files.

**Comment by sebastien-baillet** [comment]
I think my IDE (Goland) auto updates those files

**Comment by ldez** [comment]
run a `go mod tidy`

**Comment by sebastien-baillet** [comment]
```
$ go version
go version go1.15.2 linux/amd64
```
`go mod tidy` doesn't seems to do anything (no modification in any file)

**Comment by ldez** [comment]
Check your Go version in Goland and revert the change on `go.mod` and `go.sum`

**Comment by sebastien-baillet** [comment]
Commit details:
https://github.com/sebastien-baillet/lego/commit/711c5d8f591e37107a729d839d0aa38aff94bd2c

I open a PR, we'll continue this discussion there

**Comment by sebastien-baillet** [comment]
Ok, i'm removing it

**Comment by sebastien-baillet** [comment]
PR https://github.com/go-acme/lego/pull/1258 created
