### ISSUE TITLE
[CLI] generate certbot like files

### ISSUE THREAD

**Issue by mhf-ir** [go-acme/lego#1264]
How to use lego **CLI** to generate

* fullchain.pem
* cert.pem
* chain.pem
* privkey.pem

**Comment by dmke** [comment]
Executing `lego run` will look like this:

```console
$ cd .../some/where
$ dist/lego --domains example.com [some options omitted] run
```

will create a directory `.../some/where/.lego/certificates`:

```
$ ls .lego/certificates
example.com.crt	example.com.issuer.crt	example.com.json	example.com.key
```

where:

- `$domain.crt` and `$domain.key` are the server certificate and key (equivalent to `cert.pem` and `privkey.pem`),
- `$domain.issuer.crt` is the CA certificate (= `chain.pem)`, and
- `$domain.json` contains some meta information.

To create an equivalent to the `fullchain.pem`, just run

```
$ cat .lego/certificates/$domain.issuer.crt .lego/certificates/$domain.crt > .lego/certificates/$domain.fullchain.crt
$ chmod 0600 .lego/certificates/$domain.fullchain.crt # optional, for consistency
```

Notes:

1. The path of the `.lego` directory can be changed by explicitly adding a `--path` flag (like `lego --path /opt/lego/ ...`).
2. All `.crt` and the `.key` file are PEM encoded (they're just text files), the file extension (usually) doesn't matter.

**Comment by dmke** [comment]
Notes to self:

- improve https://go-acme.github.io/lego/usage/cli/ and state more obvious where to find the certificate files
- maybe add a `--fullchain` flag to auto-generate the aforementioned full chain file

**Comment by dmke** [comment]
@mhf-ir: I'm sorry, I've misread the code. Lego actually already writes the full chain to `$domain.crt`. I've updated my answer above: you don't need to `cat domain.issuer.crt domain.crt > domain.fullchain.crt`.

**Comment by CsarGabriel** [comment]
This is old, but I end two times here. In my case the generated **$domain.crt**, fail in some applications, to correct this I navigate to a page that uses the new certificate generated and get the PEM (chain) file using the Firefox certificate viewer in the **Miscellaneous** section to update the server.

The result have 3 certificates and resolve all the problems. maybe there is a more elegant solution, but this allows to keep all running while research a definitive solution.
![Screenshot from 2024-06-14 18-21-57](https://github.com/go-acme/lego/assets/61531635/55d16e67-97b3-4756-8f4a-c7c15d023fa9)
