### ISSUE TITLE
 Provider does not support requested mode mode=default provider=azure

### ISSUE THREAD

**Issue by Keithsc** [go-acme/lego#1268]
I am getting a provider error while using another project "[acmeproxy](https://github.com/mdbraber/acmeproxy)" that uses lego as the dns provider.  I have raised an [issue](https://github.com/mdbraber/acmeproxy/issues/8) with acmeproxy but though I would ask here to see if anyone recognises the error and could point me in the right direction.

"Provider does not support requested mode mode=default provider=azure"

Thanks for looking.

**Comment by ldez** [comment]
Hello, it's an error with acmeproxy, it's not related to lego.
