### ISSUE TITLE
Add support for .edgerc file on Akamai EdgeDNS provider

### ISSUE THREAD

**Issue by asenci** [go-acme/lego#1269]
Would improve user experience when running directly from the CLI (similar to Route53 credentials file).
I can prepare a PR with the required changes, if this is something you would consider including. 😊 
Cheers

**Comment by dmke** [comment]
> I can prepare a PR with the required changes, [...]

Please do :-)

**Comment by asenci** [comment]
Sorry, have been a few busy months since I opened this issue. Submitting the PR now... 😅
