### ISSUE TITLE
Invalid FQDN for wildcard DNS challenge if target domain have CNAME record

### ISSUE THREAD

**Issue by loganmzz** [go-acme/lego#1272]
I'm using Traefik 2 to generate wildcard certificate through DNS challenge.

My "public" domain (e.g. `company.com`) is managed by OVH and I expose services running on a specific host with a "public" domain (e.g. `*.host01.node.company.com`) through wildcard CNAME targetting another managed domain service (e.g. `host01.provider.com.`.

However, it seems OVH is called for the CNAME target domain zone which is refused as it's not managed by OVH:

```
time="2020-10-20T07:38:57Z" level=info msg="Testing certificate renew..." providerName=letsencrypt-dns.acme
time="2020-10-20T07:38:57Z" level=info msg="Testing certificate renew..." providerName=letsencrypt-http.acme
time="2020-10-20T07:38:58Z" level=info msg="Renewing certificate from LE : {Main:*.host01.node.company.com SANs:[]}" providerName=letsencrypt-dns.acme
time="2020-10-20T07:40:45Z" level=error msg="Error renewing certificate from LE: {*.host01.node.company.com []}, error: one or more domains had a problem:\n[*.host01.node.company.com] time limit exceeded: last error: could not determine the zone: unexpected response code 'REFUSED' for host01.provider.com.\n" providerName=letsencrypt-dns.acme
```

**Comment by dauriata** [comment]
You would have to set LEGO_EXPERIMENTAL_CNAME_SUPPORT  to true but unfortunately it is not used in OVH DNS-01 implementation, I proposed a fix in PR #1467
