### ISSUE TITLE
Not working on AMD64

### ISSUE THREAD

**Issue by genisysram** [go-acme/lego#1273]
Hi 
Thanks for the code , but the code is  not working on AMD64 , by throwing a error

cmd/certs_storage.go:200:28: wrapperFunc: use strings.ReplaceAll method in `strings.Replace(domain, "*", "_", -1)` (gocritic)
	safe, err := idna.ToASCII(strings.Replace(domain, "*", "_", -1))

**Comment by ldez** [comment]
Hi,
The error is not related to the compilation but to an update of a linter rule.

You can build anyway.

I will create a PR to update the linter in our CI.
