### ISSUE TITLE
"404 - The given domain is not registered" with GoDaddy and Caddy 2

### ISSUE THREAD

**Issue by drbw** [go-acme/lego#1274]
I'm trying to use the lego_deprecated DNS plugin for Caddy 2.2.1 to set up certificate generation for internal-only servers. Our TLD is example.com, the subdomain in question is *.staging.example.com. example.com is hosted with GoDaddy, but also on an internal PowerDNS server.

Internally, *.staging.example.com is a CNAME for staging.example.com. staging.example.com is an A record for the server Caddy is running on (in a Docker container). Externally, staging.example.com shouldn't exist, but I tried setting an A record for it without any change. The Caddy server can not be reached from the outside.

The goal is to be able to just throw any virtualhost on the Caddy server as necessary, e. g. www.staging.example.com, shop.staging.example.com etc without having to set up individual RRs for them, but still being able to generate valid certificates.

The following is my Caddy config for the test run. (Authentication is in Env variables.)

```
{
  acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
  email admins@example.com
}

www.staging.example.com {
  reverse_proxy / staging-wordpress:80
  tls { dns lego_deprecated godaddy }
}
```

This is the error I'm getting:

```
{
  "level": "error",
  "ts": 1603384500.3116715,
  "logger": "tls.obtain",
  "msg": "will retry",
  "error": "[www.staging.example.com] Obtain: [www.staging.example.com] solving challenges: presenting for challenge: godaddy: failed to get TXT records: could not get records: Domain: staging.example.com; Record: _acme-challenge.www, Status: 404; Body: {\"code\":\"UNKNOWN_DOMAIN\", \"message\":\"The given domain is not registered, or does not have a zone file\"}\n (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/16247326/171109003) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)",
  "attempt": 2,
  "retrying_in": 120,
  "elapsed": 65.883899801,
  "max_duration": 2592000
}
```

I'm not sure what that's trying to tell me - of course, the domain we bought is example.com, not staging.example.com. However, even when I create the A record for staging.example.com and change the above Caddy config to just use staging.example.com, I get practically the same error:

```
{
  "level": "error",
  "ts": 1603384212.695005,
  "logger": "tls.obtain",
  "msg": "will retry",
  "error": "[staging.example.com] Obtain: [staging.example.com] solving challenges: presenting for challenge: godaddy: failed to get TXT records: could not get records: Domain: staging.example.com; Record: _acme-challenge, Status: 404; Body: {\"code\":\"UNKNOWN_DOMAIN\",\"message\":\"The given domain is not registered, or does not have a zone file\"}\n (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/16247326/171107366) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)",
  "attempt": 6,
  "retrying_in": 1200,
  "elapsed": 1229.225932228,
  "max_duration": 2592000
}
```

I'm not sure where the problem is since the documentation on all involved components is extremely sparse (or maybe I'm just too daft). I'm not sure what exactly lego does in the process of submitting the correct request, what GoDaddy expects of it or what LE expects of the resulting RRs.

I'd be willing to part with the wildcard idea even though it'd be neat, but since it doesn't even work with staging.example.com itself (which is a normal A record internally and externally), I don't know how to proceed. For now, all I need are valid certificates for anything under the staging subdomain.

I'm aware that having two different "authoritative" DNS servers is bad, but that's something we absolutely can't get rid of. Seeing how common that is, I'd be surprised if it's the root of the issue, though.

**Comment by ldez** [comment]
Hello, I recommend asking your question in the Caddy forum https://caddy.community/

**Comment by drbw** [comment]
OK, done. https://caddy.community/t/404-the-given-domain-is-not-registered-with-godaddy-and-caddy-2/10229

Feel free to close this.
