### ISSUE TITLE
Add custom AWS session config support to Route53 provider

### ISSUE THREAD

**Issue by relvira** [go-acme/lego#1281]
Hi Folks,

The Route53 provider can be customized via [Config](https://github.com/go-acme/lego/blob/master/providers/dns/route53/route53.go#L37) and [NewDNSProviderConfig](https://github.com/go-acme/lego/blob/master/providers/dns/route53/route53.go#L100) at the moment.

When using AWS SDK for Golang, the session can be further customized to change other settings like the [endpoint URL](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config.WithEndpoint). 

This comes in very handy as having the ability to change the endpoint URL allows us to have a local route53 via [localstack](https://github.com/localstack/localstack) and use that for integration testing or local development.

I'd like to submit a pull request that allows specifying a custom AWS session config to the Route53 provider via NewDNSProviderConfig that the provider would use to create an AWS session.

Let me know if this is something you're keen on, suggestions on other approaches are also welcome.

Cheers,
Rafa.

**Comment by ldez** [comment]
Hello,

the `NewDNSProviderConfig` take a `Config` and in this struct you have a field `Client             *route53.Route53`.
If you provide a `Client` you are able to create a custom session.

**Comment by relvira** [comment]
I can confirm your suggestion works, @ldez. I completely missed the `Config` struct had a `Client` field.

Closing this one as it's not really an issue, thank you so much for your reply 🙇🏼
