### ISSUE TITLE
Setting up renew on cron

### ISSUE THREAD

**Issue by madprops** [go-acme/lego#1287]
I have this in crontab:
>55 5 * * * lego --email="me@email.com" -d *.domain.com -d domain.com --dns="linodev4" renew --days 5

Why would that fail?
I woke up to an expired cert

Also, what can I add so it reloads apache if it succeeds?
Since that's required to apply the cert

Thanks.

**Comment by ldez** [comment]
> Why would that fail?

Could you provide the log?

**Comment by madprops** [comment]
Hmm I noticed something
If I run the command anywhere outside /root/
I get something like:
>No key found for account me@email.com. Generating a P384 key.
>Saved key to /root/go/src/github.com/go-acme/.lego/accounts/acme-v02.api.letsencrypt.org/me@email.com/keys/me@email.com.key
>Account me@email.com is not registered. Use 'run' to register a new account.

If I run it inside /root/ it works
Not sure why, but I could just make a script to cd to /root/ before running that
But how do I know if it succeeds, to reload apache, just use "&&"?

**Comment by madprops** [comment]
> > Why would that fail?
> 
> Could you provide the log?

Sorry I couldn't find a log, but I did test running the command and see that error which I thought was the problem

**Comment by HackingGate** [comment]
I have the same issue, the same command works for `run` but not for `renew`.

```
Account email@example.com is not registered. Use 'run' to register a new account.
```
