### ISSUE TITLE
DNS provider INWX randomly failing / inwx 2002

### ISSUE THREAD

**Issue by dragetd** [go-acme/lego#1297]
I am trying to use the DNS provider inwx.de

Usually using it with traefik, which repeatedly causes the inwx issue `'2002' Command error`, which is sent by INWX if a command is send after a logout. I suspect some race conditions if multiple domains are handled via traefik.

For debugging purposes, I tried using the CLI which also fails somewhat randomly:

The CLI command I use is:
```
lego --email="admin@mydomain.de" --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains=mydomain.de --dns="inwx" run
```
or even
```
lego --email="admin@mydomain.de" --server=https://acme-staging-v02.api.letsencrypt.org/directory --domains=mydomain.de --dns="inwx" --dns.resolvers=8.8.8.8 --dns.disable-cp run
```

which works in 5% of the cases, but often enough it does not.

Often the DNS propagation does not seem to work. It runs into the 60s timeout or even detects the wrong token as the TXT record. Any advice on how I could debug this further and improve the INWX support?

Related to https://github.com/traefik/traefik/issues/6989

**Comment by ldez** [comment]
Ping @smueller18

**Comment by smueller18** [comment]
Hi @dragetd,

let's get started with the CI command first. When I was using Traefik before I switched to [cert-manager](https://cert-manager.io/) to handle ACME requests, I also discovered problems with the default timeout of 60s. It seems like INWX needs a couple of minutes until the DNS change is propagated. It usually took more than 5 minutes. In my old setup, I used a propagation timeout of 420s.
Please set the env variable `INWX_PROPAGATION_TIMEOUT` to at least 420s, run the CLI commands again and share the results.

**Comment by dragetd** [comment]
I had been experimenting with the timeouts and increasing them, checking public, local and INWX(!) name-servers in parallel for propagation. I could not find a pattern that led me to believe I would have to increase them even more. Sometimes it looked like google (8.8.8.8) knew before INWX or would respond with an invalid challenge…? x.x


Anyways, I did some tests now with the timeout set to 7 minutes:
Test1: 2:37min -> success
Test2: 3:46min -> success
Test3: 0:07min -> success

This might depend on the time of day or random other factors, but I think the high instability does in fact cause the issues.

Since I am using traefik, it might re-try this anyways every now and then, which could be the reason why it worked apparently for some time, but at some random later date I got certificate expiration warnings from LE.

May I create a PR that addresses this at the code level (would overwrite the default to 360s and document it) or would you prefer this to be a documentation-only change or no change at all?

**Comment by ldez** [comment]
@dragetd you can on a PR to change the default propagation timeout

**Comment by ad-m** [comment]
Have you considered contacting INWX support for the recommended DNS propagation value? It is possible that they have a specific propagation latency value they target.

**Comment by dragetd** [comment]
Hmm, okay, I will quickly ask the support if they have any explanation why this could be. :)

**Comment by dragetd** [comment]
Did not get a response. o.o Unusual, but I'll try asking again in a few days. But whatever their answer is, I think upping the default does not hurt.

I have not yet passed the 90 days auto-renewal but if something seems to not work with the default of 360s, I will report it.

PR #1314
