### ISSUE TITLE
custom DNS resolver question

### ISSUE THREAD

**Issue by relvira** [go-acme/lego#1306]
Hello folks,

Is there a way we can setup lego to use a custom DNS resolver when using it as a library rather than a cli? I see there's a way of doing that in the cli via `dns.resolvers` but not when using lego as a library. Would you have further advice?

Thanks for your help.

**Comment by ad-m** [comment]
Here is it: 
https://github.com/go-acme/lego/blob/88823a5c92f8d398ccddf7615771e9212bfaec62/challenge/dns01/nameserver.go#L66
https://github.com/go-acme/lego/blob/37746be75f31b4d6799d96e15734eb1480808130/cmd/setup_challenges.go#L117

**Comment by relvira** [comment]
hey @ad-m - That works, I now see I can do something like this to get it working:
`client.Challenge.SetDNS01Provider(r53, dns01.AddRecursiveNameservers([]string{"localhost:8053"}))` 

Thanks for your fast response!
