### ISSUE TITLE
Utilize versioning that matches go.mod best practices

### ISSUE THREAD

**Issue by itsmontoya** [go-acme/lego#1316]
I've noticed that the release tags are up in the v4.x.x range. The issue is that go.mod isn't friendly with major versions over 2. Is there any way we could normalize this to match the intentions of go.mod?

**Comment by ldez** [comment]
Hello,

we follow the Go rule to handle v2+ version https://golang.org/ref/mod#major-version-suffixes

https://github.com/go-acme/lego/blob/136f159d53aed184119ccc603c5f84977adbe1f0/go.mod#L1

There are no other constraints than the name of the module and the name of the import.
