### ISSUE TITLE
ClouDNS: acme challenge fails frequently

### ISSUE THREAD

**Issue by david-aggeler** [go-acme/lego#1330]
ClouDNS allows for multiple TXT records of the same host. Which in my opinion is correct

This creates following issue:
- The dns-01 challenge fails, when there is one ore more pre-existing DNS entries (e.g. from previous attempts)

ClouDNS has more name servers than those that appear in the propagation phase (currently 8 NS for my zone, only 4 that appear authoritative to lego)
- This will cause the during secondary verification. It may fails fail with NXDOMAIN

A tested fix is available, but I was not yet able to push it to github

**Comment by ldez** [comment]
NXDOMAIN means Non-eXistent Domain: your domain is not globally available when you run lego.

**Comment by david-aggeler** [comment]
I'm all for automation where possible. ClouDNS provides an API to monitor the sync status between their servers. 

This is what my fix will do. The sync is currently part if the set not the solve, because I didn't want to change the interface.

`2021/01/26 07:38:14 [INFO] [docker-test.mydomain.com] acme: Preparing to solve DNS-01
2021/01/26 07:38:14 [INFO] Wait for Nameserver sync on docker-test.mydomain.com [timeout: 3m0s, interval: 10s]
2021/01/26 07:38:14 [INFO] [docker-test.mydomain.com] Sync 0/8 complete
2021/01/26 07:38:24 [INFO] [docker-test.mydomain.com] Sync 2/8 complete
2021/01/26 07:38:34 [INFO] [docker-test.mydomain.com] Sync 3/8 complete
2021/01/26 07:38:44 [INFO] [docker-test.mydomain.com] Sync 3/8 complete
2021/01/26 07:38:54 [INFO] [docker-test.mydomain.com] Sync 3/8 complete
2021/01/26 07:39:04 [INFO] [docker-test.mydomain.com] Sync 4/8 complete
2021/01/26 07:39:15 [INFO] [docker-test.mydomain.com] Sync 4/8 complete
2021/01/26 07:39:25 [INFO] [docker-test.mydomain.com] Sync 8/8 complete
2021/01/26 07:39:25 [INFO] [docker-test.mydomain.com] acme: Trying to solve DNS-01
2021/01/26 07:39:25 [INFO] [docker-test.mydomain.com] acme: Checking DNS record propagation using [172.27.240.1:53]
2021/01/26 07:39:35 [INFO] Wait for propagation [timeout: 3m0s, interval: 10s]
2021/01/26 07:39:46 [INFO] [docker-test.mydomain.com] The server validated our request
2021/01/26 07:39:46 [INFO] [docker-test.mydomain.com] acme: Cleaning DNS-01 challenge
2021/01/26 07:39:46 [INFO] [docker-test.mydomain.com] acme: Validations succeeded; requesting certificates
2021/01/26 07:39:47 [INFO] [docker-test.mydomain.com] Server responded with a certificate.`

**Comment by ldez** [comment]
Sorry but I'm not sure about your diagnosis.

ping @tzakrajs

**Comment by david-aggeler** [comment]
Yes, the issue itself is very brief. I've submitted it to submit a pull request. Unfortunately, the out-of-the box lego client does not report essential DNS parts (like a detailed list servers queried and the conclusion drawn from it). To me that was needed for troubleshooting. Therefore attaching a simple 'error' at the end did not make much sense to me. The pull request my explain it better. **I had to debug** the code to get a handle on it. I don't understand absence of success messages when talking to external components.

First, lego sometimes complained that my _acme-challenge is wrong (from my computers nslookup perspective), but there was no API error while setting it. So where did it take the old value from? So at some point, I realized by accident, that I had multiple TXT records for _acme-challenge.host.example.com in the web interface of ClouDNS. So I cleaned them manually and I got a step further. So I've added a simple cleanup loop before setting the DNS. 

But that was not enough. The client checks pns10*.cloudns.net and once it was happy, it handed the check to the letsenypt server, which then failed. Looking at the API with postman I saw, that in the failed cases the ns10*.cloudns.net (without p) were not yet synced. So I've added ClouDNS NS sync part. And If I'm not wrong, I though I saw a comment somewhere, that an API based sync for a provider would be preferred over the nslookup approach.

Now looking at the code again today precheck.checkAuthoritativeNss(), it might be, that multiple TXT for the same host actually work, but I've not tried it yet.

**Comment by ldez** [comment]
CoulDNS has created the implementation of the challenge in acme.sh https://github.com/ClouDNS/acme.sh/blob/master/dnsapi/dns_cloudns.sh

Based on that I don't think there is an issue with lego.

**Comment by david-aggeler** [comment]
It has been a long journey. And not a good experience. And the lack of relevant logging for an outsider to me was significant part of the story.

I started at: `https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/`. 

- Got login errors with Dyn
- Had to learn that docker secrets don't work with docker compose (at least on my fully current wsl2, but I don't see to be alone)
- Then had to realized that my Dyn account does not qualify for DynAPI (nowhere mentioned). As per support request with Dyn, one needs a corporate account which one probably can't even get on its own anymore. Because it has been replaced and is now part of a cloud offering fro Oracle.
- Then had to evaluate a new DDNS provider
- Then still faced issues with traefik. It constantly failed and always reported an old challlenege
- Then figured out that it's using lego 
- Then figured out that calling lego directly worked (without --dns.resolvers). Later found to not to be true.
- Tried to debug traefik, because I was assuming it to be a container thing
- Then by luck I realized that the lego client now also fails (that's when I saw the two entries)
- Then went deep dive into lego

So now I've tried 

`--dns.resolvers  pns101.cloudns.net`

And so far it is stable. But now, how do I get this configured from traefik? I've not see it mentioned in the example listed in the beginning, not was a quick google search of any help.

**Comment by david-aggeler** [comment]
I realized, that I already had .acme.dnschallenge.resolvers in my docker compose (with IPs), it failed. So I've changed to to a single NS entry, and it still fails. It's being picked up, but does not work all the way to the end.

`
  traefik:
    #image: "traefik:v2.3"
    image: "traefik"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudns"
      **- "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=pns101.cloudns.net"**
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=myemail@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"`

The actual runtime

traefik    | time="2021-01-31T11:52:05Z" level=debug msg="Domains [\"docker-test.example.com\"] need ACME certificates generation for domains \"docker-test.example.com\"." rule="Host(`docker-test.example.com`)" providerName=myresolver.acme routerName=whoami@docker
traefik    | time="2021-01-31T11:52:05Z" level=debug msg="Loading ACME certificates [docker-test.example.com]..." providerName=myresolver.acme routerName=whoami@docker rule="Host(`docker-test.example.com`)"
traefik    | time="2021-01-31T11:52:05Z" level=debug msg="Building ACME client..." providerName=myresolver.acme
traefik    | time="2021-01-31T11:52:05Z" level=debug msg="https://acme-staging-v02.api.letsencrypt.org/directory" providerName=myresolver.acme
traefik    | time="2021-01-31T11:52:06Z" level=debug msg="Using DNS Challenge provider: cloudns" providerName=myresolver.acme
traefik    | time="2021-01-31T11:52:06Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Obtaining bundled SAN certificate"
traefik    | time="2021-01-31T11:52:07Z" level=debug msg="legolog: [INFO] [docker-test.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/200869820"
traefik    | time="2021-01-31T11:52:07Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Could not find solver for: tls-alpn-01"
traefik    | time="2021-01-31T11:52:07Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Could not find solver for: http-01"
traefik    | time="2021-01-31T11:52:07Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: use dns-01 solver"
traefik    | time="2021-01-31T11:52:07Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Preparing to solve DNS-01"
traefik    | time="2021-01-31T11:52:09Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Trying to solve DNS-01"
**traefik    | time="2021-01-31T11:52:09Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Checking DNS record propagation using [pns101.cloudns.net:53]"**
traefik    | time="2021-01-31T11:52:13Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 2m0s, interval: 4s]"
traefik    | time="2021-01-31T11:52:13Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Waiting for DNS record propagation."
traefik    | time="2021-01-31T11:52:18Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Waiting for DNS record propagation."
traefik    | time="2021-01-31T11:52:23Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Waiting for DNS record propagation."
traefik    | time="2021-01-31T11:52:28Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Waiting for DNS record propagation."
traefik    | time="2021-01-31T11:52:32Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Waiting for DNS record propagation."
traefik    | time="2021-01-31T11:52:46Z" level=debug msg="legolog: [INFO] [docker-test.example.com] acme: Cleaning DNS-01 challenge"
traefik    | time="2021-01-31T11:52:46Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/200869820"
traefik    | time="2021-01-31T11:52:46Z" level=debug msg="legolog: [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/200869820"
traefik    | time="2021-01-31T11:52:46Z" level=error msg="Unable to obtain ACME certificate for domains \"docker-test.example.com\": unable to generate a certificate for the domains [docker-test.example.com]: error: one or more domains had a problem:\n[docker-test.example.com] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.docker-test.example.com - check that a DNS record exists for this domain, url: \n" rule="Host(`docker-test.example.com`)" providerName=myresolver.acme routerName=whoami@docker
^CGracefully stopping... (press Ctrl+C again to force)
Stopping traefik        ... done
Stopping simple-service ... done

**Comment by ldez** [comment]
So increase the propagation timeout: `CLOUDNS_PROPAGATION_TIMEOUT`


https://go-acme.github.io/lego/dns/cloudns/

**Comment by david-aggeler** [comment]
As you might have realized, it only waits for 30s (11:52:13 toT11:52:46), so I assume the lego client is happy with the result.

**Comment by ldez** [comment]
```
400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.docker-test.example.com
```

This error is returned by Let's Encrypt, so that means that the resolver(s) use to validate the propagation is not the best.
For me, the DNS provider's NS is the worst for checking this propagation, have you try to use something else?

Now about your PR, I can understand the "Wait for NS server sync" but not the clean all TXT records.

**Comment by ldez** [comment]
About your PR, I can understand the "Wait for NS server sync" but not the clean all TXT records.
For me, you have to remove the "clean all" approach and add a "Wait for NS server sync" in the `Present` and in the `Cleanup`.

Also, I think the `is-updated.json` endpoint is better than `update-status.json`
- `is-updated.json`: https://www.cloudns.net/wiki/article/54/
- `update-status.json:` https://www.cloudns.net/wiki/article/53

**Comment by david-aggeler** [comment]
**DNS Resolver**

Looks like we start to have a shared understanding of the problem statement.

>>For me, the DNS provider's NS is the worst for checking this propagation, have you try to use something else?

I guess that means that this property is not passed to the let's encrypt server. And then your statement makes a lot of sense. But this was clear to me reading the documentation. 

The lego client by the way uses the four pns10x.cloudns.net NS, when the parameter is not provided (not visible in the default log, but that's what I added to the log to get an understanding), So I guess that means that the default behavior is also a bad criteria then? 

I'll try other NS. and report how it goes.

**API**
Since the cross-the world update takes almost two minutes in a regular case, I see a benefit in the progress indication. That's where the additional information from update-status.json comes in handy.

**Multiple TXT records and clean up**
I'll do some more digging. Do you know whether the Let's Encrypt Server also support multiple TXT entries for the same FQDN?
- If yes, a cleanup all, but only at the end still makes sense to me. Just to reduce confusion. But no initial cleanup needed, I agree.
- If no, what's your suggestion? Then I don't see how the '-d *.domain -d domain' can work.

**Comment by ldez** [comment]
> Do you know whether the Let's Encrypt Server also support multiple TXT entries for the same FQDN?

Yes, Let's Encrypt supports that, so please remove the "clean all"

**Comment by david-aggeler** [comment]
**DNS Resolver**

Just to close of the the resolver part and possibly help others. I've tried non ClouDNS NS, as well as having all NS from the service provider. Neither of them is reliable in traefik (like 50% success). Still get the NXDOMAIN error. While towards the outside, it looks like I have 8 NS assigned to my domain, in the sync dialog on their web page I see those 8 NS being replicated around the globe. So I'm not sure how many real NS they really have. 

`- "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1,8.8.8.8"`

and

`- "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=ns101.cloudns.net,ns102.cloudns.net,ns103.cloudns.net,ns104.cloudns.net,pns101.cloudns.net,pns102.cloudns.net,pns103.cloudns.net,pns104.cloudns.net"`

So unless I add a suspend somewhere, or know how the let's decrypt server do their job, I'd better off with the wait for sync. Since you sent part of my pull request further, I'd say we are good here.

**Comment by david-aggeler** [comment]
**Multiple TXT records**

As suggested, I've removed the CleanUp() in the Present() part and ran lego with `-d *.docker-test.example.com -d docker-test.example.com.` No more errors, but still only one certificate is retrieved (as before my changes). The console output is attached.

Yes in this case, we wait twice for the sync.

[multiple_domains.txt](https://github.com/go-acme/lego/files/5905655/multiple_domains.txt)
