### ISSUE TITLE
DNS Provider INWX – multi domain certificate failing with subdomains

### ISSUE THREAD

**Issue by macwinnie** [go-acme/lego#1337]
Hi everyone,

with Træfik (using the Lego framework as far as I know), I'm currently facing some strange problems with the domain registrar and NS provider INWX.

I've got one service that runs with multi-domains:

* subdomain1.example.com
* subdomain2.example.com
* other.domain.net

The ACME challenging TXT entry for DNS is only registered for subdomain1.example.com and other.domain.net ... the second subdomain of example.com does not receive an DNS entry for verification. That's why the whole certification request fails.

Thanks a lot for your support!
Best,
Martin

**Comment by ldez** [comment]
Hi, I think it's a duplicate of #1297

**Comment by macwinnie** [comment]
Hi @ldez,

Thanks – I've increased `INWX_PROPAGATION_TIMEOUT` to `600` and now it works ...

Best,
Martin
