### ISSUE TITLE
powerdns: always get DNS problem: NXDOMAIN looking up TXT

### ISSUE THREAD

**Issue by fboerman** [go-acme/lego#1339]
hi,

I am running my own powerdns instance (at ns.boerman.at) and I am trying to get a LE cert with lego. I am testing it on the staging server for now

I am trying the follow command:
```PDNS_POLLING_INTERVAL=30 PDNS_PROPAGATION_TIMEOUT=300 PDNS_TTL=300 LEGO_PATH=/etc/letsencrypt-lego PDNS_API_URL=http://<internalvpnip>:8080/ PDNS_API_KEY=<snip> lego --email <snip> -dns pdns -d <domain>.nl --server=https://acme-staging-v02.api.letsencrypt.org/directory run```

when lego says it is waitng for dns propagation I can see the _acme-challenge.<domain>.nl txt entry being created by polling with dig, so the api calls to powerdns seem to be working. However whatever I try with timeout settings etc I keep getting:

```acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.<domain>.nl - check that a DNS record exists for this domain```

I am not sure what I am doing wrong?

**Comment by ldez** [comment]
https://community.letsencrypt.org/t/acme-challenge-fails-with-nxdomain-with-own-nameservers-using-powerdns/144090
