### ISSUE TITLE
Add support for Njalla DNS provider

### ISSUE THREAD

**Issue by Lctrs** [go-acme/lego#1343]
- Site : https://njal.la/
- API : https://njal.la/api/

**Comment by ldez** [comment]
Hello,

@Lctrs If I create a PR are you able to perform tests for me?

FYI I don't have a domain in njalla.

**Comment by ldez** [comment]
ping @Lctrs

**Comment by dprandzioch** [comment]
@ldez I can test it if @Lctrs is not responding :)

**Comment by ldez** [comment]
@dprandzioch thank you, then I will create a PR.

**Comment by Lctrs** [comment]
@ldez Sorry for the lack of response. Truth is I don't have yet a domain in Njalla as well, I'm still in the phase of configuring my infrastructure and this takes longer than expected.

Thanks @dprandzioch for stepping in !
