### ISSUE TITLE
Route53 race condition

### ISSUE THREAD

**Issue by madsholden** [go-acme/lego#1351]
It appears there is a race condition in the route53 provider, and also maybe generally:

We have several instances of an application (Traefik) using lego. They all try to get a certificate for the same domain at the same time. They are trying to add a TXT record at `_acme-challenge.my-domain` with a random token.

What happens is this:
- One instance checks to see if there exists a TXT record with that key. It does not.
- It creates it in route53
- Another instance checks to see if there exists a TXT record with that key. It does, so it appends its own token.
- It updates route53 with both tokens
- The first instance gets the certificate, and removes the entire TXT record
- The second instance fails, because there is no TXT record with its token any more.

I imagine the fix would be to only remove the instance's own token in the TXT record after validating, instead of deleting the entire thing.

Even if this is fixed, there seems to be a more general race condition in the dns challenge:
- One instance checks to see if there exists a TXT record with that key. It does not.
- Another instance checks to see if there exists a TXT record with that key. It does not.
- The first instance creates a record with its own token in route53
- The second instance creates a record with its own token in route53, overwriting the first token
- The second instance gets the certificate
- The first instance fails

**Comment by ldez** [comment]
Hello,

It's not an issue with lego: you are trying to create a cluster of Traefik with "shared ACME certificates" but Traefik doesn't support that.

**Comment by YuryHrytsuk** [comment]
> Hello,
> 
> It's not an issue with lego: you are trying to create a cluster of Traefik with "shared ACME certificates" but Traefik doesn't support that.

To solve this you can either use Kubernetes Cert Manager (if you are in Kubernetes realm), buy enterprise edition (I think it supports shared certificate state) or use user-defined certificates and generate certificates manually ([read more here](https://github.com/ITISFoundation/osparc-ops-environments/issues/394))
