### ISSUE TITLE
Add support for GratisDNS.dk

### ISSUE THREAD

**Issue by bottiger** [go-acme/lego#1352]
I would be really nice with support for GratisDNS.dk which is a free DNS provider. I am unsure if they have an official API, but acme.sh has managed to support them:

Here is the acme.sh implementation: https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_gdnsdk.sh

**Comment by ldez** [comment]
Hello,

We (the lego maintainers) don't have an account in all DNS providers in the world.

By default, we do not add a DNS provider that we are not able to handle.
It is, therefore, necessary that a contributor, having an account for the DNS provider, create a PR and be able to maintain the implementation for the DNS provider.
Or a contributor able to test the implementation.

Do you want to create a PR?
If not, if I create a PR are you able to perform tests for me?

**Comment by ldez** [comment]
In fact, if a provider doesn't have an API, we will not integrate it. (we don't want to have HTML parsing)

**Comment by hjorslev** [comment]
GratisDNS has been shutdown so I guess this issue can be closed.
