### ISSUE TITLE
Docs: Typo in environment variable name in example usage for Mythic Beasts provider

### ISSUE THREAD

**Issue by codebrewer** [go-acme/lego#1355]
The doc for the Mythic Beasts provider contains this example usage:

```bash
MYTHICBEASTS_USER_NAME=myuser \
MYTHICBEASTS_PASSWORD=mypass \
lego --email myemail@example.com --dns mythicbeasts --domains my.example.org run
```

The later **Credentials** section of the doc says there should be no `_` between `USER` and `NAME`:

| Environment Variable Name | Description |
|-----------------------|-------------|
| `MYTHICBEASTS_PASSWORD` | Password |
| `MYTHICBEASTS_USERNAME` | User name |

and using the provider confirms the name in the table is correct.

**Comment by ldez** [comment]
Hello,

do you plan to open a PR to fix it?

**Comment by codebrewer** [comment]
You've seen it quicker than I could reply 😄
