### ISSUE TITLE
LEGO_EXPERIMENTAL_CNAME_SUPPORT not following recursive CNAME's

### ISSUE THREAD

**Issue by vrubiella** [go-acme/lego#1366]
I have several customers with this DNS configuration:

CNAME  *    => www
CNAME www => basedomain.tld

Call:
`acmeRecord, value := dns01.GetRecord(domain,keyAuth)`
Returns
`www.basedomain.tld`
Expected result was
`basedomain.tld`

This DNS configuration is stupid but it's correct in terms of DNS/CNAMEs configuration.

**Comment by ldez** [comment]
Hello,

I think that with the recursivity (since v4.9.0) the problem must be fixed.

#1677
