### ISSUE TITLE
unable to make http channel certificate 

### ISSUE THREAD

**Issue by haril-github** [go-acme/lego#1369]
I am getting below error 

acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://XYZ.tk/.well-known/acme-challenge/XjvYGSC5bf6uLrwn8KJMYA7WTzEY-fS9YMZz9xKDy1g: Timeout during connect (likely firewall problem), url:

**Comment by ldez** [comment]
Hello,

you have a network problem, check your network.
