### ISSUE TITLE
nifcloud: You can only get a certificate with a common name that has the same name as the hostedZone.

### ISSUE THREAD

**Issue by kakakikikeke-fork** [go-acme/lego#1382]
- [x] Yes, I'm using a binary release within 2 latest releases.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### What did you expect to see?
I want to get a certificate that includes a single host name or a certificate that includes host names separated by dots.

### What did you see instead?
I want to be able to obtain a certificate with the above pattern. The correct code is here. https://github.com/go-acme/lego/pull/1381

### Steps to reproduce
I have a hostedZone on nifcloud called devops.xxx.xxx.xxx (a part of the domain is hidden). In this case, there are only two certificates that can be obtained by specifying --domains:

* devops.xxx.xxx.xxx
* *.devops.xxx.xxx.xxx

I cannot get a certificate containing a single host name or a certificate containing a dotted host name, such as:

* aaa.devops.xxx.xxx.xxx
* *.aaa.devops.xxx.xxx.xxx

![hosted_zone](https://user-images.githubusercontent.com/11570790/113951455-92a3a000-984e-11eb-9f93-6a534ace25e6.PNG)

1. Register a hostedZone called devops.xxx.xxx.xxx with nifcloud.
2. Set NIFCLOUD_ACCESS_KEY_ID and NIFCLOUD_SECRET_ACCESS_KEY.
3. docker run --rm -e NIFCLOUD_ACCESS_KEY_ID=xxxx -e NIFCLOUD_SECRET_ACCESS_KEY=xxxx -v $(pwd)/lego_certificates:/lego goacme/lego --path /lego --email your-name@mail.domain --dns nifcloud --domains aaa.devops.xxx.xxx.xxx --key-type rsa2048 --accept-tos run
4. "No hosted zone found" error occurred.

The execution error log is described below.

### Details

<details><summary>Version of lego</summary>

```console
$ docker run --rm goacme/lego -v
lego version v4.3.1 linux/amd64
```

</details>

<details><summary>Logs</summary>

```console
2021/04/08 00:53:06 [INFO] [aaa.devops.xxx.xxx.xxx] acme: Obtaining bundled SAN certificate
2021/04/08 00:53:06 [INFO] [aaa.devops.xxx.xxx.xxx] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12167329310
2021/04/08 00:53:06 [INFO] [aaa.devops.xxx.xxx.xxx] acme: Could not find solver for: tls-alpn-01
2021/04/08 00:53:06 [INFO] [aaa.devops.xxx.xxx.xxx] acme: Could not find solver for: http-01
2021/04/08 00:53:06 [INFO] [aaa.devops.xxx.xxx.xxx] acme: use dns-01 solver
2021/04/08 00:53:06 [INFO] [aaa.devops.xxx.xxx.xxx] acme: Preparing to solve DNS-01
2021/04/08 00:53:07 [INFO] [aaa.devops.xxx.xxx.xxx] acme: Cleaning DNS-01 challenge
2021/04/08 00:53:07 [WARN] [aaa.devops.xxx.xxx.xxx] acme: cleaning up failed: nifcloud: failed to change NIFCLOUD record set: an error occurred: No hosted zone found
2021/04/08 00:53:08 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/12167329310
2021/04/08 00:53:08 Could not obtain certificates:
        error: one or more domains had a problem:
[aaa.devops.xxx.xxx.xxx] [aaa.devops.xxx.xxx.xxx] acme: error presenting token: nifcloud: failed to change NIFCLOUD record set: an error occurred: No hosted zone found
```

</details>

**Comment by ldez** [comment]
Thanks, I think that your PR #1381 is not a good way to fix the problem, the problem can be fixed by following the same pattern as the other providers:

https://github.com/go-acme/lego/blob/ae7daa7d3321fcefa4aee1bb690b1b7ce9b5c78b/providers/dns/netlify/netlify.go#L106-L111

**Comment by kakakikikeke-fork** [comment]
Thank you good idea. I recreated new p-r https://github.com/go-acme/lego/pull/1383.
