### ISSUE TITLE
Bad certificate generation

### ISSUE THREAD

**Issue by bitbreakr** [go-acme/lego#1418]
- [ ] Yes, I'm using a binary release within 2 latest releases.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

### What did you expect to see?
One  certificate block

### What did you see instead?

It looks like there is an issue with the content of the generated certs:
* result.Certificate
* result.PrivateKey

There are 3 times Begin certificate and End certificate blocks

Is it a normal behavior ?

### Details
I'm on staging (CADirURL = lego.LEDirectoryStaging)
And generating certs from the library.

<details><summary>Version of lego</summary>

```console
$ lego --version
v4.3.1 
```

</details>

<details><summary>Logs</summary>

```console
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

You haven't provided enough information for a complete answer.

The generated certificates contain the issuer certificates.

With the information that you provided, I cannot say more.

**Comment by bitbreakr** [comment]
@ldez 

I did not want to put the certificates for security reasons and I apologize for that.

I managed to understand this morning that this certificate is a full chain one, so it is all 👍 

Thanks
