### ISSUE TITLE
Resolver doesn't say properly real error when ussing backoff

### ISSUE THREAD

**Issue by quenbyako** [go-acme/lego#1427]
### note for maintainers

I already realize how to fix it, backoff has `Permanent` error to tell repeater that it must be stopped, so just wait, i'll create pr for it

- [x] Yes, I'm using a binary release within 2 latest releases. (using lib latest 2 releases)
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

In latest versions i found new dependency called `backoff` (btw, idea to add it in lego is awesome i think), so problem starts here:

after setuping http-01 (or any other) resolver, **real** resolver calling `validate` function from `challenge/resolve/solver_manager.go`. When validator can't reach target host (f.e. it can set wrong ports, like in my situation, but i realize it after lots of debugging), or, i think, any other error, backoff **DOES NOT** return real error, instead, it returns `context cancelled` somehow.

### What did you see instead?

So, long story short: backoff returns `error: one or more domains had a problem: context canceled` instead of **real error** `error: 400 :: urn:ietf:params:acme:error:connection :: Get "http://some.domain:5002/.well-known/blahblahblah": dial tcp 127.0.0.1:5002: connect: connection refused`

### Steps to reproduce

1. idk, use pebble, like me, for testing and fuck up its config (in my case, target resolver located at 80 port, but pebble knocks at 5002 port)
2. well, try to obtain cert, lol.
3. ...
4. bingo! you don't know what the hell happened

### Details

`lego package v4.3.1`

<details><summary>Logs</summary>

```console
INFO[0005] [INFO] [some.domain] AuthURL: https://127.0.0.1:14000/authZ/KeksGKHSk4uib4mt0EWaYv_NdupZzvNN6pwXqDgtC_g 
INFO[0005] [INFO] [some.domain] acme: Could not find solver for: tls-alpn-01 
INFO[0005] [INFO] [some.domain] acme: use http-01 solver 
INFO[0005] [INFO] [some.domain] acme: Trying to solve HTTP-01 
INFO[0005] [INFO] canceling after check acme!!!!!!                              // btw, here i "debugged" via println lol, but it works!
error: 400 :: urn:ietf:params:acme:error:connection :: Get "http://some.domain:5002/.well-known/acme-challenge/Qw88IeNVrDt33ZaE15xrBIpb7EyPYimCxvDVN9MZv0M": dial tcp 127.0.0.1:5002: connect: connection refused
INFO[0008] [INFO] Deactivating auth: https://127.0.0.1:14000/authZ/KeksGKHSk4uib4mt0EWaYv_NdupZzvNN6pwXqDgtC_g 
ERRO[0008] certgen failed!                               domain=xelaj.local err="obtaining certificate: error: one or more domains had a problem:\n[some.domain] context canceled\n"
```

</details>

**Comment by ldez** [comment]
Hello,

I'm not able to reproduce your error, I tried:
- with pebble and a wrong port
```
2021/06/11 04:28:41 Could not obtain certificates:
	error: one or more domains had a problem:
[acme.wtf] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Get "http://acme.wtf:5020/.well-known/acme-challenge/kLqEq1FvmfR-w_8gS7sXx8gfOhZ3_fmMWq7I_CN7dtA": dial tcp 127.0.0.1:5020: connect: connection refused
```
- programmatically
```go

func TestBackOff_cancel(t *testing.T) {
	initialInterval := 10 * time.Second

	bo := backoff.NewExponentialBackOff()
	bo.InitialInterval = initialInterval
	bo.MaxInterval = 10 * initialInterval
	bo.MaxElapsedTime = 100 * initialInterval

	ctx, cancel := context.WithCancel(context.Background())

	operation := func() error {
		err := foo()
		if err != nil {
			cancel()
			return err
		}

		return errors.New("END")
	}

	go func() {
		time.Sleep(2 * time.Second)
		cancel()
		fmt.Println("STOP", ctx.Err())
	}()

	err := backoff.Retry(operation, backoff.WithContext(bo, ctx))

	fmt.Println(err)
}

func foo() error {
	fmt.Println("foo")
	// time.Sleep(3 * time.Second)
	return errors.New("OOPS")
	// return nil
}
```

**Comment by ldez** [comment]
Are you using lego as lib or as a command line?

**Comment by quenbyako** [comment]
@ldez i'm using the lib, as i can understand, main problem is that context cancelling _before_ returning error to backoff

btw, i don't know, maybe i got some bug to backoff, i need to investigate it more

**Comment by grongor** [comment]
Hi, I've encountered the same issue today when I updated the libs I use, including lego. In old logs I have errors like:
```
ERROR	certificate issuer error	{"error": "failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/, url: ", "requestId": "91452a29-4967-4ea9-9f44-76b6f72d4d68", "domains": ["...censored..."]}
```
but now I see just this:
```
ERROR	certificate issuer error	{"error": "failed to obtain certificate: context canceled", "requestId": "30231e1c-1c02-449c-b0bd-115a92181fbc", "domains": ["...censored..."]}
```
I didn't change anything else, so I guess there must be something wrong...

By the way, wouldn't it be better to just use the `PermanentError` instead of complicating things with context?

Current code:
```go
ctx, cancel := context.WithCancel(context.Background())

var resp *http.Response
operation := func() error {
	var err error
	resp, err = a.signedPost(uri, content, response)
	if err != nil {
		// Retry if the nonce was invalidated
		var e *acme.NonceError
		if errors.As(err, &e) {
			return err
		}

		cancel()
		return err
	}

	return nil
}

notify := func(err error, duration time.Duration) {
	log.Infof("retry due to: %v", err)
}

err := backoff.RetryNotify(operation, backoff.WithContext(bo, ctx), notify)
if err != nil {
	return resp, err
}
```

What I propose:

```go
var resp *http.Response
operation := func() error {
	var err error
	resp, err = a.signedPost(uri, content, response)
	if err != nil {
		// Retry if the nonce was invalidated
		var e *acme.NonceError
		if errors.As(err, &e) {
			return err
		}

		return backoff.Permanent(err)
	}

	return nil
}

notify := func(err error, duration time.Duration) {
	log.Infof("retry due to: %v", err)
}

err := backoff.RetryNotify(operation, bo, notify)
if err != nil {
	return resp, err
}
```
