### ISSUE TITLE
InsecureSkipVerify should not be used in production code. 

### ISSUE THREAD

**Issue by jauderho** [go-acme/lego#1442]
https://github.com/go-acme/lego/blob/2a194d6ab92ddb2b2d87d0dc0e15f26eb4588739/providers/dns/dnsmadeeasy/dnsmadeeasy.go#L52

This was flagged by CodeQL as a potential issue. It is unclear if this was the intended choice to do so.

**Comment by ldez** [comment]
hello, It's a dnsmadeeasy constraint, we don't have choice.
