### ISSUE TITLE
package github.com/go-acme/lego: no Go files in D:\goProject\src\github.com\go-acme\lego

### ISSUE THREAD

**Issue by yueqianlong** [go-acme/lego#1445]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

when i use: `go get  github.com/go-acme/lego`
and then the message out:
```
package github.com/go-acme/lego: no Go files in D:\goProject\src\github.com\go-acme\lego
```

### What did you see instead?

when i use: `go get  github.com/go-acme/lego`
and then the message out:
```
package github.com/go-acme/lego: no Go files in D:\goProject\src\github.com\go-acme\lego
```

### Reproduction steps
```
go get  github.com/go-acme/lego
```

### Version of lego

<details>

```console
$ lego --version
# paste output here
go get  github.com/go-acme/lego
```

</details>

### Logs

<details>

```console
# paste output here
D:\goProject\src\goMicroTest>go get  github.com/go-acme/lego
package github.com/go-acme/lego: no Go files in D:\goProject\src\github.com\go-acme\lego
```

</details>

**Comment by yueqianlong** [comment]
How to resolve the proprem

**Comment by ldez** [comment]
https://go-acme.github.io/lego/installation/

**Comment by yueqianlong** [comment]
https://go-acme.github.io/lego/installation/ can not visit

**Comment by ldez** [comment]
https://github.com/go-acme/lego/blob/master/docs/content/installation/_index.md

**Comment by yueqianlong** [comment]
go env
set GO111MODULE=on
set GOARCH=amd64

still the proprem
D:\goProject\src\goMicroTest>go get -u github.com/go-acme/lego/v4/cmd/lego
package github.com/go-acme/lego/v4/cmd/lego: no Go files in D:\goProject\src\github.com\go-acme\lego\v4\cmd\lego

**Comment by yueqianlong** [comment]
go version
go version go1.16.5 windows/amd64
