### ISSUE TITLE
cannot find package "github.com/go-acme/lego/v3/challenge" in any of:

### ISSUE THREAD

**Issue by yueqianlong** [go-acme/lego#1446]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

go get  github.com/micro/micro
cannot find package "github.com/go-acme/lego/v3/challenge" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\challenge (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\challenge (from $GOPATH)
cannot find package "github.com/go-acme/lego/v3/providers/dns/cloudflare" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOPATH)

### What did you see instead?

go get  github.com/micro/micro
cannot find package "github.com/go-acme/lego/v3/challenge" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\challenge (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\challenge (from $GOPATH)
cannot find package "github.com/go-acme/lego/v3/providers/dns/cloudflare" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOPATH)

### Reproduction steps

go get  github.com/micro/micro
cannot find package "github.com/go-acme/lego/v3/challenge" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\challenge (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\challenge (from $GOPATH)
cannot find package "github.com/go-acme/lego/v3/providers/dns/cloudflare" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOPATH)

### Version of lego

go get  github.com/micro/micro
cannot find package "github.com/go-acme/lego/v3/challenge" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\challenge (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\challenge (from $GOPATH)
cannot find package "github.com/go-acme/lego/v3/providers/dns/cloudflare" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOPATH)

### Logs

go get  github.com/micro/micro
cannot find package "github.com/go-acme/lego/v3/challenge" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\challenge (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\challenge (from $GOPATH)
cannot find package "github.com/go-acme/lego/v3/providers/dns/cloudflare" in any of:
        C:\Program Files\Go\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOROOT)
        D:\goProject\src\github.com\go-acme\lego\v3\providers\dns\cloudflare (from $GOPATH)

**Comment by yueqianlong** [comment]
how to resolve the proprem?

**Comment by ldez** [comment]
I don't answer this kind of low-quality issue.
