### ISSUE TITLE
Support for provider: Freemyip

### ISSUE THREAD

**Issue by CuriousEl3phant502** [go-acme/lego#1450]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [x] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://freemyip.com/

### Link to the API documentation

https://freemyip.com/help

### Additional Notes

No account needed, dynamic dns provider with privacy focus. 

> Free dynamic DNS. No login required. No ads, newsletters, links to click, expiration dates, etc.

Account management is done by passing URL parameters including your token which is given at creation  to https://freemyip.com/update.

TXT file can be add simply by hitting this URL:
https://freemyip.com/update?token=mytoken&domain=mydomain.freemyip.com&txt=dns_challenge_token

and removed by 
https://freemyip.com/update?token=mytoken&domain=mydomain.freemyip.com&txt=
or
https://freemyip.com/update?token=mytoken&domain=mydomain.freemyip.com&txt=null

"&verbose=yes" can be added as well for additional info other than the standard "OK" response.

**Comment by ldez** [comment]
Hello @CuriousEl3phant502,

I created a Go client for freemyip.com and the lego DNS provider implementation:
- https://github.com/nrdcg/freemyip
- #1451 

Feel free to test it.

**Comment by CuriousEl3phant502** [comment]
wow! that was fast. Thank you so much! I'll take a look at it, and try to test it. I have no experience with go, but i'll see if i can learn something about it so i can test it.

**Comment by CuriousEl3phant502** [comment]
I tested both the client and dns provider (through docker). It worked for me. Thanks! :)
