### ISSUE TITLE
Security issue with lego dependency for JWT 

### ISSUE THREAD

**Issue by jauderho** [go-acme/lego#1452]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Snyk has identified an issue with github.com/dgrijalva/jwt-go which lego depends on. This has been an identified issue for a while.

### What did you see instead?

See https://app.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515

Fix is to update to a newer version

### How do you use lego?

Binary

### Reproduction steps

1. Create Snyk account
2. Attach Snyk to scan lego code or binary
3. See warning

### Version of lego

```console
lego version 4.4.0 linux/amd64
```

### Logs

lego version 4.4.0 linux/amd64

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

This dependency is only used by the azure provider.

```console
$ go mod why github.com/dgrijalva/jwt-go
# github.com/dgrijalva/jwt-go
github.com/go-acme/lego/v4/providers/dns/azure
github.com/Azure/go-autorest/autorest
github.com/Azure/go-autorest/autorest/adal
github.com/dgrijalva/jwt-go
```

**Comment by jauderho** [comment]
Thanks. Please consider a v4.4.1 point release once merged

**Comment by ldez** [comment]
the next version will be v4.5.0, this bug is a minor bug from the point of view of lego.
