### ISSUE TITLE
EasyDNS dns provider doesn't properly handle domains with multi-part TLDs

### ISSUE THREAD

**Issue by Confuzed** [go-acme/lego#1466]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

When attempting to obtain a cert for a domain with a ccTLD that is made up of two parts, e.g. _example.co.uk_, I expect lego to correctly submit the zone update to the EasyDNS REST API to complete the DNS challenge before generating certificates.

### What did you see instead?

When attempting to obtain certificates for a domain in the form of _example.co.uk_ using the DNS challenge provider for EasyDNS, I consistently get an error response:

```
Could not obtain certificates:
	error: one or more domains had a problem:
[www.example.co.uk] [www.example.co.uk] acme: error presenting token: easydns: error adding zone record: 403: request failed: {"error":{"code":403,"message":"Access to resource denied due to permissions"}}
```

When I tested the zone update against the REST API directly, using Postman and the same credentials, the request succeeded.

On inspection of the logging available through EasyDNS's management portal I noticed that the domain was split such that the domain was _co.uk_ and it treated _example_ as part of the host name.

### How do you use lego?

Docker image

### Reproduction steps

Pre-requisite: A domain registered and managed with EasyDNS that has a multi-part TLD, such as _.co.uk_. It is also necessary to sign up explicitly for API access.

1. Obtain the access token and API key for the EasyDNS API, making sure that you have the correct credentials for the endpoint you use for testing (sandbox or production). FWIW, the results are the same for both endpoints.
2. Configure the env variables EASYDNS_TOKEN and EASYDNS_KEY, and optionally EASYDNS_ENDPOINT using the values obtained for the REST API.
3. Run `lego -a --dns easydns --domains example.co.uk --email confuzed@example.co.uk`

In order to test this more easily I wrote a script which sets up the environment variables and executes lego via docker. I'll share that here:

<details>

```bash
#!/bin/bash

set -e

# Replace with your full domain name
DOMAIN="www.example.co.uk"

# The email address to use in the request
EMAIL="someone@example.co.uk"

# LetsEncrypt staging server
CASERVER="https://acme-staging-v02.api.letsencrypt.org/directory"

# The EasyDNS endpoint to use, usually test with the sandbox endpoint
EASYDNS_ENDPOINT="https://sandbox.rest.easydns.net"

# easyDNS API creds
EASYDNS_TOKEN="Your Token Here"
EASYDNS_KEY="Your Key Here"

docker run \
  --rm \
  -v "$(pwd)/lego:/.lego" \
  -e EASYDNS_ENDPOINT=${EASYDNS_ENDPOINT} \
  -e EASYDNS_TOKEN=${EASYDNS_TOKEN} \
  -e EASYDNS_KEY=${EASYDNS_KEY} \
  goacme/lego \
  -a \
  --server "${CASERVER}" \
  --dns easydns \
  --dns.resolvers "dns1.easydns.com" \
  --domains "${DOMAIN}" \
  --email "${EMAIL}" \
  run 
```

</details>

### Version of lego

```console
lego version v4.4.0 linux/amd64
```

### Logs

<details>

```console
2021/08/17 16:59:59 [INFO] [www.example.co.uk] acme: Obtaining bundled SAN certificate
2021/08/17 17:00:00 [INFO] [www.example.co.uk] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/292448088
2021/08/17 17:00:00 [INFO] [www.example.co.uk] acme: Could not find solver for: tls-alpn-01
2021/08/17 17:00:00 [INFO] [www.example.co.uk] acme: Could not find solver for: http-01
2021/08/17 17:00:00 [INFO] [www.example.co.uk] acme: use dns-01 solver
2021/08/17 17:00:00 [INFO] [www.example.co.uk] acme: Preparing to solve DNS-01
2021/08/17 17:00:00 [INFO] [www.example.co.uk] acme: Cleaning DNS-01 challenge
2021/08/17 17:00:01 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/292448088
2021/08/17 17:00:01 Could not obtain certificates:
	error: one or more domains had a problem:
[www.example.co.uk] [www.example.co.uk] acme: error presenting token: easydns: error adding zone record: 403: request failed: {"error":{"code":403,"message":"Access to resource denied due to permissions"}}
```

</details>

### Go environment (if applicable)

The docker container

**Comment by ldez** [comment]
Hello,

could you provide the log from the start of lego?

**Comment by Confuzed** [comment]
@ldez Sure, I updated the log section in the description to include the full output.

This looks suspect to me, seems like it assumes that the domain part of a host is only two parts:

https://github.com/go-acme/lego/blob/bc8ff4a192723bd756e844fee64d8e3958867dcf/providers/dns/easydns/easydns.go#L168-L175

**Comment by ldez** [comment]
Hello @Confuzed,
if I create a PR are you able to test it?

**Comment by Confuzed** [comment]
> Hello @Confuzed,
> if I create a PR are you able to test it?

Yes, be happy to 👍🏻

**Comment by ldez** [comment]
The main problem with the EasyDNS API is to find a way to get the domain/zone from an FQDN.

The API documentation is a bit weak on examples, then I will need you to get more information about the API behavior.

Can you try to give me the responses of the following API endpoint, with several FQDN (exmaple.co.uk, example.com, foo.example.co.uk, foo.example.com)?

- https://sandbox.rest.easydns.net:3001/#/read/listUserDomains
- https://sandbox.rest.easydns.net:3001/#/read/listParsedZone

**Comment by Confuzed** [comment]
@ldez definitely want to help with this, just been struggling for time and am currently away from home. Will test those endpoints as soon as I can.

**Comment by tsg1992** [comment]
Hello we are experiencing the same issue, with same error message as original post. Direct cURL requests to EasyDNS seem to work just fine using multi-part TLD domains. We build from latest --version shows 

`lego version 615e601d787696ab33dbf690bc351a2cb279783a linux/amd64`

**Comment by thadius83** [comment]
I have this same issue with example.id.au

works fine with example.com.au
Was there every a solution discovered?

I found that it doesn't even create the TXT records

**Comment by ldez** [comment]
`example.com.au` or `example.id.au` will provide the same result because the split between the zone and the subdomain will be wrong:
- `_acme-challenge.example.com.au`:
  - zone: `com.au`
  - subdomain: `_acme-challenge.example`
- `_acme-challenge.example.id.au`:
  - zone: `id.au`
  - subdomain: `_acme-challenge.example`

The problem is the way to get to the zone.

https://github.com/go-acme/lego/issues/1466#issuecomment-915585417

I will try to find something but I will need people to test it.

**Comment by ldez** [comment]
You can try the following PR #2121

**Comment by thadius83** [comment]
> example

Could it possibly be because my actual domain is ab.id.au

One of those rare two character domain names ?

**Comment by ldez** [comment]
No, the algo is simple and just splits the domain based on dots.
