### ISSUE TITLE
Rlease a new release of the library for Traefik to adopt

### ISSUE THREAD

**Issue by tam481** [go-acme/lego#1474]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Through Traefik

### Detailed Description

Hello,
Please issue a new release for Traefik to use newly added freemyip.com

Thank you in advance

**Comment by ldez** [comment]
Hello,

Sorry but it's a question, the issues are for problems or feature requests.

In all cases, we don't answer about ETA and release date/request.

Thank you.
