### ISSUE TITLE
Support for provider: Apache LibCloud

### ISSUE THREAD

**Issue by cha0tic87** [go-acme/lego#1484]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://libcloud.apache.org/

### Link to the API documentation

https://libcloud.readthedocs.io/en/stable/dns/api.html

**Comment by ldez** [comment]
Hello, Lib cloud is not DNS provider but a Python package
