### ISSUE TITLE
Support for provider: epik.com

### ISSUE THREAD

**Issue by marius-locomotion** [go-acme/lego#1489]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://www.epik.com

### Link to the API documentation

https://www.epik.com/support/knowledgebase/epik-domain-management-api/

https://docs.userapi.epik.com/v2/

### Additional Notes

thank you!

**Comment by ldez** [comment]
Hello @marius-locomotion,

as the API documentation is a bit weak about the response of the API endpoint, I will need you to help me to get more information.

First, you will need a [Epik API signature](https://registrar.epik.com/account/api-settings/).

I will need the JSON response for the following calls:
- https://docs.userapi.epik.com/v2/#/DNS%20Host%20Records/getDnsRecord
- https://docs.userapi.epik.com/v2/#/DNS%20Host%20Records/createHostRecord
- https://docs.userapi.epik.com/v2/#/DNS%20Host%20Records/removeHostRecord

You should anonymize the JSON response to protect your data and then copy-paste the content here.

Thank you.

**Comment by marius-locomotion** [comment]
`curl -X GET "https://usersapiv2.epik.com/v2/domains/MYDOMAIN.ORG/records?SIGNATURE=MYSIGNATURE" -H "accept: application/json"`

`
{
  "data": {
    "name": "MYDOMAIN.ORG",
    "code": 1000,
    "records": [
      {
        "id": "abc123",
        "name": "www",
        "type": "CAA",
        "data": "1 issue letsencrypt.org",
        "aux": 0,
        "ttl": 300
      },
      {
        "id": "abc123",
        "name": "www",
        "type": "A",
        "data": "192.64.147.249",
        "aux": 0,
        "ttl": 300
      },
      {
        "id": "abc123",
        "name": "*",
        "type": "A",
        "data": "192.64.147.249",
        "aux": 0,
        "ttl": 300
      },
      {
        "id": "abc123",
        "name": "",
        "type": "CAA",
        "data": "0 issue trust-provider.com",
        "aux": 0,
        "ttl": 300
      },
      {
        "id": "abc123",
        "name": "",
        "type": "CAA",
        "data": "1 issue letsencrypt.org",
        "aux": 0,
        "ttl": 300
      },
      {
        "id": "abc123",
        "name": "",
        "type": "A",
        "data": "192.64.147.249",
        "aux": 0,
        "ttl": 300
      }
    ]
  }
}
`

**Comment by marius-locomotion** [comment]
`curl -X POST "https://usersapiv2.epik.com/v2/domains/MYDOMAIN.ORG/records?SIGNATURE=MYSIGNATURE" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"create_host_records_payload\": { \"HOST\": \"string\", \"TYPE\": \"string\", \"DATA\": \"string\", \"AUX\": 0, \"TTL\": 0 }}"`

response body:
`{
  "code": 1000,
  "message": "Command completed successfully.",
  "description": null
}`

response headers
` cache-control: no-store, no-cache, must-revalidate 
 content-type: application/json 
 expires: Thu, 19 Nov 1981 08:52:00 GMT 
 pragma: no-cache
`

**Comment by marius-locomotion** [comment]
`curl -X DELETE "https://usersapiv2.epik.com/v2/domains/MYDOMAIN.ORG/records?SIGNATURE=MYSIGNATURE&ID=RECORDID" -H "accept: application/json"`

response body
`{
  "code": 1000,
  "message": "Command completed successfully.",
  "description": null
}`

response headers
` cache-control: no-store, no-cache, must-revalidate 
 content-type: application/json 
 expires: Thu, 19 Nov 1981 08:52:00 GMT 
 pragma: no-cache 
 `

**Comment by marius-locomotion** [comment]
Please see above the output from the 3 API calls. I hope this helps!
Let me know if there's anything else I can help with.
And thanks a lot for your help with it!

**Comment by ldez** [comment]
the responses of the 2 calls (createHostRecord, removeHostRecord) are really different than the documentation.

from the doc (createHostRecord):
```
{
  "data": {
    "data": [
      {
        "name": "string",
        "code": "string",
        "message": "string"
      }
    ]
  }
}
```

from the doc (removeHostRecord):
```
{
  "data": {
    "data": [
      {
        "name": "string",
        "code": "string",
        "message": "string"
      }
    ]
  }
}
```

Can you confirm that you don't drop the `data.data` section for these calls?

**Comment by marius-locomotion** [comment]
Yes, 100%
There is no upper level "data".
That is the exact output of the curl commands I posted, where I replaced only the sensitive values.
