### ISSUE TITLE
OVH DNS-01 is broken for subdomain certification

### ISSUE THREAD

**Issue by asbachb** [go-acme/lego#1492]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Existing certificate should be renewed.

### What did you see instead?

Renewing is aborted due to DNS-01 errors. It seems that the url for the ovh api call is wrongly constructed.  Would expect `/domain/zone/impl.it/record` instead of `/domain/zone/it/record`.

### How do you use lego?

Binary

### Reproduction steps

Try to renew an existing certificate with dns-01 with ovh module
`lego --accept-tos --path . -d webmail.impl.it --email ****@impl.it --key-type ec256 --dns ovh renew --days 30``

### Version of lego

```console
lego version 4.4.0 linux/amd64
```

### Logs

<details>

```console
Sep 18 11:01:05 nixos acme-webmail.impl.it-start[432701]: + lego --accept-tos --path . -d webmail.impl.it --email ****@impl.it --key-type ec256 --dns ovh renew --days 30
Sep 18 11:01:06 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:06 [INFO] [webmail.impl.it] acme: Trying renewal with 101 hours remaining
Sep 18 11:01:06 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:06 [INFO] [webmail.impl.it] acme: Obtaining bundled SAN certificate
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] [webmail.impl.it] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3208****890
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] [webmail.impl.it] acme: Could not find solver for: tls-alpn-01
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] [webmail.impl.it] acme: Could not find solver for: http-01
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] [webmail.impl.it] acme: use dns-01 solver
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] [webmail.impl.it] acme: Preparing to solve DNS-01
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] [webmail.impl.it] acme: Cleaning DNS-01 challenge
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [WARN] [webmail.impl.it] acme: cleaning up failed: ovh: unknown record ID for '_acme-challenge.webmail.impl.it.'
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3208****890
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: 2021/09/18 11:01:07 error: one or more domains had a problem:
Sep 18 11:01:07 nixos acme-webmail.impl.it-start[432710]: [webmail.impl.it] [webmail.impl.it] acme: error presenting token: ovh: error when call api to add record (/domain/zone/it/record): Error 404: "This service does not exist"

```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

It's a problem related to the resolution of your domain: lego tried to find the zone (through SOA calls) but it fail to get a valid answer.

It's related to your network configuration (local DNS, firewall, ...).

**Comment by asbachb** [comment]
@ldez Can you give some more context to narrow down the problem? I did not change any dns settings, my OS just do regular updates. How can I replicate the acme with command line tools to nail down the problem?

**Comment by ldez** [comment]
You have to check the answers of SOA requests for each part of your domains, ex:
for `foo.bar.example.com`:
- `foo.bar.example.com`
- `bar.example.com`
- `example.com`

You can also check your DNS resolvers (local DNS server, `/etc/hosts`, ...)

If needed you can change the resolvers used by lego via `--dns.resolvers`: https://go-acme.github.io/lego/usage/cli/#usage

**Comment by asbachb** [comment]
I think I see the problem:

```
[root@nixos:~]# host -t soa webmail.impl.it
webmail.impl.it has no SOA record

[root@nixos:~]# host -t soa impl.it
impl.it has no SOA record

[root@nixos:~]# host -t soa it
it has SOA record dns.nic.it. hostmaster.nic.it. 2021091818 10800 900 604800 3600
```

Will do further investigations.
