### ISSUE TITLE
Support for provider: UKFast

### ISSUE THREAD

**Issue by kale1d0code** [go-acme/lego#1503]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://www.ukfast.co.uk/

### Link to the API documentation

https://developers.ukfast.io/documentation/safedns

### Additional Notes

I would like to use wildcard certificates from lets encrypt but my DNS provider it is not supported
I have never used lego outside of the context of traefik, and I know very little about the go language,
however I would like to help bring support for my DNS provider to lego

**Comment by Xiol** [comment]
I've submitted a PR for this, and I (and UKFast) can continue to maintain this implementation going forward.
