### ISSUE TITLE
Revoke asking for valid reason input

### ISSUE THREAD

**Issue by eduardolmedeiros** [go-acme/lego#1509]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

```console
$ ./lego --accept-tos --server=https://acme.server.com/acme/xxxx/directory --eab --kid xxx --hmac xxx --email=admin@email.com --domains=xyz.app.mydomain.com revoke
```

### What did you see instead?

```console
$ ./lego --accept-tos --server=https://acme.server.com/acme/xxxx/directory --eab --kid xxx --hmac xxx --email=admin@email.com --domains=xyz.app.mydomain.com revoke

2021/10/07 13:04:03 Trying to revoke certificate for domain xyz.app.mydomain.com
2021/10/07 13:04:03 Error while revoking the certificate for domain xyz.app.mydomain.com
	acme: error: 0 :: POST :: https://acme.server.com:443/acme/xxxx/revokeCert :: urn:ietf:params:acme:error:badRevocationReason :: Valid revocation reasons are 1,3,4 or 5
```

### How do you use lego?

Binary

### Reproduction steps

1. run lego binary with revoke option

### Version of lego

```console
lego version 4.5.3 linux/amd64
```

### Logs
```
2021/10/07 13:04:03 Trying to revoke certificate for domain xyz.app.mydomain.com
2021/10/07 13:04:03 Error while revoking the certificate for domain xyz.app.mydomain.com
	acme: error: 0 :: POST :: https://acme.server.com:443/acme/xxxx/revokeCert :: urn:ietf:params:acme:error:badRevocationReason :: Valid revocation reasons are 1,3,4 or 5
```

**Comment by eduardolmedeiros** [comment]
Hey @ldez 

Indeed. I agree that the issue is on ACME server implementation, once the revoke reason is optional according to the RFC.

I just would like to know, if it is possible to set the revoke reason.

I meant, I did find nothing in the documentation. Is that feature missing currently? If so, is there any roadmap to implement that?

Thanks.
Eduardo.

**Comment by ldez** [comment]
Currently, it's not possible, but I'm working on it, I will create a PR this week.
