### ISSUE TITLE
Improve error message for provider DuckDNS if domain string is not "duckdns.org"

### ISSUE THREAD

**Issue by arkanoid87** [go-acme/lego#1522]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Through Traefik

### Detailed Description

I've by mistake submitted lego request for mysub.duckdns.COM instead of ORG and the result was "domains=com" in submitted request.

Error was on my side, but result was misleading. Improving error message could save some time considering that there's no other option than "duckdns.org"

https://github.com/go-acme/lego/blob/dc2b19e1b1a455b271716dffbcd1ff85cd3076ee/providers/dns/duckdns/client.go#L54

**Comment by ldez** [comment]
Hello,

duckdns.com is a valid domain that you can buy or own, I don't see any reason to handle this domain as an exception.

There are a lot of LTD (.com, .net, .io, .dev, ...), I don't think we will handle all the TLD.

**Comment by arkanoid87** [comment]
Not if the selected provider is duckdns
