### ISSUE TITLE
Versio - Problems on our DirectAdmin-platform

### ISSUE THREAD

**Issue by VersioSupport** [go-acme/lego#1528]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

### Detailed Description

Hi,

It's not really a bug report or feature request because we were not aware that we were incorporated within the lego-script: https://github.com/go-acme/lego/tree/master/providers/dns/versio

We just noticed that the request from Letsencrypt in our DirectAdmin-environment gets this error:

`versio: 401: request failed: You are not authorized to access this resource. Did you supply the correct credentials and have you IP whitelisted for API use?`

Our system administrators fixed it for now (not sure exactly how) but is this "provider"-support really needed because we are not the ones that requested this.

Is it possible that this provider-support to be removed from LeGo?

Hesdy
Support Versio BV

**Comment by ldez** [comment]
Hi,

this provider has been added, 2 years ago, by @fjmk, a contributor and user of your services, in #909.

I'm not sure to understand why do you want to remove the provider from lego, could you explain in detail?

FYI, There is no request from Let's Encrypt to your API, the calls are from lego (which can be used as a library by other projects or a CLI tool).

I don't know how your API works exactly but the error seems to be a misconfiguration of the credentials of users.
