### ISSUE TITLE
certcrypto.generateDerCert 365 nanoseconds – is that meant to be the case?

### ISSUE THREAD

**Issue by jufemaiz** [go-acme/lego#1533]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

N/A

### What did you see instead?

N/A

### How do you use lego?

Other

### Reproduction steps

https://github.com/go-acme/lego/blob/master/certcrypto/crypto.go#L263-L265

Is the duration of `365ns` from `time.Now()` as the expiration where it is the zero value of time intentional or is it an unintended artefact?

### Version of lego

```console
@ https://github.com/go-acme/lego/commit/e79975cf142ede5138e5a239c61b1474a80c3874
```
Originating source was 2015.
https://github.com/go-acme/lego/blob/a2d9bf4cc35cad86e7bbfdab1f8d7256ac3209f7/acme/simple_http_challenge.go#L129-L155

### Logs

N/A

### Go environment (if applicable)

N/A

**Comment by sjauld** [comment]
I feel like maybe the intention was to be a year. PR to follow.
