### ISSUE TITLE
The --dns-timeout option is either broken, or needs its usage documented more clearly

### ISSUE THREAD

**Issue by kevincantu** [go-acme/lego#1535]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I've run lego with something like this:
```
lego --accept-tos --dns-timeout 300 --dns cloudflare -d app.example.test --email me@example.test renew
```

Amongst the output I expected a **5m** timeout (corresponding to my flag and 300s) but saw a **2m** one instead.

However, by defining some additional timeout envvars I was able to get the longer timeouts I wanted.

So is that **--dns-timeout** option working!?  Or was I confused when I thought it was equivalent to `CLOUDFLARE_PROPAGATION_TIMEOUT`?

Compare the following documentation I was referencing:
```
GLOBAL OPTIONS:
...
   --http-timeout value         Set the HTTP timeout value to a specific value in seconds. (default: 0)
   --dns-timeout value          Set the DNS timeout value to a specific value in seconds. Used only when performing authoritative name servers queries. (default: 10)
```
https://go-acme.github.io/lego/usage/cli/

> CLOUDFLARE_HTTP_TIMEOUT: API request timeout
> CLOUDFLARE_POLLING_INTERVAL: Time between DNS propagation check/
> CLOUDFLARE_PROPAGATION_TIMEOUT:  Maximum waiting time for DNS propagation
https://go-acme.github.io/lego/dns/cloudflare/

### What did you see instead?

With no extra envvars, I saw this:
```
2021/11/30 12:25:12 [INFO] [app.example.test] acme: Preparing to solve DNS-01
2021/11/30 12:35:12 [INFO] cloudflare: new record for app.example.test, ID <snip>
2021/11/30 12:35:12 [INFO] [app.example.test] acme: Trying to solve DNS-01
2021/11/30 12:35:12 [INFO] [app.example.test] acme: Checking DNS record propagation using [10.0.0.1:53]
2021/11/30 12:35:14 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
```

Now, that's been timing out with a somewhat garbled error message, and we've just found that by _actually_ extending the timeout we can get our cert generated ok:
```
export CLOUDFLARE_HTTP_TIMEOUT=60
export CLOUDFLARE_POLLING_INTERVAL=10
export CLOUDFLARE_PROPAGATION_TIMEOUT=301
```

With those flags, output looks like this:
```
2021/11/30 12:57:38 [INFO] [app.example.test] acme: Checking DNS record propagation using [10.47.120.1:53]
2021/11/30 12:57:48 [INFO] Wait for propagation [timeout: 5m1s, interval: 10s]
```

So is that **--dns-timeout** working!?  Or was I confused when I thought it was equivalent to `CLOUDFLARE_PROPAGATION_TIMEOUT`?

### How do you use lego?

Binary

### Reproduction steps

To see 2m propagation timeout (despite --dns-timeout 300), run this:
```
lego --accept-tos --dns-timeout 300 --dns cloudflare -d app.example.test --email me@example.test renew
```

### Version of lego

```console
I installed lego via:

go install github.com/go-acme/lego/v4/cmd/lego@v4.5.3


The version as displayed is:
```
% lego --version
lego version dev darwin/amd64

```
```

### Logs

(see above)

### Go environment (if applicable)

I'm on Go 1.17.2.

**Comment by ldez** [comment]
Hello,

`--dns-timeout` is not related to provider timeout `xxx_PROPAGATION_TIMEOUT`.

The doc is clear to me:

> Used only when performing authoritative name servers queries.

This timeout (`--dns-timeout`) is used when lego does the DNS queries.

`xxx_PROPAGATION_TIMEOUT` is used when lego waits for the propagation.

> Maximum waiting time for DNS propagation

**Comment by kevincantu** [comment]
So, @ldez, the --dns-timeout is for each single query, but the propagation timeout is for the total duration of waiting, during which lego makes another query every poll interval?

**Comment by ldez** [comment]
Yes.
