### ISSUE TITLE
Support for provider: huawei cloud

### ISSUE THREAD

**Issue by zhangdongdong7** [go-acme/lego#1543]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://huaweicloud.com
https://www.huaweicloud.com/intl/en-us/

### Link to the API documentation

https://support.huaweicloud.com/api-dns/zh-cn_topic_0132421999.html
https://support.huaweicloud.com/intl/en-us/api-dns/dns_api_10000.html

https://github.com/huaweicloud/huaweicloud-sdk-go
https://github.com/huaweicloud/huaweicloud-sdk-go-v3

### Additional Notes

https://github.com/acmesh-official/acme.sh/blob/edd46eb3d1bb3698b80d9beba79ba1be0c9b59e4/dnsapi/dns_huaweicloud.sh

**Comment by Anyexyz** [comment]
Is there any plan to resolve this issue？

**Comment by ldez** [comment]
_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

**Comment by jiuyue52** [comment]
目前有计划支持华为云没

**Comment by ldez** [comment]
_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

if we have someone to create a PR or to be able to test a PR, we will implement it.
