### ISSUE TITLE
Support for provider: self-signed

### ISSUE THREAD

**Issue by Yivan** [go-acme/lego#1549]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

http://localhost

### Link to the API documentation

http://self-signed

### Additional Notes

Hello,

I was replying to a Q&A about self-signing certificate (https://github.com/go-acme/lego/discussions/1541), but I think my request we be better here.

We use Traefik which uses Lego. And we would like to have a provider called "self-signed".
I looked for exec and http providers, but they work with "present" and "cleanup" format for DNS-01 challenge.

Two possibilities would be for instance :
- having a provider called "self signed" which handle the creation of self signed certificate (but with the common name corresponding to what is asked)
- having a pure exec which will return the certificates to lego (so we can call openssl to generate the way we want). Return will be the certificate paths to download for instance (in a structured format, like json for instance)

We need local certificates for development, we don't need valid certs, just certs having the right common name so we can do Host SNI for TCP proxy. As not reachable from exterior (dev environment), DNS-01 challenge cannot be used, and some domains are just dev domains (no real domains registered).

Thanks for reading me.

**Comment by ldez** [comment]
The goal of lego is to provide certificates based on the ACME RFC (like Let's Encrypt)

self-signed certificates are out of the scope of lego.

If you want to handle local certificates you can take a look at [mkcert](https://github.com/FiloSottile/mkcert)
