### ISSUE TITLE
Add support for aarch64 linux

### ISSUE THREAD

**Issue by via-justa** [go-acme/lego#1551]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

### Detailed Description

I've created a [Home-Assistant addon](https://github.com/via-justa/via-justa-home-assistant-addons) wrapper around Lego and would love to have an aarch64 binary available for pulling (For HA on raspberry Pi).

At the moment I build Lego from code and run it successfully so I do not think it should be an issue to add it.

**Comment by ldez** [comment]
Hello,

If I remember well aarch64 is ARMv8 (ie arm64).

We already provide an ARM64 binary.

https://github.com/go-acme/lego/releases
