### ISSUE TITLE
Joker DNS challenge fails with `acme: error presenting token: error: 401: badauth`

### ISSUE THREAD

**Issue by ieure** [go-acme/lego#1554]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

A shiny new certificate for `foo.bar.mydomain.tld`, with the `*.foo.bar.mydomain.tld` wildcard as an alternative name.

### What did you see instead?

An authentication error.

### How do you use lego?

Docker image

### Reproduction steps

1. Enable dynamic DNS on your domain in Joker.
2. Put the credentials in `joker-username` and `joker-password` files.
3. Create two CNAME records, one for `foo.bar.mydomain.tld`, one for `*.foo.bar.mydomain.tld`, both pointing at the same host.
4. Run lego: `JOKER_DEBUG=true JOKER_API_MODE=SVC JOKER_USERNAME_FILE=joker-username JOKER_PASSWORD_FILE=joker-password lego --accept-tos --email me@mydomain.tld --dns joker --domains 'foo.bar.mydomain.tld' --domains '*.foo.bar.mydomain.tld' run`

I have a dynamic DNS service which runs using these exact same credentials, so I'm sure the username/password are correct and that Joker's stuff works with them.

Fundamentally:

- I'm not sure if I'm using lego correctly, and the documentation doesn't clarify whether I am or not.  I'd be happy to hear that I'm Just Doing It Wrong, but wish there was a better way than filing a bug report.
  - Can I not have a wildcard on a subdomain like I want?
  - Do I have to manually create a `TXT` record in Joker for lego to be able to update it?
- I have no idea what lego is *actually doing* to result in that error, so I can't troubleshoot it.
- There's no `--verbose` option to make lego show me what it's doing.
- While I found the undocumented `JOKER_DEBUG` environment variable in the code, it doesn't appear to do anything.

### Version of lego

```console
lego version v4.5.3 linux/amd64
```
I'm running with [this Docker image](https://hub.docker.com/layers/goacme/lego/latest/images/sha256-0df0fd0f0fb03ce9567c70d9e58704226071c1304c2d564a0ac1db2b0a806f01?context=explore)

### Logs

<details>

```console
2021/12/30 02:04:21 [INFO] [foo.bar.mydomain.tld, *.foo.bar.mydomain.tld] acme: Obtaining bundled SAN certificate
2021/12/30 02:04:22 [INFO] [*.foo.bar.mydomain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/63247760480
2021/12/30 02:04:22 [INFO] [foo.bar.mydomain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/63247760490
2021/12/30 02:04:22 [INFO] [*.foo.bar.mydomain.tld] acme: use dns-01 solver
2021/12/30 02:04:22 [INFO] [foo.bar.mydomain.tld] acme: Could not find solver for: tls-alpn-01
2021/12/30 02:04:22 [INFO] [foo.bar.mydomain.tld] acme: Could not find solver for: http-01
2021/12/30 02:04:22 [INFO] [foo.bar.mydomain.tld] acme: use dns-01 solver
2021/12/30 02:04:22 [INFO] [*.foo.bar.mydomain.tld] acme: Preparing to solve DNS-01
2021/12/30 02:04:22 [INFO] [*.foo.bar.mydomain.tld] acme: Cleaning DNS-01 challenge
2021/12/30 02:04:23 [WARN] [*.foo.bar.mydomain.tld] acme: cleaning up failed: error: 401: badauth

2021/12/30 02:04:23 [INFO] [foo.bar.mydomain.tld] acme: Preparing to solve DNS-01
2021/12/30 02:04:23 [INFO] [foo.bar.mydomain.tld] acme: Cleaning DNS-01 challenge
2021/12/30 02:04:23 [WARN] [foo.bar.mydomain.tld] acme: cleaning up failed: error: 401: badauth

2021/12/30 02:04:23 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/63247760480
2021/12/30 02:04:23 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/63247760490
2021/12/30 02:04:24 Could not obtain certificates:
	error: one or more domains had a problem:
[*.foo.bar.mydomain.tld] [*.foo.bar.mydomain.tld] acme: error presenting token: error: 401: badauth

[foo.bar.mydomain.tld] [foo.bar.mydomain.tld] acme: error presenting token: error: 401: badauth
```

</details>

**Comment by ldez** [comment]
username and passsword are not my email and account passwords, but those displayed in Joker.com domain dashboard when enabling Dynamic DNS.

Reference: https://joker.com/faq/content/6/496/en/let_s-encrypt-support.html

```
Setting a TXT record is fairly straightforward:
1. please login at Joker.com, visit 'My Domains', find the domain you want to add  Let's Encrypt
 certificate for, and chose "DNS" in the menu

2. on the top right, you will find the setting for 'Dynamic DNS'. If not already active, please activate it. 
It will not affect any other already existing DNS records of this domain.

3. please take a note of the credentials which are now shown as 'Dynamic DNS Authentication',
 consisting of a 'username' and a 'password'.

4. this is all you have to do here - and only once per domain.
```

**Comment by ieure** [comment]
@Idez I appreciate the documentation efforts, but it unfortunately doesn't solve my problem.  I already enabled Dynamic DNS for my domain and am using those credentials with lego, but all I get is the 401 error.  I looked around the source and saw that it's using `svc.joker.com`, which I know requires the per-domain DDNS creds.

I also tried a simpler case of a non-wildcard cert for a direct address, `foo.mydomain.tld`, but I get the same 401 error.

Are there troubleshooting steps I can take to determine what lego is doing and what's going wrong?

**Comment by ldez** [comment]
The SVC API is really simple, and the error `badauth` is an error from the API itself.
The error is clear about the root cause: bad authentication credentials

You can check if there are no extra characters in the content of your files (`JOKER_USERNAME_FILE`, `JOKER_PASSWORD_FILE`), you can also use `JOKER_USERNAME`, `JOKER_PASSWORD`

**Comment by ieure** [comment]
Okay, wow, I feel very dumb.  The issue ended up being that I read the same credential file for both username and password:

```yaml
secrets:
  joker-username:
    file: ./secrets/joker-username.txt
  joker-password:
    file: ./secrets/joker-username.txt
```

Thanks for the help.
