### ISSUE TITLE
Support Azure Private DNS Zones for dns challenge

### ISSUE THREAD

**Issue by knutejoh** [go-acme/lego#1562]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

### Detailed Description

Add support for Azure Private DNS Zones for running a private ACME server inside Azure without the need to register in public dns. 

I've created the PR #1561 for this, and this might also be relevant for #1432 as they could use private zones and not public.

**Comment by knutejoh** [comment]
As #1561 has been merged, this could be closed now. 
When will the 4.6 version likely be released?

**Comment by ldez** [comment]
Closed by #1561
