### ISSUE TITLE
Support for provider: Variomedia

### ISSUE THREAD

**Issue by SIMULATAN** [go-acme/lego#1637]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://www.variomedia.de

### Link to the API documentation

- https://api.variomedia.de/docs/dns-records.html
- https://www.variomedia.de/faq/Wie-kann-ich-die-API-fuer-den-Lets-Encrypt-Certbot-nutzen/article/327

### Additional Notes

The site is entirely in german, the "docs" can be found in the google translated version [here](https://api-variomedia-de.translate.goog/docs/dns-records.html?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=fr&_x_tr_pto=wapp) and [here](https://www-variomedia-de.translate.goog/faq/Wie-kann-ich-die-API-fuer-den-Lets-Encrypt-Certbot-nutzen/article/327?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc)

The shell script version is [here](https://www.variomedia.de/tools/certbot/certbot-dns-master.zip)

**Comment by ldez** [comment]
Hello,

Can you give me the output of the following command?
Because the API documentation doesn't describe the response of the API endpoints

```bash
API_TOKEN=<your_token> \
DOMAIN=<your_domain> \
SUBDOMAIN=<your_subdomain> \
curl -s -X POST "https://api.variomedia.de/dns-records" \
-H "Authorization: token $API_TOKEN" \
-H "Content-Type: application/vnd.api+json" \
-H "Accept: application/vnd.variomedia.v1+json" \
--data '{"data":{"type":"dns-record","attributes":{"record_type":"TXT","name":"'_acme-challenge${SUBDOMAIN}'","domain":"'$DOMAIN'","data":"test","ttl":300}}}'
```

**Comment by ldez** [comment]
@SIMULATAN any news?

**Comment by SIMULATAN** [comment]
Unfortunately, it turns out that it's harder to get a key than stated on the website. I contacted the support and they said that they can create a key for me which is what I'll ask for today, I will notify you once I have it and can test the call.

I'm very sorry for the delay, I really didn't expect it to be harder than stated in the FAQ.

**Comment by ldez** [comment]
@SIMULATAN any news?

**Comment by SIMULATAN** [comment]
### `GET https://api.variomedia.de/queue-jobs/JOB_ID`
HTTP 200
```json
{
    "data": {
        "id": "171717",
        "type": "queue-job",
        "links": {
            "self": "https://api.variomedia.de/queue-jobs/171717",
            "object": "https://api.variomedia.de/dns-records/212121"
        },
        "attributes": {
            "job_type": "dns-record",
            "status": "done"
        },
        "relationships": {
            "owner": {
                "data": {
                    "id": "505050",
                    "type": "customer"
                }
            }
        }
    },
    "links": {
        "self": "https://api.variomedia.de/queue-jobs/171717"
    }
}
```

### `DELETE https://api.variomedia.de/dns-records/RECORD_ID`
!**HTTP 202 ACCEPTED**!
```json
{
    "data": {
        "type": "queue-job",
        "id": "303030",
        "attributes": {
            "status": "pending"
        },
        "links": {
            "queue-job": "https://api.variomedia.de/queue-jobs/303030"
        }
    },
    "links": {
        "self": "https://api.variomedia.de/dns-records/212121"
    }
}
```
(another job, running the status for this returns this:)
```json
{
    "data": {
        "id": "303030",
        "type": "queue-job",
        "links": {
            "self": "https://api.variomedia.de/queue-jobs/303030",
            "object": "https://api.variomedia.de/dns-records/212121"
        },
        "attributes": {
            "job_type": "dns-record",
            "status": "done"
        },
        "relationships": {
            "owner": {
                "data": {
                    "id": "505050",
                    "type": "customer"
                }
            }
        }
    },
    "links": {
        "self": "https://api.variomedia.de/queue-jobs/303030"
    }
}
```
(this is pretty much the same as the create request)
