### ISSUE TITLE
Dynu dns-challenge fails creating a certificates for subdomains

### ISSUE THREAD

**Issue by daneget** [go-acme/lego#1672]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

While dynu dns-challenge is working to generate a certificate, I expect to see an _acme-challenge.subdomain.example.com txt record in my dns manager

### What did you see instead?

Dynu dns-challenge does not create a certificate and I saw an _acme-challenge.example.com txt record that is not deleted in my dns manager

### How do you use lego?

Through Traefik

### Reproduction steps

1. Configure traefik with dynu dns-challenge including the needed environment variable with the api key
2. Add a website redirection througth traefik using subdomain.example.com as domain
3. Open the website in a navigator using the domain configured in traefik

### Version of lego

```console
Traefik: 2.8.0
Lego: v4.7.0
```

### Logs

<details>

```console
proxy-traefik-1  | time="2022-07-04T21:45:17Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Obtaining bundled SAN certificate"
proxy-traefik-1  | time="2022-07-04T21:45:18Z" level=debug msg="legolog: [INFO] [subdomain.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/126983907086"
proxy-traefik-1  | time="2022-07-04T21:45:18Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Could not find solver for: tls-alpn-01"
proxy-traefik-1  | time="2022-07-04T21:45:18Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Could not find solver for: http-01"
proxy-traefik-1  | time="2022-07-04T21:45:18Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: use dns-01 solver"
proxy-traefik-1  | time="2022-07-04T21:45:18Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Preparing to solve DNS-01"
proxy-traefik-1  | time="2022-07-04T21:45:24Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Cleaning DNS-01 challenge"
proxy-traefik-1  | time="2022-07-04T21:45:34Z" level=debug msg="legolog: [WARN] [subdomain.example.com] acme: cleaning up failed: dynu: could not find root domain for subdomain.example.com: client error: Get \"https://api.dynu.com/v2/dns/getroot/subdomain.example.com\": net/http: TLS handshake timeout "
proxy-traefik-1  | time="2022-07-04T21:45:35Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/126983907086"
proxy-traefik-1  | time="2022-07-04T21:45:36Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 3m0s, interval: 10s]"
```

</details>

**Comment by ldez** [comment]
hello,

> net/http: TLS handshake timeout

this error means that Dynu takes more than 10s to do the handshake: this is very slow.

**Comment by daneget** [comment]
> hello,
> 
> > net/http: TLS handshake timeout
> 
> this error means that Dynu takes more than 10s to do the handshake: this is very slow.

Hi Idez, the previous log isn't a very good sample of what is happening because the error you indicated.

Here you have a new log without that error and with the same throuble

```console
proxy-traefik-1  | time="2022-07-04T22:10:24Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Obtaining bundled SAN certificate"
proxy-traefik-1  | time="2022-07-04T22:10:25Z" level=debug msg="legolog: [INFO] [subdomain.example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/126990389246"
proxy-traefik-1  | time="2022-07-04T22:10:25Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Could not find solver for: tls-alpn-01"
proxy-traefik-1  | time="2022-07-04T22:10:25Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Could not find solver for: http-01"
proxy-traefik-1  | time="2022-07-04T22:10:25Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: use dns-01 solver"
proxy-traefik-1  | time="2022-07-04T22:10:25Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Preparing to solve DNS-01"
proxy-traefik-1  | time="2022-07-04T22:10:28Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Trying to solve DNS-01"
proxy-traefik-1  | time="2022-07-04T22:10:28Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Checking DNS record propagation using [127.0.0.11:53]"
proxy-traefik-1  | time="2022-07-04T22:10:38Z" level=debug msg="legolog: [INFO] Wait for propagation [timeout: 3m0s, interval: 10s]"
proxy-traefik-1  | time="2022-07-04T22:10:40Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:10:50Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:11:00Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:11:10Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:11:20Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:11:31Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:11:41Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:11:51Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:12:01Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:12:11Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:12:21Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:12:31Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:12:42Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:12:52Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:13:02Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:13:12Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:13:22Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:13:32Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Waiting for DNS record propagation."
proxy-traefik-1  | time="2022-07-04T22:13:42Z" level=debug msg="legolog: [INFO] [subdomain.example.com] acme: Cleaning DNS-01 challenge"
proxy-traefik-1  | time="2022-07-04T22:13:44Z" level=debug msg="legolog: [INFO] retry due to: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/authz-v3/126990389246 :: urn:ietf:params:acme:error:badNonce :: JWS has an invalid anti-replay nonce: \"0001J5hPeMQlw52SR2oaDJIWE9XOB8rREijFJ01Il6MQBuM\""
proxy-traefik-1  | time="2022-07-04T22:13:45Z" level=debug msg="legolog: [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/126990389246"
```

**Comment by ldez** [comment]
Your log doesn't contain any problem, the retry is not a problem.

**Comment by daneget** [comment]
Hi Idez,

The trouble I had configuring traefik with lego's dynu provider is not TXT records aren't being deleted, the trouble is that is doen't generate the certificate for the domain I've configured and allways I enter in a web managed by traefik I have an insecure certificate warning in my navigator.

This error happends also with the second log I included, which indicates no error but I have saw this things happends:

1. Dynu provider creates a **_acme-challenge.example.com** TXT record instead of **_acme-challenge.subdomain.example.com**
2. Dns Challenge fails because **_acme-challenge.subdomain.example.com** TXT record is never created
3. Finally dynu provider tries to delete the **_acme-challenge.subdomain.example.com** TXT record, but it doesn't do anything because it doesn't exist

**Comment by ldez** [comment]
The API of Dynu is really unstable and nonreliable, it was already a problem when I created the provider.

https://github.com/go-acme/lego/pull/1081

Note: My login is **L**dez

**Comment by an0t8** [comment]
I just ran into this problem as well.  I tracked in down to providers/dns/dynu/dynu.go line 102, where the hostname is rendered down to the root.  When calling the dynu api (currently): https://api.dynu.com/v2/dns/getroot/subdomain.example.com will return a root domain of example.com IF both example.com and subdomain.example.com are listed in the domains.  dynu.go then uses the ID of the root domain to create the record. So the TXT record is getting created on the wrong domain entry. (i.e _acme-challenge.example.com instead of _acme-challenge.subdomain.example.com)

**Comment by jorgecastello** [comment]
Same issue here using Traekik v2.9 with wildcard certificates

ACME challenge expects TXT DNS record named **_acme-challenge.traefik.mydomain.dynu.net**
However, the record that Lego generates using Dynu API is **_acme-challenge.mydomain.dynu.net**, so it timesout as the expected record is never propagated.

If I manually generate such record, challenge completes successfully and certificates are issued correctly.

**Comment by xuguangyuansh** [comment]
This problem may be caused by NAT .

**Comment by jorgecastello** [comment]
> This problem may be caused by NAT .

I don't think so. I guess Dynu's API is not being called the right way. To create the TXT record entry in the **subdmain**, this post requet should be used:

{
	"nodeName": "_acme-challenge.subdomain",
	"recordType": "TXT",
	"ttl":300,
	"state":true,
	"textData": "TXT_CHALLENGE_VALUE"
}

I've forced challenge to succeed by issuing a POST to Dynu's API whith that content while LEGO was trying to validate it

**Comment by ldez** [comment]
Currently, it's what lego is trying to do.
But the algo can have a flaw if the [root domain](https://www.dynu.com/en-US/Support/API#/dns/dnsGetrootHostnameGet) is not related to the domain.
