### ISSUE TITLE
Fetch URL Printout & Persistent file option

### ISSUE THREAD

**Issue by DocterDum** [go-acme/lego#1681]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

I'm getting an error:
[mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 111.111.111.111: Fetching https://mydomain.com/.well-known/acme-challenge/R7RpTdXcc0pABB6PvbuClqr2LyuYJLamQxVQJW-ahAE: Connection refused

In trying to troubleshoot this, I'd like to test the URL it's fetching, however the URL is printed out at the same time the file is deleted. I can watch as the file is being created and I can create and test similar files (And URLs) and everything is successful, so I cannot see why this would be failing (hence wanting to test the specific URL).

It would be helpful if there was an option to leave the acme-challenge file in place instead of deleting it.

**Comment by ldez** [comment]
Hello,

you're not providing enough context to understand your problem.

**Comment by DocterDum** [comment]
I run lego with:
lego -a --email my@email.com --http --http.webroot /opt/nginx/html/ --domains mydomain.com run

It runs for a bit and then gets the following error:
[mydomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 111.111.111.111: Fetching https://mydomain.com/.well-known/acme-challenge/R7RpTdXcc0pABB6PvbuClqr2LyuYJLamQxVQJW-ahAE: Connection refused

I can create files in my acme-challenge directory:
/opt/nginx/html/.well-known/acme-challenge/example.txt

And they are properly served up and accessible over both HTTP and HTTPS:
https://mydomain.com/.well-known/acme-challenge/example.txt

I am unable to specifically test the acme-challenge file created by lego, because right after it prints the error message, it deletes the file  (e.g. in this case R7RpTdXcc0pABB6PvbuClqr2LyuYJLamQxVQJW-ahAE). I can re-create the file myself, and successfully access it at the corresponding URL. 

It would be helpful if there was a command-line option for lego to keep the acme-challenge file in place instead of deleting it, to assist with troubleshooting.

**Comment by ldez** [comment]
So you are using the HTTP-01 challenge. The error "Connection refused" is not related to the content of the token file or the file itself, it's related to a network problem.

I thin that the fact to keep the file will not help you to find the root cause of your problem.

**Comment by DocterDum** [comment]
Aah okay, that makes sense. I'll do some more troubleshooting and figure out why it might be refusing the connection. Thanks for your help :)
