### ISSUE TITLE
Njalla dns provider not working anymore: unmarshal error

### ISSUE THREAD

**Issue by manuel2258** [go-acme/lego#1685]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

That dnsChallenge using traefik and the dns provider 'njalla' returns valid certificates.

Additional notes:
- Also reproducible using docker image without traefik, therefor I included the reproduction steps of the docker image.
- It did work a few weeks / maybe a month ago, so maybe the API changed?

### What did you see instead?

acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int

### How do you use lego?

Docker image

### Reproduction steps

1. docker run -it -e NJALLA_TOKEN=51b...2e7 goacme/lego:v4.8.0 --email "development@manu.software" --dns njalla --domains "test.manu.software" -a run

### Version of lego

```console
lego version v4.8.0 linux/amd64
```

### Logs

<details>

```console
2022/08/01 18:34:56 No key found for account development@manu.software. Generating a P256 key.
2022/08/01 18:34:56 Saved key to /.lego/accounts/acme-v02.api.letsencrypt.org/development@manu.software/keys/development@manu.software.key
2022/08/01 18:34:57 [INFO] acme: Registering account for development@manu.software
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "/.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2022/08/01 18:34:58 [INFO] [test.manu.software] acme: Obtaining bundled SAN certificate
2022/08/01 18:34:59 [INFO] [test.manu.software] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/137177728806
2022/08/01 18:34:59 [INFO] [test.manu.software] acme: Could not find solver for: tls-alpn-01
2022/08/01 18:34:59 [INFO] [test.manu.software] acme: Could not find solver for: http-01
2022/08/01 18:34:59 [INFO] [test.manu.software] acme: use dns-01 solver
2022/08/01 18:34:59 [INFO] [test.manu.software] acme: Preparing to solve DNS-01
2022/08/01 18:34:59 [INFO] [test.manu.software] acme: Cleaning DNS-01 challenge
2022/08/01 18:34:59 [WARN] [test.manu.software] acme: cleaning up failed: njalla: unknown record ID for '_acme-challenge.test.manu.software.' 'cEmnxvprPUKZNbXWLHXcO5YWS3ELCjWjIucSHAIPP78'
2022/08/01 18:34:59 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/137177728806
2022/08/01 18:35:00 Could not obtain certificates:
	error: one or more domains had a problem:
[test.manu.software] [test.manu.software] acme: error presenting token: njalla: failed to add record: failed to unmarshal response result: json: cannot unmarshal string into Go struct field Record.id of type int
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by manuel2258** [comment]
Probing the API a bit seems to reveal the problem:
```
curl -s \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Njalla ${NJALLA_TOKEN}" \
    --data '{"method":"list-records", "params": {"domain": "manu.software"}}' \
    https://njal.la/api/1/
{"result": {"records": [{"id": "401747", "name": "cloud", "type": "A", "content": "79.143.179.92", "ttl": 10800}, ...]}}
```

'id' is supposed to be an Int as of here:
https://github.com/go-acme/lego/blob/master/providers/dns/njalla/internal/types.go#L34

I guess the API changed, although they still state that its supposed to be a int: https://njal.la/api/ , or is it normal that the id is encoded as a string?

**Comment by ldez** [comment]
Hello,
I don't have access to the API documentation, can you take a screenshot or something else?

**Comment by manuel2258** [comment]
Oh god that not nice of them ...
I guess the endpoints concerning the records are enough?

<details>
<summary>API Doc</summary>

## add-record
Add new DNS Record to domain
params: {
    domain: string
    name: string
    content: string
    ttl: int
    type: string
    ...
}
returns: {
    id: int
    content: string
    domain: string
    name: string
    ttl: int
    type: string
}


## edit-record
Edit DNS Record

params: {
    domain: string
    id: int
    content: string
}
returns: {
}

## list-records
List DNS records for given domain

params: {
    domain: string
}
returns: {
    records: list
}


## remove-record
Remove DNS Record

params: {
    domain: string
    id: int
}
returns: {
}
</details>

**Comment by manuel2258** [comment]
I could send them a support ticket asking whether the API change was on purpose and if so then I would just be a matter of converting the value, right? If so and wanted then I could also fix it right away.

However it seems rather odd that they would just change such an parameter from and int to string without reflecting it in their docu. 
Or could it be that they did not change anything and there is a issue somewhere else? (I'm not familiar on how the used deserialization is working)

**Comment by ldez** [comment]
I think they "fix" their API: the deserialization in Go is strict but some languages are less strict, so they can see that as a transparent change.
But it's not transparent in Go.

**Comment by ldez** [comment]
If you want to create a PR to fix the problem, you can do it.

**Comment by manuel2258** [comment]
Well then lets fix their fix :)

I already fixed and tested in locally, I would create a PR if wanted.
I also wrote a support ticket to check whether it was intentionally or not, so I would wait until they answer before we merge anything.

**Comment by mikniche** [comment]
Would also love an update for this 😃
