### ISSUE TITLE
Support short-lived certificates

### ISSUE THREAD

**Issue by Seirdy** [go-acme/lego#1714]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

ACME clients [like acme.sh](https://github.com/acmesh-official/acme.sh/wiki/Validity) support customizing the "notAfter" field of a cert for supported CAs (currently ZeroSSL and Google). This allows users to set validity periods shorter than three months.

When certificate renewal is fully automated, there's no need to use certs with excessively long lifetimes (three months!); we can auto-renew them on a daily basis. Combined with something like [a regular OCSP stapling-file renewal](https://github.com/tomwassenberg/certbot-ocsp-fetcher), this *significantly* reduces the impact of issues like a compromised certificate.

**Comment by ldez** [comment]
Hello,

You can use `--days`:

```

   --days value                              The number of days left on a certificate to renew it. (default: 30)
```

**Comment by Seirdy** [comment]
@ldez does this change the duration of a certificate's validity, or just customize the duration to wait before triggering an auto-renewal? The docs don't seem to state which.

-- 
Seirdy (https://seirdy.one)

**Comment by ldez** [comment]
I think you cannot control the certificate's validity, I have to check the ACME RFC.

**Comment by Seirdy** [comment]
ZeroSSL and Google Trust Services support the "notAfter" flag, which is implemented in the /x/crypto/acme package and acme.sh

-- 
Seirdy (https://seirdy.one)

**Comment by imlonghao** [comment]
Should be easy to implement, I did the following modify then issue a certificate lifetime with 228 hours

```
