### ISSUE TITLE
Support for provider: Knot (self-hosted)

### ISSUE THREAD

**Issue by McSinyx** [go-acme/lego#1721]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Other

### Link to the DNS provider

https://www.knot-dns.cz

### Link to the API documentation

https://www.knot-dns.cz/docs/latest/html/man_knsupdate.html

### Additional Notes

I use NixOS [security.acme.certs](https://search.nixos.org/options?show=security.acme.certs.%3Cname%3E.dnsProvider&query=security.acme.certs+dns) for automated renewal.

[Support for Knot has been implemented for acme.sh](https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_knot.sh).  I may be able to implement it for Lego with some guidance.

**Comment by ldez** [comment]
Hello,

to create an implementation you can follow this implementation: https://github.com/go-acme/lego/tree/master/providers/dns/njalla

**Comment by ldez** [comment]
@McSinyx any news?

**Comment by Saklad5** [comment]
Why not use RFC 2136? That's what I use.

---

I _would_ appreciate the ability to use Unix domain sockets with RFC 2136, which Knot DNS added support for in 3.2.5.

**Comment by McSinyx** [comment]
Thanks, I thought about using exec but RFC 2136 is much better.

**Comment by Saklad5** [comment]
I've opened [a distinct issue](https://github.com/go-acme/lego/issues/1832) for the UDS request.
