### ISSUE TITLE
Support for provider: Pair Domains

### ISSUE THREAD

**Issue by sirbrucea** [go-acme/lego#1728]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://www.pairdomains.com/

### Link to the API documentation

https://www.pairdomains.com/kb/

**Comment by ldez** [comment]
Hello,

I don't see any API so I will close this issue.
An API is a requirement.
