### ISSUE TITLE
duckdns DNS-01 challenge failing

### ISSUE THREAD

**Issue by ioExpander** [go-acme/lego#1744]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Duckdns DNS-01 challenge to generate proper SSL certificates

### What did you see instead?

Unfortunately the challenge is failing with i/o timeout.

`time limit exceeded: last error: read udp 172.17.0.2:57687->35.183.157.249:53: i/o timeout`

Below are some more details.

### How do you use lego?

Docker image

### Reproduction steps

I encounter the issue with my Traefik home setup but it can be reproduced from a fresh server

1. Created a brand new server instance and installed docker.
2. run:
`docker run -e DUCKDNS_TOKEN=XXXXXX -v /root/duck/:/ssl goacme/lego -m YYYY@outlook.com --dns duckdns -d 'legotesting.duckdns.org' --path /ssl -a -s https://acme-staging-v02.api.letsencrypt.org/directory --dns.resolvers 1.1.1.1 run`
3. The challenge fails (see logs)

### Version of lego

```console
lego version v4.9.0 linux/amd64
```

### Logs

<details>

```console
2022/10/27 15:54:07 [INFO] [legotesting.duckdns.org] acme: Obtaining bundled SAN certificate
2022/10/27 15:54:08 [INFO] [legotesting.duckdns.org] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4119054314
2022/10/27 15:54:08 [INFO] [legotesting.duckdns.org] acme: Could not find solver for: tls-alpn-01
2022/10/27 15:54:08 [INFO] [legotesting.duckdns.org] acme: Could not find solver for: http-01
2022/10/27 15:54:08 [INFO] [legotesting.duckdns.org] acme: use dns-01 solver
2022/10/27 15:54:08 [INFO] [legotesting.duckdns.org] acme: Preparing to solve DNS-01
2022/10/27 15:54:13 [INFO] [legotesting.duckdns.org] acme: Trying to solve DNS-01
2022/10/27 15:54:18 [INFO] [legotesting.duckdns.org] acme: Checking DNS record propagation using [8.8.8.8:53]
2022/10/27 15:54:20 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2022/10/27 15:54:49 [INFO] [legotesting.duckdns.org] acme: Waiting for DNS record propagation.
2022/10/27 15:55:06 [INFO] [legotesting.duckdns.org] acme: Waiting for DNS record propagation.
2022/10/27 15:55:26 [INFO] [legotesting.duckdns.org] acme: Waiting for DNS record propagation.
2022/10/27 15:55:28 [INFO] [legotesting.duckdns.org] acme: Cleaning DNS-01 challenge
2022/10/27 15:55:28 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/4119054314
2022/10/27 15:55:28 Could not obtain certificates:
	error: one or more domains had a problem:
[legotesting.duckdns.org] time limit exceeded: last error: read udp 172.17.0.2:57687->35.183.157.249:53: i/o timeout
```

</details>

### Go environment (if applicable)

N/A

**Comment by ldez** [comment]
Hello,

`i/o timeout` is related to your network: some DNS calls are slow.
Check your firewall or your local DNS.

**Comment by ioExpander** [comment]
Hi. Thank you for the very quick feedback.

Here are a few checks I ran on that same server : 
1. DNS lookup from 8.8.8.8 or 1.1.1.1 works:
```
nslookup legotesting.duckdns.org 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	legotesting.duckdns.org
Address: 1.2.3.4
```
2. During the challenge I can see the TXT field being propagated using : 
```
nslookup -type=txt legotesting.duckdns.org 8.8.8.8
```
3. The duckDNS server is also reachable (I've ran the command after the challenge so the entry is gone)
````
nslookup -type=txt legotesting.duckdns.org 35.183.157.249
Server:		35.183.157.249
Address:	35.183.157.249#53

legotesting.duckdns.org	text = ""
````

4. I noticed that lego uses `35.183.157.249:53` even if I've added the option `--dns.resolvers 1.1.1.1`. Could this be related ?

**Comment by ioExpander** [comment]
I've managed to get the certs generated. By :
1. Adding the following env variables : `DUCKDNS_PROPAGATION_TIMEOUT=340 DUCKDNS_POLLING_INTERVAL=10 `
2. Adding the following option to lego : --dns-timeout 20

Will close the issue. Thank you for the help !
