### ISSUE TITLE
Support for provider: plesk dns server

### ISSUE THREAD

**Issue by tahaghafuri** [go-acme/lego#1755]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Other

### Link to the DNS provider

https://www.plesk.com/

### Link to the API documentation

https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference.28784/

### Additional Notes

none

**Comment by ldez** [comment]
Hello,

An API, to be able to add/remove records, is a requirement.

I don't know what is the real DNS server used by Plesk, and if there is an API.

You haven't provided any documentation, so I will decline this issue.

Maybe you can use one of the following implementation:
- https://go-acme.github.io/lego/dns/rfc2136/
- https://go-acme.github.io/lego/dns/acme-dns/
- https://go-acme.github.io/lego/dns/exec/
- https://go-acme.github.io/lego/dns/httpreq/

**Comment by si458** [comment]
Hi @ldez 
Sorry to tag onto this but could a plesk dns provider now be added?
I'm happy to help debug your issues!
Plesk has a rest api that supports adding dns entries
https://docs.plesk.com/en-US/obsidian/api-rpc/about-rest-api.79359/
I will edit this post shortly when I get the swagger url for you to look at the api

**Comment by ldez** [comment]
yes, we can reopen this issue, if you are able to provide the documentation about adding and removing DNS records.

**Comment by ldez** [comment]
![Screenshot 2023-01-03 at 14-10-30 Pastebin com - Forbidden (#403)](https://user-images.githubusercontent.com/5674651/210363676-18037aae-d996-4514-9c0e-6adac6994872.png)

**Comment by si458** [comment]
im just looking into the api now and we might have an issue but maybe not?

turns out you can only UPDATE a dns record, you cant CREATE or DELETE them, which is bloody stupid?

so you would have to manually login into plesk first create a blank `_acme-challenge` record first then update it via the api

im updating this post as i get info/examples for you

```
GET DOMAIN RECORDS

curl -X 'GET' \
  'https://YOURSERVER:8443/api/v2/dns/records?domain=YOURDOMAIN.COM' \
  -H 'accept: application/json' \
  -H 'authorization: Basic USER+PASS BASIC-AUTH'

EXAMPLE REPLY
[
  {
    "id": 3867,
    "type": "CNAME",
    "host": "www.mydomain.com.",
    "value": "mydomain.com.",
    "opt": ""
  },
  {
    "id": 3868,
    "type": "TXT",
    "host": "_dmarc.mydomain.com.",
    "value": "v=DMARC1; p=none",
    "opt": ""
  },
  {
    "id": 3869,
    "type": "TXT",
    "host": "mydomain.com.",
    "value": "v=spf1 +a +mx +a:mydomain -all",
    "opt": ""
  }
]
```

**Comment by si458** [comment]
plesk also have an XML API but ive never tried this so im googling for examples at the moment, and will update this post here

https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-dns/managing-dns-records/adding-dns-record.34798/ - ADD DNS RECDORD

https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-dns/managing-dns-records/deleting-dns-records.34864/ - DELETE DNS RECORD

**Comment by si458** [comment]
@ldez full working examples below using the XML api as it works a treat!
just a pain no way of controlling the TTL

step 1 - get the site ID from plesk
```
package main
import (
	"fmt"
	"strings"
	"net/http"
	"io/ioutil"
)
func main() {
	url := "https://plesk.myserver.com:8443/enterprise/control/agent.php"
        // set plesk.myserver.com to your plesk server 
	payload := strings.NewReader("<packet>\n\t<site>\n\t\t<get>\n\t\t\t<filter>\n\t\t\t\t<name>mydomain.com</name>\n\t\t\t</filter>\n\t\t\t<dataset>\n\t\t\t\t<gen_info/>\n\t\t\t</dataset>\n\t\t</get>\n\t</site>\n</packet>") 
        // CHANGE mydomain.com to the domain name in question
	req, _ := http.NewRequest("POST", url, payload)
	req.Header.Add("Content-Type", "text/xml")
	req.Header.Add("HTTP_AUTH_LOGIN", "admin")
        // CHANGE admin to your admin account name
	req.Header.Add("HTTP_AUTH_PASSWD", "password")
        // CHANGE password to the admins password
	res, _ := http.DefaultClient.Do(req)
	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)
	fmt.Println(res)
	fmt.Println(string(body))
}
```
``` 
REPLY XML
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.9.1">
	<site>
		<get>
			<result>
				<status>ok</status>
				<filter-id>mydomain.com</filter-id>
				<id>82</id>
				<data>
					<gen_info>
						<cr_date>2022-12-31</cr_date>
						<name>mydomain.com</name>
						<ascii-name>mydomain.com</ascii-name>
						<status>0</status>
						<real_size>2717782016</real_size>
						<dns_ip_address>217.28.1.1</dns_ip_address>
						<htype>vrt_hst</htype>
						<guid>e9114a63-e626-4977-ac15-a8e608750a33</guid>
						<webspace-guid>e9114a63-e626-4977-ac15-a8e608750a33</webspace-guid>
						<sb-site-uuid></sb-site-uuid>
						<webspace-id>82</webspace-id>
						<description></description>
					</gen_info>
				</data>
			</result>
		</get>
	</site>
</packet>
```

step 2 - add dns record using the ID from the previous XML
```
package main
import (
	"fmt"
	"strings"
	"net/http"
	"io/ioutil"
)
func main() {
	url := "https://plesk.myserver.com:8443/enterprise/control/agent.php"
        // set plesk.myserver.com to your plesk server 
	payload := strings.NewReader("<packet>\n\t<dns>\n\t\t<add_rec>\n\t\t\t<site-id>82</site-id>\n\t\t\t<type>TXT</type>\n\t\t\t<host>_acme-challenge.mydomain.com</host>\n\t\t\t<value>a1b2c3d4e5</value>\n\t\t</add_rec>\n\t</dns>\n</packet>")
        // CHANGE mydomain.com to the domain name in question and also set a1b2c3d4e5 to the acme challenge
	req, _ := http.NewRequest("POST", url, payload)
	req.Header.Add("Content-Type", "text/xml")
	req.Header.Add("HTTP_AUTH_LOGIN", "admin")
        // CHANGE admin to your admin account name
	req.Header.Add("HTTP_AUTH_PASSWD", "password")
        // CHANGE password to the admins password
	res, _ := http.DefaultClient.Do(req)
	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)
	fmt.Println(res)
	fmt.Println(string(body))
}
```
```
REPLY XML
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.9.1">
	<dns>
		<add_rec>
			<result>
				<status>ok</status>
				<id>4537</id>
			</result>
		</add_rec>
	</dns>
</packet>
```

step 3 - delete dns record
```
package main
import (
	"fmt"
	"strings"
	"net/http"
	"io/ioutil"
)
func main() {
	url := "https://plesk.myserver.com:8443/enterprise/control/agent.php"
        // set plesk.myserver.com to your plesk server 
	payload := strings.NewReader("<packet>\n\t<dns>\n\t\t<del_rec>\n\t\t\t<filter>\n\t\t\t\t<id>4537</id>\n\t\t\t</filter>\n\t\t</del_rec>\n\t</dns>\n</packet>")
        // CHANGE 4537 to the result ID from step 2
	req, _ := http.NewRequest("POST", url, payload)
	req.Header.Add("Content-Type", "text/xml")
	req.Header.Add("HTTP_AUTH_LOGIN", "admin")
        // CHANGE admin to your admin account name
	req.Header.Add("HTTP_AUTH_PASSWD", "password")
        // CHANGE password to the admins password
	res, _ := http.DefaultClient.Do(req)
	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)
	fmt.Println(res)
	fmt.Println(string(body))
}
```
```
REPLY XML
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.9.1">
	<dns>
		<del_rec>
			<result>
				<status>ok</status>
				<id>4537</id>
			</result>
		</del_rec>
	</dns>
</packet>
```

**Comment by ldez** [comment]
can you also provide the responses when there are errors (invalid auth, invalid request, etc.)?

**Comment by si458** [comment]
**invalid user/pass**
<details>

```xml
<?xml version="1.0"?>
<packet version="1.6.9.1">
	<system>
		<status>error</status>
		<errcode>1001</errcode>
		<errtext>You have entered incorrect username or password.</errtext>
	</system>
</packet>
```
</details>

**invalid domain when looking for siteid - step 1**
<details>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.9.1">
	<site>
		<get>
			<result>
				<status>error</status>
				<errcode>1013</errcode>
				<errtext>Site does not exist</errtext>
				<filter-id>bollox.com</filter-id>
			</result>
		</get>
	</site>
</packet>
```
</details>

**invalid siteid if adding dns record - step 2**
<details>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.9.1">
	<dns>
		<add_rec>
			<result>
				<status>error</status>
				<errcode>1015</errcode>
				<errtext>Domain does not exist.</errtext>
			</result>
		</add_rec>
	</dns>
</packet>
```
</details>

**invalid id when deleting dns record - step 3**
<details>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.9.1">
	<dns>
		<del_rec>
			<result>
				<status>error</status>
				<errcode>1013</errcode>
				<errtext>Record does not exist</errtext>
				<id>453899</id>
			</result>
		</del_rec>
	</dns>
</packet>
```
</details>

@ldez anything else?

**Comment by ldez** [comment]
Do you want to try to create a real implementation?
It's easy and I can help you.

**Comment by si458** [comment]
> Do you want to try to create a real implementation? It's easy and I can help you.

ive never learned golang (i started too but gave up as was so confusing)
i used insominia to test/build all the requests and it then generated the examples for me,
i can try build it and submit pr if you have any examples i could follow?

**Comment by ldez** [comment]
You can use this provider as example: https://github.com/go-acme/lego/tree/master/providers/dns/regru

**Comment by ldez** [comment]
My main expectation is to have something that works.
I will help you, and I will take care of the idiomatic Go approach.

**Comment by si458** [comment]
> My main expectation is to have something that works. I will help you, and I will take care of the idiomatic Go approach.

ok im in the office stationary 2moz so i will give examples a read tonight and a go building etc tomorrow for you 👍

**Comment by ldez** [comment]
@si458 do you need help?

**Comment by si458** [comment]
> @si458 do you need help?

Sorry not had time to look at this, will have a look when I get chance for u

**Comment by ldez** [comment]
@tahaghafuri can you explain do you close this issue?

**Comment by si458** [comment]
> @tahaghafuri can you explain do you close this issue?

beat me too it, im struggling at mo to find time to write the plugin but its on my to-do-list

**Comment by ldez** [comment]
I will re-open

**Comment by si458** [comment]
> @si458 I created an implementation based on your snippets and the API doc, can you test it? #1837

Will give it a try when I'm back in the office on Wednesday if OK?
Holiday this weekend and not taking lappy hehe

**Comment by ldez** [comment]
> Will give it a try when I'm back in the office on Wednesday if OK?

no problem :+1:
