### ISSUE TITLE
Support for provider:  Neustar

### ISSUE THREAD

**Issue by shivabasu** [go-acme/lego#1762]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Other

### Link to the DNS provider

https://www.home.neustar/

### Link to the API documentation

https://ultra-portalstatic.ultradns.com/static/docs/REST-API_User_Guide.pdf

### Additional Notes

neustar is one of the top DNS provider

**Comment by ldez** [comment]
Hello,

> [x] Yes, I'm able to create a pull request and be able to maintain the implementation.

As you checked this box, will you open a PR?
