### ISSUE TITLE
ARVANCLOUD

### ISSUE THREAD

**Issue by hadi-dindar** [go-acme/lego#1775]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

### Detailed Description

ARVANCLOUD DNS CHANGED . PLEASE EDIT IT
NOW IS ARVANCLOUD.IR            .COM IS BLOCKED

**Comment by ldez** [comment]
#1770

**Comment by hadi-dindar** [comment]
Yeah . But we use arvancloud cdn as internal relay server to bypass censorship
