### ISSUE TITLE
arvancloud dns provider

### ISSUE THREAD

**Issue by hadi-dindar** [go-acme/lego#1783]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Other

### Detailed Description

arvancloud dns provider domain and api changed to arvancloud.ir
please change it and relase new one lego
when i want o have certificate it show me this :
 acme: error presenting token: arvancloud: failed to add TXT record: fqdn=_acme-challenge.my.domain.store.: Post "https://napi.arvancloud.com/cdn/4.0/domains/mydomain/dns-records": dial tcp: lookup napi.arvancloud.com on 8.8.8.8:53: no such host
 
 best regards

**Comment by ldez** [comment]
stop spamming.

You are now blocked.
