### ISSUE TITLE
certificate creation with luadns/dns01-provider not possible

### ISSUE THREAD

**Issue by h0m1** [go-acme/lego#1795]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

issue of a certificate

### What did you see instead?

```
2023/01/02 00:11:37 Could not obtain certificates:
  error: one or more domains had a problem:
[example.net] [example.net] acme: error presenting token: luadns: no matching zone found for domain example.net
```

### How do you use lego?

Binary

### Reproduction steps

```
lego --accept-tos --path . -d example.net --email mail@gmail.com --key-type ec256 --dns luadns run
```

### Version of lego

```console
lego version a824cab316e0bc31fe9049e130c84f97cdfcb697 linux/amd64
lego version 4.9.0 linux/amd64
```

### Logs

<details>

```console
# paste output here
2023/01/02 00:11:36 [INFO] [example.net] acme: use dns-01 solver
2023/01/02 00:11:36 [INFO] [example.net] acme: Preparing to solve DNS-01
2023/01/02 00:11:37 [INFO] [example.net] acme: Cleaning DNS-01 challenge
2023/01/02 00:11:37 [WARN] [example.net] acme: cleaning up failed: luadns: unknown record ID for '_acme-challenge.example.net.'
2023/01/02 00:11:37 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/111111111111111
2023/01/02 00:11:37 Could not obtain certificates:
  error: one or more domains had a problem:
[example.net] [example.net] acme: error presenting token: luadns: no matching zone found for domain example.net
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

When the provider has been added in #1135, it was working, so I'm a bit surprised.

**Comment by h0m1** [comment]
Hello,

all I can say is that it does not work for me without the pr.

I think it's related to #1717

There is a report from @jordemort at the bottom that sounds similar.

**Comment by jordemort** [comment]
Yes, I never got around to debugging it but I am still pinned to Traefik 2.9.1, which is the last version of Traefik that included a version of lego that works for me with LuaDNS
