### ISSUE TITLE
Namecheap challenge for wildcard domain not completing even after propagation

### ISSUE THREAD

**Issue by sshaikh** [go-acme/lego#1804]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

DNS challenge to succeed on `run`

### What did you see instead?

Continuously:

`acme: Waiting for DNS record propagation.`

### How do you use lego?

Binary

### Reproduction steps

Run the following script:

```
#!/bin/sh

export NAMECHEAP_POLLING_INTERVAL=600
export NAMECHEAP_PROPAGATION_TIMEOUT=172800
export NAMECHEAP_API_USER=user
export NAMECHEAP_API_KEY_FILE=key.txt
./lego --email email@email.com --dns namecheap --domains *.domain.com run
```

Checking Namecheap dashboard I can see the following TXT record created:

Host: `_acme-challenge.`
Value: some string

Using whatsmydns.net to check propagation fails on `https://www.whatsmydns.net/#TXT/domain.com`

But I see the correct string at `https://www.whatsmydns.net/#TXT/_acme-challenge.domain.com`

Which makes me thing that lego isn't setting the correct record, or isn't checking the correct propagation.

### Version of lego

```console
4.9.1
```

### Logs

<details>

```console
2023/01/07 15:22:39 [INFO] [*.domain.com] acme: Obtaining bundled SAN certificate
2023/01/07 15:22:40 [INFO] [*.domain.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxxxxxx
2023/01/07 15:22:40 [INFO] [*.domain.com] acme: use dns-01 solver
2023/01/07 15:22:40 [INFO] [*.domain.com] acme: Preparing to solve DNS-01
2023/01/07 15:22:41 [INFO] [*.domain.com] acme: Trying to solve DNS-01
2023/01/07 15:22:41 [INFO] [*.domain.com] acme: Checking DNS record propagation using [127.0.0.1:53 [::1]:53]
2023/01/07 15:32:41 [INFO] Wait for propagation [timeout: 48h0m0s, interval: 10m0s]
2023/01/07 15:32:41 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2023/01/07 15:42:42 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.

...

2023/01/08 15:53:16 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2023/01/08 16:03:16 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.
2023/01/08 16:13:16 [INFO] [*.domain.com] acme: Waiting for DNS record propagation.

```

</details>

### Go environment (if applicable)

N/A using release

**Comment by ldez** [comment]
Hello,

lego checks the propagation by calling some DNS servers, but in some cases, when the DNS calls are handled by a firewall or some local (cached) DNS, the check can be prevented.

So I recommend checking your network (firewall, local DNS, ...) and maybe use the option `--dns.resolvers`

**Comment by sshaikh** [comment]
`--dns.resolvers 9.9.9.9` did the trick (and within 30 seconds!)
