### ISSUE TITLE
Support for provider: Websupport

### ISSUE THREAD

**Issue by dominikbullo** [go-acme/lego#1811]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://websupport.sk/

### Link to the API documentation

https://rest.websupport.sk/docs/v1.zone

### Additional Notes

Please, implement this provider. I can help you or give you some account to work on this. I would love to use it with Treafik 👏

**Comment by ldez** [comment]
Hello @dominikbullo,

I'm working on this, can you give me apiKey and a secret to working on this more easily?
How would you like to share them securely?
