### ISSUE TITLE
Specific Zone ID when configuring the gcloud dns challenge provider

### ISSUE THREAD

**Issue by xynova** [go-acme/lego#1818]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Library

### Detailed Description

The current challenge uses a SOA dns lookup to find the managed zone it has to create the TXT records in. The issue we are facing is that the lookup fails if the machine we are running the request from doesn't have internet egress

```
nslookup -type=soa mydomain.com ns-cloud-b1.googledomains.com.
;; communications error to 216.239.32.107#53: timed out
;; communications error to 216.239.32.107#53: timed out
;; communications error to 216.239.32.107#53: timed out
;; no servers could be reached
```

It would be really good if there was a way to directly specify the Cloud DNS zoneID and bypass the dns lookup magic.

**Comment by ldez** [comment]
Hello,

lego will use the internet to find the zone but also check the propagation, and call Let's Encrypt.

To find the zone, lego doesn't require an internet connection but it requires to be able to call a DNS server.
You can change the resolvers to use your local DNS.

Being able to call Let's encrypt without the internet seems a bit impossible.

**Comment by xynova** [comment]
Yeah that is what we have tried by using `ns-cloud-b1.googledomains.com`, that is one of the NS records for the public zone in Google Cloud DNS. It seems however, there is no way to reach the backing NS IPs from a VPC without internet egress and they currently don't provide a way to set up private access for them. All the http connections however are easily forwarded through an HTTP Proxy.

I wasn't aware that the lego client also checks for the DNS propagation. Isn't the final TXT record validation done from Let's Encrypt servers themselves?

**Comment by ldez** [comment]
> I wasn't aware that the lego client also checks for the DNS propagation. Isn't the final TXT record validation done from Let's Encrypt servers themselves?

lego checks the propagation of the TXT record before asking the LE to validate the challenge so that we reduce the risk of failure and rate limit issues.

**Comment by ldez** [comment]
Note there is an option to remove the check of the propagation but you will be exposed to rate-limit issues.

I'm not closed to the fact of adding the zone id env var but you have to understand that is a real limitation of the capacity of the lego (limited to one zone if this env var is set) and like you want to use lego without internet egress you will be exposed the rate-limit issues.
