### ISSUE TITLE
Support for provider: dnshome.de

### ISSUE THREAD

**Issue by DFS-90** [go-acme/lego#1820]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://www.dnshome.de

### Link to the API documentation

https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_dnshome.sh

### Additional Notes

Hi,

unfortunately, I'm not able to "transcribe" an existing acme.sh plugin for dnshome.de to use it with LEGO.

The existing (tested / working) script can be found here:
https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_dnshome.sh

Is anybody able to help me integrating this provider?

Thanks in advance and best regards,
David

**Comment by ldez** [comment]
Hello,

can you provide a link to the API documentation (not a link the acmesh)?

**Comment by DFS-90** [comment]
Unfortunately, the acme.sh script was the only document containing API I was able to find...

There is no further information on the provider's homepage either.

My idea was to use the acme script in order to "translate" it into a certbot plugin - however, I don't possess sufficient programming / scripting skills in order to do so 😔

**Comment by ldez** [comment]
I'm currently trying to get the API works but I have an error: `error - no valid acme txt record`

**Comment by ldez** [comment]
I found the problem there is a min size for the TXT value, weird API...

**Comment by ldez** [comment]
I created a PR #1821

**Comment by DFS-90** [comment]
Sorry for the delay and thank you very much for your efforts!
I just tested the dnshome.de plugin and it works like a charm! 👍
