### ISSUE TITLE
Ionos DNS Provider API Error

### ISSUE THREAD

**Issue by fluc-tus** [go-acme/lego#1825]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

A successful ACME certificate request with Ionos DNS provider configured correctly.

### What did you see instead?

```
time="2023-02-01T02:36:52+01:00" level=error msg="Unable to obtain ACME certificate for domains \"domain.com,*.domain.com\"" ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=vaultwarden@file rule="Host(`bla.domain.com`)" providerName=letsencrypt.acme error="unable to generate a certificate for the domains [domain.com *.domain.com]: error: one or more domains had a problem:\n[*.domain.com] [*.domain.com] acme: error presenting token: ionos: failed to get records (zone=123): 400: INVALID_REQUEST: Invalid 'suffix' request parameter.\n[domain.com] [domain.com] acme: error presenting token: ionos: failed to get records (zone=123): 400: INVALID_REQUEST: Invalid 'suffix' request parameter.\n"
```

### How do you use lego?

Through Traefik

### Reproduction steps

Configure Ionos DNS Provider and start traefik.

Please look at [/providers/dns/ionos/internal/client.go#L96](https://github.com/go-acme/lego/blob/master/providers/dns/ionos/internal/client.go#L96) and compare to [API as described at Ionos](https://developer.hosting.ionos.com/docs/dns). You can see that the API must have changed, the GET that is called doesn't exist anymore.

### Version of lego

```console
apperantly not available in docker container? dunno...
```

### Logs

<details>

```console
# paste output here
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

Can you provide the Traefik version? (even in a container you can have the version if you are able to get the version inside the container you can just use an explicit traefik version)

Have you tried another Traefik version?

Do you have a CNAME wildcard record?


> Please look at [/providers/dns/ionos/internal/client.go#L96](https://github.com/go-acme/lego/blob/master/providers/dns/ionos/internal/client.go#L96) and compare to [API as described at Ionos](https://developer.hosting.ionos.com/docs/dns). You can see that the API must have changed, the GET that is called doesn't exist anymore.

sorry but the GET /v1/zones/:id exists.

![Screenshot 2023-02-01 at 03-54-02 Developer API Portal IONOS](https://user-images.githubusercontent.com/5674651/215933881-9d50986f-cf4a-4e4b-9a90-f4dd86f4e8b5.png)

**Comment by fluc-tus** [comment]
Nevermind, the CNAME wildcard was my problem ... still learning.
