### ISSUE TITLE
alidns: There is no fine filtering when parsing record modification

### ISSUE THREAD

**Issue by yjw-test** [go-acme/lego#1828]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Library

### Detailed Description

Hello, the code of this project does not filter non-TXT records. As a result, when the txt record of certificate renewal is modified by this project, the resolution records of other records of the same host will be deleted.
https://github.com/go-acme/lego/blob/master/providers/dns/alidns/alidns.go#L258

**Comment by cloverzrg** [comment]
My "A" Type record has be deleted many times
![image](https://user-images.githubusercontent.com/13957666/216582345-dbc5cd44-9f65-4c0f-95c0-5981efc00444.png)
