### ISSUE TITLE
lego watch docker socket and create certificates on new label

### ISSUE THREAD

**Issue by philipzgithub** [go-acme/lego#1846]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Docker image

### Detailed Description

Feature Request

for instance, a docker compose file could include a custom label, such as the following:

```
labels:
  - lego.account="admin@example.com"
  - lego.host="www.example.com"
 ```

with lego watching the socket for creation of this label and then automatically  obtaining a certificate.

I believe Traefik works in this way.

**Comment by ldez** [comment]
Hello,

we don't plan to support Docker, I recommend using Traefik if you want to do that.

**Comment by philipzgithub** [comment]
oh, thanks for reply, there is limitation in traefik with global proxy and this would be a solution
