### ISSUE TITLE
Cannot renew or create certificate to versio: `versio: 400: request failed: ObjectDoesNotExist|Domain not found`

### ISSUE THREAD

**Issue by tim-vk** [go-acme/lego#1851]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I use traefik 2.9.8 (but this also happened to traefik 2.8.2) which automatically updated my certificates. (last update in december).
I would expect that to keep working.

### What did you see instead?

Traefik fails throwing: `versio: 400: request failed: ObjectDoesNotExist|Domain not found. ` (full log below).
This also happens when manually using the lego binary (see instructions below).

I am wondering if this is something with my personal setup, or if something has changed in the versio API (they did have changes recently, just not sure if it happend on the API side too).

### How do you use lego?

Through Traefik

### Reproduction steps

1. `export VERSIO_PASSWORD=[password]`
2. `export VERSIO_USERNAME=[username]`
3. `export VERSIO_ENDPOINT=https://www2.versio.nl/api/v1` (or use the default one, same response for both)
4. lego --email [my-email] --dns versio --server https://acme-staging-v02.api.letsencrypt.org/directory --domains tevk.nl run
5. This throws: `versio: 400: request failed: ObjectDoesNotExist|Domain not found`

To check if versio is not doing anything funky i checked their [api](https://www.versio.nl/RESTapidoc/).

1. GET request to: `https://www2.versio.nl/api/v1/domains\tevk.nl?show_dns_records=true` (with valid credentials) results in response below.

response to `GET` on versio:
```json
{
    "domainInfo": {
        "domain": "tevk.nl",
        "status": null,
        "expire-date": "2027-11-10",
        "auto_renew": false,
        "ns": [],
        "registrant_id": "[i don't know if this should be secret, just to be sure]",
        "dns_management": true,
        "dns_records": [
            {
                "type": "TXT",
                "name": "*.tevk.nl.",
                "value": "[i don't know if this should be secret, just to be sure]"
                "prio": 0,
                "ttl": 14400
            },
            {
                "type": "A",
                "name": "*.tevk.nl.",
                "value": "[i don't know if this should be secret, just to be sure]"
                "prio": 0,
                "ttl": 14400
            },
            {
                "type": "A",
                "name": "tevk.nl.",
                "value" "[i don't know if this should be secret, just to be sure]"
                "prio": 0,
                "ttl": 14400
            }
        ],
        "dns_redirections": [],
        "dnssec_keys": []
    }
}
```

### Version of lego

```console
lego version 4.10.2 linux/386 and the built in version of traefik
```

### Logs

<details>

```console
2023/02/26 19:17:25 [INFO] [tevk.nl] acme: Obtaining bundled SAN certificate
2023/02/26 19:17:25 [INFO] [tevk.nl] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5527757734
2023/02/26 19:17:25 [INFO] [tevk.nl] acme: Could not find solver for: tls-alpn-01
2023/02/26 19:17:25 [INFO] [tevk.nl] acme: Could not find solver for: http-01
2023/02/26 19:17:25 [INFO] [tevk.nl] acme: use dns-01 solver
2023/02/26 19:17:25 [INFO] [tevk.nl] acme: Preparing to solve DNS-01
2023/02/26 19:17:28 [INFO] [tevk.nl] acme: Cleaning DNS-01 challenge
2023/02/26 19:17:28 [WARN] [tevk.nl] acme: cleaning up failed: versio: 400: request failed: ObjectDoesNotExist|Domain not found
2023/02/26 19:17:28 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/5527757734
2023/02/26 19:17:28 Could not obtain certificates:
        error: one or more domains had a problem:
[tevk.nl] [tevk.nl] acme: error presenting token: versio: 400: request failed: ObjectDoesNotExist|Domain not found
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by tim-vk** [comment]
@fjmk Since you wrote this: I'm wondering if you are still using versio & lego and if it is still working for you.

**Comment by ldez** [comment]
Hello,

> 1. GET request to: https://www2.versio.nl/api/v1/domains\tevk.nl?show_dns_records=true (with valid credentials) results in response below.

Can you provide the results?

**Comment by ldez** [comment]
> lego version 4.10.2 linux/386 and the built in version of traefik

Traefik doesn't use v4.10.2 because I created the version yesterday, and for now I updated the version in Traefik.

Traefik v2.9.8 uses lego v4.10.0:
https://github.com/traefik/traefik/blob/v2.9.8/go.mod#L22

Traefik v2.8.2 uses lego v4.7.0:
https://github.com/traefik/traefik/blob/v2.8.2/go.mod#L22

**Comment by tim-vk** [comment]
> > lego version 4.10.2 linux/386 and the built in version of traefik
> 
> Traefik doesn't use v4.10.2 because I created the version yesterday, and for now I don't update the version in Traefik.
> 
> Traefik v2.9.8 uses lego v4.10.0: https://github.com/traefik/traefik/blob/v2.9.8/go.mod#L22
> 
> Traefik v2.8.2 uses lego v4.7.0: https://github.com/traefik/traefik/blob/v2.8.2/go.mod#L22

Apolagies: I was not clear.

I had this error in traefik v2.8.2 (so lego 4.7.0). I then updated to 2.9.8 (hoping this would solve my problem: but didn't).

Then I started testing using the newest lego binary: So 4.10.2. 

But all three versions had the same response.

**Comment by ldez** [comment]
> https://www2.versio.nl/api/v1/domains\tevk.nl?show_dns_records=true

I think there is a typo in the URL, can you confirm?

**Comment by ldez** [comment]
> 400: request failed: ObjectDoesNotExist|Domain not found

This error comes from Versio.

Currently, lego makes the following requests:
- `{BASE_URL}/domains/{your_domain}?show_dns_records=true`
- `{BASE_URL}/domains/{your_domain}/update`

**Comment by tim-vk** [comment]
> > [https://www2.versio.nl/api/v1/domains\tevk.nl?show_dns_records=true](https://www2.versio.nl/api/v1/domains%5Ctevk.nl?show_dns_records=true)
> 
> I think there is a typo in the URL you provided, can you confirm?

Man you are fast...

The only typo is the backslash instead of the forward slash. But that shouldn't be a big problem.
The thing is: you need credentials with versio (and ownership over this domain) if you want to test it out. So you won't be able to get results unless i share my credentials (which i, for obvious reasons, won't do).

I did some further testing and the issue seems to arise during a POST request to [/domains/:domain/update](https://www.versio.nl/RESTapidoc/#api-Domains-Update). Which would also happen in [client.go](https://github.com/go-acme/lego/blob/90e478ef23c4f828dd0310f86d8de35ecb16dabb/providers/dns/versio/client.go#L39).

When I do a call to `{{endpoint}}/domains/tevk.nl/update` I get the error. So my guess would be one of the following options:

- The error is because the versio API changed and the 'update' call is wrong (and the versio documentation is incomplete)
- The error is because there is something wrong with my personal account.

problem is that versio has quite strict rate limiting and i'm locked out for today...

@ldez Man you are fast... while typing this out you confirmed my suspicions. I'm going to send Versio an email.

**Comment by ldez** [comment]
> The only typo is the backslash instead of the forward slash. But that shouldn't be a big problem.

It was to confirm your report.

> The thing is: you need credentials with versio (and ownership over this domain) if you want to test it out

Yes I'm aware of the requirement of credentials :smile: 

> So my guess would be one of the following options:

I agree it's either an API problem or the rights/permission problem with your account.

**Comment by tim-vk** [comment]
I've sent Versio an e-mail. I'll update here if I get a response.

**Comment by tim-vk** [comment]
I got an e-mail back from versio & scoured their forums. 
There is definitely something wrong on their side (and as far as I can see: the API is the least of their troubles). For now, their API is non-functional. 

Nothing LEGO can do anything about. Closing

**Comment by ldez** [comment]
Thank you for the feedback :+1: 
If you can add a message here when the problem will be fixed, it can help other users.
