### ISSUE TITLE
acmedns: 4.10.1 regression - acmedns provider creates a new account when another valid account is already present in storage

### ISSUE THREAD

**Issue by default-username-was-already-taken** [go-acme/lego#1861]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

When selecting an AcmeDNS account (from `ACME_DNS_STORAGE_PATH`), lego should use an account that corresponds to the domain's FQDN, or, if account file is missing or empty, create a new account, ask user to create a CNAME record, and after a 2nd lego run it should issue a certificate (pre-4.10.1 behaviour):

```
2023/03/02 19:28:32 [INFO] [test.example.tld] acme: Obtaining bundled SAN certificate
2023/03/02 19:28:32 [INFO] [test.example.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/*
2023/03/02 19:28:32 [INFO] [test.example.tld] acme: Could not find solver for: tls-alpn-01
2023/03/02 19:28:32 [INFO] [test.example.tld] acme: Could not find solver for: http-01
2023/03/02 19:28:32 [INFO] [test.example.tld] acme: use dns-01 solver
2023/03/02 19:28:32 [INFO] [test.example.tld] acme: Preparing to solve DNS-01
2023/03/02 19:28:32 [INFO] Found CNAME entry for "_acme-challenge.test.example.tld.": "babf1901-e94f-45c7-852b-8c4936b0428c.acmedns.example.tld."
2023/03/02 19:28:33 [INFO] [test.example.tld] acme: Trying to solve DNS-01
2023/03/02 19:28:33 [INFO] Found CNAME entry for "_acme-challenge.test.example.tld.": "babf1901-e94f-45c7-852b-8c4936b0428c.acmedns.example.tld."
2023/03/02 19:28:33 [INFO] [test.example.tld] acme: Checking DNS record propagation using [1.1.1.1:53 8.8.8.8:53 9.9.9.9:53]
2023/03/02 19:28:35 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2023/03/02 19:28:48 [INFO] [test.example.tld] The server validated our request
2023/03/02 19:28:48 [INFO] [test.example.tld] acme: Cleaning DNS-01 challenge
2023/03/02 19:28:48 [INFO] [test.example.tld] acme: Validations succeeded; requesting certificates
2023/03/02 19:28:49 [INFO] [test.example.tld] Server responded with a certificate for the preferred certificate chains "ISRG Root X1".
```

### What did you see instead?

Even if an account is already present in `ACME_DNS_STORAGE_PATH`, lego tries to create a new account with a domain's AcmeDNS challenge response URL, when it actually should create or use an account with a domain's FQDN (e.g. it creates `f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld.` instead of using `test.example.tld`):

```
2023/03/03 09:49:48 [INFO] [test.example.tld] acme: Obtaining bundled SAN certificate
2023/03/03 09:49:48 [INFO] [test.example.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/*
2023/03/03 09:49:48 [INFO] [test.example.tld] acme: Could not find solver for: tls-alpn-01
2023/03/03 09:49:48 [INFO] [test.example.tld] acme: Could not find solver for: http-01
2023/03/03 09:49:48 [INFO] [test.example.tld] acme: use dns-01 solver
2023/03/03 09:49:48 [INFO] [test.example.tld] acme: Preparing to solve DNS-01
2023/03/03 09:49:48 [INFO] Found CNAME entry for "_acme-challenge.test.example.tld.": "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld."
_2023/03/03 09:49:49 [INFO] effectiveDomain: "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld.", domain: "test.example.tld", fqdn: "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld."
2023/03/03 09:49:49 [INFO] no account found_
2023/03/03 09:49:49 [INFO] [test.example.tld] acme: Cleaning DNS-01 challenge
2023/03/03 09:49:49 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/*
2023/03/03 09:49:50 Could not obtain certificates:
        error: one or more domains had a problem:
[test.example.tld] [test.example.tld] acme: error presenting token: acme-dns: **new account created** for "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld.". To complete setup for "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld." you must provision the following CNAME in your DNS zone and re-run this provider when it is in place:
f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld. CNAME d8325367-255c-4363-a021-8a63460d9093.acmedns.example.tld.
```

The regression has been introduced in PR #1847 (commit 83b6a87) as a fix for issue #1710.
Downgrading to 4.10.0 or an earlier version works as intended.

The problem seems to occur here: https://github.com/go-acme/lego/pull/1847/commits/83b6a8795289b7d527cec2a10e3ff0c8ef48a356#diff-64320444e4da2ce3c01918ceeac6347f8192fbec19710789e7efe4b26cd2bf09R108-R111

Here is the partial state before `d.storage.Fetch(effectiveDomain)` is ran but after `isCNAME` is called (line 115):
- **effectiveDomain**: `"f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld."`
- **domain**: `"test.example.tld"`
- **fqdn**: `"f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld."`

, and this results in a new account being created for `f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld.` (line 120), which is obviously missing from `ACME_DNS_STORAGE_PATH` file.

It seems like `isCNAME()` should correctly handle cases when both `domain` and `fqdn` belong to the same NS zone.

### How do you use lego?

Binary

### Reproduction steps

1. Deploy lego 4.10.2
2. Deploy an instance of acme-dns (latest version)
3. `ACME_DNS_STORAGE_PATH=./accounts.conf`
4. `ACME_DNS_API_BASE=https://acmedns.example.tld`
5. `./lego --domains test.example.tld --server https://acme-v02.api.letsencrypt.org/directory --accept-tos --email admin@example.tld --key-type ec384 --path . --dns acme-dns --dns.resolvers 1.1.1.1 --dns.resolvers 8.8.8.8 --dns.resolvers 9.9.9.9 --dns.disable-cp run --preferred-chain 'ISRG Root X1'`

### Version of lego

```console
lego version v4.10.2 linux/amd64
```

### Logs

CLI logs: see above.

`ACME_DNS_STORAGE_PATH` contents with lego 4.10.0 (ok: only one account in storage):
<details>

```json
{
  "test.example.tld": {
    "fulldomain": "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld",
    "subdomain": "f4166513-bd9b-46e2-b0b6-0925a9ed83af",
    "username": "77ea7ef7-3816-48bc-9a80-d83aff74fa48",
    "password": "snip",
    "server_url": "https://acmedns.example.tld"
  }
}
```

</details>

`ACME_DNS_STORAGE_PATH` contents with lego >= 4.10.1 (not ok: two accounts in storage: domain FQDN and acme-dns challenge-response FQDN):
<details>

```json
{
  "test.example.tld": {
    "fulldomain": "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld",
    "subdomain": "f4166513-bd9b-46e2-b0b6-0925a9ed83af",
    "username": "77ea7ef7-3816-48bc-9a80-d83aff74fa48",
    "password": "snip",
    "server_url": "https://acmedns.example.tld"
  },
  "f4166513-bd9b-46e2-b0b6-0925a9ed83af.acmedns.example.tld.": {
    "fulldomain": "d8325367-255c-4363-a021-8a63460d9093.acmedns.example.tld",
    "subdomain": "d8325367-255c-4363-a021-8a63460d9093",
    "username": "c4121a39-63da-49a4-a6ad-09a7a38226b3",
    "password": "snip",
    "server_url": "https://acmedns.example.tld"
  }
}
```

</details>

**Comment by ldez** [comment]
Hello,

Maybe I made a wrong assumption about #1710: I was thinking that was just a CNAME issue.

FYI, the server used to handle the propagation check is not related to the domain or NS for this domain, it's a global option `--resolvers`.

So will revert my fix.
