### ISSUE TITLE
Support for provider: Google Domains (Not Google Cloud)

### ISSUE THREAD

**Issue by SeubertE** [go-acme/lego#1865]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://domains.google.com/

### Link to the API documentation

https://developers.google.com/domains/acme-dns/reference/rest

### Additional Notes

_Edit:_ Whoops, posted the issue without looking at the PRs; There is a PR in progress here: https://github.com/go-acme/lego/pull/1839

Google has _finally_ made an API for the consumer grade Google Domains (not to be confused for Google Cloud DNS) for TXT records specifically for ACME. Would be great to implement in lego,

Certbot community implementation: https://github.com/aaomidi/certbot-dns-google-domains, 

Blog posts: https://domains.google/learn/gts-acme/, https://security.googleblog.com/2023/03/google-trust-services-now-offers-tls.html

Help page: https://support.google.com/domains/answer/7630973?authuser=0&hl=en#acme_dns&zippy=%2Clist-of-known-acme-clients-to-work-the-acme-dns-api

**Comment by ldez** [comment]
Hello,

there is a PR in progress by @aaomidi about this topic.

https://github.com/go-acme/lego/pull/1839

**Comment by aaomidi** [comment]
Yep slowly working towards it, no ETAs as of yet and if someone is faster than me they're definitely more than welcome to go!
