### ISSUE TITLE
Support for provider:  Derak Cloud

### ISSUE THREAD

**Issue by Hamed-F** [go-acme/lego#1872]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://derak.cloud/

### Link to the API documentation

https://app.derak.cloud/

### GET:  Get a list of all DNS records

`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords`

**Query**

<table style="width:100%">
  <tr>
    <th>The name of the parameter</th>
    <th>Description</th> 
  </tr>
  <tr>
    <td>dnsType</td>
    <td>dnsType query</td> 
  </tr>
  <tr>
    <td>content</td>
    <td>The Host value of the DNS record</td> 
  </tr>
</table>
**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
  <tr>
    <td>RateLimitExceeded</td>
    <td>1013</td> 
  </tr>
</table>

**Example**

**CURL:**
`curl -X GET --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords`

![derak cloud 2023-03-20_08-40](https://user-images.githubusercontent.com/66952123/226252100-f64e0677-ec0b-4522-a723-b8be0522704a.png)

---------------------------------------------------------------------------------------------------------------------------------------------------------------

### PUT:  Creating a new DNS record on the desired website

`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords`

**parameters**
<table style="width:100%">
  <tr>
    <th>The name of the parameter</th>
    <th>Description</th> 
  </tr>
  <tr>
    <td>*type</td>
    <td>DNS record type [of types Aand AAAAand CNAMEand MXand NSand CAAand TXTand SPFand PTRand SRV]</td> 
  </tr>
  <tr>
    <td>*host</td>
    <td>The Host value of the DNS record</td> 
  </tr>
  <tr>
    <td>*content</td>
    <td>The Host value of the DNS record</td> 
  </tr>
  <tr>
    <td>ttl</td>
    <td>TTL of DNS record [default: 0]</td> 
  </tr>
  <tr>
    <td>cloud</td>
    <td>This parameter specifies whether the traffic of this record passes through the cloud or not [Default: false]</td> 
  </tr>
  <tr>
    <td>priority</td>
    <td>Priority of MX and SRV records [Default: 0]</td> 
  </tr>
  <tr>
    <td>service</td>
    <td>SRV record service</td> 
  </tr>
  <tr>
    <td>protocol</td>
    <td>SRV record protocol [default: _tcp]</td> 
  </tr>
  <tr>
    <td>weight</td>
    <td>SRV Record Weight [Default: 0]</td> 
  </tr>
  <tr>
    <td>port</td>
    <td>Priority of MX and SRV records [Default: 0]</td> 
  </tr>
  <tr>
    <td>advanced</td>
    <td>This parameter specifies whether this record has advanced settings or not [default: false]</td> 
  </tr>
  <tr>
    <td>upstreamPort</td>
    <td>Upstream Port of DNS record [Default: 80]</td> 
  </tr>
  <tr>
    <td>upstreamProtocol</td>
    <td>Upstream protocol related to DNS records. Note that if you change these settings for another record of the same subdomain, the settings will be overwritten. [Default: http]</td> 
  </tr>
  <tr>
    <td>customSSLType</td>
    <td>Custom SSL related DNS record. Note that if you change these settings for another record of the same subdomain, the settings will be overwritten.</td> 
  </tr>
</table>

**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
  <tr>
    <td>RateLimitExceeded</td>
    <td>1013</td> 
  </tr>
  <tr>
    <td>DNSValidationError</td>
    <td>1008</td> 
  </tr>
</table>

**Example**

**CURL:**

`curl -X PUT --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords  \
    -F type="A"  \
    -F host="app"  \
    -F content="1.2.3.4"`

###  GET: Get the information of a single DNS record

`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords/:recordId`

**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
  <tr>
    <td>RateLimitExceeded</td>
    <td>1013</td> 
  </tr>
  <tr>
    <td>RecordNotFoundError</td>
    <td>1021</td> 
  </tr>
</table>

**Example**

**CURL**

`curl -X GET --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords/:recordId`

### PATCH: Edit the parameters of a DNS record

`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords/:recordId`

**parameters**
<table style="width:100%">
  <tr>
    <th>The name of the parameter</th>
    <th>Description</th> 
  </tr>
  <tr>
    <td>type</td>
    <td>DNS record type [of types Aand AAAAand CNAMEand MXand NSand CAAand TXTand SPFand PTRand SRV]</td> 
  </tr>
  <tr>
    <td>host</td>
    <td>The Host value of the DNS record</td> 
  </tr>
  <tr>
    <td>content</td>
    <td>The Host value of the DNS record</td> 
  </tr>
  <tr>
    <td>ttl</td>
    <td>TTL of DNS record [default: 0]</td> 
  </tr>
  <tr>
    <td>cloud</td>
    <td>This parameter specifies whether the traffic of this record passes through the cloud or not [Default: false]</td> 
  </tr>
  <tr>
    <td>priority</td>
    <td>Priority of MX and SRV records [Default: 0]</td> 
  </tr>
  <tr>
    <td>service</td>
    <td>SRV record service</td> 
  </tr>
  <tr>
    <td>protocol</td>
    <td>SRV record protocol [default: _tcp]</td> 
  </tr>
  <tr>
    <td>weight</td>
    <td>SRV Record Weight [Default: 0]</td> 
  </tr>
  <tr>
    <td>port</td>
    <td>Priority of MX and SRV records [Default: 0]</td> 
  </tr>
  <tr>
    <td>advanced</td>
    <td>This parameter specifies whether this record has advanced settings or not [default: false]</td> 
  </tr>
  <tr>
    <td>upstreamPort</td>
    <td>Upstream Port of DNS record [Default: 80]</td> 
  </tr>
  <tr>
    <td>upstreamProtocol</td>
    <td>Upstream protocol related to DNS records. Note that if you change these settings for another record of the same subdomain, the settings will be overwritten. [Default: http]</td> 
  </tr>
  <tr>
    <td>customSSLType</td>
    <td>Custom SSL related DNS record. Note that if you change these settings for another record of the same subdomain, the settings will be overwritten.</td> 
  </tr>
</table>

**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
  <tr>
    <td>RateLimitExceeded</td>
    <td>1013</td> 
  </tr>
  <tr>
    <td>RecordNotFoundError</td>
    <td>1021</td> 
  </tr>
  <tr>
    <td>DNSValidationError</td>
    <td>1008</td> 
  </tr>
</table>

**Example**

**CURL**
`curl -X PATCH --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords/:recordId  \
    -F cloud="true"`

 **DELETE: Delete a DNS record**

`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords/:recordId`

**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
  <tr>
    <td>RateLimitExceeded</td>
    <td>1013</td> 
  </tr>
  <tr>
    <td>RecordNotFoundError</td>
    <td>1021</td> 
  </tr>
</table>

**Example**

**CURL:**
`curl -X DELETE --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/dnsrecords/:recordId`

---------------------------------------------------------------------------------------------------------------------------------------------------------------
### POST:  Clearing (Purge Cache) specified parameters, if no parameter is specified, the entire cache is deleted.

   `https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/cache/purge`

**parameters**
<table style="width:100%">
  <tr>
    <th>The name of the parameter</th>
    <th>Description</th> 
  </tr>
  <tr>
    <td>hostname</td>
    <td>The hostname to be deleted</td> 
  </tr>
  <tr>
    <td>hostnames</td>
    <td>An array of hostnames to be cleared</td> 
  </tr>
  <tr>
    <td>url</td>
    <td>The URL to be deleted</td> 
  </tr>
  <tr>
    <td>urls</td>
    <td>An array of URLs to be purged</td> 
  </tr>
</table>
**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
  <tr>
    <td>RateLimitExceeded</td>
    <td>1013</td> 
  </tr>
</table>

**PURGE URLS SAMPLE CODE:**
`curl -X POST --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/cache/purge  \
    -F urls[]="https://www.derak.cloud/post/1"  \
    -F urls[]="https://www.derak.cloud/post/2"`

**PURGE HOSTNAMES SAMPLE CODE:**
`curl -X POST --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/cache/purge  \
    -F hostnames[]="www.derak.cloud"  \
    -F hostnames[]="app.derak.cloud"`

**PURGE EVERYTHING SAMPLE CODE:**
`curl -X POST --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/cache/purge`

---------------------------------------------------------------------------------------------------------------------------------------------------------------

### Code guide for SSL certificates

**PUT:  Enable SSL for a domain**
`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/ssl/`

**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
</table>

**Example**
`curl -X PUT --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/ssl/`

**DELETE:  Disable SSL for a domain**
`https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/ssl/`

**Errors**
<table style="width:100%">
  <tr>
    <th>type error</th>
    <th>Error code</th> 
  </tr>
  <tr>
    <td>ForbiddenError</td>
    <td>1003</td> 
  </tr>
</table>

**EXAMPLE SAMPLE CODE:**
`curl -X DELETE --user "api:YOUR_API_KEY" \
    https://api.derak.cloud/v1.0/zones/47c0ecf6c91243308c649ad1d2d618dd/ssl/`

**Comment by ldez** [comment]
Hello,

your issue is unreadable, can you improve that?

A real link to the API documentation should be better.

**Comment by Hamed-F** [comment]
I edited and optimized the issue
No, unfortunately, I did not find the link to the api document page or it does not exist

**Comment by Hamed-F** [comment]
> Hello,
> 
> your issue is unreadable, can you improve that?
> 
> A real link to the API documentation should be better.

I edited and optimized the issue
No, unfortunately, I did not find the link to the api document page or it does not exist

**Comment by Hamed-F** [comment]
Hello
I updated the sent text again and added a new text.
If you need an account on this website to help you, I can give you my account details.
Thanks.

> Hello,
> 
> your issue is unreadable, can you improve that?
> 
> A real link to the API documentation should be better.

**Comment by ldez** [comment]
> If you need an account on this website to help you, I can give you my account details.

OK give me your email.

Are you an employee or a customer of Derak Cloud?

**Comment by Hamed-F** [comment]
I am just one of the derak cloud customers.

Email: hamed.holyday@gmail.com
