### ISSUE TITLE
Support for provider: BrandIT

### ISSUE THREAD

**Issue by ChristianGroentved** [go-acme/lego#1876]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Terraform ACME provider

### Link to the DNS provider

https://brandit.com/

### Link to the API documentation

https://portal.brandit.com/apidocv3

**Comment by ldez** [comment]
Hello,

> - [X] Yes, I'm able to create a pull request and be able to maintain the implementation.

you have checked this box, do you plan to create a PR?

**Comment by ChristianGroentved** [comment]
Hi @ldez,  
Definitely, I probably just misunderstood the contribution guidelines. I read it as, ask first then do the PR😊

**Comment by ldez** [comment]
I just asked because some people check the box without reading.
So it's good news. If you need help don't hesitate to ask.
