### ISSUE TITLE
Support ACME Renewal Information

### ISSUE THREAD

**Issue by Saklad5** [go-acme/lego#1878]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

While it is still [a draft specification](https://datatracker.ietf.org/doc/draft-ietf-acme-ari/), Let's Encrypt has [announced](https://letsencrypt.org/2023/03/23/improving-resliiency-and-reliability-with-ari.html) production deployment of ARI. This extension allows ACME providers to suggest a renewal window.

If you're willing to implement the draft version (and I'm not necessarily saying you should), this could be implemented quite easily as a better default than "thirty days before the certificate expires". Of course, it may be best to make this opt-in until the IETF actually adopts it as an RFC, even if Let's Encrypt feels it is ready.

#### Renewal Behavior

Section 4.1 of the current draft includes the following:

> Conforming clients MUST attempt renewal at a time of their choosing
> based on the suggested renewal window.  The following algorithm is
> RECOMMENDED for choosing a renewal time:
>
> 1.  Select a uniform random time within the suggested window.
>
> 2.  If the selected time is in the past, attempt renewal immediately.
>
> 3.  Otherwise, if the client can schedule itself to attempt renewal
>     at exactly the selected time, do so.
>
> 4.  Otherwise, if the selected time is before the next time that the
>     client would wake up normally, attempt renewal immediately.
>
> 5.  Otherwise, sleep until the next normal wake time, re-check ARI,
>     and return to Step 1.
>
> In all cases, renewal attempts are subject to the client's existing
> error backoff and retry intervals.

Steps 1 and 3 may justify sleeping until the correct time, though that could cause complications if Lego is started again while waiting.

Optionally, to better implement step 4, Lego could accept a parameter describing when it would next be run (I'm specifically thinking of Cron jobs). That could also serve as maximum sleep time for the other steps, since it wouldn't get run again during that period. Whether this is worth bothering with is up to you.

The simplest approach, of course, is to just renew if within or after the window and stop otherwise.

**Comment by beautifulentropy** [comment]
I'm glad to see that an ARI proposal has been submitted already! Over the next week, I'll start working on a pull request to add ARI support in `go-acme/lego`.

**Comment by beautifulentropy** [comment]
> I'm glad to see that an ARI proposal has been submitted already! Over the next week, I'll start working on a pull request to add ARI support in `go-acme/lego`.

I was delayed while starting on this but I've forked the repo and begun work this week.

**Comment by beautifulentropy** [comment]
Made some really good progress this week. I've got a little bit of testing that I want to do before I post the PR, but I believe I'm getting relatively close.

Diff:
https://github.com/go-acme/lego/compare/master...beautifulentropy:lego:initial-ari-impl

**Comment by beautifulentropy** [comment]
I have a forked PR out to my team for review. Once I've finished incorporating any feedback they have I'll submit a PR to this repo.

**Comment by beautifulentropy** [comment]
PR is posted. I'm happy to make any changes and welcome additional commits if you'd like to be added as a collaborator. Let me know if you need anything.
