### ISSUE TITLE
autodns: add 2FA support

### ISSUE THREAD

**Issue by jonastaedcke** [go-acme/lego#1887]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Through Traefik

### Detailed Description

I protect my autodns account using 2FA. But this also protects the API access. According to your [documentation](https://go-acme.github.io/lego/dns/autodns/), currently only username and password can be passed. And autodns supports 2FA via [their api](https://en.help.internetx.com/display/APIXMLEN/Authentication#Authentication-AuthenticationviaTwo-FactorAuthentication(2FA)).

It would be great if I could specify the shared secret, like at provider [INWX](https://go-acme.github.io/lego/dns/inwx/).

**Comment by ldez** [comment]
Hello,

lego uses the JSON API, based on the autoDNS documentation the 2FA is not available for the JSON API.

![2023-04-11 at 21-42-53 Authentication - API (JSON_XML) - InterNetX Help Center](https://user-images.githubusercontent.com/5674651/231271626-766f95aa-7bf1-48d8-bbab-54039f41f1cf.png)


https://help.internetx.com/display/APIXMLEN/Authentication

**Comment by jonastaedcke** [comment]
Thank you for your quick answer!
I solved my security problem with a separate internetx user with less permissions
