### ISSUE TITLE
Documented key type rsa3072 aren't accepted in flag `--key-type`

### ISSUE THREAD

**Issue by CompuRoot** [go-acme/lego#1899]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Expecting `lego` to obtain RSA3072 SSL certificate

### What did you see instead?

`lego` failed with error: **"Unsupported KeyType: rsa3072"**

### How do you use lego?

Binary

### Reproduction steps

```
d=domain.tld
e=user@${d}

lego --email="${e}" --domains="${d}" --key-type rsa3072 --http run
```

### Version of lego

```console
lego version 4.10.2 linux/amd64
```

### Logs

```console
2023/04/23 17:21:47 Unsupported KeyType: rsa3072
```

### Go environment (if applicable)

```console
No GoLang on target machine
```

**Comment by ldez** [comment]
Hello,

lego supports rsa3072 but Let's Encrypt doesn't support it.

https://github.com/go-acme/lego/issues/1854#issuecomment-1450251748

**Comment by CompuRoot** [comment]
> lego supports rsa3072 but Let's Encrypt doesn't support it.

I successfully obtained form Let's Encrypt RSA certificate with size 3072 bits using [`dehydrated`](https://github.com/dehydrated-io/dehydrated) with option in `config` equal `KEYSIZE="3072"`
