### ISSUE TITLE
Error when using do.de DNS provider

### ISSUE THREAD

**Issue by SuNNjek** [go-acme/lego#1915]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I expect to obtain a valid certificate. This has been working in the past (last time it worked was around February).

### What did you see instead?

I just get an error. See console output in the logs below.

According to the error message, the domain needs to start with `_acme-challenge`. I can see in the logs in my do.de dashboard that when it still worked, this was the case, but not anymore.

### How do you use lego?

Through Traefik

### Reproduction steps

1. Download lego binary release
2. Run the following command: `DODE_TOKEN=... ./lego --email [e-mail] --domains example.com -a run`
3. I get the error message above

### Version of lego

```console
lego version 4.11.0 linux/amd64
```

### Logs

<details>

Domain and token/value removed for privacy.
```console
2023/05/11 18:27:32 [INFO] [example.com] acme: Obtaining bundled SAN certificate
2023/05/11 18:27:32 [INFO] [example.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/226903983767
2023/05/11 18:27:32 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2023/05/11 18:27:32 [INFO] [example.com] acme: Could not find solver for: http-01
2023/05/11 18:27:32 [INFO] [example.com] acme: use dns-01 solver
2023/05/11 18:27:32 [INFO] [example.com] acme: Preparing to solve DNS-01
2023/05/11 18:27:32 [INFO] Found CNAME entry for "_acme-challenge.example.com.": "example.com."
2023/05/11 18:27:33 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2023/05/11 18:27:33 [INFO] Found CNAME entry for "_acme-challenge.example.com.": "example.com."
2023/05/11 18:27:33 [WARN] [example.com] acme: cleaning up failed: request to change TXT record for do.de returned the following error result ({
    "error": "domain doesn't start with _acme-challenge."
}); used url [https://www.do.de/api/letsencrypt?action=delete&domain=example.com&token=...] 
2023/05/11 18:27:33 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/226903983767
2023/05/11 18:27:33 Could not obtain certificates:
        error: one or more domains had a problem:
[example.com] [example.com] acme: error presenting token: request to change TXT record for do.de returned the following error result ({
    "error": "domain doesn't start with _acme-challenge."
}); used url [https://www.do.de/api/letsencrypt?domain=example.com&token=...&value=...]
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

> 2023/05/11 18:27:32 [INFO] Found CNAME entry for "_acme-challenge.example.com.": "example.com."

as you can see you have a CNAME, you need to disable the support of CNAME.

You have to set the env var `LEGO_DISABLE_CNAME_SUPPORT` to `true`
