### ISSUE TITLE
Support for provider: Yandex 360

### ISSUE THREAD

**Issue by kllakk83** [go-acme/lego#1917]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://360.yandex.ru

### Link to the API documentation

https://yandex.ru/dev/api360/doc/ref/DomainDNSService.html

### Additional Notes

Project pdd.yandex.ru was closed and unavailable

**Comment by ldez** [comment]
Hello,

Have you tried: https://go-acme.github.io/lego/dns/yandexcloud/

Seems related to https://github.com/go-acme/lego/issues/1693

**Comment by ldez** [comment]
Another remark, you have not checked the following box:

> - [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
> - [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

you have also checked this box:

> - [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.

Without someone to create a PR or be able to test a PR it's impossible to add a new provider.

Are you sure to not be able to test a PR?

**Comment by kllakk83** [comment]
Yandex Cloud is a public cloud platform like Amazon AWS
Yandex 360 is a virtual workspace for team with DNS management

You have Yandex PDD provider, but this service was closed and now it is in Yandex 360

I be able to test a PR. Checked it

**Comment by ldez** [comment]
Hello @kllakk83,

I created a PR (#1975) to add yandex360, could you test it?
I created the PR only based on the API documentation.

---

_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

**Comment by kllakk83** [comment]
Hello @ldez, I left some comments in the pull request, after that it should work
