### ISSUE TITLE
Support for provider: Efficient IP

### ISSUE THREAD

**Issue by ventz** [go-acme/lego#1921]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

Efficient IP

### Link to the API documentation

https://github.com/efficientip-labs/solidserver-go-client
and
https://efficientip.com/blog/python-library/

### Additional Notes

Efficient IP has been recently replacing a lot of InfoBlox deployments. It should be relatively easy to go from one to the other. 
It would be great to get a plugin.

The team behind EIP is willing to help out.

**Comment by ldez** [comment]
Hello,

do you need help creating your PR?

**Comment by ventz** [comment]
@ldez Hi - I don't have anything yet, but working with the vendor to hopefully create a solution. Is there a template for adding a new DNS provider?

**Comment by ldez** [comment]
> Is there a template for adding a new DNS provider?

No but you can take a look to [hosttech](https://github.com/go-acme/lego/tree/master/providers/dns/hosttech) or any other provider implementations.

**Comment by ventz** [comment]
@ldez Thanks - I was just going through the infoblox one :)

**Comment by ldez** [comment]
any news?

**Comment by ventz** [comment]
@ldez Thank you so much for the offer. I reached out to the EIP team to comment here (we are just a recent user, coming from infoblox).

**Comment by ventz** [comment]
@ldez If it helps - the vendor just released: https://pypi.org/project/certbot-dns-solidserver/

**Comment by ldez** [comment]
as a customer, I think you can have access to the API documentation.

https://efficientip.com/solutions/solidserver-api-for-it-automation/

It's weird to have a private API doc/spec but :shrug:
