### ISSUE TITLE
Debian 11: unrecognized DNS provider: cloudflare

### ISSUE THREAD

**Issue by stephen-hill** [go-acme/lego#1922]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I expected my certificate to be generated using Cloudflare.

lego dnshelp outputs the following:
```bash
Credentials for DNS providers must be passed through environment variables.

To display the documentation for a DNS providers:

  $ lego dnshelp -c code

All DNS codes:
  acme-dns, alidns, auroradns, autodns, azure, bindman, bluecat, cloudflare, cloudns, cloudxns, conoha, designate, digitalocean, dnsimple, dnsmadeeasy, dnspod, dode, dreamhost, duckdns, dyn, easydns, exec, exoscale, fastdns, gandi, gandiv5, gcloud, glesys, godaddy, hostingde, httpreq, iij, inwx, joker, lightsail, linode, linodev4, liquidweb, manual, mydnsjp, namecheap, namedotcom, namesilo, netcup, nifcloud, ns1, oraclecloud, otc, ovh, pdns, rackspace, rfc2136, route53, sakuracloud, selectel, stackpath, transip, vegadns, versio, vscale, vultr, zoneee
```

### What did you see instead?

unrecognized DNS provider: cloudflare

### How do you use lego?

Binary

### Reproduction steps

- Install Debian 11
- Install "lego" package
- Run lego using "--dns cloudflare"

### Version of lego

```console
lego version dev linux/amd64
```

**Comment by ldez** [comment]
Hello,

can you provide the whole command line ?

**Comment by stephen-hill** [comment]
```bash
export CLOUDFLARE_DNS_API_TOKEN="<redacted>"
export CLOUDFLARE_ZONE_API_TOKEN="<redacted>"
export LEGO_PATH="/etc/lego"

lego --email webmaster@example.com --dns cloudflare --domains example.com --domains '*.example.com' run
```

**Comment by stephen-hill** [comment]
@ldez I have provided full command above, however, I do not think this is an issue with the command but I but in the Debian version of Lego.

**Comment by ldez** [comment]
Your command line seems right.

yes I think this is a problem with the debian package.
We are not maintainers of the package, it's handle by someone outside of the lego team.

Then sorry but I will close this.

I recommend using our binary as a workaround.

**Comment by stephen-hill** [comment]
@ldez Thanks for letting me know. I have forwarded your reply to the package maintainers.

Just out of interest, do you communicate (have a relationship) with the Debian package maintainers?

**Comment by stephen-hill** [comment]
@ldez I'm sorry to hear that.

Asking a naive question here, but, is this something you could or me could pickup. How easy is it to take over and look after a debian package?

Seems a real shame that such an awesome tool is left abandoned in one of the major linux distros.

**Comment by ldez** [comment]
> How easy is it to take over and look after a debian package?

I don't really know but I think it's complex because each lego dependencies seem to need a package and the publication workflow is unclear.

I'm using Linux but I'm not using debian distro based for a long time.

**Comment by ehcloninger** [comment]
@stephen-hill  and anyone else coming across this thread.

The Debian package is old, so you will need to build from source. It requires golang 1.22+ and the Debian bookworm version of go is 1.19 (of course), so you have to use backports.

Update `/etc/apt/sources` with this line

```
deb http://deb.debian.org/debian bookworm-backports main
```

Then issue

```
apt update
apt install -t bookworm-backports golang
cd ~
git clone https://github.com/go-acme/lego.git
cd lego
make build```

It will download a bunch of packages and build. This will take some time. I'm on a 2 core 512MB RAM Proxmox VE LXC, so it's maxing out RAM and the CPU. I stopped the LXC and set it to 2GB RAM and 4 cores long enough to build.

Or, after you have golang installed, issue

```
go install github.com/go-acme/lego/v4/cmd/lego@latest
```

The binary will be ~/lego/dist/lego
