### ISSUE TITLE
Support for provider: ManageEngine CloudDNS

### ISSUE THREAD

**Issue by dgarner-cg** [go-acme/lego#1933]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://clouddns.manageengine.com/

### Link to the API documentation

https://pitstop.manageengine.com/portal/en/kb/articles/manageengine-clouddns-rest-api-documentation#GET_All_9

### Additional Notes

Pu-leeeeees. :D

**Comment by ldez** [comment]
Hello,

you have check the following box:
```
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.
```

This means that you will create a PR, do you need help?

**Comment by ldez** [comment]
@duanegtr any news?

**Comment by ldez** [comment]
@dgarner-cg do you need help?

**Comment by dgarner-cg** [comment]
> @dgarner-cg do you need help?

Yes, I created a plugin for Manage Engine, unfortunately my plugin was incredibly more involved and requires considerably more work than a simple one pager.

I am not sure why, but after working with the Product Owner at Manage Engine, who was very generous with his time, this was the best we could do.

If you have any feedback or are able to help, I'd love assistance. I believe one of the last updates broke our solution and all of my certificates are now expired as my data center was offline for a few months while initiating and pending a personal matter.

I can provide our files and correspondence if that helps as to why we did it the way we did, or simply the API documentation if you are unable to find it.

But you'd be a godsend for providing assistance. :p

**Comment by dgarner-cg** [comment]
@ldez Yes, I created a plugin for Manage Engine, unfortunately my plugin was incredibly more involved and requires considerably more work than a simple one pager.

I am not sure why, but after working with the Product Owner at Manage Engine, who was very generous with his time, this was the best we could do.

If you have any feedback or are able to help, I'd love assistance. I believe one of the last updates broke our solution and all of my certificates are now expired as my data center was offline for a few months while initiating and pending a personal matter.

I can provide our files and correspondence if that helps as to why we did it the way we did, or simply the API documentation if you are unable to find it.

But you'd be a godsend for providing assistance. :p

**Comment by ldez** [comment]
@dgarner-cg I created PR #2365 based on the API documentation, can you try it?

**Comment by dgarner-cg** [comment]
> @dgarner-cg I created PR #2365 based on the API documentation, can you try it?

Yes sir, it may be around 1h before I can sit down uninterrupted and try it, go is not installed on pfsense by default and is discouraged to install non-pfsense repo packages on firewall, but I will give a shot anyway..

Default way to install is simply use Acme plugin so they can be managed in GUI.

**Comment by ldez** [comment]
You can try it locally, you don't need to install it on pfsense.

**Comment by dgarner-cg** [comment]
Real men test in PROD. 8-)

**Comment by dgarner-cg** [comment]
I'm having an issue with getting a proper version of go installed on the version of FreeBSD used by PFSense to install lego and give this a try.

**Comment by dgarner-cg** [comment]
***@***.***/home/ssmith/lego: make build
BIN_OUTPUT:
rm -rf dist/ builds/ cover.out
Version:
go build -trimpath -ldflags '-X "main.version="' -o /home/ssmith/lego/
no Go files in /home/ssmith/lego
*** Error code 1

Stop.
make: stopped in /home/ssmith/lego

***@***.***/home/ssmith/lego: go build
no Go files in /home/ssmith/lego

**Comment by ldez** [comment]
It feels like you are not using the right commands.

This command `go build -trimpath -ldflags '-X "main.version="' -o /home/ssmith/lego/` cannot work and `go build` too.

You should follow the instructions from the section "how to test" inside the issue: https://github.com/go-acme/lego/pull/2365#issue-2705547659

```console
$ git clone https://github.com/ldez/lego.git
Cloning into 'lego'...
remote: Enumerating objects: 24629, done.
remote: Counting objects: 100% (1272/1272), done.
remote: Compressing objects: 100% (441/441), done.
remote: Total 24629 (delta 927), reused 1083 (delta 819), pack-reused 23357 (from 1)
Receiving objects: 100% (24629/24629), 14.26 MiB | 100.00 KiB/s, done.
Resolving deltas: 100% (14606/14606), done.
$ cd lego
$ git checkout feat/manageengine
branch 'feat/manageengine' set up to track 'origin/feat/manageengine'.
Switched to a new branch 'feat/manageengine'
$ make build       
BIN_OUTPUT: dist/lego
rm -rf dist/ builds/ cover.out
Version: e07c5b27f706d874d56eded62b3c4f782d99df16
go build -trimpath -ldflags '-X "main.version=e07c5b27f706d874d56eded62b3c4f782d99df16"' -o  dist/lego ./cmd/lego/
$
```

**Comment by dgarner-cg** [comment]
Okay .. I finally got lego installed and ran the commands successfully that you gave.

***@***.*****p.gg]/home/ssmith/lego: MANAGEENGINE_CLIENT_ID="DY**QI" \
? MANAGEENGINE_CLIENT_SECRET="OR***N" \
? ./dist/lego -m ***@***.******p.gg --dns manageengine -d *.svc.office.c**p.gg -d svc.office.c**p.gg -s https://acme-staging-v02.api.letsencrypt.org/directory run
MANAGEENGINE_CLIENT_ID=DY**QI: No match.

**Comment by ldez** [comment]
can you answer through the GitHub UI (not email) with the full logs?

**Comment by ldez** [comment]
any news?

**Comment by dgarner-cg** [comment]
Just saw this .. I will upload full logs tonight, let me finish up a work project. I thought this posted to Github responses, sorry.

**Comment by ldez** [comment]
can you use single quotes instead of double quotes?
and single quotes around the wildcard domain?

```bash
MANAGEENGINE_CLIENT_ID='xxx' \
MANAGEENGINE_CLIENT_SECRET='yyy' \
./dist/lego -m your_email@example.com --dns manageengine -d '*.example.com' -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

**Comment by ldez** [comment]
@dgarner-cg any news?

**Comment by dgarner-cg** [comment]
Hey Lud, I’m going to try and get all your information tonight. I apologize for delay and keeping this open in the mean time, I own rental property and have been dealing with water pipes breaking every day this week I’ve had to repair after work and it’s been so cold when I get in for the night, I’m ready to pass out. Lol.

I’m working on mainframe project right now and will find logs to post to GitHub when I’m done with this, my friend. Thanks for your hard work and patience.


Duane A. Garner, C.R.S.S.,
Mobile: (502) 528 - 3336
Office: (551) 307-6202
Business: ***@***.***


Infrastructure Architect, Critical Communications, United Parcel Service
http://ups.com
Chief Executive Officer, Threat Level Gaming, LLC   https://www.threatlevel.gg - https://discord.gg/tlgg
Chief Executive Officer, Catalyst Group, LLC & NextLevel Analytics, a division of Catalyst Group
https://www.catalystgroup.gg - https://cghq.me
Director of IT and Security, Eastern Shore Recovery Foundation, 501(c)3
https://esrecovery.org

This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.
