### ISSUE TITLE
Add support for http.net

### ISSUE THREAD

**Issue by saz** [go-acme/lego#2013]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Through Traefik

### Detailed Description

Right now, it's not possible to use the `hostingde` DNS provider for `http.net`, but one is a "reseller" of the other and you just need to provide a different API url to get it working.

See https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_hostingde as an example.

**Comment by ldez** [comment]
Hello,

I would propose something else:
- Create a dedicated provider (with shared client)
- or create a "mode"

**Comment by exmatrikulator** [comment]
Thanks for adding httpnet.
But it doesn't work in traefik 2.11 :(

"cannot get ACME client unrecognized DNS provider: httpnet"

Probably you forgot to register the name? Like
https://github.com/go-acme/lego/blob/master/providers/dns/dns_providers.go#L247
