### ISSUE TITLE
Error acme: Error 429 in acme

### ISSUE THREAD

**Issue by lifang218c** [go-acme/lego#2024]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [ ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ ] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Error acme: Error 429

### What did you see instead?

```
// overallRequestLimit is the overall number of request per second
// limited on the "new-reg", "new-authz" and "new-cert" endpoints.
// From the documentation the limitation is 20 requests per second,
// but using 20 as value doesn't work but 18 do.
overallRequestLimit = 18
```

20 did not work ， 18 did not work.    1 did work fine!!!
1 rps did indeed work. 20 did not. 18 did not. 1 did. I didn't test any other number.

I can confirm seeing this issue on staging. Lowering the rate helped, but hopefully letsencrypt fixes the issue quickly

### How do you use lego?

Through Terraform ACME provider

### Reproduction steps

just run 

### Version of lego

```console
v4.14.2
```

### Logs

<details>

```console
Error acme: Error 429
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
v1.19
```

</details>

**Comment by ldez** [comment]
Hello,

We are not Let's Encrypt, so I recommend to expose your problem in their forum https://community.letsencrypt.org
