### ISSUE TITLE
Azure DNS OIDC support

### ISSUE THREAD

**Issue by stmcx** [go-acme/lego#2027]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Through Terraform ACME provider

### Detailed Description

The Terraform ACME provider with "azuredns" config has failed to authenticate via OIDC token provided by [Terraform Dynamic Credentials](https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials/azure-configuration).

Not sure if it a misconfig on my side. I was only passing `AZURE_RESOURCE_GROUP` and got 401. I attempted to pass the vars by hand but didn't work and still getting 401. 

```
ARM_SUBSCRIPTION_ID  = data.azurerm_subscription.current.subscription_id
ARM_TENANT_ID        = data.azurerm_subscription.current.tenant_id
ARM_OIDC_TOKEN       = data.environment_variables.all.items["ARM_OIDC_TOKEN"]
ARM_CLIENT_ID        = data.environment_variables.all.items["ARM_CLIENT_ID"]
ARM_USE_OIDC         = "true"
AZURE_RESOURCE_GROUP = var.certificate_dns_challenge_azure_resource_group_name
```

I don't see any mention of generic OIDC being supported in the docs https://go-acme.github.io/lego/dns/azuredns/ for things like Terraform Cloud or GitHub Actions for example.

Would love to see this supported to avoid static secrets, thank you.

**Comment by ldez** [comment]
Hello,

I think it's better to open an issue inside the repo https://github.com/vancluever/terraform-provider-acme

**Comment by ldez** [comment]
@pchanvallon do you have an idea?

**Comment by pchanvallon** [comment]
Hello, at the moment this authentication method is not embedded in the `DefaultAzureCredential` which is the function used inside `azuredns` provider.
For that we need to implement the logic to retrieve OIDC token like [`azrerm` terraform provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/provider/provider.go#L513).
@ldez I can add it in a new PR

**Comment by pchanvallon** [comment]
Yes this case is working because it is the mechanism used by Workload Identity Authentication as described in this [doc](https://learn.microsoft.com/en-us/samples/azure-samples/azure-ad-workload-identity/azure-ad-workload-identity/).
But we still need to handle the other cases.
