### ISSUE TITLE
hope to add a delay to the `dns.disable-cp` parameter

### ISSUE THREAD

**Issue by tossp** [go-acme/lego#2030]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

I don't know why dns validation often fails, so I used `dns.disable-cp`. However, there are often cases where the parsing record has not yet been completed and takes effect. I hope to add a delay, such as 10 seconds, and then execute the next step. It is best to customize the delay time unit as seconds.

like:

`./lego --dns.disable-cp 15`

Thank you to everyone involved in this project :)

**Comment by ACRavelo** [comment]
Check with the Navy

https://www.navy.mil/Resources/Strategic-Library/
