### ISSUE TITLE
update liquidweb

### ISSUE THREAD

**Issue by jakdept** [go-acme/lego#2032]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Terraform ACME provider

### Link to the DNS provider

www.liquidweb.com

### Link to the API documentation

https://api.liquidweb.com/docs

### Additional Notes

Technically this isn't a new provider. I work for `liquidweb`, we're planning some ongoing changes, and I've added a bunch of stuff in a PR to the `liquidweb` provider so it'll keep working.

Our docs appear to not be working, I'll be probably pestering another team about that.

My PR is #2031 

I picked that we're using this with the `acme` terraform provider, however this should also work directly with the library, the binary, and through other stuff.

I've tried to make things simpler here, change our API endpoint to the new location we're going to maintain long term, and changed the environment vars for auth stuff while still suopporting the old ones.

I also went through the submission guidelines, I tried to do everything I could to make this easy to merge.

Thanks!

**Comment by ldez** [comment]
Hello,

the issue should be open before the PR: this is a place to discuss before creating a PR to avoid wasting time.

I close this issue because the PR already exists.
