### ISSUE TITLE
GANDIv5:  API Key and PAT

### ISSUE THREAD

**Issue by Knight1** [go-acme/lego#2041]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

A Certificate, at least changed DNS settings on the provider. 

### What did you see instead?

Errors. 

The Gandi Implementation expects an API Key and optionally a PAT (Personal Access Token)

- If you do not supply the API Key: lego errors and exits.
```console
gandi: some credentials information are missing: GANDIV5_API_KEY
```
- If you supply a PAT as API Key: API errors.
```console
acme: error presenting token: unable to get TXT records for domain x.x and name _acme-challenge: 500: request failed: The server has either erred or is incapable of performing the requested operation.
```
- If you supply both: Lego uses the deprecated API Key. 

### How do you use lego?

Binary

### Reproduction steps

PAT Variable: "GANDIV5_PERSONAL_ACCESS_TOKEN"

Use API Key in PAT Variable
OR: Use only PAT Variable. 

### Version of lego

```console
lego version 4.14.2 linux/amd64
```

### Logs

<details>

With new PAT as API Key
```console
acme: error presenting token: unable to get TXT records for domain x.x and name _acme-challenge: 500: request failed: The server has either erred or is incapable of performing the requested operation.
```

Without API Key and only "GANDIV5_PERSONAL_ACCESS_TOKEN"
```console
gandi: some credentials information are missing: GANDIV5_API_KEY
```
</details>

**Comment by ldez** [comment]
Hello,

The support of PAT will happen in v4.15.
v4.14.x doesn't support PAT, so it's expected that PAT doesn't work with v4.14.2.
