### ISSUE TITLE
Dnspod api deprecated

### ISSUE THREAD

**Issue by anhao** [go-acme/lego#2057]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

update dnspod api

### What did you see instead?

dnspod api is 404  ,  https://dnsapi.cn/ is 404

### How do you use lego?

Binary

### Reproduction steps

Dnspod api deprecated

### Version of lego

```console
Dnspod api deprecated
```

### Logs

Dnspod api deprecated

**Comment by ldez** [comment]
already fixed in #1715 there is one year.

> DNSPod (deprecated)
> ..
> Use the Tencent Cloud provider instead.

https://go-acme.github.io/lego/dns/dnspod/
