### ISSUE TITLE
Can't get single certificate for both `DOMAIN.com` and `*.DOMAIN.com`

### ISSUE THREAD

**Issue by Azq2** [go-acme/lego#2068]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Single certificate with both `DOMAIN.com` and `*.DOMAIN.com`

### What did you see instead?

```
2023/12/08 13:40:09 Could not obtain certificates:
	error: one or more domains had a problem:
[DOMAIN.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: During secondary validation: Incorrect TXT record "....................removed....................." found at _acme-challenge.global-repair-management.com
```

### How do you use lego?

Binary

### Reproduction steps

```
CLOUDFLARE_API_KEY=.... CLOUDFLARE_EMAIL='my@email' lego --domains 'DOMAIN.COM,*.DOMAIN.COM' --accept-tos --email 'my@email' --dns cloudflare --server 'https://acme-staging-v02.api.letsencrypt.org/directory' run
```

### Version of lego

```console
lego version 4.14.2 linux/386
```

### Logs

<details>

```console
2023/12/08 13:39:40 [INFO] [DOMAIN.com, *.DOMAIN.com] acme: Obtaining bundled SAN certificate
2023/12/08 13:39:41 [INFO] [*.DOMAIN.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/992829....
2023/12/08 13:39:41 [INFO] [DOMAIN.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/9928292....
2023/12/08 13:39:41 [INFO] [*.DOMAIN.com] acme: use dns-01 solver
2023/12/08 13:39:41 [INFO] [DOMAIN.com] acme: Could not find solver for: tls-alpn-01
2023/12/08 13:39:41 [INFO] [DOMAIN.com] acme: Could not find solver for: http-01
2023/12/08 13:39:41 [INFO] [DOMAIN.com] acme: use dns-01 solver
2023/12/08 13:39:41 [INFO] [*.DOMAIN.com] acme: Preparing to solve DNS-01
2023/12/08 13:39:43 [INFO] cloudflare: new record for DOMAIN.com, ID 10465c2f68d22366681ddc837e7d....
2023/12/08 13:39:43 [INFO] [DOMAIN.com] acme: Preparing to solve DNS-01
2023/12/08 13:39:44 [INFO] cloudflare: new record for DOMAIN.com, ID fb5e065f065a367bd10c4a7f4cb1....
2023/12/08 13:39:44 [INFO] [*.DOMAIN.com] acme: Trying to solve DNS-01
2023/12/08 13:39:44 [INFO] [*.DOMAIN.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2023/12/08 13:39:46 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2023/12/08 13:39:52 [INFO] [*.DOMAIN.com] The server validated our request
2023/12/08 13:39:52 [INFO] [DOMAIN.com] acme: Trying to solve DNS-01
2023/12/08 13:39:52 [INFO] [DOMAIN.com] acme: Checking DNS record propagation using [127.0.0.53:53]
2023/12/08 13:39:54 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2023/12/08 13:39:54 [INFO] [DOMAIN.com] acme: Waiting for DNS record propagation.
2023/12/08 13:39:56 [INFO] [DOMAIN.com] acme: Waiting for DNS record propagation.
2023/12/08 13:39:58 [INFO] [DOMAIN.com] acme: Waiting for DNS record propagation.
2023/12/08 13:40:00 [INFO] [DOMAIN.com] acme: Waiting for DNS record propagation.
2023/12/08 13:40:02 [INFO] [DOMAIN.com] acme: Waiting for DNS record propagation.
2023/12/08 13:40:05 [INFO] [*.DOMAIN.com] acme: Cleaning DNS-01 challenge
2023/12/08 13:40:07 [INFO] [DOMAIN.com] acme: Cleaning DNS-01 challenge
2023/12/08 13:40:09 [INFO] Skipping deactivating of valid auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/9928292....
2023/12/08 13:40:09 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/9928292....
2023/12/08 13:40:09 Could not obtain certificates:
	error: one or more domains had a problem:
[DOMAIN.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: During secondary validation: Incorrect TXT record "Bg53EFRT7ZYcLZ_M...." found at _acme-challenge.DOMAIN.com
```

</details>

### Go environment (if applicable)

<details>

</details>

**Comment by ldez** [comment]
Hello,

it feels like a propagation issue: clean your TXT records and try again.

**Comment by Azq2** [comment]
> Hello,
> 
> it feels like a propagation issue: clean your TXT records and try again.

I reproduce this issue even with clean records.

```bash
rm -rf ~/.lego # This is important
CLOUDFLARE_API_KEY=.... CLOUDFLARE_EMAIL='my@email' lego --domains 'DOMAIN.COM,*.DOMAIN.COM' --accept-tos --email 'my@email' --dns cloudflare --server 'https://acme-staging-v02.api.letsencrypt.org/directory' run
```

Important condition - we must don't have a cached challenge for DOMAIN.com (just `rm ~/. Lego`)
Otherwise, all works.

I think, the main issue is that LEGO add two records at one time: one for DOMAIN.com and second for *.DOMAIN.com
But both of these records are added to DOMAIN.com

**Comment by ldez** [comment]
> I think, the main issue is that LEGO add two records at one time: one for DOMAIN.com and second for *.DOMAIN.com

This is expected: having 2 TXT records for the same domain is not a problem.
The problem is the propagation of your TXT records to other DNS servers.

**Comment by Azq2** [comment]
> > I think, the main issue is that LEGO add two records at one time: one for DOMAIN.com and second for *.DOMAIN.com
> 
> This is expected: having 2 TXT records for the same domain is not a problem. The problem is the propagation of your TXT records to other DNS servers (the 2 records are not available when LE does the validation).

But anyway this is LEGO's bug. I don't see any problem with this case on acme.sh or certbot.

Maybe, for fixing this issue, LEGO must work like this:
1. Get challenge for DOMAIN.com and set to the DNS
2. Validate challenge for DOMAIN.com and clean DNS records
3. Get challenge for *.DOMAIN.com and set to the DNS
4. Validate challenge for *.DOMAIN.com and clean DNS records
5. Request certificate

The current behavior is:
1. Get challenge for DOMAIN.com and set to the DNS
2. Get challenge for *.DOMAIN.com and set to DNS
3. Validate challenge for DOMAIN.com and clean DNS records
4. Validate challenge for *.DOMAIN.com and clean DNS records
5. Request certificate

But failing on 4 or 3 steps.

**Comment by Azq2** [comment]
> The problem is the propagation of your TXT records to other DNS servers (the 2 records are not available when LE does the validation).

Hmm, yes, with `--dns-timeout 120` seems to be works. Thanks.

**Comment by ldez** [comment]
> Seems like, LEGO use incorrect TXT in cases where more than one TXT present at the same time (because *.DOMAIN.com and DOMAIN.com adds TXT to DOMAIN.com)

lego uses and adds the right TXT records, the validation is not done by lego but by Let's Encrypt.

> Maybe, it is impossible to distinguish which TXT belongs to a specific domain in this case.

It's not how it works. lego uses a "parallel" approach (several TXT records for the same domain) on 90% of the DNS providers without any issues.

**It's a propagation issue.** There are several possibilities:
- the TTL is too long or too short
- the deletion of the previous TXT records is not propagated
- the second TXT record is not propagated enough quickly

**Comment by ldez** [comment]
The `time.Sleep(60 * time.Second)` is not the right solution:
- waiting 1 minute between 2 challenges is extremely slow, this will create a huge regression when a user has to handle thousands of domains.
- you just slow down the challenge requests, it's not related to DNS, so it will be flaky.

**Comment by Azq2** [comment]
> The `time.Sleep(60 * time.Second)` is not the right solution:
> 
> * waiting 1 minute between 2 challenges is extremely slow, this will create a huge regression when a user has to handle thousands of domains.
> * you just slow down the challenge requests, it's not related to DNS, so it will be flaky.

This is not suggestion for fix, this is how I check problem, nothing more.

But, I think, option like `--dnssleep` (acme.sh, minimum sleep between adding DNS records and validating in LE) should be useful for cases like this.
I can wait a few seconds if it helps avoid DNS issues on LE side. 

I didn't find a similar option from LEGO.

**Comment by Azq2** [comment]
Hm, I found CLOUDFLARE_POLLING_INTERVAL=30 and it working

**Comment by AleXoundOS** [comment]
I experience exactly the same problem with cloudflare. @Azq2, how reliable `CLOUDFLARE_POLLING_INTERVAL=30` solution works for you? And how the interval value is chosen?

Still, I think the issue is not resolved, since none of developers promoted any official solution or fix.

**Comment by ldez** [comment]
> Still, I think the issue is not resolved, since none of developers promoted any official solution or fix.

FYI, I'm the main maintainer of lego.

The solution found by Azq2 is in the same direction as my suggestions and fixes his problem, so it becomes the "official" solution.

**Comment by AleXoundOS** [comment]
@ldez, it seems for deSEC `DESEC_POLLING_INTERVAL=30` does not help.

**Comment by ldez** [comment]
This was related to Cloudflare, if you have an issue with deSEC, can you open a dedicated issue?

**Comment by AleXoundOS** [comment]
I'm not sure if all the options below are relevant, but this combination works reliably:

```
DESEC_POLLING_INTERVAL=30
DESEC_PROPAGATION_TIMEOUT=180
DESEC_TTL=3600
```

@ldez, currently, I'm not ready to investigate the issue further, unless it stops working.
