### ISSUE TITLE
desec: increase default `DESEC_PROPAGATION_TIMEOUT` by 60s

### ISSUE THREAD

**Issue by Atemu** [go-acme/lego#2072]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

Due to an upstream PowerDNS bug, deSEC appears to be polling propagations once a minute which results in the default configuration hitting the timeout almost every time which is a bad default experience.

See https://talk.desec.io/t/global-record-propagation-issues/332/ for context.

Would it be possible to increase the default timeout as a workaround? 120s would probably be a good value.

I'm not at all familiar with Go or else I would have opened a PR but perhaps something like

```Go
 // Propagation can currently take upwards of a minute: https://talk.desec.io/t/global-record-propagation-issues/332/
 PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, dns01.DefaultPropagationTimeout + 60 * time.second)
```

in here

https://github.com/go-acme/lego/blob/7186ebb6f194c55781432162a47ff62a0bb21023/providers/dns/desec/desec.go#L46-L46

would do it.

**Comment by ldez** [comment]
Hello,

> Would it be possible to increase the default timeout as a workaround?

Yes

> I'm not at all familiar with Go or else I would have opened a PR but perhaps something like

I will help you, so feel free to open a PR.

You just need to replace `dns01.DefaultPropagationTimeout` by `120 * time.second`.

**Comment by Atemu** [comment]
I'll see what I can do.

I'd prefer to increase the default timeout by the delay inherent to the service rather than hard-coding a new timeout.

**Comment by ldez** [comment]
@Atemu do you need help?

**Comment by Atemu** [comment]
Sorry, simply haven't found the time to get into this yet.
