### ISSUE TITLE
directadmin plugin 

### ISSUE THREAD

**Issue by jwklijnsma** [go-acme/lego#2079]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Library

### Detailed Description

is it possibly to add directadmin plugin https://certbot-dns-directadmin.readthedocs.io/en/latest/ ?

https://github.com/go-acme/lego/issues/1101#issue-589679170

**Comment by ldez** [comment]
duplicate of #1101
