### ISSUE TITLE
AutoDNS - mandatory credentials listed as additional

### ISSUE THREAD

**Issue by specculator** [go-acme/lego#2080]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

https://go-acme.github.io/lego/dns/autodns/

In order to Auth with the autodns API user needs to provide:

AUTODNS_API_USER
AUTODNS_API_PASSWORD
AUTODNS_CONTEXT

Currently the AUTODNS_CONTEXT is listed as additional but its mandatory. If user is not sending the context he will always receive user not found response.

### What did you see instead?

Please move 

AUTODNS_CONTEXT

from 

Additional Configuration

up to 

Credentials

Further i would ask to expand the description as following:

API Context (4 for AutoDNS, 1 for Demosystem, 10 for Schlundtech)

Personal AutoDNS / AutoDNS Pro users have their own context, please check with your Provider if you are unsure about your context)

Thanks and have a nice week!

### How do you use lego?

Other

### Reproduction steps

doesnt matter in this case

### Version of lego

```console
doesnt matter in this case
```

### Logs

doesnt matter in this case

### Go environment (if applicable)

doesnt matter in this case

**Comment by ldez** [comment]
Hello,

`AUTODNS_CONTEXT` is optional because there is a default value (4).


For the other suggestions, the source of the documentation is [here](https://github.com/go-acme/lego/blob/master/providers/dns/autodns/autodns.toml), feel free to open a PR.

**Comment by ldez** [comment]
No news, so I will close this issue.
