### ISSUE TITLE
Provider "do.de" not working, API call invalid

### ISSUE THREAD

**Issue by PinguCloud** [go-acme/lego#2117]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

The call to generate a wildcard certificate for "do.de" should look like this: 
https://my.do.de/api/letsencrypt?token=TOKEN&domain=_acme-challenge.testdomain.de&value=VALUE

### What did you see instead?

The generation fails as the call in lego (via Treafik) seems to look like this:
https://my.do.de/api/letsencrypt?token=TOKEN&domain=testdomain.de&value=VALUE

### How do you use lego?

Through Traefik

### Reproduction steps

Configure Treafik to use config provided here: https://go-acme.github.io/lego/dns/dode/ and let it try to generate cert.

### Version of lego

```console
v4.15.0
```

### Logs

<details>

```console
time="2024-02-22T09:50:28+01:00" level=error msg="Unable to obtain ACME certificate for domains \"RemovedForPrivacy\": unable to generate a certificate for the domains [RemovedForPrivacy]: error: one or more domains had a problem:\n[RemovedForPrivacy] [RemovedForPrivacy] 
acme: error presenting token: request to change TXT record for do.de returned the following error result ({\n    \"error\": \"domain doesn't start with _acme-challenge.\"\n}); used url [https://www.do.de/api/letsencrypt?domain=RemovedForPrivacy&token=RemovedForPrivacy&value=RemovedForPrivacy]\n" 
rule="Host(`RemovedForPrivacy`)" routerName=RemovedForPrivacy@docker providerName=wildcard.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

do you have a CNAME?

**Comment by PinguCloud** [comment]
I had actually tried that to no success, but I just figured out that i need I also needed some additional configuration in the traefik labels and change the `delayBeforeCheck`
It seems to work now. Thanks!

**Comment by ldez** [comment]
_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_
