### ISSUE TITLE
Support for provider: shellrent

### ISSUE THREAD

**Issue by urgali** [go-acme/lego#2124]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Traefik

### Link to the DNS provider

https://www.shellrent.com/

### Link to the API documentation

https://api.shellrent.com/section/apien

### Additional Notes

Here is a LE community post reporting shellrent as functioning: https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438

Here is shellrent certbot git: https://github.com/shellrent/certbot-dns-shellrent

And here is official acme.sh implementation: https://github.com/acmesh-official/acme.sh/wiki/dnsapi2#dns_shellrent

**Comment by ldez** [comment]
FYI there is no official acme.sh implementation: the wiki was updated but the [PR](https://github.com/acmesh-official/acme.sh/pull/2996) was never merged.

**Comment by ldez** [comment]
> [x] Yes, I'm able to create a pull request and be able to maintain the implementation.

You checked this box, do you plan to create a PR?

**Comment by urgali** [comment]
No, my bad, I'm availabel to test it if someone implements it though
