### ISSUE TITLE
azure: find zones via serviceDiscovery (or allow multiple values for AZURE_RESOURCE_GROUP)

### ISSUE THREAD

**Issue by mblaschke** [go-acme/lego#2131]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Docker image

### Detailed Description

Sometimes DNS zones are inside multiple Azure ResourceGroups.

One solution could be to find available Zones via Azure REST API or ResourceGraph Query based on a list of ResourceGroups before using them as a kind of lookup.

Same could be done for subscription IDs or to have the possibility to leave both empty and try to find the zones via ResourceGraph based on roleAssignment visibility.

possible resourcegraph query:

```
resources
| where type =~ "microsoft.network/dnszones"
| project id, subscriptionId, resourceGroup, name
```

**Comment by ldez** [comment]
@pchanvallon do you have any thoughts on this question?

**Comment by pchanvallon** [comment]
Hello @mblaschke ,

I am a bit confused about the underlying use-case.
Can you explain a bit more what you attend to do with this new feature ?

**Comment by mblaschke** [comment]
Create a certificate with multiple SANs using Azure DNS zones which are in multiple resourceGroups or subscriptions.

As a user i expect that Lego finds the DNS zones automatically in my subscriptions based on the assigned roleAssignments of the serviceprincipal. It should not need a `AZURE_SUBSCRIPTION_ID` or `AZURE_RESOURCE_GROUP` but could be possible to filter service discovery.

without  `AZURE_SUBSCRIPTION_ID` and `AZURE_RESOURCE_GROUP`:
(find all DNS zones in visible scope)
```
resources
| where type =~ "microsoft.network/dnszones"
| project id, subscriptionId, resourceGroup, name
```

with only `AZURE_SUBSCRIPTION_ID`:
(find all DNS zones in one subscription)
```
resources
| where type =~ "microsoft.network/dnszones"
| where subscriptionId =~ "${AZURE_SUBSCRIPTION_ID}"
| project id, subscriptionId, resourceGroup, name
```

with `AZURE_SUBSCRIPTION_ID` and `AZURE_RESOURCE_GROUP`:
(find all DNS zones in a specific resourcegroup)
```
resources
| where type =~ "microsoft.network/dnszones"
| where subscriptionId =~ "${AZURE_SUBSCRIPTION_ID}" and resourceGroup =~ "${AZURE_RESOURCE_GROUP}"
| project id, subscriptionId, resourceGroup, name
```

This would make Azure DNS provider more flexible and easier to use.

I'm willing to create a PR if you are ok with this feature using resourceGraph for service discovery.

**Comment by mblaschke** [comment]
@pchanvallon 

implemented a first working preview (tested only with public zones)

**Comment by mblaschke** [comment]
@ldez  any chance we get a new release with this feature in the next days?

**Comment by ldez** [comment]
Just out of curiosity, why in the next days?

**Comment by mblaschke** [comment]
Nothing special, but we're actually waiting for this feature because it makes everything easier.
We're currently using a forked build and would like to get rid of it.
