### ISSUE TITLE
Scaleway DNS Challenge credentials not correct

### ISSUE THREAD

**Issue by birkanozer** [go-acme/lego#2135]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

SCW_ACCESS_KEY and SCW_SECRET_KEY variables as described in https://www.scaleway.com/en/developers/api/domains-and-dns/

### What did you see instead?

SCALEWAY_API_TOKEN

### How do you use lego?

Through Traefik

### Reproduction steps

I'have checked the documentation of Scaleway and LeGo and also verified by looking to the source code of scaleway.go

### Version of lego

```console
Lastest
```

### Logs

No logs

### Go environment (if applicable)

No details

**Comment by ldez** [comment]
Hello,

the env vars inside `SCW_ACCESS_KEY` and `SCW_SECRET_KEY` in this [doc](https://www.scaleway.com/en/developers/api/domains-and-dns/) are just examples used inside a guide with cURL calls.

the env var `SCALEWAY_API_TOKEN` is the "secret key", you don't need the access key when using the SDK.

https://github.com/go-acme/lego/pull/1393/files#r622246653
