### ISSUE TITLE
ERROR acme: error: 500 :: POST renewing with v4.16.0 --- v4.15.0 is OK

### ISSUE THREAD

**Issue by stefanomarty** [go-acme/lego#2137]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Normal renewal of a certificate

### What did you see instead?

This error:
```
2024/03/10 21:36:14 [INFO] [redacted] acme: Trying renewal with 1316 hours remaining
2024/03/10 21:36:14 [INFO] [redacted] acme: Obtaining bundled SAN certificate
2024/03/10 21:36:14 acme: error: 500 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:serverInternal :: While validating order as a replacement and error occurred
```

### How do you use lego?

Binary

### Reproduction steps

Install lego v4.16.0 and try to renew a certificate

### Version of lego

```
lego version 4.16.0 linux/amd64
```

Going back to lego v4.15.0 the certificate gets renewed without errors:

```console
$ wget https://github.com/go-acme/lego/releases/download/v4.15.0/lego_v4.15.0_linux_amd64.tar.gz
tar xf lego_v4.15.0_linux_amd64.tar.gz lego
$ ./lego --version
lego version 4.15.0 linux/amd64

$ ./lego --email="redacted" --http --http.webroot "/var/www/html/"  --domains="redacted" --path=/etc/lego renew --days 60
2024/03/10 21:46:34 [INFO] [redacted] acme: Trying renewal with 1316 hours remaining
2024/03/10 21:46:34 [INFO] [redacted acme: Obtaining bundled SAN certificate
2024/03/10 21:46:35 [INFO] [redacted] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/324772220427
2024/03/10 21:46:35 [INFO] [redacted] acme: Could not find solver for: tls-alpn-01
2024/03/10 21:46:35 [INFO] [redacted] acme: use http-01 solver
2024/03/10 21:46:35 [INFO] [redacted] acme: Trying to solve HTTP-01
2024/03/10 21:46:39 [INFO] [redacted] The server validated our request
2024/03/10 21:46:39 [INFO] [redacted] acme: Validations succeeded; requesting certificates
2024/03/10 21:46:39 [INFO] [redacted] Server responded with a certificate.

```

### Logs

<details>

```console
2024/03/10 21:36:14 [INFO] [redacted] acme: Trying renewal with 1316 hours remaining
2024/03/10 21:36:14 [INFO] [redacted] acme: Obtaining bundled SAN certificate
2024/03/10 21:36:14 acme: error: 500 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:serverInternal :: While validating order as a replacement and error occurred

```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
go version go1.22.0 linux/amd64
```

</details>

**Comment by ldez** [comment]
:thinking: feel related to ARI, @beautifulentropy maybe you can help us?

**Comment by ldez** [comment]
@stefanomarty can we try to bisect the problem?
Can you try the following commits?
- 82e9a5e2a917e72870781d80d2de515c27208304
- adea063bb1692148a1858ad2b8a4041dc1e766b1
- 6dd8d035d18b3d858f419e0ed735162d25a290d1
-

**Comment by ldez** [comment]
I bisected the problem and it's related to 6dd8d035d18b3d858f419e0ed735162d25a290d1 (#2114)

**Comment by ldez** [comment]
I found a fix #2138 for users who don't use ARI but the problem is still here.
I will create a release v4.6.1

**Comment by beautifulentropy** [comment]
> 🤔 feel related to ARI, @beautifulentropy maybe you can help us?
> 
> * https://github.com/letsencrypt/boulder/blob/7d633c6e781ba891192f78745720750195f897b6/wfe2/wfe.go#L2321
> * https://github.com/letsencrypt/boulder/blob/7d633c6e781ba891192f78745720750195f897b6/wfe2/wfe.go#L2217

Thanks for bringing this to our attention. This one is our fault. We need to make a slight adjustment to our production configuration. I'll post once we have this fixed.

**Comment by beautifulentropy** [comment]
This issue has been resolved.
