### ISSUE TITLE
when i run it on armv7I-32 CPU，it told me "runtime: this CPU has no VFPv3 floating point hardware, so it cannot run a binary compiled for VFPv3 hard floating point. Recompile adding ,softfloat to GOARM or changing GOARM to 6."

### ISSUE THREAD

**Issue by ErDongChen1973** [go-acme/lego#2143]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I hope it can run on armv7I CPU

### What did you see instead?

when i run it on armv7-32 CPU，it told me "runtime: this CPU has no VFPv3 floating point hardware, so it cannot run a binary compiled for VFPv3 hard floating point. Recompile adding ,softfloat to GOARM or changing GOARM to 6."

### How do you use lego?

Library

### Reproduction steps

./lego --email="xxx@xx.com" --domains="www.xxxx.com" --http run

### Version of lego

```console
v4.16.1
```

### Logs

runtime: this CPU has no VFPv3 floating point hardware, so it cannot run
a binary compiled for VFPv3 hard floating point. Recompile adding ,softfloat
to GOARM or changing GOARM to 6.

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

as you don't have VFPv3 floating point hardware you should the armv6 version.

https://github.com/go-acme/lego/releases/tag/v4.16.1

**Comment by ErDongChen1973** [comment]
> Hello,
> 
> as you don't have VFPv3 floating point hardware you should the armv6 version.
> 
> https://github.com/go-acme/lego/releases/tag/v4.16.1

I have tried to run it(v5/v6), but it tells me "Segmentation fault"

**Comment by ldez** [comment]
Which hardware are you using with an armv7I?
