### ISSUE TITLE
Support for provider: mittwald

### ISSUE THREAD

**Issue by jotimann** [go-acme/lego#2177]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://www.mittwald.de/

### Link to the API documentation

https://api.mittwald.de/v2/docs/

**Comment by ldez** [comment]
Hello,

I checked quickly the [API documentation](https://api.mittwald.de/v2/docs/#/Domain), and I didn't find an endpoint to delete a record.

I also didn't find how to get a zone ID or project ID.

Could you give me more information about those elements?

---

_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

**Comment by ldez** [comment]
ACME DNS-01 challenge requires to create and delete a TXT record (ex: `_acme-challenge.example.com` or `_acme-challenge.sub.example.com`)

> The projectid you can get when you lists your projects belonging to your user: https://api.mittwald.de/v2/docs/#/Project/project-list-projects and with that id you can list your zones connected to the project: https://api.mittwald.de/v2/docs/#/Domain/dns-list-dns-zones

The endpoint [`/v2/projects`](https://api.mittwald.de/v2/docs/#/Project/project-list-projects) requires the customer ID and the server ID.
How do I get this information based on the API token?

If I follow your explanation, to create a record:
- call [`/v2/projects`](https://api.mittwald.de/v2/docs/#/Project/project-list-projects) to get the project ID (but need customer ID and the server ID)
- call [`/v2/projects/{projectId}/dns-zones`](https://api.mittwald.de/v2/docs/#/Domain/dns-list-dns-zones) with the project ID to get all the zones (pagination?)
- call [`/v2/dns-zones`](https://api.mittwald.de/v2/docs/#/Domain/dns-create-dns-zone) to create a zone (if needed) and get the zone ID. (ex: `_acme-challenge.example.com` or `_acme-challenge.sub.example.com`)

I didn't find the call to create a TXT record. [`/v2/dns-zones/{dnsZoneId}/record-sets/{recordSet}/actions/set-managed`](https://api.mittwald.de/v2/docs/#/Domain/dns-set-record-set-managed) allows to create A or MX record only (and the request schema is missing from the doc).

to delete a record:
- call [`/v2/projects`](https://api.mittwald.de/v2/docs/#/Project/project-list-projects) to get the project ID (but need customer ID and the server ID)
- call [`/v2/projects/{projectId}/dns-zones`](https://api.mittwald.de/v2/docs/#/Domain/dns-list-dns-zones) with the project ID to get all the zones (pagination?)
- call [`/v2/dns-zones/{dnsZoneId}`](https://api.mittwald.de/v2/docs/#/Domain/dns-delete-dns-zone) with the zone ID to delete the zone and the TXT record.

**Comment by ldez** [comment]
@jotimann any news?

**Comment by ldez** [comment]
> but the response can be multiple projects.

How do I get the project ID when I only have a domain and a token?

---

Can you give me a list of the calls to create only one TXT record based on a token and a domain name?

Can you give me a list of the calls to remove only one TXT record based on a token and a domain name?

**Comment by jotimann** [comment]
## Create a txt record only with domain and token:
- [/v2/domains](https://api.mittwald.de/v2/docs/#/Domain/domain-list-domains) -> Array with the domains to get the projectId
- [/v2/projects/{projectId}/dns-zones](https://api.mittwald.de/v2/docs/#/Domain/dns-list-dns-zones) -> Array with the dns zones of the project -> get the Id of the dns-zone of your domain
- [/v2/dns-zones](https://api.mittwald.de/v2/docs/#/Domain/dns-create-dns-zone) -> create Subzone with:
```
{
  "name": "_acme-challenge",
  "parentZoneId": "zoneId"
}
```
The response is your new zoneId.
-[ /v2/dns-zones/{dnsZoneId}/record-sets/{recordSet}](https://api.mittwald.de/v2/docs/#/Domain/dns-update-record-set) -> use the response zoneId and recordSet = txt with the body:
```
{
  "settings": {
    "ttl": {
      "auto": true
    }
  },
  "entries": [
    "test"
  ]
}
```

## Delete a txt-record:
- [/v2/domains](https://api.mittwald.de/v2/docs/#/Domain/domain-list-domains) -> Array with the domains to get the projectId
- [/v2/projects/{projectId}/dns-zones](https://api.mittwald.de/v2/docs/#/Domain/dns-list-dns-zones) -> Array with the dns zones of the project -> get the Id of the dns-zone of your domain
- [/v2/dns-zones/{dnsZoneId}](https://api.mittwald.de/v2/docs/#/Domain/dns-delete-dns-zone) -> delete the dns-zone


-------------

> Is Mittwald support for multiple TXT entries for the same domain?

Yes you can create multiple entries for `_acme-challenge.example.com` just fill them in the entries:
```
{
  "settings": {
    "ttl": {
      "auto": true
    }
  },
  "entries": [
    "test",
    "test2"
  ]
}
```

**Comment by feroxib** [comment]
ping @jotimann
