### ISSUE TITLE
Suppress "no renewal" message on renew

### ISSUE THREAD

**Issue by Sxderp** [go-acme/lego#2214]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

```
The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal.
```

When running via a cron job or other situation where output causes alerts it's nice to avoid "informational" outputs. It seems this message is printed to "stderr" so I can't just redirect it, otherwise I'd miss errors. As far as I can tell there's no way to natively suppress this output.

**Comment by ldez** [comment]
Duplicate of #1531
