### ISSUE TITLE
ovh: allow to use ovh.conf

### ISSUE THREAD

**Issue by yomovh** [go-acme/lego#2215]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Through Terraform ACME provider

### Detailed Description

Hello there !

We have some OVHcloud customers that are using the ability to provide the API credentials through ovh.conf file (see [README](https://github.com/ovh/go-ovh/blob/6817886d12a8c5650794b28da635af9fcdfd1162/README.md?plain=1#L152)) notably in OVHcloud terraform provider.

When they are also using acme provider in a plan, they need to change the way they provide the credentials since in acme, the only supported way seems to be through [environment variables](https://github.com/go-acme/lego/blob/master/providers/dns/ovh/ovh.go#L102)

This feature request would be to enable the usage of `ovh.conf` file in acme for the OVHcloud provider.

**Comment by ldez** [comment]
Hello @yomovh,

You are a product manager at OVH, and your request is for your customers, it would feel fair if you could sponsor this project.

https://github.com/sponsors/ldez

I will do a PR to support this in any case.

**Comment by yomovh** [comment]
That's a fair point, I will pull some strings and see what happens.

**Comment by ldez** [comment]
I created a [PR](https://github.com/go-acme/lego/pull/2216) but I need a change inside `go-ovh`: https://github.com/ovh/go-ovh/pull/84

**Comment by ldez** [comment]
@yomovh any news?

**Comment by yomovh** [comment]
Thanks for the heads up. I have put one more coin in the machine 🤞

**Comment by yomovh** [comment]
Hello,

I did not manage to get some funding for you. I am really sorry I did made it happen 😞
