### ISSUE TITLE
zerossl RFC8738 certificate issuing for IP address not working

### ISSUE THREAD

**Issue by t-chab** [go-acme/lego#2222]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

A message noticing successful certificate generation.

### What did you see instead?

The following error message:

```
2024/07/10 12:51:13 [INFO] [REDACTED] acme: Obtaining bundled SAN certificate
2024/07/10 12:51:14 Could not obtain certificates:
	acme: error: 400 :: POST :: https://acme.zerossl.com/v2/DV90/newOrder :: urn:ietf:params:acme:error:unsupportedIdentifier :: IPv4 and IPv6 identifier types are not yet supported
```

### How do you use lego?

Binary

### Reproduction steps

Create a [free zerossl account](https://app.zerossl.com/signup) and generate eab kid and hmac key through [web interface](https://app.zerossl.com/developer)
Launch lego CLI with following options :

```bash
lego \
  --email="${ZEROSSL_EMAIL}" \
  --domains="[REDACTED_IP_ADDRESS]" \
  --server "https://acme.zerossl.com/v2/DV90" \
  --eab \
  --kid="${ZEROSSL_KID}" \
  --hmac="${ZEROSSL_HMAC_KEY}" \
  --http run
```

### Version of lego

```console
lego version 4.17.4 linux/amd64
```

### Logs

<details>

```console
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

the error is reported by zeroSSL itself, it's not a lego problem.

**Comment by t-chab** [comment]
Hello, 

Thanks, but Let's Encrypt [does not seems to support certificate for IP address, only for domains](https://community.letsencrypt.org/t/is-it-possible-to-issue-certificate-for-ip-address/203820/2)

And it seems that zerossl supports it only with manual configuration, not through ACME API.

Sorry for the trouble.
