### ISSUE TITLE
cloudflare: can't obtain certificates from LE with dns challenge

### ISSUE THREAD

**Issue by dkleber89** [go-acme/lego#2227]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Obtain certificates from LE with cloudflare dns challenge with the following command -> `lego --dns cloudflare --email hostmaster@mydomain.at --domains subdomain.mydomain.at --server https://acme-staging-v02.api.letsencrypt.org/directory --dns.resolvers 1.1.1.1:53  run`

(subdomain.mydomain.at is a replacment for my real domain)

### What did you see instead?

Same output for Variant 1 (CLOUDFLARE_DNS_API_TOKEN) and Variant 2 (CLOUDFLARE_EMAIL, CLOUDFLARE_API_KEY):

```console
2024/07/17 13:25:07 [INFO] [subdomain.mydomain.at] acme: Obtaining bundled SAN certificate
2024/07/17 13:25:08 [INFO] [subdomain.mydomain.at] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/13198637873
2024/07/17 13:25:08 [INFO] [subdomain.mydomain.at] acme: Could not find solver for: tls-alpn-01
2024/07/17 13:25:08 [INFO] [subdomain.mydomain.at] acme: Could not find solver for: http-01
2024/07/17 13:25:08 [INFO] [subdomain.mydomain.at] acme: use dns-01 solver
2024/07/17 13:25:08 [INFO] [subdomain.mydomain.at] acme: Preparing to solve DNS-01
2024/07/17 13:25:48 [INFO] [subdomain.mydomain.at] acme: Cleaning DNS-01 challenge
2024/07/17 13:26:28 [WARN] [subdomain.mydomain.at] acme: cleaning up failed: cloudflare: could not find zone for domain "subdomain.mydomain.at": [fqdn=_acme-challenge.subdomain.mydomain.at.] could not find the start of authority for '_acme-challenge.subdomain.mydomain.at.': DNS call error: read udp 10.0.3.37:51647->1.1.1.1:53: i/o timeout [ns=1.1.1.1:53, question='at. IN  SOA'] 
2024/07/17 13:26:28 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/13198637873
2024/07/17 13:26:28 Could not obtain certificates:
        error: one or more domains had a problem:
[subdomain.mydomain.at] [subdomain.mydomain.at] acme: error presenting token: cloudflare: could not find zone for domain "subdomain.mydomain.at": [fqdn=_acme-challenge.subdomain.mydomain.at.] could not find the start of authority for '_acme-challenge.subdomain.mydomain.at.': DNS call error: read udp 10.0.3.37:38961->1.1.1.1:53: i/o timeout [ns=1.1.1.1:53, question='at. IN  SOA']
```

### How do you use lego?

Binary

### Reproduction steps

Described above.

I try also with no custom dns resolver and no custom server but it is every time the same output. 

### Version of lego

```console
lego version v4.16.1 linux/amd64
also with actual git version
lego version 321cea51e4388e396bd2602196c2c6d22bb01e0e linux/amd64
```

**Comment by ldez** [comment]
Hello,

> DNS call error: read udp 10.0.3.37:38961->1.1.1.1:53: i/o timeout [ns=1.1.1.1:53, question='at. IN  SOA']

You have a network issue: the DNS call is blocked, it can related to a firewall.

**Comment by dkleber89** [comment]
Yes i think that too but a dnslookup for at on 1.1.1.1 works like a charm ->

```
dnslookup at 1.1.1.1
dnslookup v1.10.0
Server: 1.1.1.1

dnslookup result (elapsed 36.823851ms):
;; opcode: QUERY, status: NOERROR, id: 6391
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;at.    IN       A

;; AUTHORITY SECTION:
at.     10800   IN      SOA     dns.nic.at. domain-admin.univie.ac.at. 1721217602 10800 3600 604800 10800

```

**Comment by ldez** [comment]
do this call: `drill @1.1.1.1 example.com SOA`

The DNS call is not about an A record but a SOA record.

**Comment by ldez** [comment]
I will close this issue, if you need to more help don't hesitate to open a discussion: https://github.com/go-acme/lego/discussions
