### ISSUE TITLE
BlueCat cleanup fails so no cert created

### ISSUE THREAD

**Issue by dittman1** [go-acme/lego#2229]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Certificates created

### What did you see instead?
```
2024/07/19 10:09:30 [INFO] [bam.abc.domain.net] acme: Cleaning DNS-01 challenge
2024/07/19 10:09:30 [WARN] [bam.abc.domain.net] acme: cleaning up failed: bluecat: deploy: unexpected status code: [status code: 500] body: "bdds1.abc.domain.net: A deployment is possibly currently being processed. Please wait until the deployment is completed, and try again.; nested exception is: \n\tjava.lang.RuntimeException: A deployment is possibly currently being processed. Please wait until the deployment is completed, and try again." 
2024/07/19 10:09:30 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/379109383177
2024/07/19 10:09:31 error: one or more domains had a problem:
[bam.abc.domain.net] [bam.abc.domain.net] acme: error presenting token: bluecat: deploy: unexpected status code: [status code: 500] body: "bdds1.abc.domain.net: A deployment is possibly currently being processed. Please wait until the deployment is completed, and try again.; nested exception is: \n\tjava.lang.RuntimeException: A deployment is possibly currently being processed. Please wait until the deployment is completed, and try again."
```

### How do you use lego?

Binary

### Reproduction steps

I run the following command:

```
./lego --dns="bluecat" --email="me@domain.net" --csr="bam.abc.domain.net.csr" rene
```

### Version of lego

```console
# ./lego --version
lego version 4.14.2 linux/amd64
```

### Logs

<details>

```console
# paste output here
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by dittman1** [comment]
BlueCat Address Manager is version 9.6.0.

**Comment by ldez** [comment]
Hello,

> java.lang.RuntimeException: A deployment is possibly currently being processed.

This error is from Bluecat: lego is written in Go, so there is no Java runtime error inside lego.

The problem seems to be in your Bluecat instance.

**Comment by dittman1** [comment]
The error is saying lego is trying to do the deployment while the other deployment is still in process, is there any way to put a wait in before the deployment is attempted to test whether this is what is happening?  I have the zone set to automatic deployment and it was working in May and I haven't done any updates to the BAM since.  I did set the zone to not automatically deploy and it didn't make a difference.

It would be nice to have a flag to tell lego to not try to deploy for zones that are set to automatic deployment.

**Comment by dittman1** [comment]
Checking the transaction history in the BAM the records are getting added and removed.

**Comment by dittman1** [comment]
Sorry, I read my notes wrong, I upgraded the BAM from 9.5.1 to 9.6.0 in June, so this appears to be change in BlueCat that's causing the issue.

**Comment by ldez** [comment]
>  is there any way to put a wait in before the deployment is attempted to test whether this is what is happening? 

No

> It would be nice to have a flag to tell lego to not try to deploy for zones that are set to automatic deployment.

The BlueCat API is "unfriendly", so it seems complex to automate that but we can try to add an env var.
We don't have a BlueCat account, so we will need you to test it.
Can you try the PR #2230?

**Comment by dittman1** [comment]
Yes.  Still would be nice to skip deployment if not necessary.

I need to learn enough Go to see what the lego code is doing, my BlueCat API work has all been in Python.

**Comment by ldez** [comment]
> I need to learn enough Go to see what the lego code is doing, my BlueCat API work has all been in Python.

I already open a PR, you just need to test it.

**Comment by ldez** [comment]
To test the PR:
- checkout the branch related to the PR
- install Go https://go.dev/doc/install
- run `make build`

**Comment by dittman1** [comment]
I'm going to have to build a new environment to test, RHEL9 doesn't have Go 1.22 and trying to install results in missing lib errors.

**Comment by dittman1** [comment]
That worked.  Thank you.

I'm going to see if I can find out if there's a known issue with any of the APIs that are used in 9.6.0.
