### ISSUE TITLE
Tencent cloud cannot be successfully generated through DNS

### ISSUE THREAD

**Issue by hhs66317** [go-acme/lego#2237]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Hope to generate Tencent cloud domain name certificate through DNS

### What did you see instead?

```
2024/08/01 10:41:28 No key found for account xxxxxxxx@gmail.com. Generating a P256 key.
2024/08/01 10:41:28 Saved key to D:\Software\lego\.lego\accounts\acme-v02.api.letsencrypt.org\xxxxxxxx@gmail.com\keys\xxxxxxxx@gmail.com.key
2024/08/01 10:41:29 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf
Do you accept the TOS? Y/n
Y
2024/08/01 10:41:33 [INFO] acme: Registering account for xxxxxxxx@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "D:\Software\lego\.lego\accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Obtaining bundled SAN certificate
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/123456789
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Could not find solver for: tls-alpn-01
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Could not find solver for: http-01
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: use dns-01 solver
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Preparing to solve DNS-01
2024/08/01 10:44:55 [INFO] [pc.xxxxx.top] acme: Cleaning DNS-01 challenge
2024/08/01 10:48:16 [WARN] [pc.xxxxx.top] acme: cleaning up failed: tencentcloud: failed to get hosted zone: could not find zone: [fqdn=_acme-challenge.pc.xxxxx.top.] could not find the start of authority for '_acme-challenge.pc.xxxxx.top.': DNS call error: read udp 127.0.0.1:52731->127.8.0.1:53: i/o timeout [ns=google-public-dns-a.google.com:53, question='top. IN  SOA']
DNS call error: read udp 127.0.0.1:52783->127.8.0.2:53: i/o timeout [ns=google-public-dns-b.google.com:53, question='top. IN  SOA']
2024/08/01 10:48:17 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/123456789
2024/08/01 10:48:17 Could not obtain certificates:
        error: one or more domains had a problem:
[pc.xxxxx.top] [pc.xxxxx.top] acme: error presenting token: tencentcloud: failed to get hosted zone: could not find zone: [fqdn=_acme-challenge.pc.xxxxx.top.] could not find the start of authority for '_acme-challenge.pc.xxxxx.top.': DNS call error: read udp 127.0.0.1:52295->127.8.0.1:53: i/o timeout [ns=google-public-dns-a.google.com:53, question='top. IN  SOA']
DNS call error: read udp 127.0.0.1:52337->127.8.0.2:53: i/o timeout [ns=google-public-dns-b.google.com:53, question='top. IN  SOA']
```

### How do you use lego?

Binary

### Reproduction steps

lego.exe --email xxxxxxxx@gmail.com --dns tencentcloud --domains pc.xxxxx.top run

### Version of lego

```console
lego version 4.17.4 windows/amd64
```

### Logs

<details>

```console
2024/08/01 10:41:28 No key found for account xxxxxxxx@gmail.com. Generating a P256 key.
2024/08/01 10:41:28 Saved key to D:\Software\lego\.lego\accounts\acme-v02.api.letsencrypt.org\xxxxxxxx@gmail.com\keys\xxxxxxxx@gmail.com.key
2024/08/01 10:41:29 Please review the TOS at https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf
Do you accept the TOS? Y/n
Y
2024/08/01 10:41:33 [INFO] acme: Registering account for xxxxxxxx@gmail.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "D:\Software\lego\.lego\accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Obtaining bundled SAN certificate
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/123456789
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Could not find solver for: tls-alpn-01
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Could not find solver for: http-01
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: use dns-01 solver
2024/08/01 10:41:34 [INFO] [pc.xxxxx.top] acme: Preparing to solve DNS-01
2024/08/01 10:44:55 [INFO] [pc.xxxxx.top] acme: Cleaning DNS-01 challenge
2024/08/01 10:48:16 [WARN] [pc.xxxxx.top] acme: cleaning up failed: tencentcloud: failed to get hosted zone: could not find zone: [fqdn=_acme-challenge.pc.xxxxx.top.] could not find the start of authority for '_acme-challenge.pc.xxxxx.top.': DNS call error: read udp 127.0.0.1:52731->127.8.0.1:53: i/o timeout [ns=google-public-dns-a.google.com:53, question='top. IN  SOA']
DNS call error: read udp 127.0.0.1:52783->127.8.0.2:53: i/o timeout [ns=google-public-dns-b.google.com:53, question='top. IN  SOA']
2024/08/01 10:48:17 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/123456789
2024/08/01 10:48:17 Could not obtain certificates:
        error: one or more domains had a problem:
[pc.xxxxx.top] [pc.xxxxx.top] acme: error presenting token: tencentcloud: failed to get hosted zone: could not find zone: [fqdn=_acme-challenge.pc.xxxxx.top.] could not find the start of authority for '_acme-challenge.pc.xxxxx.top.': DNS call error: read udp 127.0.0.1:52295->127.8.0.1:53: i/o timeout [ns=google-public-dns-a.google.com:53, question='top. IN  SOA']
DNS call error: read udp 127.0.0.1:52337->127.8.0.2:53: i/o timeout [ns=google-public-dns-b.google.com:53, question='top. IN  SOA']

```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
> DNS call error: read udp 127.0.0.1:52337->127.8.0.2:53: i/o timeout [ns=google-public-dns-b.google.com:53, question='top. IN  SOA']


This means that when lego tries to find the zone by doing SOA calls, your local DNS doesn't answer.

So you have to check your network (firewall, local DNS, etc.), and in some cases the usage `--dns.resolvers` can help.

https://go-acme.github.io/lego/usage/cli/options/

**Comment by hhs66317** [comment]
> > DNS call error: read udp 127.0.0.1:52337->127.8.0.2:53: i/o timeout [ns=google-public-dns-b.google.com:53, question='top. IN  SOA']
> 
> This means that when lego tries to find the zone by doing SOA calls, your local DNS doesn't answer.
> 
> So you have to check your network (firewall, local DNS, etc.), and in some cases the usage `--dns.resolvers` can help.
> 
> https://go-acme.github.io/lego/usage/cli/options/

My local dns supports SOA queries, see below for queries：

```
; <<>> DiG 9.9.5-W1 <<>> pc.xxxxx.top SOA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20190
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pc.xxxxx.top.                        IN      SOA

;; AUTHORITY SECTION:
xxxxx.top.            180     IN      SOA     f1g1ns1.dnspod.net. freednsadmin.dnspod.com. 1722505877 3600 180 1209600 180

;; Query time: 20 msec
;; SERVER: 172.17.0.200#53(172.17.0.200)
;; WHEN: Thu Aug 01 17:51:37 中国标准时间 2024
;; MSG SIZE  rcvd: 120
```
Also I tried to try with the --dns.resolvers you provided and still couldn't get the certificate

```
2024/08/01 17:50:05 [INFO] [pc.xxxxxxxx.top] acme: Obtaining bundled SAN certificate
2024/08/01 17:50:06 [INFO] [pc.xxxxxxxx.top] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/111111111111
2024/08/01 17:50:06 [INFO] [pc.xxxxxxxx.top] acme: Could not find solver for: tls-alpn-01
2024/08/01 17:50:06 [INFO] [pc.xxxxxxxx.top] acme: Could not find solver for: http-01
2024/08/01 17:50:06 [INFO] [pc.xxxxxxxx.top] acme: use dns-01 solver
2024/08/01 17:50:06 [INFO] [pc.xxxxxxxx.top] acme: Preparing to solve DNS-01
2024/08/01 17:50:07 [INFO] [pc.xxxxxxxx.top] acme: Trying to solve DNS-01
2024/08/01 17:50:08 [INFO] [pc.xxxxxxxx.top] acme: Checking DNS record propagation. [nameservers=223.5.5.5:53]
2024/08/01 17:50:10 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/08/01 17:50:30 [INFO] [pc.xxxxxxxx.top] acme: Waiting for DNS record propagation.
2024/08/01 17:50:52 [INFO] [pc.xxxxxxxx.top] acme: Waiting for DNS record propagation.
2024/08/01 17:51:14 [INFO] [pc.xxxxxxxx.top] acme: Waiting for DNS record propagation.
2024/08/01 17:51:16 [INFO] [pc.xxxxxxxx.top] acme: Cleaning DNS-01 challenge
2024/08/01 17:51:18 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/384631242247
2024/08/01 17:51:18 Could not obtain certificates:
        error: one or more domains had a problem:
[pc.xxxxxxxx.top] propagation: time limit exceeded: last error: DNS call error: read udp 127.0.0.1:55015->127.8.0.3:53: i/o timeout [ns=f1g1ns1.dnspod.net.:53, question='_acme-challenge.pc.xxxxxxxx.top. IN  TXT']

```

**Comment by ldez** [comment]
> My local dns supports SOA queries
> ...
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
> ...


The answer section is empty (`ANSWER: 0`), so your local DNS doesn't answer SOA calls.

**Comment by wangdakanga** [comment]
try
```
lego --email xxx --dns tencentcloud --domains xxx --dns.resolvers 114.114.114.114 run 
```

**Comment by hhs66317** [comment]
> try
> 
> ```
> lego --email xxx --dns tencentcloud --domains xxx --dns.resolvers 114.114.114.114 run 
> ```

```
lego --email xxxxxxxx@gmail.com --dns tencentcloud --domains xx.xxxx.com --dns.resolvers 114.114.114.114 run
2024/09/06 11:54:02 [INFO] [xx.xxxx.com] acme: Obtaining bundled SAN certificate
2024/09/06 11:54:03 [INFO] [xx.xxxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/111111111111
2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: Could not find solver for: tls-alpn-01
2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: Could not find solver for: http-01
2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: use dns-01 solver
2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: Preparing to solve DNS-01
2024/09/06 11:54:05 [INFO] [xx.xxxx.com] acme: Trying to solve DNS-01
2024/09/06 11:54:05 [INFO] [xx.xxxx.com] acme: Checking DNS record propagation. [nameservers=114.114.114.114:53]
2024/09/06 11:54:07 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/09/06 11:54:27 [INFO] [xx.xxxx.com] acme: Waiting for DNS record propagation.
2024/09/06 11:54:49 [INFO] [xx.xxxx.com] acme: Waiting for DNS record propagation.
2024/09/06 11:55:11 [INFO] [xx.xxxx.com] acme: Waiting for DNS record propagation.
2024/09/06 11:55:13 [INFO] [xx.xxxx.com] acme: Cleaning DNS-01 challenge
2024/09/06 11:55:15 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/111111111111
2024/09/06 11:55:15 Could not obtain certificates:
        error: one or more domains had a problem:
[xx.xxxx.com] propagation: time limit exceeded: last error: DNS call error: read udp 127.0.0.1:64054->127.8.0.3:53: i/o timeout [ns=f1g1ns1.dnspod.net.:53, question='_acme-challenge.xx.xxxx.com. IN  TXT']

```

**Comment by xeahsoon** [comment]
> > try
> > ```
> > lego --email xxx --dns tencentcloud --domains xxx --dns.resolvers 114.114.114.114 run 
> > ```
> 
> ```
> lego --email xxxxxxxx@gmail.com --dns tencentcloud --domains xx.xxxx.com --dns.resolvers 114.114.114.114 run
> 2024/09/06 11:54:02 [INFO] [xx.xxxx.com] acme: Obtaining bundled SAN certificate
> 2024/09/06 11:54:03 [INFO] [xx.xxxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/111111111111
> 2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: Could not find solver for: tls-alpn-01
> 2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: Could not find solver for: http-01
> 2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: use dns-01 solver
> 2024/09/06 11:54:03 [INFO] [xx.xxxx.com] acme: Preparing to solve DNS-01
> 2024/09/06 11:54:05 [INFO] [xx.xxxx.com] acme: Trying to solve DNS-01
> 2024/09/06 11:54:05 [INFO] [xx.xxxx.com] acme: Checking DNS record propagation. [nameservers=114.114.114.114:53]
> 2024/09/06 11:54:07 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
> 2024/09/06 11:54:27 [INFO] [xx.xxxx.com] acme: Waiting for DNS record propagation.
> 2024/09/06 11:54:49 [INFO] [xx.xxxx.com] acme: Waiting for DNS record propagation.
> 2024/09/06 11:55:11 [INFO] [xx.xxxx.com] acme: Waiting for DNS record propagation.
> 2024/09/06 11:55:13 [INFO] [xx.xxxx.com] acme: Cleaning DNS-01 challenge
> 2024/09/06 11:55:15 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/111111111111
> 2024/09/06 11:55:15 Could not obtain certificates:
>         error: one or more domains had a problem:
> [xx.xxxx.com] propagation: time limit exceeded: last error: DNS call error: read udp 127.0.0.1:64054->127.8.0.3:53: i/o timeout [ns=f1g1ns1.dnspod.net.:53, question='_acme-challenge.xx.xxxx.com. IN  TXT']
> ```

楼主这个有后续吗，我也碰到同样的问题

**Comment by ldez** [comment]
Hello,

You have a problem with your local nameserver, check your `/etc/resolv.conf` file.

**Comment by ldez** [comment]
Based on the logs:

> [pc.xxxxxxxx.top] propagation: time limit exceeded: last error: DNS call error: read udp 127.0.0.1:55015->127.8.0.3:53: i/o timeout [ns=f1g1ns1.dnspod.net.:53, question='_acme-challenge.pc.xxxxxxxx.top. IN  TXT']


> [xx.xxxx.com] propagation: time limit exceeded: last error: DNS call error: read udp 127.0.0.1:64054->127.8.0.3:53: i/o timeout [ns=f1g1ns1.dnspod.net.:53, question='_acme-challenge.xx.xxxx.com. IN  TXT']


There is a problem with authoritative nameservers (`f1g1ns1.dnspod.net`).

Since v4.19, there is an option (`--dns.propagation-disable-ans`) to skip this check.

```bash
lego --email xxx --dns tencentcloud --domains xxx --dns.propagation-disable-ans --dns.resolvers 114.114.114.114 run 
```

**Comment by hhs66317** [comment]
> 楼主这个有后续吗，我也碰到同样的问题
> 
> Translation: Is there any follow-up to this? I have the same problem.

并没有找到办法解决，过段时间，我再用新版本试试看

**Comment by hhs66317** [comment]
> Hello,
> 
> You have a problem with your local nameserver: check your `/etc/resolv.conf` file.

 The above problem, I encountered it in the Windows environment, not the Linux environment, my main working environment is Windows

**Comment by ldez** [comment]
If you are on Windows, lego fallback on Google DNS (`google-public-dns-a.google.com:53`, `google-public-dns-b.google.com:53`)

If you want to override this you must use `--dns.resolvers`.

So you can follow my previous comment: https://github.com/go-acme/lego/issues/2237#issuecomment-2402481708

**Comment by hhs66317** [comment]
> If you are on Windows, lego fallbacks on Google DNS (`google-public-dns-a.google.com:53`, `google-public-dns-b.google.com:53`)
> 
> If you want to override this, you must use `--dns.resolvers`.
> 
> So you can follow my previous comment: [#2237 (comment)](https://github.com/go-acme/lego/issues/2237#issuecomment-2402481708)

Wow, you're amazing! With this parameter you said, it really worked successfully, thank you so much!!

In a Windows environment, the certificate can be successfully generated using the following method:

`lego --email xxx --dns tencentcloud --domains xxx --dns.propagation-disable-ans --dns.resolvers 114.114.114.114 run`
