### ISSUE TITLE
Liquidweb documentation is wrong

### ISSUE THREAD

**Issue by DavidRueter** [go-acme/lego#2242]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Documentation for Liquidweb (DNS provider) has errors.

The correct environment variables have a prefix of "LIQUID_WEB" such as LIQUID_WEB_USERNAME

https://github.com/go-acme/lego/blob/master/docs/content/dns/zz_gen_liquidweb.md
https://go-acme.github.io/lego/dns/liquidweb/

### What did you see instead?

The documentation on Liquidweb environment variables show a prefix of "LWAPI" such as:  LWAPI_USERNAME

This is not correct.  The correct environment variables have a prefix of "LIQUID_WEB" such as LIQUID_WEB_USERNAME

### How do you use lego?

Binary

### Reproduction steps

I read the documentation, and tested the actual operation of the software.  Environment variables with a LIQUID_WEB prefix work.  Environment variables with a prefix of LWAPI do not work.

The original commit used LIQUID_WEB (see https://github.com/go-acme/lego/pull/951 )

This commit had discussion on the topic:  the prefix was to be changed to LWAPI but this change was omitted from the PR.  I suspect the error was introduced as  a result of the confusion:  https://github.com/go-acme/lego/pull/2031#issuecomment-1762962188

### Version of lego

```console
Not applicable;  bug is in documentation only.
```

### Logs

Not applicable;  bug is in documentation only.

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

The documentation is right: there are 2 env vars prefixes `LIQUID_WEB_` and `LWAPI_`.

We document only one prefix `LWAPI_` but both work.
