### ISSUE TITLE
Support for provider: mijn.host

### ISSUE THREAD

**Issue by shubhamku044** [go-acme/lego#2251]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://mijn.host/

### Link to the API documentation

https://mijn.host/api/doc/api-3563906

### Additional Notes

I have the API key and a domain associated with it, I will be writing the code I just need your help to add this DNS provider.

**Comment by shubhamku044** [comment]
Hey @ldez whatever support you need to add this provider, I am always here to help you. I just want to get started with this as soon as possible.

Thanks

**Comment by ldez** [comment]
Your 2 PRs (#2250, #2249) are off-topic: adding the provider to the readme is useless if there is no implementation, also the readme is generated.

Either you know how to write a provider and create a PR or you don't know how to do it and will test a PR if someone doing one.

Spamming this repository with invalid PRs is not respectful.

**Comment by shubhamku044** [comment]
I am sorry for that, also I was not aware that the README is auto generated. So, I created the draft PR, and I thought once everything will be done, I will mark it as a PR instead of draft pr.
