### ISSUE TITLE
GoDaddy API Limitations

### ISSUE THREAD

**Issue by kanwhoa** [go-acme/lego#2269]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

The GoDaddy DNS provider cleans up old record of type TXT with name _acme-challenge.

Note that I understand this is not a lego fault, it's a change with the API access allowed by GoDaddy. However, after some playing, I found that the APIs which could be used for ACME are still open.

For example, the following request is allowed to delete:

```
curl --verbose \
  -X DELETE \
  -H "Authorization: sso-key x:y" \
  -d "" \
  "https://api.godaddy.com/v1/domains/domain.tld/records/TXT/_acme-challenge.infra"
```

So, there's likely some API used which is disallowed by the new policies put in place by GoDaddy. However, there seems to be some workarounds. Btw, the TXT record creation works without an issue.

### What did you see instead?

The command line reported 
```
failed to get all TXT records: unexpected status code: [status code: 403] body: {"code":"ACCESS_DENIED","message":"Authenticated user is not allowed access"
```
### How do you use lego?

Binary

### Reproduction steps

1. Issue the command
```
GODADDY_API_KEY=x GODADDY_API_SECRET=y lego \
  --domains "subdomain.domain.tld" \
  --accept-tos --email "certificates@domain.tld" \
  --dns godaddy \
  --dns.resolvers "ns17.domaincontrol.com,ns18.domaincontrol.com" \
  --dns-timeout 600 \
  run
```

### Version of lego

```console
lego version 4.18.0 darwin/arm64
```

### Logs

<details>

```console
2024/09/10 14:19:22 [INFO] [subdomain.domain.tld] acme: Obtaining bundled SAN certificate
2024/09/10 14:19:23 [INFO] [subdomain.domain.tld] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/XXXXXXXXXXXXX
2024/09/10 14:19:23 [INFO] [subdomain.domain.tld] acme: Could not find solver for: tls-alpn-01
2024/09/10 14:19:23 [INFO] [subdomain.domain.tld] acme: Could not find solver for: http-01
2024/09/10 14:19:23 [INFO] [subdomain.domain.tld] acme: use dns-01 solver
2024/09/10 14:19:23 [INFO] [subdomain.domain.tld] acme: Preparing to solve DNS-01
2024/09/10 14:19:25 [INFO] [subdomain.domain.tld] acme: Trying to solve DNS-01
2024/09/10 14:19:25 [INFO] [subdomain.domain.tld] acme: Checking DNS record propagation. [nameservers=ns17.domaincontrol.com:53,ns18.domaincontrol.com:53]
2024/09/10 14:19:27 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2024/09/10 14:19:27 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:30 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:32 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:34 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:36 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:39 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:41 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:43 [INFO] [subdomain.domain.tld] acme: Waiting for DNS record propagation.
2024/09/10 14:19:50 [INFO] [subdomain.domain.tld] acme: Cleaning DNS-01 challenge
2024/09/10 14:19:51 [WARN] [subdomain.domain.tld] acme: cleaning up failed: godaddy: failed to get all TXT records: unexpected status code: [status code: 403] body: {"code":"ACCESS_DENIED","message":"Authenticated user is not allowed access"}
2024/09/10 14:19:51 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/XXXXXXXXXXXXX
2024/09/10 14:19:51 Could not obtain certificates:
        error: one or more domains had a problem:
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
FYI, your suggested endpoint is already the endpoint that lego uses.

But, this endpoint is not enough to handle the DNS challenge: the endpoint only allows handling all TXT records, which means that lego needs to get the existing TXT records else all TXT records (even those nonrelated to the ACME challenge) will be deleted.

**Comment by ldez** [comment]
You should consider replacing GoDaddy with a DNS provider with a better policy.

If you already own a domain in another DNS provider, you can use the [CNAME approach](https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname), like that you will be able to still use your GoDaddy domain. 

Sadly I have no other solution, the GoDaddy API policies are extremely bad.

**Comment by kanwhoa** [comment]
Hi,

I should have noted in my original, that the GET URL also appears to work without restriction:

```
curl --verbose \
  -X GET \
  -H "Authorization: sso-key x:y" \
  -d "" \
  "https://api.godaddy.com/v1/domains/domain.tld/records/TXT/_acme-challenge.infra"
```

This should allow getting all TXT record for a domain or subdomain. I'm not sure where the "Authenticated user is not allowed access" message is being generated from, the log line just before indicate that it is cleaning up. I'm not sure of the particular API being called at this point though.

```
2024/09/10 19:19:15 [INFO] [*.subdomain.domain.tld] acme: Cleaning DNS-01 challenge
2024/09/10 19:19:15 [WARN] [*.subdomain.domain.tld] acme: cleaning up failed: godaddy: failed to get all TXT records: unexpected status code: [status code: 403] body: {"code":"ACCESS_DENIED","message":"Authenticated user is not allowed access"}
```

**Comment by ldez** [comment]
Sorry, I mixed the 2 endpoints in my head but the problem is the same:

lego uses:
- GET `https://api.godaddy.com/v1/domains/example.com/records/TXT/_acme-challenge.example.com` to get all the TXT records.
- PUT `https://api.godaddy.com/v1/domains/example.com/records/TXT/_acme-challenge.example.com` to add/delete TXT records.

**Comment by ldez** [comment]
After re-checking the doc, there is another endpoint https://developer.godaddy.com/doc/endpoint/domains#/v1/recordAdd

But I guess the limitations are the same as the PUT endpoint.

**Comment by ldez** [comment]
The lego implementation for GoDaddy is basic:
- one call to get all TXT records: 
  - https://developer.godaddy.com/doc/endpoint/domains#/v1/recordGet
- one call to update the TXT records:
  - https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName
- one call to delete the TXT record:
  - https://developer.godaddy.com/doc/endpoint/domains#/v1/recordReplaceTypeName

It's the same call to add and "delete".

So nothing special.

**Comment by ldez** [comment]
GoDaddy limitations are extreme: one call can work but 2 calls in a row are not working.

Clearly, you should go away from this DNS provider or use the CNAME approach with another DNS provider.

**Comment by ldez** [comment]
Also the "present" and the "cleanup" use the exact same code, so it doesn't make sense to have a different behavior between them.

The only way to get an empty subdomain is to have the auth zone equal to effective FQDN, which is impossible.

**Comment by ldez** [comment]
Can you try https://github.com/go-acme/lego/pull/2270 ?

**Comment by kanwhoa** [comment]
Tested. There were some latent issues with the API. I've fixed and attached a diff. Sorry, was having trouble updating the PR.
[godaddyfix.diff.patch](https://github.com/user-attachments/files/16947205/godaddyfix.diff.patch)

**Comment by ldez** [comment]
Most of your patch was already inside the PR, so I just kept the effective diff.

d424d2d09d11b604b65da74db625e7a2d617509d
