### ISSUE TITLE
lego allows you to rename the requested certificate

### ISSUE THREAD

**Issue by aaro-n** [go-acme/lego#2271]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Docker image

### Detailed Description

lego allows you to rename the requested certificate instead of using the domain name to store the certificate file.
Example:
```
docker-compose run --rm lego --email xxx@gmail.com --dns alidns -domains tan123.plus,*.tan123.plus,211.xyz,*.211.xyz run
```
The requested certificate will be saved as `tan123.plus.crt` and `tan123.plus.key`, and I want to save the certificate as `letsencrypt.crt` and `letsencrypt.key`

**Comment by ldez** [comment]
Hello,

you can use the flag `--filename` but it is deprecated, if want more information: https://github.com/go-acme/lego/issues/838
