### ISSUE TITLE
Provide an option to verify propagation against a custom list of DNS-servers

### ISSUE THREAD

**Issue by Jonher937** [go-acme/lego#2276]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary and Traefik.

### Detailed Description

Hi, we've hit an issue using DNS-01 challenge with EAB and CNAME delegation with [EJBCA](https://www.ejbca.org/) as the CA, but this deployment scenario is probably going to be more common as ACME has started to be adopted in enterprise.

I have included a diagram to try and explain our interpretation of the current flow, and where we see an issue.

![lego](https://github.com/user-attachments/assets/fffd498c-00e7-4507-8757-34077cce81c3)

1. We issue a renewal request, all good so far
2. We create the TXT record with the challenge
3. LEGO uses our `--dns.resolvers` that points to the same DNS-server as the PKI will query for the challenge. These servers are used by lego to find the authoritative servers only as specified [here](https://github.com/go-acme/lego/blob/0da0942081a1666a73b4f2f3f35328e9ae28af0f/cmd/flags.go#L121-L123).
  It finds the authoritative servers and can successfully query to verify they serve the TXT record with the correct value.
4. LEGO gives the all clear to the PKI
5. PKI queries DNS against the company wide DNS-service. This company DNS-service has network communication to the authoritative DNS-servers over tcp/udp 53. Queries are cached and if forwarded.

So now to the problem:
* Step 5 we can see the PKI is NOT querying the authoritative DNS-server. This is by network security design.
* In Step 3 we would like to validate the same record as we added to the authoritative DNS-server has propagated to the DNS-servers used by the PKI before giving the "All good" message to the PKI.

Essentially we'd want something like this (behind a flag such as `--dns.propagation-servers` of `[]string` type) to specify what additional servers we'd want to append to the `checkAuthoritativeNss` function.

https://github.com/Jonher937/lego/blob/a152249a1a02146604936099d3bf1a9d13999280/challenge/dns01/precheck.go#L76-L88

Full commit can be found [here](https://github.com/go-acme/lego/compare/master...Jonher937:lego:verify-propagation-at-recursor) and acts as an example. I have not found a good way to pass down a flag this deep into the process, but this issue is created as a topic for discussing how and if this could be implemented.

In the end our issues comes down to the DNS topology/implementation and slow (60+ seconds) propagations to the company DNS-service which the PKI verifies against.

We have also tries with the newly added `--dns.propagation-wait` option and have successfully managed to obtain certificates if we tweak it high enough for the propagation to happen, but this might randomly fail if the zone update has not yet made it's way to the company DNS-service.

**Comment by ldez** [comment]
Hello,

you can already do that:
- `--dns.resolvers` allows defining the DNS used to check the propagation
- `--dns.disable-cp` allows to skip the "classic" authoritative NSs.

**Comment by Jonher937** [comment]
We have tried the disable-cp option: `By setting this flag to true, disables the need to await propagation of the TXT record to all authoritative name servers.`

Our problem is the reverse, the authoritative name servers replies correct and do so straight away. But the servers the PKI uses for validation are slow to serve the record.

What we need to do is either:
* Sleep for long enough before blindly telling the PKI the record has "propagated" using the `dns.propagation-wait` option and hope that it has propagated to the DNS-service used by the PKI to do the TXT lookup
* OR we need to verify using lego against the DNS-service's servers that the record has propagated rather than depending on a time.Duration which does not guarantee it's there

`--dns.resolvers` option documents it's only used to:
> Set the resolvers to use for performing (recursive) CNAME resolving and apex domain determination.
> For DNS-01 challenge verification, the authoritative DNS server is queried directly.
[source for the quote](https://github.com/go-acme/lego/blob/0da0942081a1666a73b4f2f3f35328e9ae28af0f/cmd/flags.go#L121-L123)

I tried using the options you suggested but it does not wait for any propagation at all, unless of course I use `--dns.propagation-wait` in addition to those values.
We need to verify the propagation has occured on the non-authoritative DNS-service before telling the PKI it's ready to do the DNS challenge.

**Comment by Jonher937** [comment]
Today we looked into why cert-manager has had more success and it looks like cert-manager has this option: [dns01-recursive-nameservers-only](https://github.com/cert-manager/cert-manager/blob/6d2f5e145ec54c0cb531cedabcfdcd1aad76fea3/cmd/controller/app/options/options.go#L158) documented [here](https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check)
> --dns01-recursive-nameservers-only Forces cert-manager to only use the recursive nameservers for verification. Enabling this option could cause the DNS01 self check to take longer due to caching performed by the recursive nameservers.

* https://github.com/cert-manager/cert-manager/blob/6d2f5e145ec54c0cb531cedabcfdcd1aad76fea3/cmd/controller/app/controller.go#L332
* https://github.com/cert-manager/cert-manager/blob/master/pkg/issuer/acme/dns/dns.go#L120-L121 here `s.Context.DNS01CheckAuthoritative` would be false, which means util.PreCheckDNS will use the user-specified nameservers instead of the Authoritative, just like we would want with LEGO.

**Comment by danragnar** [comment]
Makes sense to me to actually verify the TXT record on the provided recursive nameserver to minimize errors and load towards the PKI. Feels like a neater solution than the recently implemented `--dns.propagation-wait` flag. 

I guess it's not needed in a regular setup (even with split-horizon DNS) if the PKI queries the authoritative nameserver, but otherwise there's high risk that the PKI would fail the challenge due to the zone not having refreshed on the recursor when the ACME client claims it's ready for challenge verification.

**Comment by ldez** [comment]
> `--dns.resolvers` option documents it's only used to:
> > Set the resolvers to use for performing (recursive) CNAME resolving and apex domain determination.
> > For DNS-01 challenge verification, the authoritative DNS server is queried directly.
[source for the quote](https://github.com/go-acme/lego/blob/0da0942081a1666a73b4f2f3f35328e9ae28af0f/cmd/flags.go#L121-L123)

This option is not only used for zone detection and CNAME resolving, it's also used during propagation checks.

The NS from `--dns-resolvers` are used first, before authoritative NS, but as a difference with authoritative NS, lego doesn't browse all the resolvers and continues the process if at least one resolver returns a successful answer.

**Comment by ldez** [comment]
I thought about this issue, and I found 2 solutions:
- add an option that only sets recursive NSs
- add an option that checks all the recursive NSs instead of one

The second option is better because it allows checking all the recursive NSs and all the authoritative NSs.

With this option lego can have several interesting combinations:
- default: check only one recursive NSs and all the authoritative NSs
- `dns.disable-propagation-ans` => check only one recursive NSs
- `dns.propagation-rns` => check all the recursive NSs and all the authoritative NSs
- `dns.propagation-rns` + `dns.disable-propagation-ans` (aka `dns.disable-cp`) => check only recursive NSs

This can be changed in the future (inside a major version) to `dns.disable-propagation-ans` and `dns.disable-propagation-rns` and by default checking all the recursive NSs and all the authoritative NSs.
IMHO, the migration path will be easier with this approach.

**Comment by ldez** [comment]
I opened PR #2284

**Comment by Jonher937** [comment]
Hi, I have reviewed your PR (from the perspective of this issue) and even with the above mentioned changes it's not enough to solve a certificate in our scenario, or rather there is no change from current master branch's available flags.

With the PR it still expects the propagation has already happened, it does not wait to verify propagation unless `--dns.propagation-wait` is used, which again is just a time.Sleep() and does not actually validate the value of the record and might fail.
This leads to failed certificate requests as lego returns to the PKI before the record has propagated.

It seems like @danragnar is on the same track as I, verifying the propagation value (maybe some retry logic inside/around [checkAuthoritativeNss](https://github.com/go-acme/lego/blob/d2898e170653a5d77bd2e98e633be082f6f92052/challenge/dns01/precheck.go#L78-L110)?) to actually wait for the TXT record to propagate and to verify it has the expected value.

**Comment by ldez** [comment]
sorry but I implemented exactly what you asked for:

>  which means util.PreCheckDNS will use the user-specified nameservers instead of the Authoritative, just like we would want with LEGO. 

`dns.propagation-rns` + `dns.disable-propagation-ans` (aka `dns.disable-cp`)- `--dns.resolvers` => check only recursive NSs (aka `resolvers)

**Comment by Jonher937** [comment]
Hi, sorry but that is just one part of the GitHub issue where I've tried to explain the full scenario and to give comparison to a project that is very similar to this one. And it seems I was mistaken there would be some sort of retry attempts looking up the TXT record which could have confused a bit as well. But instead it instantly fails using the `--dns.resolvers --dns.propagation-rns --dns.propagation-disable-ans` flags on your branch, just like it would before your PR/branch.

It is true that we need to use the recursors to validate the request, so those flags are useful. But it's also true that we need to wait for it to propagate to recursors before moving to the PKI to verify.

The text you quoted is specifically from when we compared to cert-manager. I have mentioned quite a few times that we also need to wait for the propagatiaon to happen before we can move on to the PKI.
The opttions you reference above check the resolvers straight away and fails due to the record not having propagated yet.

Other than testing our luck with `--dns.propagation-wait` is there a way to accomplish this?

> In Step 3 we would like to validate the same record as we added to the authoritative DNS-server has propagated to the DNS-servers used by the PKI before giving the "All good" message to the PKI.
---
> I tried using the options you suggested but it does not wait for any propagation at all, unless of course I use --dns.propagation-wait in addition to those values.
> We need to verify the propagation has occured on the non-authoritative DNS-service before telling the PKI it's ready to do the DNS validation. If we don't the PKI will check with DNS-service which does not know about this TXT value and it will fail the issuing of the certificate.

**Comment by ldez** [comment]
:thinking: the propagation timeout can be configured by providers (`XXX_PROPAGATION_TIMEOUT` and `XXX_POLLING_INTERVAL`, so you can already extend it.
The `NXDOMAIN` is not a blocking error during the propagation check.

Maybe I miss something :thinking:

**Comment by ldez** [comment]
Can you provide the full logs related to your trial with my PR?

**Comment by Jonher937** [comment]
I was looking into providing you logs today and as it was instantly failing after looking at `authoritative` servers I added some more log and found the culprit. I left a comment in your PR.
Once you've made the necessary changes I'll re-test your branch and we should be in a working state.

Current state of the branch would check on authoritative (which had the record) and then return to PKI straight away without waiting for propagation.
PR comment should set the correct variable to true and the process waits for propagation from the recursor servers.

**Comment by Jonher937** [comment]
Your latest commit on the branch works on my end :rocket: 
Thank you!

**Comment by ldez** [comment]
I hope you enjoyed my work, please consider donating or asking your company to do so.
This will be appreciated, thank you :heart:

https://github.com/sponsors/ldez
