### ISSUE TITLE
Support for provider: Volcano Engine

### ISSUE THREAD

**Issue by liuruibin** [go-acme/lego#2279]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://www.volcengine.com/docs/6420/192724

### Link to the API documentation

https://www.volcengine.com/docs/6420/192724

### Additional Notes

Does TrafficRoute DNS have a support plan?

**Comment by ldez** [comment]
Hello,

> https://www.volcengine.com/docs/6420/192724

This is a link to the documentation of a UI.

You provided no link to the API, so guess there is no API, and no link to the DNS provider itself.

> - [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
> - [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

You are neither able to create nor test a PR, and as we don't have a Volcengine account, it will be difficult to do something.

---

I found this SDK: https://github.com/volcengine/volc-sdk-golang

Based on the information from this issue, it will be difficult to work on this.

We need someone who can either create a PR or test a PR.

**Comment by ldez** [comment]
@liuruibin can you try PR #2282?

Ask me if you need help to test it.

**Comment by ldez** [comment]
@liuruibin can you answer, please?

Creating an issue is the first step, but I need a user to test the implementation.
I can help you to learn how to test the PR.

**Comment by ldez** [comment]
@liuruibin any news?

**Comment by liuruibin** [comment]
> @liuruibin any news?

Thanks, I will test this feature in [1Panel](https://github.com/1Panel-dev/1Panel)

**Comment by ldez** [comment]
@liuruibin any news?

**Comment by liuruibin** [comment]
Sorry, China is on holiday from October 1st to 7th.
![image](https://github.com/user-attachments/assets/953a5b68-fbe8-44af-bdc9-f14b9669efc5)

**Comment by liuruibin** [comment]
<img width="1782" alt="image" src="https://github.com/user-attachments/assets/b3a0bdca-2a31-490b-a774-adfa6d43f096">

new issue
