### ISSUE TITLE
namesilo: challenges are deleted to early when multiple challenges are needed.

### ISSUE THREAD

**Issue by JCLengeling** [go-acme/lego#2286]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I am using Traefik, which utilizes Lego, to manage certificates with NameSilo. I am trying to obtain a certificate for my domain, as well as for any subdomains (a so-called wildcard certificate). As a result, two challenges need to be passed, which should work (and does work for me with other providers, but not with NameSilo).

### What did you see instead?

As shown in the table from NameSilo, two challenges are created, but one of them is removed immediately.
![image](https://github.com/user-attachments/assets/55f1fa6b-695a-44e6-b07e-81b941f7655f)
The timestamps in the table are not very precise, but the sequence of events is as follows: challenge 1 is created, then challenge 1 is deleted, challenge 2 is created, some time passes until challenge 2 is successful, and then challenge 2 is deleted.

The expected behavior, however, would be for challenge 1 to remain and not be deleted immediately when challenge 2 is created.

### How do you use lego?

Through Traefik

### Reproduction steps

I'm not entirely sure, but based on my understanding of the Go code [here](https://github.com/go-acme/lego/blob/master/providers/dns/namesilo/namesilo.go), it appears that the Present function first calls CleanUp to remove any existing TXT records before adding a new one. As a result, when challenge 2 is created, challenge 1 gets deleted.

### Version of lego

```console
NA, using Traefik
```

### Logs

<details>

```console
# paste output here
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment]
Hello,

> ### Version of lego
> NA, using Traefik

You need to, at least, provide the Traefik version.

**Comment by ldez** [comment]
> I'm not entirely sure, but based on my understanding of the Go code [here](https://github.com/go-acme/lego/blob/master/providers/dns/namesilo/namesilo.go), it appears that the Present function first calls CleanUp to remove any existing TXT records before adding a new one. As a result, when challenge 2 is created, challenge 1 gets deleted.

It doesn't work as you think.

The challenges are handled in "parallel":
- all the `Present` are done first. (created all TXT records)
- the challenge checks are happening on all domain (sequentially)
- all the `CleanUp` are done. (deleted all TXT records)

-

**Comment by ldez** [comment]
So I need Traefik version, logs, and potentially the configuration, to be able to diagnose.

**Comment by ldez** [comment]
Just checked the code, and there is a specific implementation related to:
- https://github.com/go-acme/lego/issues/1831
- https://github.com/go-acme/lego/pull/1833

**Comment by JCLengeling** [comment]
It's traefik:latest docker image; which should be [v3.1.4](https://github.com/traefik/traefik/releases/tag/v3.1.4).

I only have traefik logs, this is the latest logged error logged: 
`traefik               | 2024-09-29T18:41:57.952726361Z 2024-09-29T18:41:57Z ERR github.com/traefik/traefik/v3/pkg/provider/acme/provider.go:469 > Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [adcp.cloud *.adcp.cloud]: error: one or more domains had a problem:\n[*.adcp.cloud] propagation: time limit exceeded: last error: NS ns3.dnsowl.com. did not return the expected TXT record [fqdn: _acme-challenge.adcp.cloud., value: _y43Zgf0GLsE0jNcgaZh_SFULGWeTT6vPoG3vBXT8uU]: O3N7XtswAxz79YICwtKUahFJse2mHzjaeF1f8o0vK14\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["adcp.cloud","*.adcp.cloud"] providerName=mydnsresolver.acme routerName=solid@docker rule=Host("adcp.cloud")`

One of the challenges is working, the other isn't. As can be seen on the screenshotted table one of the challenges is also directly removed, the other one keeps being there. I have been using these enviornment variables besides the API key.
`
      - NAMESILO_PROPAGATION_TIMEOUT=3600
      - NAMESILO_POLLING_INTERVAL=120
      - NAMESILO_TTL=3600
`

**Comment by JCLengeling** [comment]
It's traefik:latest docker image; which should be [v3.1.4](https://github.com/traefik/traefik/releases/tag/v3.1.4).

I only have traefik logs, this is the latest logged error logged: 
`traefik               | 2024-09-29T18:41:57.952726361Z 2024-09-29T18:41:57Z ERR github.com/traefik/traefik/v3/pkg/provider/acme/provider.go:469 > Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [adcp.cloud *.adcp.cloud]: error: one or more domains had a problem:\n[*.adcp.cloud] propagation: time limit exceeded: last error: NS ns3.dnsowl.com. did not return the expected TXT record [fqdn: _acme-challenge.adcp.cloud., value: _y43Zgf0GLsE0jNcgaZh_SFULGWeTT6vPoG3vBXT8uU]: O3N7XtswAxz79YICwtKUahFJse2mHzjaeF1f8o0vK14\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["adcp.cloud","*.adcp.cloud"] providerName=mydnsresolver.acme routerName=solid@docker rule=Host("adcp.cloud")`

One of the challenges is working, the other isn't. As can be seen on the screenshotted table one of the challenges is also directly removed, the other one keeps being there. Before the error I posted I get following logs every two minuts 
`
traefik               | 2024-09-29T17:47:47.308676125Z 2024-09-29T17:47:47Z DBG github.com/go-acme/lego/v4@v4.18.0/log/logger.go:48 > [INFO] [*.adcp.cloud] acme: Waiting for DNS record propagation. lib=lego
traefik               | 2024-09-29T17:49:47.344968789Z 2024-09-29T17:49:47Z DBG github.com/go-acme/lego/v4@v4.18.0/log/logger.go:48 > [INFO] [*.adcp.cloud] acme: Waiting for DNS record propagation. lib=lego
traefik               | 2024-09-29T17:51:47.380781227Z 2024-09-29T17:51:47Z DBG github.com/go-acme/lego/v4@v4.18.0/log/logger.go:48 > [INFO] [*.adcp.cloud] acme: Waiting for DNS record propagation. lib=lego
traefik               | 2024-09-29T17:53:47.389182582Z 2024-09-29T17:53:47Z DBG github.com/go-acme/lego/v4@v4.18.0/log/logger.go:48 > [INFO] [*.adcp.cloud] acme: Waiting for DNS record propagation. lib=lego
traefik               | 2024-09-29T17:55:47.399383488Z 2024-09-29T17:55:47Z DBG github.com/go-acme/lego/v4@v4.18.0/log/logger.go:48 > [INFO] [*.adcp.cloud] acme: Waiting for DNS record propagation. lib=lego
traefik               | 2024-09-29T17:57:47.410273092Z 2024-09-29T17:57:47Z DBG github.com/go-acme/lego/v4@v4.18.0/log/logger.go:48 > [INFO] [*.adcp.cloud] acme: Waiting for DNS record propagation. lib=lego
`
Which is the result of my enviornment:
`
      - NAMESILO_PROPAGATION_TIMEOUT=3600
      - NAMESILO_POLLING_INTERVAL=120
      - NAMESILO_TTL=3600
`



> > I'm not entirely sure, but based on my understanding of the Go code [here](https://github.com/go-acme/lego/blob/master/providers/dns/namesilo/namesilo.go), it appears that the Present function first calls CleanUp to remove any existing TXT records before adding a new one. As a result, when challenge 2 is created, challenge 1 gets deleted.
> 
> It doesn't work as you think.
> 
> The challenges are handled in "parallel":
> 
>     * all the `Present` are done first. (creates all TXT records)
> 
>     * the challenge checks are happening on all domains (sequentially)
> 
>     * all the `CleanUp` are done. (deletes all TXT records)

I am not sure what the paramenters of CleanUp are, but could it be that there is a problem with the wildcard? So basically *.domain.com and domain.com are seen as identical?

**Comment by ldez** [comment]
I was suspicious about the PR that added this behavior: https://github.com/go-acme/lego/pull/1833#issuecomment-1418258556

And I think I was right, I fix that.
