### ISSUE TITLE
volcengine: no host in request URL

### ISSUE THREAD

**Issue by liuruibin** [go-acme/lego#2307]
<img width="1782" alt="image" src="https://github.com/user-attachments/assets/b3a0bdca-2a31-490b-a774-adfa6d43f096">

<details>

my code
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/f59e46af-0d1c-42e1-afc8-a16214819dd9">

https://github.com/1Panel-dev/1Panel/blob/f47f7c73613563a986607bfeb87077057b7d004a/backend/utils/ssl/client.go#L109

</details>

**Comment by ldez** [comment]
Can you make a sentence to explain your problem?
