### ISSUE TITLE
Support for provider: regfish

### ISSUE THREAD

**Issue by amallek** [go-acme/lego#2319]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://regfish.de

### Link to the API documentation

https://regfish.readme.io

### Additional Notes

I would love it if you could include [regfish](https://regfish.de) in the project. [A Go library is already available](https://github.com/regfish/regfish-dnsapi-go)

**Comment by ldez** [comment]
Hello @amallek,

Do you plan to create a PR?

If yes, do you need help?
If not, I can start to work on it.

---

_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

**Comment by ldez** [comment]
Do you mean you will create a PR or would you like me to make one?
