### ISSUE TITLE
rfc2136: add support for a new environment variable `RFC2136_TSIG_FILE`

### ISSUE THREAD

**Issue by datafoo** [go-acme/lego#2329]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

For the DNS provider [rfc2136](https://go-acme.github.io/lego/dns/rfc2136/index.html), rather that having to parse a key ourselves to extract the key name (i.e. `RFC2136_TSIG_KEY`), algorithm (i.e. `RFC2136_TSIG_ALGORITHM`) and secret (i.e. `RFC2136_TSIG_SECRET`), would it be possible to provide a new environment variable such as `RFC2136_TSIG_FILE` which would be the path to the key file generated by `tsig-keygen`?

This  way, lego would parse the file itself.

**Comment by ldez** [comment]
I hope you enjoyed my work, please consider donating or asking your company to do so.
This will be appreciated, thank you :heart:

https://github.com/sponsors/ldez
