### ISSUE TITLE
CHANGELOG is missing links from versions 0.4.0 and up

### ISSUE THREAD

**Issue by datafoo** [go-acme/lego#2342]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

I expected to see a hyperlink for all release versions in `CHANGELOG.md` which are surrounded with square brackets. It stopped at version `0.4.0`.

### What did you see instead?

Release versions in `CHANGELOG.md` from `0.4.0` are missing a corresponding link.

### How do you use lego?

Library

### Reproduction steps

Observe the `CHANGELOG.md`.

### Version of lego

```console
Any
```

### Logs

Not relevant

**Comment by ldez** [comment]
Hello,

the link at the end of the changelog was just a mistake, so I removed them.

**Comment by ldez** [comment]
I modified the changelog style #2346

But note that square brackets were just used as decoration and not as links (Markdown allows that)
