### ISSUE TITLE
Allow renew to soft fail on valid certificates

### ISSUE THREAD

**Issue by m1cr0man** [go-acme/lego#2367]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

When renewing certificates with lego, it will attempt to establish a client connection with the CA early in the process, before checking the certificate's expiration date. If a problem occurs at this stage (be it a networking or upstream service issue), lego will exit (returncode 1) prematurely without providing an indication that the certificate is still valid.

In most use cases, it is acceptable for the renew command to soft fail if the certificate is valid. A client with the CA is only required in the first place to check the ARI status. This is seldom a trigger for renewal in practice, whereas a networking or configuration failure can more frequently trip up automated renewal processes.

Some previous tickets of note:

- #1546 requests that the client is created after checking the expiry date, but perhaps forgets about the ARI checking.
- #1280 stems from this NixOS issue (https://github.com/NixOS/nixpkgs/issues/85794#issuecomment-721408110), which generally upsets systems as the systemd-based renewal service will fail unexpectedly which in turn can stop web servers and other dependent services from starting. Currently, NixOS relies on custom bash scripting to check the renewal date, which we would are [eager to remove](https://github.com/m1cr0man/nixpkgs/commit/53846b07f5037e854993366beab3e0a618d1fd68).

For the sake of this feature request, all that I really require is some indication that the certificate is still valid even when renewal fails. By changing the return code of lego depending on local cert validity, it can be left to the user's discretion on how to deal with the scenario. I attempted to implement this in #2366, which was closed. I agree that this was a crude implementation, but I could not decide on a less egregious solution myself.

I hope someone has the energy to work on this in lego. Although the NixOS solution is holding for now, the use of other software to check validity when lego fails is less than ideal.

Perhaps it would help to know I have created a modified version of the NixOS ACME test suite to validate #2366, which if a new implementation is created can be used to perform an integration test. You will have to fork + edit the last commit on the branch to update the lego package to include your own changes. Run it with this command:

`nix run github:$USER/nixpkgs/lego-offline-renewal-test#nixosTests.acme`

**Comment by ldez** [comment]
:thinking: I think I will reduce the possibility of a failure of the client creation.

**Comment by ldez** [comment]
I think a retryable client should provide more resilience than the classic HTTP client.

https://github.com/go-acme/lego/pull/2368

**Comment by ldez** [comment]
:thinking: do you really want an offline renew? or is this just a test example?

**Comment by m1cr0man** [comment]
The offline renewal, or more specifically, checking cert expiration date, is really useful for error handling over long periods of time. I would even settle for a command which returns the cert remaining days explicitly, or something structured output from the renew command.
