### ISSUE TITLE
infomaniak: does not create TXT record, so fails to renew certificates

### ISSUE THREAD

**Issue by ahankinson** [go-acme/lego#2370]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

The Infomaniak DNS provider no longer seems to work with their API. I have experienced this with several of the domains hosted with them.

The issue seems to be that, even though I have set up the appropriate permissions in their API token manager (`domain, domain:read, domain:write, dns:read, dns:write`) the plugin does not seem to automatically create the TXT record as it should.

@L3o-pold was the initial creator of the integration and supports it, so I will tag him.

### What did you see instead?

When running the command given, with a working token (I checked it with cURL) it will never renew the certificate.

```
$ INFOMANIAK_ACCESS_TOKEN=****************** /usr/local/bin/lego --accept-tos --dns.propagation-disable-ans --dns infomaniak --domains sub.domain.io --email security@domain --path /etc/nginx/ssl renew --renew-hook="systemctl restart nginx"
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: renewalInfo endpoint indicates that renewal is needed
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: Trying renewal with 485 hours remaining
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: Obtaining bundled SAN certificate
2024/12/02 08:10:33 [INFO] [linked.rism.io] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/1463112246/438693874647
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: Could not find solver for: tls-alpn-01
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: Could not find solver for: http-01
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: use dns-01 solver
2024/12/02 08:10:33 [INFO] [linked.rism.io] acme: Preparing to solve DNS-01
2024/12/02 08:10:34 [INFO] domain "_acme-challenge.sub.domain.io" not found, trying with "sub.domain.io"
2024/12/02 08:10:34 [INFO] domain "linked.rism.io" not found, trying with "domain.io"
2024/12/02 08:10:36 [INFO] [linked.rism.io] acme: Trying to solve DNS-01
2024/12/02 08:10:36 [INFO] [linked.rism.io] acme: Checking DNS record propagation. [nameservers=127.0.0.53:53]
2024/12/02 08:10:38 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/12/02 08:10:45 [INFO] [linked.rism.io] acme: Cleaning DNS-01 challenge
2024/12/02 08:10:46 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz/1463112246/438693874647
2024/12/02 08:10:46 error: one or more domains had a problem:
[linked.rism.io] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.sub.domain.io - check that a DNS record exists for this domain
```

### How do you use lego?

Binary

### Reproduction steps

1. Have a domain hosted by Infomaniak
2. Create a new API token with `domain:read, domain:write, dns:read, dns:write` privileges
3. run the lego command with the API token, and it will fail to create the TXT record

### Version of lego

```console
lego version 4.20.4 linux/amd64
```

### Logs

<details>

```console
# paste output here
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by L3o-pold** [comment]
Can you try with a token having all scopes?

**Comment by ldez** [comment]
>  DNS problem: NXDOMAIN looking up TXT

I think the problem is just a propagation issue, not related to API.

**Comment by ahankinson** [comment]
Ah, that seems to work?

**Comment by ldez** [comment]
I think the scope `product:read` is needed.

**Comment by L3o-pold** [comment]
If I remember well the scope `products` is needed yes. I'll confirm that and fix the documentation if needed.

**Comment by ahankinson** [comment]
I can try and confirm this too.

**Comment by ldez** [comment]
I don't think that changing the TTL will fix the problem.
If it's a propagation issue, the en var `INFOMANIAK_PROPAGATION_TIMEOUT` will have more impact.

**Comment by L3o-pold** [comment]
> Hm. I don't see a product:read scope?

no it should not be needed

> I don't think that changing the TTL will fix the problem.

no I think it's an API validation issue.

please try settings a default TTL to 300 to check.

**Comment by ldez** [comment]
> no I think it's an API validation issue.

I don't think so, NXDOMAIN error is, in 90% of the cases, related to a propagation issue.
So you can try `INFOMANIAK_PROPAGATION_TIMEOUT=120` `INFOMANIAK_POLLING_INTERVAL=20`

**Comment by ahankinson** [comment]
I was able to get a renewal with `INFOMANIAK_PROPAGATION_TIMEOUT=120 INFOMANIAK_POLLING_INTERVAL=20` on a certificate that had previously failed, even with a token with all scopes. 

I will try to find another domain and see if a token with limited scopes works with that as well?

**Comment by L3o-pold** [comment]
> Do you remember why you set the default TTL to this huge 7200?

no but 120 TTL is not yet supported, 300 is

**Comment by ldez** [comment]
> no but 120 TTL is not yet supported, 300 is 

Ok but this is not the question :smile: 
Why 7200?

**Comment by L3o-pold** [comment]
it's the no part in the answer, I don't remember.

**Comment by ldez** [comment]
ok, depending on the @ahankinson feedback, the default propagation timeout can be changed.

**Comment by ahankinson** [comment]
If I add `INFOMANIAK_PROPAGATION_TIMEOUT=120 INFOMANIAK_POLLING_INTERVAL=20` to a request with a token with limited scopes (`domain, domain:read, domain:write, dns:read, dns:write`) it seems to work OK.

If I leave off the timeouts and polling intervals, the same token fails with:

`acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.domain.io - check that a DNS record exists for this domain`

So it seems to be a problem with the timeouts?

**Comment by ldez** [comment]
ok thank you :+1: we will adjust the default timeout.

**Comment by ahankinson** [comment]
(A side note that I also filed a support issue with Infomaniak earlier, so sorry if there's some duplicate confusion)

**Comment by ldez** [comment]
A default TTL of 120 is not a requirement, but 7200 is too big IMHO.

I changed the TTL to 300 and the propagation timeout to 120 (2 minutes)

**Comment by ldez** [comment]
thank you @ahankinson for your report, and thank you @L3o-pold for your reactivity :+1:
