### ISSUE TITLE
RFC2136 updates needs trailing dot in algorithm names

### ISSUE THREAD

**Issue by thusoy** [go-acme/lego#329]
To get the RFC2136 provider working with HMAC-SHA256 you currently have to specify the `RFC2136_TSIG_ALGORITHM` env var as `hmac-256.` (notice trailing dot). This is not documented anywhere (I figured out by reading [this](https://github.com/miekg/dns/blob/db96a2b759cdef4f11a34506a42eb8d1290c598e/tsig.go#L22)), and seems like a weird API to export.

How about adding an explicit map between the algorithms supported and the constants from the dns package? Supported algorithms should also preferably be listed somewhere, either in the help output or when encountering a invalid value. Currently the only output when trying an invalid value is `Error presenting token: DNS update failed: dns: bad key algorithm`, which doesn't really help resolve the problem.

**Comment by prometheanfire** [comment]
this has been open since 2016, good sign

**Comment by pnbecker** [comment]
I got the following error message:

> "Unable to obtain ACME certificate for domains \"example.org\" : unable to generate a certificate for the domains [example.org]: error: one or more domains had a problem:\n[example.org] [example.org] acme: error presenting token: rfc2136: failed to insert: DNS update failed: dns: domain must be fully qualified\n" providerName=mydnschallenge.acme

I can resolve it by adding a dot at the end of RFC2136_TSIG_ALGORITHM. Thank you @thusoy, you made my day!

**Comment by ldez** [comment]
Closed by #1259
