### ISSUE TITLE
Provider gcloud always picks highest-level zone to create challenge TXT record in

### ISSUE THREAD

**Issue by ryan-mf** [go-acme/lego#352]
I'm attempting to use the gcloud provider in lego to automate creation of the DNS challenge response during SSL certificate request with Letsencrypt. In my case, each 'environment' has it's own subdomain-based zone, e.g.:
domain.com - parent
dev.domain.com - Dev Env
stage.domain.com - Stage Env

Whenever I create a per-env subdomain in GCE, I glue resolution to it by dropping NS records for that subdomain into my parent domain. This allows an entire environment to have an atomic DNS zone that can't impact other environments (like production!).

However, even if I specify "GCE_DOMAIN" as the actual subdomain (ie, dev.domain.com) I want the record created in (e.g., _acme-challenge.blah.dev.domain.com), lego's code still discovers only the parent domain and creates the TXT challenge response record there. This doesn't work because the parent zone already is forwarding queries for that subdomain to that subdomain's zone, so we get a resolution failure on the TXT record as a result which prevents the cert from being issued.

Can you fix the gcloud provider so it finds the correct subdomain requested? Thanks!

**Comment by alexandrezia** [comment]
I'm having this exact issue with route53 provider.
Don't know it the code responsible for this is located in providers or in core.

**Comment by dchenk** [comment]
I've noticed this issue too.

**Comment by mholt** [comment]
Pull requests welcome. :) I don't think any of the main collaborators use Google Cloud so community fix would be better.

**Comment by lawliet89** [comment]
Looking at the [source code](https://github.com/go-acme/lego/blob/master/providers/dns/gcloud/googlecloud.go) for the GCP provider, this is what's happening:

- `GCE_DOMAIN` environment variable is not used at all
- `lego` [finds](https://github.com/go-acme/lego/blob/3684cc738d370bce685da7a80744c6cb8ffaef4f/providers/dns/gcloud/googlecloud.go#L292) the DNS name of the hosted zone by ["searching upwards"](https://github.com/go-acme/lego/blob/3edb75872df36444f95c25f88c6df325de89be11/challenge/dns01/nameserver.go#L101) towards the TLD for the first FQDN with `SOA` records. The first one it finds will be the DNS name of the hosted zone it uses.

It seems like this can be fixed (at least for Google Cloud) by starting the search from ` _acme-challenge.blah.dev.domain.com` when trying to solve the DNS challenge for `blah.dev.domain.com` instead.

Not sure if this is a breaking change or not.

**Comment by martintoreilly** [comment]
Hi. I'm not sure if people are still having issues with delegated zones for subdomains, but I've just run a successful DNS-01 challenge against a subdomain delegated to Google Cloud DNS from a parent DNS zone hosted at another provider. I used the `goacme/lego:v4.2.0-arm.v8` docker image via https://github.com/kchristensen/udm-le.

My setup is:
- I have `NS` records in the DNS zone for `domain.com` to delegate the `sub` subdomain to its own Google Cloud DNS zone
- I have an `A` record for `host` in the Google hosted DNS zone for `sub.domain.com`
- I request a certificate for `host.sub.domain.com` (in my case by setting a variable in the config file for `udm-le`, which I think exposes this via a `CERT_HOSTS` environment variable when the  `goacme/lego:v4.2.0-arm.v8` docker image is run by podman).
