### ISSUE TITLE
http and tls port binding flags not working?

### ISSUE THREAD

**Issue by vendion** [go-acme/lego#387]
Running FreeBSD 10.3 with multiple jails i'm trying to use the `http` and `tls` flags to have `Lego` answer the challenge on ports other than 80 and 443 (those ports get redirected to a different jail due to firewall rules).

Running the command `lego --email="..." --domains="..." --http=:8080 --tls=:8081 run` I would expect lego to bind to port 8080 and 8081, but it seems to still try to bind to the standard ports, thus the Let's encrypt server is hitting Nginx running in my other Jail instead of lego on the expected jail.

Full output:
```
lego --email="..." --domains="foo.example.com" --http=:8080 --tls=:8081 run
2017/04/28 00:14:16 [INFO][foo.example.com] acme: Obtaining bundled SAN certificate
2017/04/28 00:14:16 [INFO][foo.example.com] acme: Trying to solve HTTP-01
2017/04/28 00:14:18 [foo.example.com] Could not obtain certificates
        acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://foo.example.com/.well-known/acme-challenge/8P3UE9CAR-WYLFqCitjFeOqu5V5Z7UpoZsvQeSVCVR0: "<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>"
Error Detail:
        Validation for foo.example.com:80
        Resolved to:
                xxx.xxx.xx.xxx
                xxx.xxx.xx.xxx
        Used: xxx.xxx.xx.xxx

        Validation for example.com:443
        Resolved to:
                xxx.xxx.xx.xxx
                xxx.xxx.xx.xxx
        Used: xxx.xxx.xx.xxx
```

**Comment by xenolf** [comment]
This is not how the alternate ports work. Using an alternate port merely allows you to use lego with an already running web server. Let's Encrypt will always use port 80 for HTTP-01 and 443 for TLS-01 respectively - there is no way to change that.

**Comment by vendion** [comment]
If that is the case how does it work if the web server that binds to port 80/443 doesn't know what to do with the request for `/.well-known/acme-challenge/...`?

If what I'm trying to do is impossible then I'll just generate the cert on the other Jail.

**Comment by mholt** [comment]
@vendion You will have to proxy the HTTP request (for the HTTP challenge) or the TLS handshake (for the TLS-SNI challenge) somehow. Your web server should be able to do that (hint, shameless plug: Caddy can do it) or your OS can proxy the ports entirely.

**Comment by vendion** [comment]
@mholt I already have requests being proxied by my firewall, I have three jails (FreeBSD virtualization/container engine) on the host I have the firewall proxying all requests on port 80 and 443 to one Jail that runs multiple sites and mail related ports (transit, imap, pop3, etc) along with 8080 and 8081 to another jail.  Those last two ports were open mainly to try and generate SSL/TLS certs to use for postfix/dovecot.  The third jail is unrelated to this matter.
