### ISSUE TITLE
DNS based ACME challenge returns 0 when time limit for propagation is exceeded. 

### ISSUE THREAD

**Issue by samnazarko** [go-acme/lego#411]
I have a cronjob to renew a few certificates. I am using the DNS based ACME challenge. The first certificate renewal always succeeds and does so promptly. However for domains after this, things seem to slow down. 

I've noticed that if the record doesn't propagate in time, then a failure is noted, but the exit code is still 0. 

```
2017/07/18 18:58:39 [INFO][paste.osmc.tv] acme: Could not find solver for: http-01
2017/07/18 18:58:39 [INFO][paste.osmc.tv] acme: Could not find solver for: tls-sni-01
2017/07/18 18:58:39 [INFO][paste.osmc.tv] acme: Trying to solve DNS-01
2017/07/18 18:58:43 [INFO][paste.osmc.tv] Checking DNS record propagation...
2017/07/18 19:58:56 Time limit exceeded. 
````

**Comment by xenolf** [comment]
Hello!

What version of lego and which DNS provider are you using?

**Comment by samnazarko** [comment]
Hi,

I'm using version 

```./lego --version
lego version v0.3.1-0-g96a2477
```

DNS provider is Namecheap API.

I did a bit of digging and saw refactoring in acme/utils.go -- so it's possible that this has been addressed in a newer version.

**Comment by xenolf** [comment]
Hey!

Yeah... Please upgrade your installation to the latest version 0.4.0 and
see if the problem persists.

**Comment by samnazarko** [comment]
Will do.

**Comment by samnazarko** [comment]
Unfortunately the issue still seems to remain on the latest published binary.

**Comment by ldez** [comment]
could you retry with the latest version?
