### ISSUE TITLE
add certbot like hook script of return codes

### ISSUE THREAD

**Issue by damageboy** [go-acme/lego#427]
I'd like to be able to hook a script like certbot can do when a new certificate is generated / updated

Ideally this would be something like: `--renew-hook /root/certbot-renew-hook.sh` 

If this sounds less fun to implement, alternatively or additionally various exit codes could be used to detect renewl?

Today, when I run `renew --days=30` I get the same exit-code from lego regardless of what happenned...

**Comment by martensson** [comment]
@damageboy I have the same problem, did you find a workaround? A bit annoying to restart the webserver each time even when its not necessary.

**Comment by damageboy** [comment]
Nada, IIRC, I did a test on the modified date of the cert files...

**Comment by martensson** [comment]
@damageboy Finally I got it solved my switching to acme.sh, but I hope lego will get a fix for it since I really appreciate the fact that its a single static binary.
