### ISSUE TITLE
Update emails?

### ISSUE THREAD

**Issue by lmas** [go-acme/lego#443]
Hi, it seems lego is missing an option to update the registered email?

On https://letsencrypt.org/docs/expiration-emails/, they show how to update it using certbot:

    ~/certbot/venv/bin/certbot register --update-registration --email yourname+1@example.com

**Comment by remilapeyre** [comment]
FTR updating the account is part of the standard ACME protocol and documented at https://ietf-wg-acme.github.io/acme/draft-ietf-acme-acme.html#rfc.section.7.3.2.

I think it should be possible to add this quite easily by adapting https://github.com/go-acme/lego/blob/master/acme/api/account.go#L14

**Comment by lmas** [comment]
Thanks guys!
