### ISSUE TITLE
Debian package is really old (0.3.1)

### ISSUE THREAD

**Issue by fd0** [go-acme/lego#510]
I noticed that the Debian package is quite old, even [unstable only has 0.3.1](https://tracker.debian.org/pkg/golang-github-xenolf-lego). Can we maybe convince the maintainers to upload a new version? What's the matter there, is it maybe that `lego` added many more new dependencies which need to be added to Debian first?

**Comment by vincentbernat** [comment]
Yes, dependencies need to be packaged. This may be easy or not. We are missing the following packages:

```
github.com/Azure/go-autorest/autorest
github.com/decker502/dnspod-go
github.com/dnsimple/dnsimple-go/dnsimple
github.com/edeckers/auroradnsclient
github.com/exoscale/egoscale
github.com/ovh/go-ovh/ovh
github.com/rainycape/memcache
github.com/timewasted/linode/dns
gopkg.in/ns1/ns1-go.v2/rest
```

And we need to update `azure-sdk-for-go`. @toddy15, I see you are working on the update of Lego. Is it still in progress on your side?

**Comment by toddy15** [comment]
Actually, I'm not working on lego, but on rclone. They share some dependencies. However, I can take a look to azure-sdk-for-go now.

**Comment by toddy15** [comment]
Well, for the new upstream version of `azure-sdk-for-go` (14.6.0) there are some dependencies missing as well:

github.com/marstr/goalias
github.com/marstr/collection
github.com/marstr/randname
github.com/dnaeon/go-vcr
github.com/globalsign/mgo
github.com/marstr/guid

So it'll take a while, I'm afraid.

**Comment by fd0** [comment]
Ok, thanks for the explanation! I hope that the situation will improve when versioning is added to go (vgo is merged), sigh.

Thanks for your work!

**Comment by jnovack** [comment]
There have been major improvements in go versioning the 18 months. 

Also referring #991 to link these two tickets.

**Comment by mholt** [comment]
Do we know who the maintainer of that lego Debian package is? I am trying to get in touch.

**Comment by fd0** [comment]
According to the [tracker](https://tracker.debian.org/pkg/golang-github-xenolf-lego) the uploaders are `onlyjob@` and `zlatan@`, but the maintainer is the Debian Go Packaging Team, so I suppose everybody in that group could upload.

**Comment by mholt** [comment]
I wasn't sure if the uploaders are the right people to contact, but I guess it's better than nothing, and might even be the right people in this case. Thanks!

**Comment by vincentbernat** [comment]
The correct way to contact maintainers is to open a bug report against the package. I just did that ([947062](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947062)). But the list of dependencies to package separately is big and Debian still requires each dependency to be packaged separately. This cannot be automated as there is a manual screening needed, notably for license checking. I think there is very little hope someone will be able to upgrade Lego.

**Comment by onlyjob** [comment]
I have upgraded [the package](https://tracker.debian.org/pkg/golang-github-xenolf-lego) to v2.7.2. Upgrading further requires to update _golang-github-cenkalti-backoff-dev_ which have 11 depending packages and I have little capacity and incentive to spend more time...
I've made some improvements to the package (mostly in regards to disabling unsatisfyable dependencies) that should make further package maintenance easier so hopefully someone else will contribute.

**Comment by onlyjob** [comment]
I had to touch few dependency packages but in the end it was not as much effort as I expected so I've managed to upload latest release 3.2.0.

I think this issue can be closed now.

**Comment by mholt** [comment]
Thank you! That is a great Christmas gift :)
