### ISSUE TITLE
namedotcom backend removing subdomains when it shouldn't?

### ISSUE THREAD

**Issue by SvenDowideit** [go-acme/lego#543]
I wonder if https://github.com/containous/traefik/issues/3306 is an issue in lego?

when using traefik to request certs for `tower.ona.im,traefik.tower.ona.im,port.tower.ona.im,kibana.tower.ona.im` it fails, as the code is checking for DNS records on `_acme-challenge.traefik.tower.ona.im`, but the TXT records are all on `_acme-challenge.ona.im`.

```
infra_traefik.1.2m6q8iyogej8@TOWER-SL    | time="2018-05-11T05:13:40Z" level=error msg="Unable to obtain ACME certificate for domains \"traefik.tower.ona.im\" detected thanks to rule \"Host:traefik.tower.ona.im\" : cannot obtain certificates map[traefik.tower.ona.im:acme: Error 403 - urn:ietf:params:acme:error:unauthorized - No TXT record found at _acme-challenge.traefik.tower.ona.im]"
```

```
_acme-challenge.ona.im.	300	IN	TXT	"HOTLkE6PtlvX3LXaD0CgQ0FONdvLag7KPsmWp9tGXdM"
_acme-challenge.ona.im.	300	IN	TXT	"jpdEr5mFP50n6GpxoJOz5oQ39_c-zufbILqZ0sjd97s"
_acme-challenge.ona.im.	300	IN	TXT	"ME7CeT50yrcWeAW2tOFuHAZ19DSdMLg5NBsXYY9SZO4"
_acme-challenge.ona.im.	300	IN	TXT	"KtcmyVvM7vq9_-FFV1Gkr1pvo6jfJ97LNxHXX7NfbcU"

```

**Comment by SvenDowideit** [comment]
when I change to use a domain i have on gandi.net, things work - so presumably its just something specific to name.com

**Comment by emfox** [comment]
I encounter the same issue, and confirm this has not been resolved yet.

**Comment by daalien** [comment]
lego version 2.3.0 linux/amd64

--domains="123.com" --domains="www.123.com" --dns="namedotcom" fails for www.123.com. The TXT record for the subdomain _acme-challenge.www.123.com is never created. If I'm mistaken thinking this record should be created...it's doesn't seem to be working regardless.

--domains="123.com" --domains="*.123.com" --dns="namedotcom" works.

I tried with just "--domains="www.123.com"" and it fails as well.

**Comment by coopernurse** [comment]
I think I'm hitting this issue while playing around with @mholt 's certmagic repo (which uses lego to solve acme challenges).

I have a domain hosted with `name.com` and the `_acme-challenge` record is incorrectly registered. I have a fix working locally so I'll open a PR with the patch.
