### ISSUE TITLE
build lego from checkout of the repo?

### ISSUE THREAD

**Issue by fd0** [go-acme/lego#567]
Hi,

for several of my projects (e.g. [restic](https://github.com/restic/restic)) I've built a small program called `build.go` (repo [here](https://github.com/fd0/build-go)), which allows end-users to compile the program directly from a checkout of the repo or the extracted release `tar`. Especially, they don't have to setup a `GOPATH` or anything, just install the Go compiler and run `go run build.go`. The program takes care of everything, provided the dependencies are vendored. And it also sets a nice version string. It can live besides regular code (a build tag prevents compilation).

Are you interested in adding this for users of lego? I'm happy to submit a PR :)

**Comment by rradillen** [comment]
I forked the repo to be able to work on #717 thinking never wrote anything in go how hard can it be. Turns out hard before writing a single line of code. Something like this for an ordinary build and for the tests (!) would be godsend.

**Comment by fd0** [comment]
When using Go with a `GOPATH`, you need to make sure that your fork of the repository is checked out at the right path within the `GOPATH`, then you don't have to change any paths. It's a well-known problem with the `GOPATH` approach, which will (hopefully) get better in the future when Go Modules are supported and you don't have a `GOPATH` structure any more.

My code is meant for end-users, but you can also run restic's tests from a checkout of the repository. It's not pretty but it works well in practice.

**Comment by rradillen** [comment]
so I have to checkout lego into GOPATH/src/github.com/xenolf/lego

**Comment by ldez** [comment]
You have to install [Golang](https://golang.org/doc/install) and after:

```bash
# Create the root folder
mkdir $GOPATH/src/github.com/xenolf
cd $GOPATH/src/github.com/xenolf

# clone your fork
git clone git@github.com:yourusername/lego.git
cd lego

# Add the xenolf/lego remote
git remote add upstream git@github.com:xenolf/lego.git
git fetch upstream

# Create your branch
git checkout -b my-feature

## Create your code ##

# Linters
make checks
# Tests
make test
# Complle
make build

# push your branch
git push -u origin my-feature

# create a pull request
```

I will update the contributor guide.

**Comment by ldez** [comment]
I think `go install` and modules have fixed that.
