### ISSUE TITLE
Request - build linux_arm

### ISSUE THREAD

**Issue by abelii** [go-acme/lego#621]
First - am a fan, this is the best let's encrypt client I've used (I've tried a few).
Second - I've had trouble building on the pi zero.  I'm not very knowledgable about go :-( I did find instructions around cloning and doing a "make build" which I'll try (I did the go gets and just "make", which didn't work...) - but I wanted to ask if you could go back to including plain linux_arm in your builds.  On the pi zero rasbian neither the arm64 or arm7 will run - they panic.  I tried the older 0.30 plain "linux_arm" and it works fine on the pi zero (and the pi 3, for that matter) - so it seems like it would be a good generic option to include in the build packages you produce.  Thanks.

**Comment by mholt** [comment]
We can probably add linux arm to the releases, if it's not already. Which version of ARM does the pi zero have?

**Comment by abelii** [comment]
Looks like it's ARM6.  You had an old build just called "arm" that worked (the binary ran - but it's too old a version to really be used now).  I installed the version of "go" which came out of the rasbian repos (so, would be the "typical / vanilla" and it reports the below:

pi@raspberrypi:~ $ go version
go version go1.7.4 linux/arm

(like your binary, just "linux/arm").  In case it helps or you want to be more specific with your build - when I do a uname -a the archececture is reported to be an armv6

pi@raspberrypi:~/Workspace $ uname -a
Linux raspberrypi 4.14.50+ #1122 Tue Jun 19 12:21:21 BST 2018 armv6l GNU/Linux
