### ISSUE TITLE
feature request: bind to unix socket

### ISSUE THREAD

**Issue by schmurfy** [go-acme/lego#648]
in my environement it is a lot easier for me to manage it that way, I can add support for this myself provided I manage to compile the project.
I like go as a language but the tooling is a whole other story... Why almost no go project include a simple "How to compile from source" ? (and I don't mean compiling from github, from my local dev folder)

**Comment by ldez** [comment]
can you explain what you want to do with an unix socket.

FYI, to build the project (min Go 1.10):
- https://github.com/xenolf/lego/blob/master/Makefile (`make build`)
- or `go build`

**Comment by schmurfy** [comment]
I use nginx as frontend with a redirection on the letsencrypt path (/.well-known/acme-challenge/) to a unix socket where I wish to start lego when I need to renew a certificate.
I just prefer to avoid using a tcp socket on the host when it is not required.

Thanks for the build step :)
