### ISSUE TITLE
Add namesilo as a provider

### ISSUE THREAD

**Issue by loganto** [go-acme/lego#650]
Hi. Could u add namesilo as a DNS povider?  
They do have an api, for example Lexicone project supports it:  
https://github.com/AnalogJ/lexicon

https://www.namesilo.com/api_reference.php

**Comment by ldez** [comment]
I created a client API for Namesilo https://github.com/nrdcg/namesilo

If someone uses Namesilo either want to create a pull request or is able to do tests, it will be appreciated.
