### ISSUE TITLE
Gandi v5 dns challenge fails with 404

### ISSUE THREAD

**Issue by dpantel** [go-acme/lego#711]
Using lego in Caddy, I can't get the DNS challenge to succeed with Gandi.

I get the following error:  "failed to get certificate: Error presenting token: Gandi DNS: request failed with HTTP status code 404"

Any chance that their API URLs have changed and need to be updated in the code?  Any other ideas on why it fails?

Thanks.

**Comment by dpantel** [comment]
Oddly enough, it seems to succeed when using the staging server from LetsEncrypt.

**Comment by dpantel** [comment]
Update:

It looks to hinge on dns resolution of the domain.  If I add a local dnsmasq exception to resolve the domain in question to an internal IP, then the request fails.  If I allow the dns resolution to propagate out to the WAN, then getting the certificate works just fine.

I am not too familiar with the ACME DNS challenge process.  Is this a limitation of the negotiation, or is there a way around that?

**Comment by tchabaud** [comment]
@dpantel : did you try using --dns.resolvers option to use an external public DNS server for resolution (for example Cloudflare or Google) ?

I had the same problem as you and calling lego like this solved the issue for me : 

```bash
/usr/local/bin/lego \
    -a \
    --dns.resolvers 1.1.1.1 \
    --path=/path/to/my/certs \
    --email=your_email@your_domain.name \
    --domains=your_domain \
    --dns=gandiv5 \
    --pem run
```

**Comment by Blankf** [comment]
did anyone managed to get this sorted?
i've tried setting --dns.resolvers but that gives the same error for me.

_acme-challenge: 404 [Not Found] request failed: The resource could not be found.

the funny part is, it will generate the _acme-challenge record in gandi, but then its unable to verify it somehow.

**Comment by ldez** [comment]
hello,

I'm not able to reproduce the error:

<details>
<summary>output</summary>

```console
$ export GANDIV5_API_KEY=xxxx
$ ./lego -a -m mail@example.com \
> -d *.example.com -d example.com \
> --DNS gandiv5 \
> -s https://acme-staging-v02.api.letsencrypt.org/directory \
> run
2020/11/27 13:09:08 [INFO] [*.example.com, example.com] acme: Obtaining bundled SAN certificate
2020/11/27 13:09:09 [INFO] [*.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/163011894
2020/11/27 13:09:09 [INFO] [example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/163011895
2020/11/27 13:09:09 [INFO] [*.example.com] acme: use dns-01 solver
2020/11/27 13:09:09 [INFO] [example.com] acme: Could not find solver for: tls-alpn-01
2020/11/27 13:09:09 [INFO] [example.com] acme: Could not find solver for: http-01
2020/11/27 13:09:09 [INFO] [example.com] acme: use dns-01 solver
2020/11/27 13:09:09 [INFO] [*.example.com] acme: Preparing to solve DNS-01
2020/11/27 13:09:10 [INFO] API response: DNS Record Created
2020/11/27 13:09:10 [INFO] [example.com] acme: Preparing to solve DNS-01
2020/11/27 13:09:10 [INFO] API response: DNS Record Created
2020/11/27 13:09:10 [INFO] [*.example.com] acme: Trying to solve DNS-01
2020/11/27 13:09:10 [INFO] [*.example.com] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/11/27 13:09:30 [INFO] Wait for propagation [timeout: 20m0s, interval: 20s]
2020/11/27 13:09:30 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2020/11/27 13:09:50 [INFO] [*.example.com] acme: Waiting for DNS record propagation.
2020/11/27 13:10:17 [INFO] [*.example.com] The server validated our request
2020/11/27 13:10:17 [INFO] [example.com] acme: Trying to solve DNS-01
2020/11/27 13:10:17 [INFO] [example.com] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/11/27 13:10:37 [INFO] Wait for propagation [timeout: 20m0s, interval: 20s]
2020/11/27 13:10:41 [INFO] [example.com] The server validated our request
2020/11/27 13:10:41 [INFO] [*.example.com] acme: Cleaning DNS-01 challenge
2020/11/27 13:10:42 [INFO] [example.com] acme: Cleaning DNS-01 challenge
2020/11/27 13:10:42 [INFO] [*.example.com, example.com] acme: Validations succeeded; requesting certificates
2020/11/27 13:10:42 [INFO] [*.example.com] Server responded with a certificate.
```

</details>

---

> the funny part is, it will generate the _acme-challenge record in Gandi, but then its unable to verify it some

lego insert the TXT record by using the Gandi API, the propagation check is made by DNS calls, it's 2 different systems, there is no correlation between both.

---

> _acme-challenge: 404 [Not Found] request failed: The resource could not be found.

This error comes from Gandi it-self, and it may not be related to your problem.

To get to the root of the problem, you have to check and provide your logs (from the start of lego).
Also, I recommend checking your environment (network, firewall, local DNS,  ...)

**Comment by Blankf** [comment]
Yeah, so i've tried with my root "domain.com" that seems to work fine.
also whenever the item is created 
`2020/11/27 13:22:13 [INFO] API response: DNS Record Created`
i can dig it with pointing to the same name server i provided with the --dns.resolvers

but whenever i use a subdomain, like test.domain.com, it will create a record in gandi
`_acme-challenge.test`
but whenever i try to dig that, it fails.

**Comment by ldez** [comment]
I don't reproduce event with a subdomain:

<details>
<summary>text</summary>

```console
$ export GANDIV5_API_KEY=xxxx
$ ./lego -a -m mail@example.com \
> -d *.test.example.com -d test.example.com \
> --dns gandiv5 \
> -s https://acme-staging-v02.api.letsencrypt.org/directory \
> run
2020/11/27 13:52:19 [INFO] [*.test.example.com, test.example.com] acme: Obtaining bundled SAN certificate
2020/11/27 13:52:20 [INFO] [*.test.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/163034190
2020/11/27 13:52:20 [INFO] [test.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/163034191
2020/11/27 13:52:20 [INFO] [*.test.example.com] acme: use dns-01 solver
2020/11/27 13:52:20 [INFO] [test.example.com] acme: Could not find solver for: tls-alpn-01
2020/11/27 13:52:20 [INFO] [test.example.com] acme: Could not find solver for: http-01
2020/11/27 13:52:20 [INFO] [test.example.com] acme: use dns-01 solver
2020/11/27 13:52:20 [INFO] [*.test.example.com] acme: Preparing to solve DNS-01
2020/11/27 13:52:20 [INFO] API response: DNS Record Created
2020/11/27 13:52:20 [INFO] [test.example.com] acme: Preparing to solve DNS-01
2020/11/27 13:52:21 [INFO] API response: DNS Record Created
2020/11/27 13:52:21 [INFO] [*.test.example.com] acme: Trying to solve DNS-01
2020/11/27 13:52:21 [INFO] [*.test.example.com] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/11/27 13:52:41 [INFO] Wait for propagation [timeout: 20m0s, interval: 20s]
2020/11/27 13:52:45 [INFO] [*.test.example.com] The server validated our request
2020/11/27 13:52:45 [INFO] [test.example.com] acme: Trying to solve DNS-01
2020/11/27 13:52:45 [INFO] [test.example.com] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/11/27 13:53:05 [INFO] Wait for propagation [timeout: 20m0s, interval: 20s]
2020/11/27 13:53:05 [INFO] [test.example.com] The server validated our request
2020/11/27 13:53:05 [INFO] [*.test.example.com] acme: Cleaning DNS-01 challenge
2020/11/27 13:53:06 [INFO] [test.example.com] acme: Cleaning DNS-01 challenge
2020/11/27 13:53:06 [INFO] [*.test.example.com, test.example.com] acme: Validations succeeded; requesting certificates
2020/11/27 13:53:06 [INFO] [*.test.example.com] Server responded with a certificate.
```

</details>

Have you created an A record for your sub-domain (`test.domain.com`)?

FYI the propagation timeout is 20min (`Wait for propagation [timeout: 20m0s, interval: 20s]`).

**Comment by Blankf** [comment]
oh men, feeling so dumb right now... i didnt have the A record yet.
i was first testing the functionality, without thinking about that part.
sorry, thnx for the help!
