### ISSUE TITLE
Add support for ionos / 1and1

### ISSUE THREAD

**Issue by seuf** [go-acme/lego#727]
### Ionos / 1and1.fr Acme DNS challenge support

Do you think it's possible to support ionos (ex 1and1.fr) for Acme DNS-01 challenge ?
I'd love to have a wildcard tls certificate :smile: 

Related issue : https://github.com/containous/traefik/issues/4267

**Comment by ldez** [comment]
Ionos / 1and1.fr seems to doesn't provide an API to add/remove TXT records.
https://cloudpanel-api.1and1.com/documentation/

So you can ask to 1&1 to create this API :wink: 

You can also try to use https://github.com/joohoi/acme-dns.

**Comment by vg** [comment]
1and1 now seems to have an DNS API. 
https://developer.hosting.ionos.com/docs/dns

**Comment by ldez** [comment]
@seuf @vg @AlexH269 if I create a PR are you able to perform tests for me?

**Comment by AlexH269** [comment]
Gladly.

**Comment by AlexH269** [comment]
It seems like i need to contact IONOS to obtain an api key -_- I will report back if i heard something!

**Comment by ldez** [comment]
I see that :disappointed: 

https://developer.hosting.ionos.com/docs/getstarted
> In order to sign up to the Beta Program for API Access to Hosting Services please contact your Personal Consultant.

**Comment by helgeerbe** [comment]
I started to write a Plugin for Ionos https://github.com/helgeerbe/certbot-dns-ionos
Right now, there isn‘t a pip package. But if you know what you are doing you can give it a try.
Clone repo and install with pip install. But be warned. The plug-in manipulates your DNS records and if anything goes wrong your dns records might be broken (no domain resolution, no resolving of you email domain).

**Comment by jankatins** [comment]
To get a beta api key, just a call to their support after enabling the "personal support" thingy :-) I needed to point to their own Website as the support seems to unaware of this: "yes, hosting accounts now also have API access, see this URL" -> got the email a day later

**Comment by jankatins** [comment]
@ldez Thank You!

**Comment by Chr3is** [comment]
Any plans when the next version including this feature will be released to include this into traefik?

**Comment by AvisVanBruch** [comment]
@Chr3is I know this is a dead thread but could you maybe explain how you did that? i can't find any infos online on how to.

**Comment by ldez** [comment]
@AvisVanBruch what are you trying to do?
