### ISSUE TITLE
challenge: function FindZoneByFqdnCustom may get a SERVFAIL response in some sub-domain

### ISSUE THREAD

**Issue by dgautumn** [go-acme/lego#768]
In my case I want to do a wildcard 2nd-level sub-domain ( such as *.st.wsy0512.com ) in alidns, but there is a problem: SOA record query in alidns on 2nd-level sub-domain will get a SERVFAIL response, on top-level sub-domain gets a correct reponse. Is it possible to add a case condition as dns.RcodeServerFailure so that the function will continue try to query next level domain zone? Thanks for your masterpiece of this project.

fuction in file: lego/challenge/dns01/nameserver.go on line 157
my domain query test as below image:

![menu saveimg savepath20190123144404](https://user-images.githubusercontent.com/30062447/51587930-5dd0fa00-1f1d-11e9-8cb5-fae322dff631.jpg)

**Comment by rc452860** [comment]
遇到此问题首先确定本机环境DNS是否被劫持，查看路由器DNS是否被翻墙插件之类的工具劫持。
