### ISSUE TITLE
New Error with DNS-01 update (powerdns 4.1.5 & 4.1.6)

### ISSUE THREAD

**Issue by freman** [go-acme/lego#817]
error presenting token: pdns: unexpected HTTP status code 404 when fetching 'http://127.0.0.1:8081/api/v1/'

Seems that they changed borked the trailing slash?

```
curl -H 'Content-Type: application/json' -H 'X-API-Key: secretsource' http://127.0.0.1:8081/api
[{"url": "/api/v1", "version": 1}]
```

```
curl -H 'Content-Type: application/json' -H 'X-API-Key: secretsource' http://127.0.0.1:8081/api/
Not Found
```

**Comment by freman** [comment]
This seems to still be an issue with 4.1.10

**Comment by almereyda** [comment]
I can replicate the behaviour with and without slash exactly as above.

What does this mean for me wanting to use a DNS challenge with Traefik through lego?

Can a valid `PDNS_API_URL` setting still be passed for using lego against a PowerDNS 4.1.10 HTTP API somehow?

**Comment by ldez** [comment]
@almereyda could you provide the log related to lego?
