### ISSUE TITLE
OVH DNS-01 fails on challenges for host.sub.example.com

### ISSUE THREAD

**Issue by sauerj** [go-acme/lego#820]
When challenging a certificate for `host.sub.example.com` the OVH API fails:

`ovh: error when call api to add record (/domain/zone/sub.example.com/record): Error 404: \"This service does not exist\"\n`

This is caused because there is no zone called `sub.example.com` on OVH.  The API URL must be `/domain/zone/example.com/record` and the record `_acme-challenge.host.sub`

**Comment by ldez** [comment]
This is a duplicate of #618 - Feel free to subscribe there for updates.

**Comment by sauerj** [comment]
I am not sure if it really is a duplicate. In #618 the issuing of `sub.example.com` fails. This works without a problem for me. I have several certificates with a single subdomain issued with traefik.

But certificates for hosts in a subdomain are failing.

**Comment by ldez** [comment]
Have to try this https://github.com/xenolf/lego/issues/618#issuecomment-449390547 ?

**Comment by sauerj** [comment]
API key is working with certbot for certificates for hosts like `host.sub.example.com`.

I just logged into the [OVH API](https://api.ovh.com/console) and executed: `/domain/zone` which gets me my available zones: `example.com`.

Executing `/domain/zone/example.com` returns HTTP 200 and information about the zone.
`/domain/zone/sub.example.com` returns
```
Not Found (404)
{ "message": "This service does not exist" }
```

I think the API url for all records must then be `/domain/zone/example.com/record`

**Comment by ldez** [comment]
@sauerj If I create a patch for lego, would you be able to build lego to test and validate the non-regression?

**Comment by ldez** [comment]
or maybe you can create the patch?

**Comment by sauerj** [comment]
@ldez yes, just tell when the patch is ready.

**Comment by sauerj** [comment]
> or maybe you can create the patch?

I do not have any skills in go. But I think this will be a rather small fix. I can give it a try.

**Comment by ldez** [comment]
so try :+1: and if you have a problem, do not hesitate to ask me for help.

**Comment by sauerj** [comment]
So, today I had time to do some testing and reproduction of the error with latest code. I did not mentioned above, that the error occurred with Traefik.

I have to apologize, this issue _IS_ absolutely my fault.

Let me explain: I have a registered domain which I use for public services. I also use DNS zone for LAN hosts and services: `internal.example.com` for which I provide my own authoritative server in the LAN. My local caching DNS server redirects requests for the internal zone to the authoritative server. Requests for e.g. `_acme-challenge.www.internal.example.com` will then be answered from the local authoritative DNS server, instead for OVH servers, and will fail.

I am not 100% sure, but I explain the failing API call with the existing SOA for `internal.example.com` which is then parsed into the API call and will fail on the OVH end.

When I define an external DNS server, like Google Public DNS, to use by lego the issuing for internal hosts succeed.
