### ISSUE TITLE
Lego 2.3.0 now generating secp384r1 keys, not working with NGINX 1.14.0

### ISSUE THREAD

**Issue by jnoxon** [go-acme/lego#826]
I updated lego from 2.1.0 to 2.3.0, and I now get secp384r1 keys, which don't work with NGINX, and it's unclear how to force the old behavior and get RSA key pairs.

**Comment by jnoxon** [comment]
If it helps, I generate my keys like so:

```/usr/local/bin/lego230 $SERVER --accept-tos --email user@example.com --path=/etc/nginx/lego --domains=foo.example.com --dns route53 run
```

**Comment by ldez** [comment]
```
-key-type value, -k value   Key type to use for private keys. Supported: rsa2048, rsa4096, rsa8192, ec256, ec384. (default: "ec384")
```

```bash
lego -k rsa2048 -a -m user@example.com --path=/etc/nginx/lego -d foo.example.com --dns route53 run
```

**Comment by jnoxon** [comment]
Man, I looked right past that at least a half-dozen times. Thank you.

/facepalm

**Comment by MikeyYeahYeah** [comment]
Where is the -k flag documented?

**Comment by ldez** [comment]
In this page https://go-acme.github.io/lego/usage/cli/, click on `CLI help`
