### ISSUE TITLE
dnspod provider: mismatched types

### ISSUE THREAD

**Issue by wI2L** [go-acme/lego#827]
https://github.com/go-acme/lego/blob/0c87df143e630a1c50b4c36c8fbdda6cd993ebba/providers/dns/dnspod/dnspod.go#L140

`hostedZone` is a `dnspod.Domain` type which contain a field ID of type `json.Number`, a string.
```
go build: invalid operation: hostedZone.ID == 0 (mismatched types "encoding/json".Number and int)
```

**Comment by ldez** [comment]
Hello, you are probably using a newer version than the one used in lego

**Comment by wI2L** [comment]
Yeah that make sense, I am using go mod to manage my dependencies.
Using `go mod edit` to require the exact revision `83a3ba562b048c9fc88229408e593494b7774684` lego is using with dep fix the problem.

Any plans to move to go mod btw ?

**Comment by ldez** [comment]
There is already a PR on the subject https://github.com/go-acme/lego/pull/706

For the moment I prefer to keep dep as long as the support of the modules are not the default.
Some tooling are still missing in the core GoLang distribution.
I know that community tools exist (I made one myself: [motoko](https://github.com/ldez/motoko).

https://blog.golang.org/modules2019

I'll close this issue, because I think the question is answered.

**Comment by KingzCheung** [comment]
I also encountered this error.
Which version should I use to avoid this problem?

**Comment by badouralix** [comment]
Hey @kingzcheung, in case your question is still relevant, here are my issues as of today:

```text
# github.com/go-acme/lego/providers/dns/designate
$GOPATH/pkg/mod/github.com/go-acme/lego@v2.6.0+incompatible/providers/dns/designate/designate.go:206:3: cannot use record.TTL (type int) as type *int in field value
# github.com/go-acme/lego/providers/dns/dnspod
$GOPATH/pkg/mod/github.com/go-acme/lego@v2.6.0+incompatible/providers/dns/dnspod/dnspod.go:140:19: cannot convert 0 (type untyped number) to type "encoding/json".Number
$GOPATH/pkg/mod/github.com/go-acme/lego@v2.6.0+incompatible/providers/dns/dnspod/dnspod.go:140:19: invalid operation: hostedZone.ID == 0 (mismatched types "encoding/json".Number and int)
```

And the current fix: (manually locking a couple of dependencies)

```bash
go mod edit -require=github.com/decker502/dnspod-go@v0.0.0-20180416134550-83a3ba562b04
go mod edit -require=github.com/gophercloud/gophercloud@v0.0.0-20190204021847-a2b0ad6ce68c
```

See [github.com/decker502/dnspod-go](https://github.com/go-acme/lego/blob/99741b0b92479bbc3be5c8e8828dc8faf5ed1dd3/Gopkg.lock#L170-L176) and [github.com/gophercloud/gophercloud](https://github.com/go-acme/lego/blob/99741b0b92479bbc3be5c8e8828dc8faf5ed1dd3/Gopkg.lock#L272-L288)

**Comment by Zerowalker** [comment]
I still get this issue, i can't install it on go 1.13

**Comment by ldez** [comment]
Lego is currently built with go1.13 and use go modules.

https://github.com/go-acme/lego/blob/e225f8d334bf823eb220cf70e8d54a9612a1bc2c/.travis.yml#L10

https://github.com/go-acme/lego/blob/master/go.mod

**Comment by Zerowalker** [comment]
Not familiar with yml, i use the go get ... -u, which sadly fails.
Should i do things differently?

**Comment by ldez** [comment]
If you don't know how to build, I recommend to use our binaries:
- https://github.com/go-acme/lego/releases

**Comment by Zerowalker** [comment]
oh didn't realize there was any, thanks!
