### ISSUE TITLE
Obtain resolvers via Environment

### ISSUE THREAD

**Issue by the-maldridge** [go-acme/lego#828]
I was just bit by #192 and I expected I could solve this by exporting some variables to the environment that specify the external nameserver.  Unfortunately it seems that this value can't come from the environment.

While I am using lego via caddy, this still seems like the kind of thing that should go inside of lego.

**Comment by ldez** [comment]
Hello, when you are use lego as lib (like Caddy), the resolvers can be define pro grammatically.
Then Caddy can to the choice to expose that with env vars or something else.

**Comment by the-maldridge** [comment]
Indeed, caddy has a ticket considering this: mholt/caddy#2476 however since caddy specifies all other lego configuration via lego's existing environment parsing, it seems appropriate to continue pulling from the environment for consistency.

**Comment by ldez** [comment]
The env vars are used for DNS providers configuration.
The resolvers are not a part of the DNS providers configuration but a part of the core lib of lego (dns challenge).
It's not comparable.

**Comment by the-maldridge** [comment]
I see; an interesting choice, but I will add that information to the issue raised against caddy.

**Comment by ldez** [comment]
I'll close this issue, because I think the question is answered.

Thanks for your contribution. 

FYI you didn't put the message in the correct issue.

**Comment by the-maldridge** [comment]
woops, thanks for catching that, I have far too many tabs open at the moment.
