### ISSUE TITLE
443: bind: address already in use Err, for subsite of WP Multisite

### ISSUE THREAD

**Issue by anandabrata** [go-acme/lego#833]
Hello,

I am on Bitnami WP(5.1) Multisite AMI on AWS and DNS through Route53. 
My primary domain SSL is created fine and everything is working fine. My subsite is configured to the same EIP as my primary domain. I have generated certificates for my primary domain using command
`sudo lego --tls --email="EMAIL-ADDRESS" --domains="DOMAIN" --domains="www.DOMAIN" --path="/etc/lego" run`

When I try to use the same command for my subsite domain, I get the following error
_Could not obtain certificates:
acme: Error -> One or more domains had a problem:

__acme: error presenting token: could not start HTTPS server for challenge -> listen tcp :443: bind: address already in use
acme: error presenting token: could not start HTTPS server for challenge -> listen tcp :443: bind: address already in us_

**The primary domain is obviously using the 443 port, then how do I generate the certificates for the secondary domain?**

Thanks

**Comment by ldez** [comment]
Hello,

TLS challenge required the port 443.

Then you have 2 choices:
- use the HTTP challenge (required the port 80)
- use the DNS challenge

**Comment by anandabrata** [comment]
@ldez 
My bad. I had my Apache server started, which was holding to the 443 port. Hence was  getting a bind address error.
Resolved when I stopped Apache.

Thanks for your suggestions.
