### ISSUE TITLE
Support "Domain Offensive" (do.de) provider

### ISSUE THREAD

**Issue by andig** [go-acme/lego#834]
I'm working with German https://do.de provider who is offering a simple API for updating TXT records. That API is usable by either the `exec` provider or could get its own provider,  much similar to duckduckdns.

Would a contribution for a dedicated do.de provider be of interest and potentially gain acceptance?

https://www.do.de/wiki/LetsEncrypt_-_Entwickler

**Comment by ldez** [comment]
We will accept your contribution with pleasure. :+1:
