### ISSUE TITLE
Proxy for outging HTTP requests.

### ISSUE THREAD

**Issue by krjensen** [go-acme/lego#840]
Hi,

I know this topic has been discussed before, and I know that the answer allway is "LEGO supports `http.ProxyFromEnvironment`". But it's a huge challenge that we can't specify a proxy server on command line as an argument.

*Example:*
LEGO is used in the modern Traefik LoadBlancer to do the Lets Encrypt configuration.
In our case we need to use a proxy to access the internet. To make LOGO work as a part of Traefik, I need to set HTTP_PROXY for the traefik process. This will make LEGO happy BUT it will also force trafik to use the HTTP_PROXY for all HTTP requests - that's a really bad thing for an internal HTTP loadbalancer. There is a lot af hacks to work around this, but it would ir so much easier if lego just accepted a `--http-proxy http://server:port --https-proxy http://server:port` argument.

**Comment by ldez** [comment]
Hi, add this options into the lego CLI will not solve your issue, because Traefik uses lego as a lib not as a CLI.

To handle this, the option must be added to the acme configuration of Traefik, no modification is required in lego.

FYI, I'm a Traefik maintainer.

**Comment by lexfrei** [comment]
@ldez is this possible in traefik now? Can find any related info in docs
