### ISSUE TITLE
get cert faild

### ISSUE THREAD

**Issue by wep1234** [go-acme/lego#843]
When I run this line of commands:
lego --email="1017335380@qq.com" --domains="xxxxx" --domains="xxxx" --domains="xxx" --domains="xxxx" --http --http.port :8090 run
Was told the following exception:
Could not create client: get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get https://acme-v02.api.letsencrypt.org/directory: proxyconnect tcp: tls: oversized record received with length 20527
What should I do to solve this problem?

**Comment by mholt** [comment]
I'm guessing there is a MITM proxy of some sort between your computer and Let's Encrypt that is borking the TLS connection. Maybe not, but I wouldn't be surprised. Which country are you running that from?

**Comment by wep1234** [comment]
> I'm guessing there is a MITM proxy of some sort between your computer and Let's Encrypt that is borking the TLS connection. Maybe not, but I wouldn't be surprised. Which country are you running that from?

Thank you for your answer, it is the reason of the proxy;
