### ISSUE TITLE
when no renewal is done, should return a different exit code

### ISSUE THREAD

**Issue by pdumais** [go-acme/lego#844]
I am running lego using the goacme/lego docker image. 
I am setting a cronjob to renew my certificates every day and if a renewal actually takes place, I need to restart my webserver. I don't want to blindly restart the webserver if no renewal took place (because there was still a good amount of days left until renewal).

For this reason, I think it would be very useful if lego would return a non-zero exit code if it refused to do the renewal.

**Comment by ldez** [comment]
Related to https://github.com/go-acme/lego/issues/216#issuecomment-222519153

**Comment by pdumais** [comment]
If you prefer not to use an exit code, then may I suggest adding a flag that will instruct lego to return, on stdout, a predictable short string that says "updated" or "noop" ?
