### ISSUE TITLE
DNS Challenge not checking "_acme-challenge" properly

### ISSUE THREAD

**Issue by vrubiella** [go-acme/lego#847]
After upgrade from 1.1 DNS Challenge not working properly.

It seems that he looks for the token in root domain records, not in "_acme-challenge.domain.tld." TXT record.

```
time="2019-04-04T07:16:08Z" level=info msg="ts=2019-04-04T07:16:08.749516961Z caller=server.go:112 component=HTTP err=\"acme: Error -> One or more domains had a problem:\\n[*.testcorreucdmon.com] time limit exceeded: last error: NS ns4.cdmondns-01.org. did not return the expected TXT record [fqdn: testcorreucdmon.com., value: 4aYhV4XE5xfO24ENBJtl9oByQgaYCVYfxvkHUqXQT8M]: \\n\""
```

```
dig +short txt _acme-challenge.testcorreucdmon.com
"4aYhV4XE5xfO24ENBJtl9oByQgaYCVYfxvkHUqXQT8M"
```

If TXT record is created directly on root domain "@", Vaditacion succeeded correctly.

But we should create token on this record:
`acmeRecord, value := dns01.GetRecord(domain,keyAuth)`

acmeRecord is "_acme-challenge", not "@".

**Comment by ldez** [comment]
Could you give your command and the name of the DNS provider.

**Comment by vrubiella** [comment]
Is a Custom DNS Challenge solver who creates/deletes records on our DNS service. Very similar to DigitalOcean way.

The code above is working fine for version 1.1. 

```go
// Present creates a TXT record to fulfil the dns-01 challenge.
func (d *DNSProvider) Present(domain, token, keyAuth string) error {

	acmeRecord, value := dns01.GetRecord(domain,keyAuth)

	//
	//Here code related to create TXT record with acmeRecord and value
       //

	if err != nil {
		log.Log.Errorf("Can't PUT DNS records on %s for domain: %s, zone: %s and authz: %s", urlRecords, domain, zoneName, keyAuth)
	}

	return err
}

// CleanUp removes the TXT record matching the specified parameters.
func (d *DNSProvider) CleanUp(domain, token, keyAuth string) error {

	acmeRecord, _ := dns01.GetRecord(domain,keyAuth)

        //
        // lines of code related to remove TXT acmeRecord
       //
	if err != nil {
		log.Log.Errorf("Can't Delete DNS records on %s for domain: %s, zone: %s and authz: %s", urlRecords, domain, zoneName, keyAuth)
	}

	return err
}

func (d *DNSProvider) Timeout() (timeout, interval time.Duration) {

	return 120 * time.Second, 5 * time.Second
}
```

**Comment by ldez** [comment]
Are you manage multiple domains?

Solvers are now called in "parallel", before (v1.x) they are called sequentially.

If your challenge solver or your DNS provider doesn't support multiple TXT records by entry, this can produce an issue.

Then:
- if your DNS provider support multiple TXT records, update your code to manage the multiple TXT records.
- if your DNS provider doesn't support mulitple TXT record, add the following line in your challenge solver:
https://github.com/go-acme/lego/blob/5d557fdc6d9ee2226c0cce65733ee686ad4bc8b1/providers/dns/duckdns/duckdns.go#L85-L89

**Comment by vrubiella** [comment]
DNS Provider support multiple TXT records, I use a HTTP api to add TXT records: is practically identical as digitalocean provider, so, I'm working with only one solver (DNS).

On the erro log the TXT records created is not shown correctly:

`time="2019-04-04T07:16:08Z" level=info msg="ts=2019-04-04T07:16:08.749516961Z caller=server.go:112 component=HTTP err=\"acme: Error -> One or more domains had a problem:\\n[*.testcorreucdmon.com] time limit exceeded: last error: NS ns4.cdmondns-01.org. did not return the expected TXT record [fqdn: testcorreucdmon.com., value: 4aYhV4XE5xfO24ENBJtl9oByQgaYCVYfxvkHUqXQT8M]: \\n\""`

In this example we can see an "empty" list of TXT records, but dig command show us that exists record:
```
dig +short txt _acme-challenge.testcorreucdmon.com
"4aYhV4XE5xfO24ENBJtl9oByQgaYCVYfxvkHUqXQT8M"
``` 
Initially I suspect about a problem with DNS propagation, but I surprised because If during validation I manually create the TXT record with token  on base domain "@", validation succeeded....

Is it posible that library is trying to check TXT records itself before calling letsencrypt?

**Comment by vrubiella** [comment]
#861

**Comment by vrubiella** [comment]
close this, was fixed.
