### ISSUE TITLE
Chrome reports possible malware on the Win32 zip dl

### ISSUE THREAD

**Issue by ras07** [go-acme/lego#857]
When downloading lego_v2.4.0_windows_386.zip, Chrome displays this warning:
![image](https://user-images.githubusercontent.com/17038818/56257006-8128c280-6090-11e9-9a1c-b7cd3e960eb5.png)
("lego_v2.4.0_windows_386.zip is not commonly downloaded and may be dangerous."). The 64-bit version displayed no such warning. I downloaded and scanned both, found no malware, and have used both successfully. A quick Google search indicates this has to do with "reputation management" and who knows what else. I'm not sure there's really anything practical to be done about it (I downloaded the file several times to do my part to increase its "reputation";) ) but perhaps it's worth a mention on the Releases page.

**Comment by webash** [comment]
I also received this, but in Brave (Chromium browser)

**Comment by ldez** [comment]
Windows 386 come from the past, only a small number of people use this OS then Google flags it as "not commonly downloaded".

We cannot do anything for it.
