### ISSUE TITLE
Problem to access certificates when run with Docker

### ISSUE THREAD

**Issue by edouardtheron** [go-acme/lego#859]
I launched Lego from Docker. My request was accepted by Lets Encrypt, but I could not access the resulting certificates, as they seem stucked in the container.

I read in the doc that the certificates are stored in a `.lego` directory in the current working dir. However, as there is no `WORKDIR` specified within the `Dockerfile`, the working dir is `/` by default.

Therefore, it is impossible to fetch the content of the `.lego` directory with a volume mapping during `docker run ...`

Am I missing something? 

Thanks for your help.

**Comment by taoru** [comment]
> Therefore, it is impossible to fetch the content of the `.lego` directory with a volume mapping during `docker run ...`

Use `docker run -v /path/to/where/you/want/it:/ssl ... goacme/lego ... --path /ssl run` to store your certificates in `/path/to/where/you/want/it`

**Comment by edouardtheron** [comment]
Thank you @taoru I did not see this optional argument `--path` anywhere, must have missed it.

**Comment by Zyprexia** [comment]
> > Therefore, it is impossible to fetch the content of the `.lego` directory with a volume mapping during `docker run ...`
> 
> Use `docker run -v /path/to/where/you/want/it:/ssl ... goacme/lego ... --path /ssl run` to store your certificates in `/path/to/where/you/want/it`

Could you add this mount point to the docker image/container documentation? This is almost vital information needed to use the docker image/container. Thanks!
