### ISSUE TITLE
add support for zonomi as DNS provider

### ISSUE THREAD

**Issue by silvacraig** [go-acme/lego#892]
When you have bandwidth - it would be useful (for me) if you could add zonomi as a dnsprovider

**Comment by silvacraig** [comment]
http://zonomi.com/app/dns/dyndns.jsp
https://blog.rimuhosting.com/2017/12/06/letsencrypt-with-zonomi-and-rimuhosting-name-servers-using-hooks/

**Comment by silvacraig** [comment]
no progress

**Comment by ldez** [comment]
We (the lego maintainers) don't have an account in all DNS providers in the world.

By default, we do not add a DNS provider that we are not able to handle. It is therefore necessary that a contributor, having an account for the DNS provider, create a PR and be able to maintain the implementation for the DNS provider.

**Comment by urbancorax** [comment]
What exactly would you need to add zonomi to your list, please?

**Comment by ldez** [comment]
- a contributor with an account for the DNS provider
- a PR with the Go implementation of the DNS challenge for that DNS provider
- a contributor able to maintain the implementation for the DNS provider

**Comment by ldez** [comment]
Zonomi and RimuHosting are now supported.
