### ISSUE TITLE
Feature request: pre/post/deploy hook

### ISSUE THREAD

**Issue by bsloeserwij** [go-acme/lego#894]
Thank you for this great product.

We are working on an implementation of lego, but we miss an essential feature for our implementation. For our use case lego should run a shell script, when a certificate should be renewed.
This feature is similar to the certbot flags --pre-hook and --post-hook.
We also want to push the certificate to Hashicorp Vault when the certificate is actually been renewed. This feature is similar to the certbot flag --deploy.

**Comment by ldez** [comment]
Hello,

It's a duplicate of #427

A hook has been aded by the PR #845.

Take a look to https://go-acme.github.io/lego/usage/cli/examples/#to-renew-the-certificate-and-hook

**Comment by bsloeserwij** [comment]
The hook you are referring to is only for when a certificate is renewed.
We want to start acme-dns when a certificate is about to be renewed and stop acme-dns after the renewal procedure. Just to state the obvious, acme-dns runs as a systemd-service on the same machine as lego runs on.
