### ISSUE TITLE
Allow ignoring of invalid certificates in the acme-dns provider

### ISSUE THREAD

**Issue by lenovouser** [go-acme/lego#900]
In case of self-signed or expired certificates.

Currently it is possible to block yourself from requesting new certificates if you use a certificate generated by lego for your self-hosted ACME-DNS instance

cpu/goacmedns#5

**Comment by cpu** [comment]
:wave: I replied with [some thoughts](https://github.com/cpu/goacmedns/issues/5) on the `goacmedns` issue.

I don't think the Lego maintainers need to take any action based on this issue and would recommend that we consolidate discussion on https://github.com/cpu/goacmedns/issues/5

Thanks!
