### ISSUE TITLE
OTC DNS Provider always fails with timeout

### ISSUE THREAD

**Issue by fnmeissner** [go-acme/lego#902]
With v2.6.0 on OSX 10.14 I get the following error:

```
[INFO] [***] acme: use dns-01 solver
[INFO] [***] acme: Preparing to solve DNS-01
[INFO] [***] acme: Cleaning DNS-01 challenge
[WARN] [***] acme: error cleaning up: otc: Get https://dns.eu-de.otc.t-systems.com/v2/zones?name=***.: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Could not obtain certificates:
	acme: Error -> One or more domains had a problem:
[***] [***] acme: error presenting token: otc: unable to get zone: Get https://dns.eu-de.otc.t-systems.com/v2/zones?name=***.: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

When I open the url `https://dns.eu-de.otc.t-systems.com/v2/zones?name=***.` with HTTPie everything works as expected.

**Comment by ldez** [comment]
Hello, could you give a more real value for `***` to help us, thanks.

**Comment by fnmeissner** [comment]
Hi,

the domain name I requested had the format of `somedomain.hanko.io`.

For me, the registration works fine if I apply the changes from PR #903.

Anyhow, I don't understand why the CI tests are failing for the PR. The changes seem to be unrelated to the failing tests, but I must say I don't speak golang well.

Let me know if I can help.
