### ISSUE TITLE
Lightsail: Make DNS_ZONE optional, use domain name from Caddy instead

### ISSUE THREAD

**Issue by nurtext** [go-acme/lego#911]
I'm trying to use Caddy with tls.dns.lightsail for multiple domains with wildcard certificates. This won't work because DNS_ZONE has to be set. However it should be possible to use the domain name from Caddy itself.

**Comment by ldez** [comment]
I think it's an issue with Caddy not lego.

**Comment by nurtext** [comment]
@ldez AFAIK the plugin requires the DNZ_ZONE variable to be set, not Caddy itself. Or am I wrong?

**Comment by ldez** [comment]
I don't know how Caddy works on that but from the point of view of the DNS challenge (it's not a plugin) for Lightsail, the `DNS_ZONE` is require.

**Comment by nurtext** [comment]
Thx for explaining.
