### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by andig** [go-acme/lego#921]
Just noticed https://github.com/go-acme/lego/blob/3edb75872df36444f95c25f88c6df325de89be11/certificate/authorization.go#L66 in one of my logfiles. Looks like broken english and I couldn't figure out what it's trying to tell me?

**Comment by ldez** [comment]
The message may appear if a challenge fails: in this case, lego disables permissions.
Some of these authorizations may have already been consumed by the process and so in this it is not possible to disable them, this is not a problem.
The reason for the real failure of the challenge is written in another log message.
