### ISSUE TITLE
Vultr API call failed by Invalid record type in v2.7.0

### ISSUE THREAD

**Issue by iquiw** [go-acme/lego#931]
I got API error when using Vultr DNS in lego v2.7.0. Lego v2.6.0 works without problem.

```
acme: error presenting token: vultr: API call failed: Invalid record type
```

[govultr API](https://github.com/vultr/govultr/blob/2def36bf8b1c11c33a73fd75a0ecc337e5caf619/dns_records.go#L35) takes type as the 3rd argument.

```go
func (d *DNSRecordsServiceHandler) Create(ctx context.Context, domain, recordType, name, data string, ttl, priority int) error {
```

while [the call](https://github.com/go-acme/lego/blob/v2.7.0/providers/dns/vultr/vultr.go#L91) seems to specify type as the 4th argument.

```go
	err = d.client.DNSRecord.Create(context.Background(), zoneDomain, name, "TXT", value, d.config.TTL, 0)
```

**Comment by ddymko** [comment]
This is my fault when I updated to the new govultr client. I accidentally swapped `recordType` and `name`. Sorry about that!
