### ISSUE TITLE
Example for http01 custom provider?

### ISSUE THREAD

**Issue by enugentdt** [go-acme/lego#933]
Hiya!

Just wanted to ask a quick question. Are there any examples for writing a custom provider for the http01 challenge, as there are with the dns01 challenge?

I'm trying to get my own provider set up, but I'm having some difficulty understanding what steps I would have to go through. If there are already docs, though, please feel free to just let me know where I should be reading and to close this issue.

Thanks!

**Comment by burgesQ** [comment]
The best example I found for my own help was the one already present in the repo  : 
https://github.com/go-acme/lego/blob/master/challenge/http01/http_challenge_server.go
