### ISSUE TITLE
Vultr API error TXT record needs quotes in v2.7.1

### ISSUE THREAD

**Issue by jesswonky** [go-acme/lego#939]
I'm getting an error with Vultr DNS in v2.7.1.

```
acme: error presenting token: vultr: API call failed: Unable to add record: Record data must be enclosed in quotes
```

I believe that the value for TXT records sent to the Vultr API must be enclosed in quotes.

I saw this same error yesterday when adding a TXT record in ansible. Adding quotes around the TXT value worked and the quotes were not added to the records data.

**Comment by ldez** [comment]
ping @ddymko

**Comment by ddymko** [comment]
@jesswonky @ldez 

This looks like it is an issue with the Vultr API itself where it is not handling strings as gracefully as it should.

I created a fix for the time being within lego to append quotes to the name variable to resolve this issue and handle record creation with TXT.
