### ISSUE TITLE
Pass information about renew certs to renew hook

### ISSUE THREAD

**Issue by QuantumGhost** [go-acme/lego#944]
I'm writing a renew hook for lego and have encounter some issues.
I'd like to copy cert for certain domains to configuration directory after renew is succeeded. However, it seems that there's no way to know which domain is renewed in hook. 
Thus, I think lego should pass information about renew certs to hook script.
I believe the best way to achieve this is setting environment variable and pass it to hooks.

I propose those variables passed to hooks:

- `LEGO_CERT_DOMAIN`: for renewed domain name
- `LEGO_CERT_EMAIL`: for Let's Encrypt email address
- `LEGO_CERT_PATH`: for new certificate file path
- `LEGO_CERT_KEY_PATH`: for certificate key file path

**Comment by wezm** [comment]
This can probably be closed now.

**Comment by ldez** [comment]
closed by  #1108
