### ISSUE TITLE
Cannot be built with GOPROXY enabled

### ISSUE THREAD

**Issue by fd0** [go-acme/lego#947]
Hi,

I've tried to build lego with `GOPROXY=https://proxy.golang.org` and noticed that this fails (Go 1.12.7 and Go 1.13):

```
% cd cmd/lego
% GORPOXY=https://proxy.golang.org go build
[...]
go: golang.org/x/lint@v0.0.0-20190511005446-959b441ac422: unexpected status (https://proxy.golang.org/golang.org/x/lint/@v/v0.0.0-20190511005446-959b441ac422.info): 410 Gone
[...]
go: golang.org/x/time@v0.0.0-20190513212739-9d24e82272b4: unexpected status (https://proxy.golang.org/golang.org/x/time/@v/v0.0.0-20190513212739-9d24e82272b4.info): 410 Gone
[...]
go: error loading module requirements

```

This is caused by an invalid timestamp in the `go.mod` of https://github.com/cloudflare/cloudflare-go in `v0.9.4`, I've opened an issue over there:

https://github.com/cloudflare/cloudflare-go/issues/335

This is just to let you know that there's an issue, after it is resolved it'd be nice to have a new release referencing the new release of `cloudflare-go` so that we can use the proxy again.

Thanks for your work!

**Comment by ldez** [comment]
Remember that `replace` directive are not transitive.

You have to add this to your project:

```
replace (
	golang.org/x/lint => golang.org/x/lint v0.0.0-20190409202823-959b441ac422
	golang.org/x/time => golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
)
```

**Comment by fd0** [comment]
Ah dang! I forgot to check the pull requests of both projects :(

Sorry about the noise!
