### ISSUE TITLE
Release 3.0.1 has "detach"-ed user-agent

### ISSUE THREAD

**Issue by mhoran** [go-acme/lego#950]
It looks like release 3.0.1 was cut after the release was [detached](https://github.com/go-acme/lego/commit/bd238c80e8907d0b2b1c841d44e47f7b2ef87bc4), so the user-agent is incorrectly set. I'm also not sure whether the `-1` in the version was intended. I wanted to check on these issues before packaging up for FreeBSD.

**Comment by ldez** [comment]
Hello,

There was a problem when creating the tag v3.0.1, but now with the use of go modules I cannot recreate the same tag, so I create a tag with `-1`.

**Comment by mhoran** [comment]
> There was a problem when creating the tag v3.0.1, but now with the use of go modules I cannot recreate the same tag, so I create a tag with -1.

Got it, thanks!

> The v3.0.1-1 is a semver valid syntax.

Yep, no concerns there. I think FreeBSD's port/package system should be OK with this as well; just wanted to double check it was intended (even if an accident.)

Should I worry about the detached user agent? It doesn't seem like a huge deal but if you'll cut another release to fix that then I'll hold off. I'm blocked on a FreeBSD committer picking up my bump anyway.

**Comment by ldez** [comment]
And yes I made a second mistake, it's not the good commit...


So:
- I will create a tag `v3.0.1+1`
- I will create a clean release v3.0.2.

Sorry for the inconvenience

**Comment by ldez** [comment]
I created a clean version v3.0.2.

`v3.0.1`, v3.0.1-1`, `v3.0.1+1` they are considered invalid.

Sorry again for the inconvenience and thanks to your vigilance.
