### ISSUE TITLE
Request certificate only if outdated

### ISSUE THREAD

**Issue by SoerenBusse** [go-acme/lego#958]
Hey there,

I'm using the go-acme cli tool to request certificates using my own DNS server.
 
I noticed that the cli tool is requesting a new certificate everytime you run the command. Is this the expected behaviour? Or is there a way to only request new certificates from let's encrypt if the old one is due to renewal, so 30 days before like certbot does?

**Comment by ldez** [comment]
Hello,

you have to use the command `renew`.

https://go-acme.github.io/lego/usage/cli/examples/

```
NAME:
   lego - Let's Encrypt client written in Go

USAGE:
   lego [global options] command [command options] [arguments...]

COMMANDS:
     run      Register an account, then create and install a certificate
     revoke   Revoke a certificate
     renew    Renew a certificate
     dnshelp  Shows additional help for the '--dns' global option
     list     Display certificates and accounts information.
     help, h  Shows a list of commands or help for one command
```
