### ISSUE TITLE
DNS Resolution on DNS-Challenge not using authoritative domain nameservers

### ISSUE THREAD

**Issue by vrubiella** [go-acme/lego#959]
I'm having problems with pre-validation TXT records propagation with some new domains.
I'm running lego-client inside kubernetes cluster pod and I'm trying to fix it with dnsPolicies because problems seems to be related with kube-dns caches, but:

Why does lego not use the same strategy as LetsEcnrypt and asks to the authoritative domain name server?

This should be the most real pre-check and easy to manage for clients.

Log sample:
```
2019/09/05 08:20:00 [INFO] [rubiella.es]acme: Checking DNS record propagation using [10.35.240.10:53]
2019/09/05 08:48:12 [INFO][rubiella.es] acme: Checking DNS record propagation using [10.35.240.10:53]
2019/09/05 09:08:21 [INFO] [rubiella.es] acme: Checking DNS record propagation using [10.35.240.10:53]
2019/09/05 09:14:03 [INFO] [rubiella.es]] acme: Checking DNS record propagation using [10.35.240.10:53]
2019/09/05 09:24:14 [INFO] [rubiella.es] acme: Checking DNS record propagation using [10.35.240.10:53]
2019/09/05 09:26:03 [INFO] [rubiella.es]acme: Checking DNS record propagation using [10.35.240.10:53]
2019/09/05 09:38:19 [INFO] [rubiella.es] acme: Checking DNS record propagation using [10.35.240.10:53]
```

10.35.240.10:53 is nameserver defined on /etc/resolf.conf automaticaly by kubernetes.

**Comment by vrubiella** [comment]
Debugging code and errors messages with more detail I think the problems is that this message it's a bit confusing: 
```
"Checking DNS record propagation using [NAMESERVER]".
```

Because "NAMESERVER" is used just for retrieve SOA and after that, waiting check is really using SOA registry:
```
"NS g.nic.es. did not return the expected TXT record [fqdn: _acme-challenge.rubiella.es., value: XXX]"
```
Therefor the problem is that when check ask for SOA on new domains, still returns nic.es.

Is there any way via code to define a resolve without modifying the resolve.conf file?

**Comment by ldez** [comment]
```
   --dns.resolvers value        Set the resolvers to use for performing recursive DNS queries. Supported: host:port. The default is to use the system resolvers, or Google's DNS resolvers if the system's cannot be determined.
```
https://go-acme.github.io/lego/usage/cli/

**Comment by vrubiella** [comment]
OK thanks, I'm using as a library, in case it can be useful for others:
```
l.AcmeClient.Challenge.SetDNS01Provider(provider,dns01.AddRecursiveNameservers(dns01.ParseNameservers(ourNameSevers)))
```
It seems that this will be enough. Thank you!
