### ISSUE TITLE
linodev4: Random propagation timeouts

### ISSUE THREAD

**Issue by PaulAcre88** [go-acme/lego#960]
Ubuntu 18.04. Using the "linodev4" DNS authenticator.

When I try to generate a new certificate I see a message like
```
"[INFO] Wait for propagation [timeout: 9m0s, interval: 15s]"
```
Where is that "timeout" number coming from? If I stop (control-c) and restart the the program, the "timeout" seemingly picks up where it left off? Very mysterious.

I need that number to always be > 15 minutes for Linode's DNS servers (very long propagation times).

Command :

```
LINODE_TOKEN_FILE=/etc/lego/linode.key lego --dns="linodev4" --path="/etc/lego" --email="me@example.com" --accept-tos --domains='example.com' --domains='*.example.com' run
```

I've experimented with different  valules for environment variables : `LINODE_HTTP_TIMEOUT` and `LINODE_POLLING_INTERVAL`

Also different values for options : `--http-timeout` and `--dns-timeout`

None seems to have an effect on the "timeout".

**Comment by ldez** [comment]
Hello,

in linode the propagation timeout is not configurable but I don't know why.

https://github.com/go-acme/lego/blob/a5a29187fea9f555ea43fae16ca65066c452d330/providers/dns/linodev4/linodev4.go#L100-L113
