### ISSUE TITLE
More consistent logging: severity missing

### ISSUE THREAD

**Issue by afreudenreich** [go-acme/lego#969]
When I try to request a certificate for a domain, which fails a DNS lookup, I get following output:
```
2019/09/17 12:25:45 [INFO] [<bad.domain>] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/8733359
2019/09/17 12:25:45 [INFO] [<bad.domain>] acme: Could not find solver for: tls-alpn-01
2019/09/17 12:25:45 [INFO] [<bad.domain>] acme: use http-01 solver
2019/09/17 12:25:50 [INFO] [<bad.domain>] acme: Trying to solve HTTP-01
2019/09/17 12:25:50 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/8733359
2019/09/17 12:25:50 Could not obtain certificates:
	acme: Error -> One or more domains had a problem:
[<bad.domain>] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for <bad.domain>, url: 
```

For easier log parsing the last entry should at least contain the severity in square brackets. E.g. like this:
```
2019/09/17 12:25:50 [ERROR] Could not obtain certificates:...
```

**Comment by ldez** [comment]
NXDOMAIN -> Non eXistant DOMAIN

So you need to create the A record for your domain.

**Comment by afreudenreich** [comment]
I am not talking about the content - I understood the log message.
I just thought it would be nice to have a consistent log format as the error message is missing the [severity] field. It makes log analysis with automated tools a lot harder, if fields in a log event are not consistent.
