### ISSUE TITLE
Running behind a reverse proxy (http-01)

### ISSUE THREAD

**Issue by dmke** [go-acme/lego#973]
Hi,

when lego runs behind a reverse proxy, [its DNS rebind attack prevention](https://github.com/go-acme/lego/blob/v3.0.2/challenge/http01/http_challenge_server.go#L67) causes the ACME validation to fail:

```console
$ lego ... --http --http.port 127.0.0.1:402
...
[WARN] Received request for domain 127.0.0.1 with method GET but the
  domain did not match any challenge. Please ensure your are passing the
  HOST header properly.
...
```

This is because a typical proxy directive for Apache will pass the [original `Host` header as `X-Forwarded-Host`](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers), and change the pass a new `Host` header containing the host of the proxied URL:

```apache
ProxyPass "/.well-known/acme-challenge/" "http://127.0.0.1:402/.well-known/acme-challenge/"
```

(NGINX does the same, other servers might behave similiar).

For Apache, there's a workaround in form of the [`ProxyPreserveHost`](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost), but that might confuse some legacy applications.

In this particular setup I'd like to have the option to change the header name used to implement DNS rebind prevention, i.e. sth. similar to:

```console
$ lego ... --http --http.port 127.0.0.1:402 --http.proxy-header X-Forwarded-Host
``` 

To make matters worse (or [better?](https://xkcd.com/927/)), [RFC 7239](https://tools.ietf.org/html/rfc7239) tries to standardize the various proxy/forwarding headers into a single `Forwarded` header, but with different semantics.

I'm currently working on a PR addressing this issue ([WIP here](https://github.com/go-acme/lego/compare/master...digineo:http01-proxy)), but that's not finished/polished yet. I would like to have some early feedback though (in particular, whether I should move the `Fowarded` header parsing into a separate package) :-)

**Comment by ldez** [comment]
Your proposition seems similar to https://github.com/go-acme/lego/pull/399

I recommend to use the new generation of reverse proxy or web server like Traefik or Caddy.

**Comment by dmke** [comment]
> Your proposition seems similar to #399

The idea is the similar, yes. My code currently is strictly opt-in: If you don't pass `--http.proxy-header` (or call `(*ProviderServer).SetProxyHeader()`), nothing happens (i.e. there's no automatic fallback to from `Host` to `X-Forwarded-Host`).

> I recommend to use the new generation of reverse proxy or web server like Traefik or Caddy.

In general, I'd agree.

Some environments require specific features not available in Træfik nor Caddy though, and putting another proxy in front of an existing application proxy is just not an option (and not only because of technical reasons...). I'm currently handling the transition of such systems from hlandau/acme to lego (among others, a 3cx phone system, which bundles its own NGINX server; an [RT](https://bestpractical.com/request-tracker), which works best behind an Apache; and many other FastCGI applications). Many of these systems can use `dns-01`, but there are still some outliers left.

Now, if you're telling me, that lego is not a good fit for those system, I can go and look for alternatives.

**Comment by mholt** [comment]
@dmke 

> Some environments require specific features not available in Træfik nor Caddy though

Can I ask what is lacking? We'll see what can be done to fix that.

@ldez I do think we should consider this proposal though, as it is is opt-in, and has a much better implementation than the previous attempt, along with tests.

**Comment by dmke** [comment]
> Can I ask what is lacking?

On top of my head I remember uWSGI support for Python apps lacking. Also the rewrite engine in Apache is much more powerful (compared to Caddy), especially in combination with access control, (e.g. routing request coming from the office directly to an internal server, and require basic auth for other requests).

I'd have to log into some servers to dig out more samples (next week, when I'm back in the office), but it's either legacy, or enterprise, or legacy enterprise applications tightly integrated with a specific server software...

**Comment by mholt** [comment]
(Not to side-track the discussion but I do want to respond) @dmke 

> On top of my head I remember uWSGI support for Python apps lacking.

True, this is tricky in Go because I don't think there's any libraries that quite do what we need for this yet, although I know there has been work in this direction the last few years. I'll have to look and see what has come of that.

> Also the rewrite engine in Apache is much more powerful  ... especially in combination with access control, (e.g. routing request coming from the office directly to an internal server, and require basic auth for other requests).

We've vastly improved these in Caddy 2 (beta 2 was released on Friday - check it out!) so now the rewrite capabilities in Caddy 2 should be able to meet your needs. (And basic auth is returning in a future beta release, will be more flexible than in Caddy 1 as well.) If not, file an issue in the Caddy repo and we'll take care of it!

**Comment by dmke** [comment]
As I said, it's those pesky legacy apps, which all need special care. Modern apps I can bundle in a Docker container, let them bundle their own web server and call it a day :-)

> We've vastly improved [rewrite capabilities] in Caddy 2 (beta 2 was released on Friday - check it out!)

That's great to hear, and I will!

---

Now, back to the issue at hand: I plan to expand the parser tests a bit more and add at least a simple test for `(*http01.ProviderServer).serve` covering the three `domainMatcher` implementations.

**Comment by ldez** [comment]
Just a quick question: are you using lego as CLI or as lib?

**Comment by dmke** [comment]
Both, but this issue is mainly for the hosts we don't own ourselves (where we, hopefully, hand over the administration at some point in the future). Here, we're using lego as a CLI.

The hosts I plan to use our CLI tool on (which uses lego as library) have a more sane configuration :-)
