### ISSUE TITLE
failure with ovh DNS challenge

### ISSUE THREAD

**Issue by dakky** [go-acme/lego#975]
Hello 
I have an issue with the dns challenge using OVH as provider.

The error is:
`acme: error presenting token: ovh: error when call api to add record (/domain/zone/XXXXXXX/record): json: cannot unmarshal number [10digits here] into Go struct field Record.id of type int`

Some background:
* basically using traefik which uses lego as acme backend
* using it on ARM7 
* already recreated the api keys at OVH
* it **seems** that this is **not** an issue on x64 arch. I have the same setup on another x64 host and there i don't see this error (although i'm not 100% shure, if i need a ssl cert renewal at the moment)

**Comment by ldez** [comment]
Already fixed by https://github.com/go-acme/lego/pull/972

Will be a part of the v3.1

**Comment by dakky** [comment]
Is there a ETA dir 3.1? My certs are running out 😅

**Comment by ldez** [comment]
I'm waiting for #985
