### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by mouzfun** [go-acme/lego#978]
I'm unable to download the package due to broken dependency. I believe github.com/labbsr0x/goh force-pushed to master and deleted the specified commit.

How to reproduce:

```
$ docker run --rm -it --entrypoint /bin/bash -w /test golang:1.12 
root@f26d74d80cdb:/test# go mod init test
go: creating new go.mod: module test
oot@f26d74d80cdb:/test# go get github.com/go-acme/lego/v3 |& grep -E 'error|unknown'
go: finding github.com/go-errors/errors v1.0.1
go: github.com/labbsr0x/goh@v0.0.0-20190417202808-8b16b4848295: unknown revision 8b16b4848295
go: error loading module requirements
```

**Comment by ldez** [comment]
The problem is ready fixed https://github.com/go-acme/lego/pull/971

**Comment by mouzfun** [comment]
Maybe it's time to push the tag so that people can get latest version?

I think most people just do go get, and it fetches latest tagged version, not HEAD of the master.
at least intelisense IDEs do the same thing. Package is still essentially broken for most users.
