### ISSUE TITLE
Cloudflare and restricted API tokens

### ISSUE THREAD

**Issue by dmke** [go-acme/lego#984]
## Context

Cloudflare has two API access modes:

1. API key (i.e. global access to everything related to a user's account), and
2. API token (i.e. scoped access to selected resources).

The latter mode is available since [at least Aug 30, 2019](https://blog.cloudflare.com/api-tokens-general-availability/) promoting the principle of least privilege. Lego has support for both access modes (`CLOUDFLARE_EMAIL` + `CLOUDFLARE_API_KEY` since v0.3.0, and `CLOUDFLARE_API_TOKEN` since v3.1, #937).

To create a API token with minimal scope, the following steps are needed:

- log into their dashboard, go to account settings, create API token
- grant the following permissions:
  - Zone / Zone / Read
  - Zone / DNS / Edit
- select resources (zone names for the domains for which Lego should obtain certificates):
  - Include / Specific zone / *zone name*

## Problem

When selecting the domains, you can alternatively choose "Include / All zones from an account / *account name*". Following the principle of least privilege, I naturally chose *not* to do this. Host A should not be able to change DNS settings for host B.

However, here a problem arises: in order for Lego to `Present()`/`CleanUp()` DNS challenge tokens, it needs to lookup the zone ID. Cloudflare's Go client library has a dedicated method for this job: [`(*cloudflare.API).ZoneIDByName`](https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L138-L139), so that's what Lego uses.

Internally, `ZoneIDByName()` queries the `/client/v4/zones` endpoint (with `name` parameter) to search *all* zones and filter for the apex name. Given a restricted scope for the API token, this endpoint access fails with the following error message:

> Actor `com.cloudflare.api.token.<token id omitted>` requires permission
> `com.cloudflare.api.account.zone.list` to list zones

## Workaround

If I change the API token scope to "include all zones from account xyz", the listing succeeds, `ZoneIDByName` can lookup the ID, and Lego can proceed to create/delete the DNS records.

This however defeats the purpose of having scoped API tokens in the first place (at least a bit, their API has many more endpoints): Now host A can change the DNS settings for host B (and vice versa).

*(Note: This propably applies only to users with multiple zones and/or domains spread to multiple machines, running more than one Lego instance...)*

## Cloudflare's reaction

I've asked the Cloudflare support whether this issue could be solved in their API (the zone endpoint should allow listing zones for which Zone/Zone/Read permissions were granted), and they responded with the following:

> [...] the permission to access the zone does not equal permission to list it.
> [...] our engineers have come up with a different solution for you to try.
>
>> The Lego client should implement a way to optionally provide a Zone ID, which would skip the need for a lookup. That way, there would be no problem with insufficient permissions. Zone ID is immutable for the life of the zone within an account, so this is something that has no problem being put into a config.

## Implementation details

The proposed solution could be implemented with a whitespace-delimited list of `NAME=ID` pairs as input for an internal `map[string]string`, which takes precedence over `ZoneIDByName`.

Having whitespace (including line breaks) allows the name/ID pairs to be read directly from an `CLOUDFLARE_ZONE_MAP` envionment variable, or to be neatly placed in a file (one entry per line) and accessed through a `CLOUDFLARE_ZONE_MAP_FILE` pointer. I believe, Lego already uses a similar mechanism for credentials, doesn't it?

```console
$ export CLOUDFLARE_API_TOKEN=xxxx CLOUDFLARE_ZONE_MAP="example.com=yyyy example.org=zzzz"
$ lego --dns cloudflare -d example.com -d www.example.com -d example.org -d www.example.org ...

## or

$ echo  >cf.map example.com=yyyy
$ echo >>cf.map example.org=zzzz
$ export CLOUDFLARE_ZONE_MAP_FILE="$(pwd)/cf.map"
$ lego --dns cloudflare -d example.com ...
```

The internal map has an additional benefit: it can act as a cache, even if the user didn't provide a name/ID mapping to begin with (or has chosen to use an API key with wider privileges):

Currently `CleanUp()` calls `ZoneIDByName()` again, after `Present()` did it a few moments earlier. The result would in all likelihood be the same as the previous call (making it redundant), as one would have to destroy and recreate the zone at Cloudflare (and in doing so disturbing the ACME dance, which would cause the validation to fail anyway). Unless I'm not aware of some insane use case which does exactly this, I assume we can memoize the result of the first `ZoneIDByName()` call :-)

## Alternative solution

It is also possible to create a pair of API tokens:

- one with Zone/Zone/Read privileges (for all Zones; no other privileges), shared among multiple Lego instances, and
- one with Zone/DNS/Edit privileges (for a selected list of Zones), private to each Lego instance.

I've found naming (and documenting) this harder, although the implementation is straight forward as well.

@ldez, @mholt: What do you think?

**Comment by ldez** [comment]
I would always take the solution with the least configuration and where the creation of certificates is the most automated possible.

**Comment by dmke** [comment]
After thinking about this a bit, I agree. Keeping the configuration on Lego's side simple is kinda important.

How would you name the environment variables? `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_ZONE_API_TOKEN`? (With v3.1 being not released yet, there might also be an opportunity to name them consistently `CLOUDFLARE_{ZONE,DNS}_API_KEY`).

**Comment by ldez** [comment]
I agree with `CLOUDFLARE_{ZONE,DNS}_API_KEY`

**Comment by dmke** [comment]
Here's a quick first pass. I still get some test failures, I need to look further into (tomorrow).

One question: How can I perform a live test (just for Cloudflare)?
