### ISSUE TITLE
Add support for dynu.com

### ISSUE THREAD

**Issue by gdeverlant** [go-acme/lego#986]
Is it possible to add this one?

https://www.dynu.com/en-US/Support/API

**Comment by gdeverlant** [comment]
I found this library which might be of help to fasten the implementation.

https://github.com/adm-github/godynu

**Comment by gdeverlant** [comment]
To have an idea of the steps to follow I also found as an inspiration for you this Powershell plugin in Posh-Acme project.

https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/DnsPlugins/Dynu.ps1

**Comment by dmke** [comment]
The adm-github/godynu client needs a lot of work to become useful in Lego:

- it is not a library; the API access methods not packaged separately and are only available as Cobra commands
- it uses the v1 API, which seems to be unsupported by Dynu
- the code itself could be improved (I could think of better ways to generate JSON than `[]byte(fmt.Sprintf(`{"name":"%s", "ipv4_address": "%s"}`, f_domain, f_ipv4))` :-))

The Posh-ACME client on the other hand looks more appropriate.

@gdeverlant: I can help adding this provider. Do you have a Dynu account and can help me test the implementation?

**Comment by gdeverlant** [comment]
@dmke Just go to https://www.dynu.com and register for a free account. Download the IP Updater App and set the account on your desktop. Or I can help you with this when you have a release.

I tried to do it with Posh-ACME and it worked flawlessly.

**Comment by gdeverlant** [comment]
Before you test anything you need to create a dynamic subdomain name like test.dynu.net and go in the API credentials to get your username and password.

**Comment by gdeverlant** [comment]
After you could test your go implementation against your dynamic domain name.

**Comment by dmke** [comment]
@gdeverlant, I try not to register on any arbitrary site and install obscure software until it becomes unavoidable. I get enough spam as it is :-)

I was more thinking of implementing the provider to the spec and package it into a small test binary for you to run (I don't want to see your credentials), which does the interesting bits without the ACME overhead (setting up a TXT record, verifying its presence and deleting it afterwards).

**Comment by gdeverlant** [comment]
Trust me I received only one email from them they won't bother you but yes I could give you my credentials for test if you really don't want to register.

**Comment by ldez** [comment]
We don't really need this lib, we can create a small client based on the API documentation.

But we need user to test the implementation.

**Comment by dmke** [comment]
Sorry for the radio silence, I've been a bit busy the last two weeks with different things.

FYI, [`dmke:lego/dns01-dynu`](https://github.com/dmke/lego/tree/dns01-dynu) currently contains a first iteration on the client, with support for both API key and OAuth authorization. It still misses tests, which I'll probably finish this week (provided nothing else comes up).

**Comment by tavinus** [comment]
Hi,
I wonder how I can compile[ traefik](https://github.com/containous/traefik) with @dmke 's Dynu patch to test it. I will problably need to run this until it gets upstream.   
  
I have been using [Dynu](https://www.dynu.com) with [acme.sh](https://github.com/Neilpang/acme.sh) for a long time.
Here is the DNS api implementation for it (maybe not needed anymore)  
https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_dynu.sh  
  
I opened a ticket with Dynu about adding support to traefik yesterday. I digged this today and linked this issue there minutes ago.  
  
How long do you think it will take for this to get all the way upstream to traefik?

**Comment by dmke** [comment]
@tavinus,

To compile Træfik with my patch, you can try the following (warning, here be dragons):

```console
$ git clone https://github.com/containous/traefik.git && cd traefik
$ go mod edit -replace=github.com/go-acme/lego=github.com/dmke/lego@dns01-dynu
$ go get ./...
$ make
```

This should get you a `dist/traefik` file, if I understand their Makefile correctly (I haven't tested this).

My patch is nearly finished, so building and using Træfik this way might already work. If you do try this, please report back (you'll need either `DYNU_API_KEY`, or `DYNU_OAUTH_CLIENT_ID` and `DYNU_OAUTH_SECRET`).

I plan to finish this today, i.e. submitting a PR for review. To get these changes into Træfik properly, the PR needs to be reviewed and merged, then it needs to decided when we release Lego v3.2<sup>1</sup>, and after that someone needs to update the Lego dependency in the `containous/trafik` repo (that's a separate PR, review, merge, release process).

<sup>(1)</sup> I would like to also include #990 in v3.2, but I haven't started that yet.

**Comment by tavinus** [comment]
Hi. I never used Go, so I may be just "idioting".  
  
Got this error
```
$ git clone https://github.com/containous/traefik.git && cd traefik
Cloning into 'traefik'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 52543 (delta 1), reused 1 (delta 1), pack-reused 52540
Receiving objects: 100% (52543/52543), 47.70 MiB | 8.26 MiB/s, done.
Resolving deltas: 100% (30828/30828), done.
```
```
$ go mod edit -replace=github.com/go-acme/lego=github.com/dmke/lego@dns01-dynu
```
```
$ go get ./...
go: finding github.com/dmke/lego dns01-dynu
go: finding github.com/dmke/lego dns01-dynu
go: errors parsing go.mod:
/home/tavinus/work/traefik/go.mod:122: replace github.com/dmke/lego: version "v1.2.2-0.20191109205526-93bb67711ca1" invalid: go.mod has post-v1 module path "github.com/go-acme/lego/v3" at revision 93bb67711ca1
```

Is this some kind of merging problem?

**Comment by gdeverlant** [comment]
How is this going?

**Comment by dmke** [comment]
Sorry, I'm currently busy with other things, maybe I can continue here some time next week...

**Comment by ldez** [comment]
@dmke do you need some help to finish the provider?

**Comment by dmke** [comment]
@ldez: I'd need more hours in a day :-)

If you want to take a stab at this, please do. I have some bits ready in https://github.com/dmke/lego/tree/dns01-dynu (I'm not sure where I left; I also don't mind throwing that code away).

**Comment by ldez** [comment]
@dmke could you open a PR, like that I will be able to commit on your branch.

**Comment by tavinus** [comment]
Good to see this supported.  
I will test soon enough.  
Good job!
