### ISSUE TITLE
DANE support when requesting certificates(static private key)

### ISSUE THREAD

**Issue by prometheanfire** [go-acme/lego#988]
I'm not sure if cert-only is done with a static csr or not.  The goal is to have an unchanging private key so that dns records don't need to update so often.

The following seems like an OK refrences to know if lego is already generating certs in the 'supported' way.

https://icicimov.github.io/blog/server/Lets-Encrypt-and-DANE/
https://www.internetsociety.org/blog/2016/01/lets-encrypt-certificates-for-mail-servers-and-dane-part-1-of-2/
https://www.internetsociety.org/blog/2016/03/lets-encrypt-certificates-for-mail-servers-and-dane-part-2-of-2/

**Comment by dmke** [comment]
I don't know the specific requirements for private keys used to sign DANE records, but Lego's CLI has a `--csr` flag, which allows you to provide your own CSR.

This way, you can have the corresponding private key under your full control. Note that `--csr` and `--domain` are mutually exclusive (the CSR already contains domains in the Subject and SAN fields).

You can also pass `--reuse-key` to, well, reuse the key Lego has previously generated. You'll find it at `.lego/certificates/$domain.key`. You'll need to call `lego ... -d $domain run` once for this key to exist.

**Comment by dmke** [comment]
@prometheanfire,

I've looked into the resources a bit deeper, and I've concluded there's nothing speaking against using the certificate generated by Lego for DANE/TLSA records.

As mentioned above, you need decide whether you provide your own CSR, or whether Lego should reuse the key generated in an earlier invocation. In both cases, you can extract the public key from the certificate file `.lego/certificates/$domain.crt`, as mentioned in the [first linked article](https://icicimov.github.io/blog/server/Lets-Encrypt-and-DANE/).

(*N.B. You can also extract the public key from the `.key` file, but the concrete command line arguments largely depend on the key type (RSA vs. ECDSA) and the version of OpenSSL used.*)

**Comment by prometheanfire** [comment]
sounds good, thanks for confirming.  guess bugging traefik about this is the next step.
