### ISSUE TITLE
Add DNS Support for servercow

### ISSUE THREAD

**Issue by jhartlep** [go-acme/lego#990]
Hi,
I have added the DNS Support for servercow some time ago to acme.sh (https://github.com/Neilpang/acme.sh/blob/master/dnsapi/dns_servercow.sh).

Could you please add this to lego?

I would try to do it by myself, but I am not firm with golang :(

https://cp.servercow.de/client/plugin/support_manager/knowledgebase/view/34/dns-api-v1/7/

**Comment by dmke** [comment]
I can help adding this, but I'll need help with testing. Do you have a servercow account and can run a small test app?

**Comment by jhartlep** [comment]
Hi, yes, I have a servercow account and I can run the tests

**Comment by ldez** [comment]
@jhartlep are you still able to help us to create and test a Servercow provider?

If yes could you run the following script and give me output (be careful to hide your username and your password):

<details>
<summary>servercow_dump.sh</summary>

```bash
#!/usr/bin/env bash

DOMAIN="example.org"
SERVERCOW_USERNAME="username"
SERVERCOW_PASSWORD="password"

# get initial state
echo 'get initial state'

curl -v "https://api.servercow.de/dns/v1/domains/${DOMAIN}" \
  -H "X-Auth-Username: ${SERVERCOW_USERNAME}" \
  -H "X-Auth-Password: ${SERVERCOW_PASSWORD}" \
  -H 'Content-Type: application/json'

echo

# add record
echo 'add record'

curl -v -X POST "https://api.servercow.de/dns/v1/domains/${DOMAIN}" \
  -H "X-Auth-Username: ${SERVERCOW_USERNAME}" \
  -H "X-Auth-Password: ${SERVERCOW_PASSWORD}" \
  -H 'Content-Type: application/json' \
  --data '{"type":"TXT","name":"_acme-challenge.sample","content":"acbdefghijklmnopqrstuvwxyz","ttl":20}'

echo

# get records
echo 'get records'

curl -v -X GET "https://api.servercow.de/dns/v1/domains/${DOMAIN}" \
  -H "X-Auth-Username: ${SERVERCOW_USERNAME}" \
  -H "X-Auth-Password: ${SERVERCOW_PASSWORD}" \
  -H 'Content-Type: application/json'

echo

# update record
echo 'update records'

curl -v -X POST "https://api.servercow.de/dns/v1/domains/${DOMAIN}" \
  -H "X-Auth-Username: ${SERVERCOW_USERNAME}" \
  -H "X-Auth-Password: ${SERVERCOW_PASSWORD}" \
  -H 'Content-Type: application/json' \
  --data '{"type":"TXT","name":"_acme-challenge.sample","content":["acbdefghijklmnopqrstuvwxyz", "txtxtxtxtxtxtxt"],"ttl":20}'

echo

# get records
echo 'get records'

curl -v -X GET "https://api.servercow.de/dns/v1/domains/${DOMAIN}" \
  -H "X-Auth-Username: ${SERVERCOW_USERNAME}" \
  -H "X-Auth-Password: ${SERVERCOW_PASSWORD}" \
  -H 'Content-Type: application/json'

echo

# delete record
echo 'delete record'

curl -v -X DELETE "https://api.servercow.de/dns/v1/domains/${DOMAIN}" \
  -H "X-Auth-Username: ${SERVERCOW_USERNAME}" \
  -H "X-Auth-Password: ${SERVERCOW_PASSWORD}" \
  -H 'Content-Type: application/json' \
  --data '{"type":"TXT","name":"_acme-challenge.sample"}'

echo
```

</details>

**Comment by jhartlep** [comment]
Hi @ldez ,
here are the curl responses. looks fine for me. Do you also need the curl -v output?

[getInitialState.txt](https://github.com/go-acme/lego/files/4176739/getInitialState.txt)
[addRecord.txt](https://github.com/go-acme/lego/files/4176740/addRecord.txt)
[getRecordsAfterAdd.txt](https://github.com/go-acme/lego/files/4176743/getRecordsAfterAdd.txt)
[updateRecords.txt](https://github.com/go-acme/lego/files/4176744/updateRecords.txt)
[getRecordsAfterUpdate.txt](https://github.com/go-acme/lego/files/4176745/getRecordsAfterUpdate.txt)
[deleteRecord.txt](https://github.com/go-acme/lego/files/4176746/deleteRecord.txt)

**Comment by ldez** [comment]
It's perfect, thank you.

I will need your help to test the provider (in a few hour).

**Comment by jhartlep** [comment]
No problem :)
Just tell me what to do :)

**Comment by ldez** [comment]
@jhartlep the PR is ready: #1056

Could you try the provider:

```bash
make

rm -rf .lego

SERVERCOW_USERNAME=xxxxxxxx \
SERVERCOW_PASSWORD=xxxxxxxx \
./dist/lego -m your@email.com --dns servercow -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

You have to replace:
- `your@email.com` by your email
- `example.com` your domain
- `xxxxxxxx` by your real username and password

Note the wildcard domain is important.

**Comment by ldez** [comment]
@jhartlep don't hesitate to ask if you have any questions, problems, etc.

**Comment by jhartlep** [comment]
Hi @ldez ,
I have problems installing lego from your feature branch.
This is what I did so far:
* Installed go version 1.13.7
* Installed golangci-ling version 1.23.3
* cloned your lego fork and switched to feat/add-servercow
* run make from the folder

Makefile:39: recipe for target 'checks' failed
make: *** [checks] Error 1

for details see the attachment.
[output.txt](https://github.com/go-acme/lego/files/4177152/output.txt)

What did I wrong?

**Comment by ldez** [comment]
It's my fault, could you just run `make build` instead of `make`

**Comment by jhartlep** [comment]
Got this error (with or without sudo)

make build
rm -rf dist/ builds/ cover.out
Version: 4e76979ebeb09f426ec141a635fdca07d4d5b16c
go build -v -ldflags '-X "main.version=4e76979ebeb09f426ec141a635fdca07d4d5b16c"' -o dist/lego ./cmd/lego/
make: execvp: go: Permission denied
Makefile:25: recipe for target 'build' failed
make: *** [build] Error 127

**Comment by ldez** [comment]
could you try to call manually:
```
go build -v -ldflags '-X "main.version=4e76979ebeb09f426ec141a635fdca07d4d5b16c"' -o dist/lego ./cmd/lego/
```

**Comment by ldez** [comment]
What operating system are you using?

**Comment by jhartlep** [comment]
I am using Ubuntu 18.04.4 LTS on my server.
And now I got lego compiled. Made an error installing go.

But now I get this error from acme:

2020/02/09 17:47:21 [INFO] acme: Registering account for xxx@xxx.xxx
!!!! HEADS UP !!!!

                Your account credentials have been saved in your Let's Encrypt
                configuration directory at "/home/jens/lego/.lego/accounts".
                You should make a secure backup of this folder now. This
                configuration directory will also contain certificates and
                private keys obtained from Let's Encrypt so making regular
                backups of this folder is ideal.2020/02/09 17:47:22 [INFO] [*.daenerys-targaryen.de, daenerys-targaryen.de] acme: Obtaining bundled SAN certificate
2020/02/09 17:47:22 [INFO] [*.daenerys-targaryen.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/38020186
2020/02/09 17:47:22 [INFO] [daenerys-targaryen.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/38020187
2020/02/09 17:47:22 [INFO] [*.daenerys-targaryen.de] acme: use dns-01 solver
2020/02/09 17:47:22 [INFO] [daenerys-targaryen.de] acme: Could not find solver for: tls-alpn-01
2020/02/09 17:47:22 [INFO] [daenerys-targaryen.de] acme: Could not find solver for: http-01
2020/02/09 17:47:22 [INFO] [daenerys-targaryen.de] acme: use dns-01 solver
2020/02/09 17:47:22 [INFO] [*.daenerys-targaryen.de] acme: Preparing to solve DNS-01
2020/02/09 17:47:23 [INFO] [daenerys-targaryen.de] acme: Preparing to solve DNS-01
2020/02/09 17:47:23 [INFO] [*.daenerys-targaryen.de] acme: Cleaning DNS-01 challenge
2020/02/09 17:47:23 [INFO] [daenerys-targaryen.de] acme: Cleaning DNS-01 challenge
2020/02/09 17:47:24 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/38020186
2020/02/09 17:47:24 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/38020187
2020/02/09 17:47:24 Could not obtain certificates:
        acme: Error -> One or more domains had a problem:
[*.daenerys-targaryen.de] [*.daenerys-targaryen.de] acme: error presenting token: servercow: failed to create TXT record _acme-challenge.daenerys-targaryen.de.: parameter type must be cname, txt, tlsa, caa, a or aaaa
[daenerys-targaryen.de] [daenerys-targaryen.de] acme: error presenting token: servercow: failed to create TXT record _acme-challenge.daenerys-targaryen.de.: parameter type must be cname, txt, tlsa, caa, a or aaaa

**Comment by ldez** [comment]
Could you pull and retry?

**Comment by jhartlep** [comment]
Now it works!

2020/02/09 17:54:36 [INFO] acme: Registering account for xxx@xxx.xxx
!!!! HEADS UP !!!!

                Your account credentials have been saved in your Let's Encrypt
                configuration directory at "/home/jens/lego/.lego/accounts".
                You should make a secure backup of this folder now. This
                configuration directory will also contain certificates and
                private keys obtained from Let's Encrypt so making regular
                backups of this folder is ideal.2020/02/09 17:54:37 [INFO] [*.daenerys-targaryen.de, daenerys-targaryen.de] acme: Obtaining bundled SAN certificate
2020/02/09 17:54:37 [INFO] [*.daenerys-targaryen.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/38021096
2020/02/09 17:54:37 [INFO] [daenerys-targaryen.de] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/38021097
2020/02/09 17:54:37 [INFO] [*.daenerys-targaryen.de] acme: use dns-01 solver
2020/02/09 17:54:37 [INFO] [daenerys-targaryen.de] acme: Could not find solver for: tls-alpn-01
2020/02/09 17:54:37 [INFO] [daenerys-targaryen.de] acme: Could not find solver for: http-01
2020/02/09 17:54:37 [INFO] [daenerys-targaryen.de] acme: use dns-01 solver
2020/02/09 17:54:37 [INFO] [*.daenerys-targaryen.de] acme: Preparing to solve DNS-01
2020/02/09 17:54:39 [INFO] [daenerys-targaryen.de] acme: Preparing to solve DNS-01
2020/02/09 17:54:41 [INFO] [*.daenerys-targaryen.de] acme: Trying to solve DNS-01
2020/02/09 17:54:41 [INFO] [*.daenerys-targaryen.de] acme: Checking DNS record propagation using [208.67.222.222:53 208.67.220.220:53 [2001:4860:4860::8888]:53 [2001:4860:4860::8844]:53]
2020/02/09 17:54:41 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/02/09 17:54:46 [INFO] [*.daenerys-targaryen.de] The server validated our request
2020/02/09 17:54:46 [INFO] [daenerys-targaryen.de] acme: Trying to solve DNS-01
2020/02/09 17:54:46 [INFO] [daenerys-targaryen.de] acme: Checking DNS record propagation using [208.67.222.222:53 208.67.220.220:53 [2001:4860:4860::8888]:53 [2001:4860:4860::8844]:53]
2020/02/09 17:54:46 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/02/09 17:54:47 [INFO] [daenerys-targaryen.de] The server validated our request
2020/02/09 17:54:47 [INFO] [*.daenerys-targaryen.de] acme: Cleaning DNS-01 challenge
2020/02/09 17:54:49 [INFO] [daenerys-targaryen.de] acme: Cleaning DNS-01 challenge
2020/02/09 17:54:52 [INFO] [*.daenerys-targaryen.de, daenerys-targaryen.de] acme: Validations succeeded; requesting certificates
2020/02/09 17:54:54 [INFO] [*.daenerys-targaryen.de] Server responded with a certificate.

**Comment by ldez** [comment]
Great, so the provider is ready !

**Comment by jhartlep** [comment]
Thanks for implementing this!
