### ISSUE TITLE
Alpine APK is using 0.3.1-rc3 (April 2016)

### ISSUE THREAD

**Issue by jnovack** [go-acme/lego#991]
Is it possible to get a refresh of this package?

https://pkgs.alpinelinux.org/package/edge/community/x86/lego

What are the steps to getting a newer package into the repository?

**Comment by ldez** [comment]
We, the lego team, don't maintain this package, so you have to contact the package maintainer.

**Comment by jnovack** [comment]
Paging @clandmeter.  Can you weigh in on the proper protocol for software developers to ensure their packages are using relatively up-to-date versions on community repositories?

**Comment by clandmeter** [comment]
updated in edge repository

**Comment by jnovack** [comment]
That was easy, thank you for responding so quickly. :)

Effectively, this is a closed issue, I don't even know if the lego team even WANTS to maintain the package, not my place to say, but begs the question of the right way to do it in the future?
